DS-114: Added isRequired as attribute in input-increment
bifrost-vui/bifrost-front-end-library pull request #142
Opened 2021-08-04 10:21 UTC by famareme

2021-11-09 20:21 UTC, ThalieVideotron requested changes
dans le index.twig, le input type text devrait avoir l'attribut `required` si `isRequired` est true mais le fichier n'a pas été modifié

2021-11-09 20:25 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-increment/_doc/doc.stories.mdx
> +        isRequired      : true,
si le default est true il n'est pas nécessaire dans l'exemple

2021-11-09 20:39 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-increment/twig/index.twig
>                 {% if attrRequired is not empty %} aria-required="true" {% endif %}
dans twig, une empty string returns false : 
`{% if attrRequired %} aria-required="true" {% endif %}` ou en ternaire `{{ attrRequired  ? 'aria-required="true"' : '' }}`

2022-04-11 00:11 UTC, JonathanLefebvreV approved these changes

2022-04-11 00:12 UTC, merged