DS-107 text 2 lines
bifrost-vui/bifrost-front-end-library pull request #148
Opened 2021-08-18 14:10 UTC by famareme

Block-selection modification is not apart of this jira that's why I've rolled back

2021-08-20 01:07 UTC, JonathanLefebvreV requested changes
Le composant est brisé, la feature du positionnement "horizontal" ne marche pu
![image](https://user-images.githubusercontent.com/75901368/130163131-f19cf43c-7bf7-465a-9ce7-4df29aaa322e.png)

Edited Jo : ✔️

2021-11-07 14:15 UTC, JonathanLefebvreV requested changes

2021-11-07 14:15 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/price/_doc/null.drupal.twig
> +                    showLongLabel : NULL,
to revert. these are not the part of the solution to let `savedLable` manage his display

2021-11-07 14:15 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/block-selection/twig/index.twig
> +
```suggestion

```

2021-11-07 14:15 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/block-selection/scss/index.scss
> +      .d-inline-flex.align-items-center.mt-2.savingTextLong {
Cette classe n'est plus utilisé dans ta PR, elle peut donc être supprimé

2021-11-07 14:15 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/price/scss/index.scss
> +          @extend .bf-text-display-medium;
mauvaise indentation dans ce fichier.  Tout reformaté sur 4 spaces

2021-11-07 14:15 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/price/twig/index.twig
> +            {% endif %}
Cette PR price le composant. Ca marche pas dans StoryBook

![image](https://user-images.githubusercontent.com/75901368/140648220-9ca5a732-b847-49cb-b2fb-1d0453a00c02.png)

2021-11-09 14:02 UTC, famareme commented on projects/front-end-library/src/lib/components/block-selection/scss/index.scss
> +      .d-inline-flex.align-items-center.mt-2.savingTextLong {
Je n'est plus cette class dans mon dernier PR

2021-11-09 14:04 UTC, famareme commented on projects/front-end-library/src/lib/components/price/twig/index.twig
> +            {% endif %}
Je n'est pas ce bug là; ni localement ni dans Vercel

2021-11-12 15:36 UTC, JonathanLefebvreV commented
Il y a encore des conflit

2021-11-15 15:34 UTC, JonathanLefebvreV requested changes
Le price label "/month ne reste pas groupé avec le prix
![image](https://user-images.githubusercontent.com/75901368/141809160-5294623c-f99c-4302-887f-8707e6290ef5.png)
Et j'ai entendu les UI dire que le StrokePrice doit être top de la section jaune promotion, pas center

2021-11-15 19:31 UTC, JonathanLefebvreV commented
TODO in https://videotron-design-system.atlassian.net/browse/DS-197

2021-11-15 19:31 UTC, JonathanLefebvreV approved these changes

2021-11-15 19:31 UTC, merged