DS-165-range-slider - wip
bifrost-vui/bifrost-front-end-library pull request #195
Opened 2021-10-18 17:35 UTC by ThalieVideotron

2021-10-21 13:04 UTC, baptistemac commented on projects/front-end-library/src/lib/components/input-range/js/index.js
> +            console.log($minRangeInput.val())
Penser à retirer les 3 console.log

2021-10-21 13:05 UTC, baptistemac commented on projects/front-end-library/src/lib/components/input-range/js/index.js
> +            let max = $maxRangeInput.val();
const min
const max

2021-10-21 13:05 UTC, baptistemac commented on projects/front-end-library/src/lib/components/input-range/js/index.js
> +            let max = doTheMath($maxRangeInput.val());
const min
const max

2021-10-21 13:06 UTC, baptistemac commented on projects/front-end-library/src/lib/components/input-range/scss/index.scss
> +    padding: 0$spacer-2;
il manque un espace ou je ne comprends pas.

2021-10-21 13:06 UTC, baptistemac commented on projects/front-end-library/src/lib/components/input-range/scss/index.scss
> +    max-width: 1200px;
pourquoi ce max-width?

2021-10-21 13:07 UTC, baptistemac commented on projects/front-end-library/src/lib/components/input-range/scss/index.scss
> +        margin: 0$spacer-2;
0 ?

2021-10-21 13:15 UTC, baptistemac commented on projects/front-end-library/src/lib/components/input-range/twig/index.twig
> +<div class='bf-input-range {{(inputRangeVariant is defined) ? 'bf-input-range' ~ inputRangeVariant : '' }} js-bf-input-range {{ class }} ' lang={{lang|default('en')}}>
Pourquoi a-t-on besoin de setter la propriété html `lang`?

2021-10-21 13:15 UTC, baptistemac commented on projects/front-end-library/src/lib/components/input-range/twig/index.twig
> +        <label for='{{ maxInputId }}'class='bf-input-range_label'></label>
espace manquant entre ```' class```

2021-10-21 16:13 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-range/twig/index.twig
> +      data-unit='{{ labelUnit|default('$') }}'
exact - c'était pour tester le script qui le positionne en suffix ou prefix et j'ai oublié de l'enlever. merci

2021-10-21 16:21 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-range/angular/input-range.component.ts
> +    @Input() minLegendDesc  : string;
ce data  a un rôle sémantique de légende et non d'un titre donc je le garde ainsi par contre ça va être `description` pour éviter les abréviations
pour le regroupement min-max faudra voir s'il y a une solution miracle pour identifier les required values

2021-10-21 16:29 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-range/scss/index.scss
> +    input[type=range]:focus {
oups... ben oui.

2021-10-22 01:03 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/_doc/doc.stories.mdx
> +    maxInputId     : 'maxRangeID',
En fait, dans le UIKIT c'est généralement des camelCase. Je suis pour de gardé cela camelCase.
Juste pour info les style s'écrive par leur style.
- camelCase
- snake_case
- PascalCase (or CamelCase)
- kebab-case

2021-10-22 01:04 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/_doc/doc.stories.mdx
> +    maxInputId     : 'maxRangeID',
```suggestion
    minInputId     : 'minRangeId',
    maxInputId     : 'maxRangeId',
```

2021-10-22 01:18 UTC, JonathanLefebvreV requested changes

2021-10-22 01:18 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> + - New `input range`  slider component (see [Component API](?path=/docs/input-range--drupal))
On a décidé que le nom du composant était "input range". Donc enlevéer les référence "slider"

2021-10-22 01:18 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/js/index.js
> +            console.log($maxRangeInput.val())
console à retirer aussi ici

2021-10-22 01:18 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/scss/index.scss
> +                width:$spacer-2;
En plus de la correction demandé par baptiste, il manque un espace

2021-10-22 01:18 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/_doc/doc.stories.mdx
> +    class          : ''
Même commentaire que @baptistemac , 
Faire des API en orienté-objet tel qu'il le donne en example

2021-10-22 01:50 UTC, JonathanLefebvreV requested changes
![image](https://user-images.githubusercontent.com/75901368/138378450-87062a24-6a71-4e99-b773-46d1b2a442f6.png)

`cursor: pointer;` ou `cursor: w-resize;` sur les controles (au choix des @bifrost-vui/ui-designer 

EDITED JO: Resolved

2021-10-22 01:50 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/twig/index.twig
> +      {% endif %}
Un `<strong>` au lieu de gérer en CSS?

2021-10-22 01:50 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/scss/index.scss
> +        color: rgba(var(--bf-color-neutral-primary-rgb), .45) ;
Dans Figma, je vois pas que la couleur a besoin d'avoir une opacity moindre.

Et t'as un espace de trop à la fin

2021-10-22 01:50 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/scss/index.scss
> +    &_legend{
```suggestion
    &_legend {
```
Fait attention au espace. Prends le temps de regardé tes fichiers

2021-10-22 01:50 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/scss/index.scss
> +    &_legend{
Corrige partout. Je ne peux pas te les pointer

2021-10-23 00:23 UTC, JonathanLefebvreV requested changes

2021-10-23 00:23 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/_doc/template.drupal.twig
> +{% set reversedClass  = '' %}
```suggestion
{% set bgClass = '' %}
{% set reversedClass = '' %}
```

Sérieux @ThalieVideotron... C'est quoi le problème avec les espacements?
80% des commentaires dans cette PR sont pour des espaces

C'est une vrai question. Je veux tu me dise c'est quoi le problème et ces quoi ta solutions pour éliminer cela.

2021-10-23 00:23 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/_doc/template.drupal.twig
> +
saut de ligne inutile

2021-10-23 00:23 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/_doc/template.drupal.twig
> +        {% if index is same as (1) or index == 4 %}
```suggestion
        {% if index == 1 or index == 4 %}
```

2021-10-23 00:23 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/_doc/template.drupal.twig
> +    grid-template-columns:repeat(auto-fit, minmax(400px, 1fr));
```suggestion
    grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
```

2021-10-23 00:23 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/angular/input-range.component.ts
> +    /** inputId is required and if no `startValue` is defined, `InputValue` will be the min start value */
```suggestion
    /** inputId is required and if no `startValue` is defined, `inputValue` will be the min start value */
```

2021-10-23 00:23 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/angular/input-range.component.ts
> +    /** inputId is required and if no `startValue` is defined, `InputValue` will be the max start value */
```suggestion
    /** inputId is required and if no `startValue` is defined, `inputValue` will be the max start value */
```

2021-10-23 00:23 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/angular/input-range.component.ts
> +     /** The positionning of the `labelUnit` is  */
"Le positionnement du `labelUnit` est"? C'est quoi tu essaie de dire?
Refaire la phrase

2021-10-23 00:23 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/angular/input-range.component.ts
> +    @Input() rangeHandles   : ''|'min' |'max';
Est-ce que tu essaie de dire que le les valeur devrait être "both" "min ou "max"?
Ce choix devrait jamais être vide dans le fond.

2021-10-23 00:23 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/angular/input-range.component.ts
> +    @Input() rangeHandles   : ''|'min' |'max';
peut être "double" au lieur de "both", ou "full"
@baptistemac  une option?

2021-10-23 00:23 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/js/index.js
> +        if ($unit == '$' && $this.attr('lang') == 'en'){
Le fichier est dégeux en espacement, aligment, etc.  A revoir en entier

2021-10-23 00:29 UTC, JonathanLefebvreV requested changes

2021-10-23 00:29 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/twig/index.twig
> +      step={{ step|default(1) }}
Ton default n'est pas documenté
![image](https://user-images.githubusercontent.com/75901368/138535332-dc7312b9-3a3c-4d70-8f53-fad17d0fcecf.png)

2021-10-23 01:01 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/twig/index.twig
> +      min={{ min.inputValue }}
Je comprends pas la façon d'avoir codé ce composant.
Comment max et min peuvent être égal au "inputValue"? Je crois pas que c'est bien nommé
Comment value peut être autre chose que "startValue"? et en fait pourquoi appelé ca "start" et pas seulement "value", vu que c'est cela que ca représente?

En plus, les valeur s'inverse. Il manque du traitement pour ne pas que cela ce produise
![image](https://user-images.githubusercontent.com/75901368/138536334-ede4c5f1-de6c-4c19-ae11-ba72d948fefd.png)

2021-10-24 00:17 UTC, baptistemac commented on projects/front-end-library/src/lib/components/input-range/_doc/template.drupal.twig
> +            {% set bgClass = (class is defined and class) ? class : ' bf-color-bg-ground' %}
`{% set bgClass = class|default(' bf-color-bg-ground') %}`
Tu peux faire pareil pour les autres `bgClass`.

2021-10-24 00:17 UTC, baptistemac commented on projects/front-end-library/src/lib/components/input-range/_doc/template.drupal.twig
> +                legend              : min.legend,
Le role des templates est de simuler ce que ferais AppNovation en incluant nos composants.
- On ne devrait pas avoir de logique comme `startValue          : (rangeHandles == 'min') ? min.startValue : min.inputValue,` sinon dans Storybook, il est impossible de savoir si c'est un comportement du composant ou du template.
- On devrait être au plus proche des controls du storybook.
- Le mieux est d'ailleurs de faire un include sans `with` pour s'assurer que le rendu correspond exactement au storybook. Ça permet de catcher les propriétés non définies, `Null`, `undefined`, string vide, ...
`{% include '@bf-components/input-range/twig/index.twig' %}`. Ceci pas toujours possible cependant, notamment pour afficher les `reversed`, ...

@famareme ça peut t'intéresser.

2021-10-24 00:17 UTC, baptistemac commented on projects/front-end-library/src/lib/components/input-range/scss/index.scss
> +            content: ' ';
pour éviter des effet de bord, je te propose de retirer l'espace vide:
`content: '';`

2021-10-24 00:26 UTC, baptistemac commented
@JonathanLefebvreV @ThalieVideotron 
- Je propose d'appeler ce composant **input-slider.** Avec une possibilité pour afficher une seule ou deux poignées (range).
- Pour OC11, on parle de prix mais ce composant devrait pouvoir afficher n'importe quelle valeur. Ex: selection d'un nombre de personnes, montant des forfait en Go, ...
- La notion de **min** et **max** devrait être réservée aux 2 valeurs aux extrémités de la barre (pas les 2 poignées rondes donc).
- Je trouve ça dangereux de se baser sur une string `$` pour déterminer le positionnement de l'unité. Que ce passe-t-il si on veux afficher une autre devise ou par exemple `$CAD`?
    - Soit on a `unitPosition: 'left' | 'right'` et AppNovation le détermine en fonction de son contexte (prix + language).
    - Soit, on les aide un peu et on créé un `isUnitPrice` qui se charge de le faire. Mais ce n'est pas l'idéal, car si le unit est `€`, il ne devrait jamais passer à gauche même en anglais. Pourquoi pas `isUnitPriceCAD` ?
- Voici l'API que je propose pour afficher un **slider avec une seule poignée**:

```
value : 25,
unit: '$',
unitPosition: 'left' | 'right',
min: {
	value: 0,
	legend: '',
	description: '',
},
max: {
	value: 100,
	legend: '',
	description: '',
},
track: 'normal' | 'inverted', // inverted = highlight la barre à droite de la poignée.
step: 10,
class: ''
```

Et pour un **range** (avec deux poignées):

```
value : [ 25, 75 ] // [ startValue, endValue ]
```

2021-10-29 18:08 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-range/_doc/template.drupal.twig
> +{% set reversedClass  = '' %}
pas surprise, le 20% qui reste sont des enjeux beaucoup plus majeurs avec beaucoup de refactoring qui génèrent des enjeux d'espaces. 

je suis prête à vivre avec 1 seul commentaire qui me dit que j'ai des erreurs d'espacements/alignement (pour l'ensemble) et je vais m'organiser pour les trouver. 

Il y a quelques ajustement à faire dans la config de l'IDE qui pourront aider (mais juste pour le css)
 - les ` {` que je dois faire à la main, 
 - les `;` qui ne sont pas obligatoires et qui devraient l'être
 - les `: ` qui ne sont pas configurés

mais ce qui me tue c'est l'alignement des = et des :  
Il est à refaire partout dès qu'on change le nom d'une variable - je vais porter davantage attention

Aussi je cois qu'on pourrait penser à une solution où - quand on construit du nouveau surtout -  on fait une validation en 2 temps api/validité du code + formatage.  je t'accorde que le formatage est important mais il ne peut pas être la priorité tant que l'api/code n'est pas finalisé et dans ce cas-ci il y a eu plusieurs changements majeurs consécutifs. Je pas surprise de voir que j'en ai laissé traîner à chaque passage et ce, malgré le fait que je fasse le tour avant chaque push - penses-tu que c'est possible?

2021-10-29 19:03 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-range/angular/input-range.component.ts
> +    /** inputId is required and if no `startValue` is defined, `InputValue` will be the min start value */
3 handle ou +, on gère pas. : n'a jamais été dans le scope
pour la position du label Uinit - on en avait discuté avec baptiste et on est arrivé à la même conclusion 
pour le renaming- 100% d'accord et dans un commit distinct 

et là je me permet de faire l'avocat du diable : 
`isInverted` est ce qui gère la direction quand il n'y a qu'un seul handle.  Pourquoi dis-tu que n'est ce pas  un besoin de business? c'est clairement dans le figma. 
Baptiste avait suggéré que ça serait intéressant de le traiter en boolean et non seulement ça marche mais c'est bien mieux que 3 valeurs là où une seule est nécessaire (un gros + pour la clarté des conditions twig).
il s'appelle IsInverted et non reversed pour éviter la confusion et c'est aussi expliqué dans la doc -> `Changes the direction of a 1 handle slider` - personne ne s'attend à ce que ça fasse quoi que ce soit sur un 2 handles. 
si j'avais `norma|inverted` ìnverted` n'aurait pas plus d'effet sur le double handle (d'où l'idée d'en faire un boolean si c'est normal alors pourquoi le spécifier)
pour être certaine que ça soit clair j'ai même ajouté plus loin dans la doc : 
```- if `isInverted` is set true and `initialValue` contains 1 value : reverts the direction of the 1 handle slider but has no effect if `initialValue` contains 2 values ``` - 
Dans cards on a beaucoup de contrôles storybook qui ne sont pas utiles pour certains variants - on est dans un contexte très similaire.  

@JonathanLefebvreV revient-moi sur ce point s'il te plait, on s'est peut-être juste mal compris mais je crois que c'est une mauvaise idée de supprimer cette propriété.

2021-10-29 19:27 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-range/twig/index.twig
> +      </p>
dans ce cas-ci le risque est calculé : 
si une des deux légende(min ou max) existe pas grave que l'autre soit un `<p>` vide -> {% if haslegend or hasdescription %}
mais je m'assure qu'il n'y a jamais 2 `<p>` vides l'un à côté de l'autre
De mon point de vue et d'un point de vue UX, ces 2 `<p>` ne devraient jamais être vides même si nous ne le forçons pas

2021-10-29 19:35 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-range/twig/index.twig
> +<div class='bf-input-range {{ inputRangeVariant is defined ? 'bf-input-range' ~ inputRangeVariant : '' }} js-bf-input-range {{ class }} ' lang={{language|default('en')}}>
exact. vestige du $ qui change avec la langue et la variable n'existe plus

2021-10-29 19:50 UTC, ThalieVideotron commented
pour https://github.com/bifrost-vui/bifrost-front-end-library/pull/195#issuecomment-954693201
c'était un exemple où ce n'est pas le default qui est appliqué - supprimé. pour voir le unit se déplacer il faut maintenant jouer dans storybook

2021-11-01 15:43 UTC, baptistemac commented
Dans le storybook, ça serait cool de présenter le input-range avec le **default** et le **reversed** pour chaque Stories.
Et pourquoi pas le **highlight**, car on sait deja que ça arrivera.

2021-11-01 15:45 UTC, baptistemac commented
Je ne comprend pa pourquoi changer le width de la track principale: Elle devrait toujours etre à 100%.
![image](https://user-images.githubusercontent.com/845412/139699585-39a80df1-4640-4d2d-8423-1df072512d2b.png)

2021-11-01 15:57 UTC, baptistemac commented
On voit un microbout du **before**, pourquoi ne pas mettre `with: 0` par défaut? A quoi sert-il d'ailleurs ce before? Question innocente, j'imagine qu'il y a une raison.
![image](https://user-images.githubusercontent.com/845412/139701322-b6a7bb8d-6239-46f4-a623-842b1036603b.png)

2021-11-02 12:21 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-range/_doc/doc.stories.mdx
> +    maxLegendDesc  : 'Max legend line 2',
renaming `initialValue` to `value` -> done

2021-11-02 12:30 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-range/_doc/doc.stories.mdx
> +    initialValue    : [40,80],
done

2021-11-02 13:30 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-range/twig/index.twig
> +      </p>
le P vide est nécessaire pour l'alignement (gauche droite) ex: si je n''ai une des deux description ou une des deux légendes. si tout est vide, il n'y a pas de <p>

si je n'ai aucune description, le <strong> ne s'affiche pas mais le <p> n'est pas nécessairement vide :
 `{{ max.legend|default('') }}`

2021-11-02 13:39 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-range/_doc/template.drupal.twig
> +    {% for index in [1,2,3,4,5]%}
> On voit un microbout du **before**, pourquoi ne pas mettre `with: 0` par défaut? A quoi sert-il d'ailleurs ce before? Pour le inverted? Question innocente, j'imagine qu'il y a une raison. ![image](https://user-images.githubusercontent.com/845412/139701322-b6a7bb8d-6239-46f4-a623-842b1036603b.png)

@batiste c'est une combinaison de margin, de positionnement du label et de largeur du handle. suite à l'optimisation proposée pour se débarasser de exclude-left et exclude-right il est possible qu'on soit obligés de conserver cette approche pour la portion grasse (la sélection)  de la track

2021-11-03 19:22 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-range/angular/input-range.component.ts
> +    /** inputId is required and if no `startValue` is defined, `InputValue` will be the min start value */
@JonathanLefebvreV  je vais acheter un décodeur ;-)
*3 handle ou +, on gère pas*...  il m'en a fallu des relectures pour comprendre qu'en ajoutant une 3e value on ajoutait un handle indésirable. je ne peux pas forcer un array à 2 éléments - ni même à forcer des chiffres. j'ai fait un slice dans twig pour ne pas traiter les 3e valeurs et plus

2021-11-04 13:29 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/angular/input-range.component.ts
> +    /** inputId is required and if no `startValue` is defined, `InputValue` will be the min start value */
Ce que baptiste a pointé avec "isInvert" c'est que le style du slider est inversé en terme de épaisseur et rendu.

Mais oui il faut que le slider gère ca valeur en relation avec "min" ou avec "max".  SAuf que le rendu reste pareil dans les 2 cas pour nous.

Je trouve ca confusant de faire cette gestion avec les naming que vous proposez. Je n'ai pas solution à chaud.
`valueRelation` : `min | max`  ?

2021-11-05 13:18 UTC, ThalieVideotron commented
@baptistemac : 
 les changements effectués vont bien au-delà de réparer le bug js. 
api, css, renaming complet - pas contre mais déçue de l'absence de communication avant de procéder.

2021-11-05 13:24 UTC, bibifrost commented
> @baptistemac : les changements effectués vont bien au-delà de réparer le bug js. api, css, renaming complet - pas contre mais déçue de l'absence de communication avant de procéder.

2021-11-05 15:26 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-slider/twig/index.twig
> +                <strong>{{ max.description }}</strong>
finalement un span.font-weight-bold au lieux du strong pour `max.description` ? 
- pour se donner l'option de le transformer en richtext plus tard

2021-11-05 15:26 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-slider/scss/index.scss
> +                left: auto !important;
![image](https://user-images.githubusercontent.com/82388009/140534190-e324ac65-3568-41dd-95b4-6f0855addfce.png)
et il y a un problème d'alignement - on n'est pas centré

2021-11-06 08:26 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-slider/_doc/doc.stories.mdx
> +    // ...
- Tu préfères avoir tous les exemples réunis en haut de page?
- Si on affiche toute l'API dans toutes les exemples, je vois plusieurs défauts:
    - Ça fait beaucoup de bruits et il difficile de trouver le control responsable du rendu.
    - C'est pas mal plus de code à maintenir.
    - C'est plus long a scroller.
J'aime l'idée qu'on ai toujours un exemple complet en haut de page et si tu veux reproduire des exemples précis, alors tu overrides avec ce qui est indiqué. Exemple: tu veux un `2 handles`: 
![image](https://user-images.githubusercontent.com/93746960/140603273-0ab4b3a0-cbe5-4792-b588-b22b3bc66c85.png)

2021-11-06 08:29 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-slider/scss/index.scss
> +    &__progress-track {
La barre de progression est basé sur les values, mais fondamentalement, ce div est bien une barre de progression.
track = le rail complet
progress track = la barre de progression.

2021-11-06 08:31 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-slider/scss/index.scss
> +                left: auto !important;
le important est necessaire car le left est setté en JS.
Pour l'alignement, j'avais essayé de l'améliorer sans succes, mais je vais ressayer.

2021-11-06 08:39 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-slider/twig/index.twig
> +		{% set unitPosition = unitPosition|default('end') %}
hum, ça me fait dire que ce n'est pas clair que `isUnitDollar` affecte `unitPosition`. On devrait plutôt ajouter une entrée: `unitPosition = 'start' | 'end' | 'price'`.
Qu'en pensez-vous?
@JonathanLefebvreV a tu un avis la dessus?
Merci

2021-11-06 08:40 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-slider/twig/index.twig
> +              {% if unitLabel and unitPosition is same as ('start') %}{{ unitLabel }}{% endif %}<span class='bf-input-slider__label__value'></span>{% if unitLabel and unitPosition is not same as ('st
non j'ai essayé. Ça marchait quand je l'avais mis dans Price. Mais la je comprends pas pourquoi ici ça marche pas.

2021-11-06 08:41 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-slider/twig/index.twig
> +                <strong>{{ max.description }}</strong>
Pourquoi pas.
Je ne comprends cependant pas pourquoi ça permettra de le changer en rich text?

2021-11-06 09:07 UTC, bibifrost commented
Bug de disparition des labels quand ils sont aux estrémités:
![image](https://user-images.githubusercontent.com/93746960/140604350-eb3b8207-384d-45be-a872-3b871a52f231.png)

2021-11-07 15:36 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +
```suggestion
```

2021-11-07 15:42 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/_doc/doc.stories.mdx
> +    value           : 40,
Pourquoi? C'est pas le role de Storybook mais de Zeroheigh, et même là sur les composant à privilégié

2021-11-07 15:43 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/_doc/template.drupal.twig
> +
```suggestion
```

2021-11-07 15:53 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-range/_doc/template.drupal.twig
> +{% set reversedClass  = '' %}
Le formatage ne devrait pas être un sujet de pull-request. Le reviewer devrait valider seulement les abération et les manque, en étant une exception. 
C'est la responsabilité du developpeur de produire du code lisible qui reste les noemclature et le style de ce qu'il écrit comme code en relation avec le type de language.

C'est sur qu'on pourrait setter des confif dans l'IDE si ca l'aide. Dans les outils JetBrains, ca prends quand même une commande pour rouler et formaté le fichier en entier.

Autre solution est d'avoir un hook avec Prettier ou autre outils qui format le code automatiquement.
Mais ce n'est pas pour l'instant, il faut finir par finir Chormatic en premier comme optimisation de flow.

2021-11-07 15:59 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/angular/input-slider.component.ts
> +    /** `max { **InputId**, **value**, legend, description }`:  **InputId** and **value** are required. */
```suggestion
    /** `min { **inputId**, **value**, legend, description }`: **inputId** and **value** are required. */
    @Input() min            : object;
    /** `max { **inputId**, **value**, legend, description }`:  **inputId** and **value** are required. */
```

2021-11-07 16:08 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/js/index.js
> +$(function () {
```suggestion
$(function() {
```

2021-11-07 16:08 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/js/index.js
> +    container.each(function (i, el) {
```suggestion
    container.each(function(i, el) {

```

2021-11-07 16:10 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/js/index.js
> +        {
```suggestion
        if (isRange) {
```

2021-11-07 16:11 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/js/index.js
> +                if(progressBarWidth < 50) {
```suggestion
                if (progressBarWidth < 50) {
```

2021-11-07 16:12 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/js/index.js
> +                } else if(isLabelMerged) {
```suggestion
                } else if (isLabelMerged) {
```

2021-11-07 16:12 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/js/index.js
> +
```suggestion
```

2021-11-07 16:13 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/js/index.js
> +
```suggestion
```

2021-11-07 16:14 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/js/index.js
> +            if(isInverted) {
```suggestion
            if (isInverted) {

```

2021-11-07 16:15 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/js/index.js
> +                if(isInverted)
```suggestion
                if (isInverted)
```

2021-11-07 16:16 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/js/index.js
> +
```suggestion
```

2021-11-07 16:16 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/js/index.js
> +                {
```suggestion
                if (isInverted) {
```

2021-11-07 16:17 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/js/index.js
> +
```suggestion
```

2021-11-07 16:18 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/js/index.js
> +
```suggestion
```

2021-11-07 16:19 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/scss/index.scss
> +    &__track{
```suggestion
    &__track {
```

2021-11-07 18:39 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/twig/index.twig
> +                <strong>{{ max.description }}</strong>
C'est du détail. laissé ca comme ca pour le moment avec les <strong> et svp, arrêté de parler de RichText tant qu'un élément est pas clairement identifié pour être en RichText.

2021-11-07 19:32 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/twig/index.twig
> +		{% set unitPosition = unitPosition|default('end') %}
Personnellement je ne vois aucun intéret d'avoir une variable `unitPosition`. Grammaticallement parlant, le unit va toujours être après la valeur, en FR et en EN, sauf en pour un montant.
Donc, j'enlèverai `unitPrice`, j'enlèverais `isUnitDollar` parce qu'on est capable de savoir avec un  `=='$'` si unit est un prix ou non. et on utilise 'FR/EN pour gérer si le `$` est avant ou après le prix.

Je crois que ce problème, et le besoin est over-complexifié dans votre implémentation.

2021-11-07 19:33 UTC, JonathanLefebvreV commented
Je remets le jira "in progress" parce qu'il reste des commentaires à gérer et tu travailles à faire

2021-11-08 13:21 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-slider/_doc/doc.stories.mdx
> +    // ...
ouais surtout pour le 2 handles

2021-11-08 13:22 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-slider/_doc/doc.stories.mdx
> +    value           : 40,
ok

2021-11-08 13:28 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-slider/scss/index.scss
> +                left: auto !important;
si le left est setté en js il n'est donc plus de la responsabilité du css. 
je suis très réticente au important et dans ce cas-ci on ne comprend pas d'òu il vient en lisant le css. 

pour l'alignement j'ai eu le même problème il est causé par la largeur des handles et était compensé par une marge dans l'overlay.

2021-11-08 13:42 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-slider/twig/index.twig
> +		{% set unitPosition = unitPosition|default('end') %}
on a 2 approches : 
ou bien ou a `unitPosition` pour laisser le choix de la position avec un défaut pour `end` (on est agnostique du contenu)
ou bien on positionne le `labelUnit` en fonction de la langue si `isUnitDollar` est à true -> pas agnostique mais on a habitué appNovation à cette solution (bien qu'on ne soit pas dans un composant price)

les 2 c'est overkill et source de confusion
pour ce qui est de gérer le `$` on ne peut pas présumer du contenu - je reprend l'argument de @baptistemac  : on pourrait: avoir `$` ou `$CAD` voire `$USD` ou même `€`

2021-11-08 13:46 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-slider/twig/index.twig
> +              {% if unitLabel and unitPosition is same as ('start') %}{{ unitLabel }}{% endif %}<span class='bf-input-slider__label__value'></span>{% if unitLabel and unitPosition is not same as ('st
je m'en doutais. On aura essayé.
explication : spaceless ne s'occupe que de l'espace entre les tag, on a un span entouré de valeurs et non une sucession de span... pas envie d'ajouter un span inutile

2021-11-09 15:55 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-slider/twig/index.twig
> +		{% set unitPosition = unitPosition|default('end') %}
Pour ce qui est de se baser sur la string `$` pour gérer le positionnement:
- Et si demain on a `$*` ou `$CAD`, ... C'est dangereux je  trouve de se baser sur une string.
- Je pense à l'intégrateur AppNovation: Comment peux-t-il savoir que un `$` comme label va gérer son positionnement en fonction de la langue. Oui, ça peux être dans la doc, mais ce n'est pas évident à la relecture...

2021-11-09 15:55 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-slider/_doc/doc.stories.mdx
> +    // ...
Peut-être qu'il y a un malentendu. Je n'ai pas déplacé les examples, je les ai laissé tel que tu les avais placé, proche de leur rendu. J'ai juste épuré les props répétitives.
Es-tu ok avec ça?

2021-11-09 15:55 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-slider/scss/index.scss
> +                left: auto !important;
ici c'est un peu différent, le problème vient du **left** et **width** de la barre de progression:
3 états qui expliquent:
![image](https://user-images.githubusercontent.com/93746960/140957567-6068ab9f-0463-4316-8069-aa291064b641.png)
![image](https://user-images.githubusercontent.com/93746960/140957624-7e701141-1300-4b10-b649-6dc627814e08.png)
![image](https://user-images.githubusercontent.com/93746960/140957672-dc715f67-7f41-4141-82fb-a628a0a2c08c.png)

2021-11-17 16:23 UTC, bibifrost commented on CHANGELOG.mdx
>  ## vX.X.X
fixé via `minimumGap`

2021-11-17 16:23 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-slider/scss/index.scss
> +                left: auto !important;
fixé

2021-11-25 01:51 UTC, JonathanLefebvreV requested changes

2021-11-25 01:51 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/twig/index.twig
> +	{% endif %}
Ce code est en 8 d'indentation au lieu de 2.

2021-11-25 01:51 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-slider/twig/index.twig
> +        </p>
```suggestion
      </p>
```

2021-11-25 02:11 UTC, JonathanLefebvreV commented
@bibifrost , as tu un iPhone? 
Peux tu essayé de jouer avec? J'ai essayé et le "drag and drop" ne marche pas "live" le slider réagi au "click - unclick" avec un lag

En plus, je ne crois pas que les bullet sont assez grosse pour être utilisable sur un mobile. (Ce point là, on pourra l'adressé dans DS-212

2021-11-25 02:54 UTC, baptistemac commented
> @bibifrost , as tu un iPhone? 
> Peux tu essayé de jouer avec? J'ai essayé et le "drag and drop" ne marche pas "live" le slider réagi au "click - unclick" avec un lag
> 
> En plus, je ne crois pas que les bullet sont assez grosse pour être utilisable sur un mobile. (Ce point là, on pourra l'adressé dans DS-212

Oui j'ai un iPhone XR iOS 14.7. Sur safari, c'est live, ça suit bien le doigt. Par contre ce n'est pas toujours facile à pogner.
Pour info, la solution ne peux pas être de grossir la zone interactive des poignées car ça va créer des conflits entre les 2 poignées. Par contre, le solution proposée aiderait effectivement beaucoup.

2021-11-25 15:46 UTC, JonathanLefebvreV commented
version iOS de 13 et 15. Ok merci pour ton test. C'est parfait alors.
Il reste juste le problème d'indentation et on va pouvoir mergé

2021-11-25 16:14 UTC, JonathanLefebvreV approved these changes

2021-11-25 16:15 UTC, merged