Ds 168 upgrade angular 12 2 1
bifrost-vui/bifrost-front-end-library pull request #198
Opened 2021-10-25 15:56 UTC by famareme

2021-11-01 12:39 UTC, famareme commented on build-storybook.log
>  [07:43:54]                : - declarations:
oui c un oublie; je vais l'enlever

2021-11-01 12:40 UTC, famareme commented on projects/front-end-library/src/_doc/1-Introduction/1-introduction.stories.mdx
> -import { Meta } from '@storybook/addon-docs/blocks';
oui le merge est déjà fait avec master

2021-11-04 14:34 UTC, JonathanLefebvreV requested changes

2021-11-04 14:34 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/js/demo/bifrost/carousel.js
>          },
L'indentation est pas égal

2021-11-05 01:06 UTC, JonathanLefebvreV commented on scripts/generate/templates/component/_doc/doc.stories.mdx
> +import { Canvas,Meta, Story, Preview, Props }  from '@storybook/addon-docs';
```suggestion
import { Canvas, Meta, Story, Preview, Props }  from '@storybook/addon-docs';
```

2021-11-05 01:14 UTC, JonathanLefebvreV requested changes
Actual:
![image](https://user-images.githubusercontent.com/75901368/140441737-02de8161-776b-468d-9784-02c4eee92e7b.png)
https://bifrost-front-end-library-git-ds-168-upgrade-404634-bifrost-vui.vercel.app/?path=/story/components-carousel--drupal

Expected: 
![image](https://user-images.githubusercontent.com/75901368/140441847-f716c07b-e1a0-41a0-b124-f7b71d5261f9.png)
https://bifrost-front-end-library-vui.vercel.app/?path=/story/components-carousel--drupal&globals=backgrounds.grid:false

2021-11-05 01:17 UTC, JonathanLefebvreV requested changes
input increment doesn't work on your branch
https://bifrost-front-end-library-git-ds-168-upgrade-404634-bifrost-vui.vercel.app/?path=/story/components-input-increment--drupal
Erreur de Mime type coté server:
![image](https://user-images.githubusercontent.com/87377125/140570380-ac95426e-8af8-4b49-bc36-fa443a3d852c.png)
En local le carrousel et le input-increment fonctionnent:
![image](https://user-images.githubusercontent.com/87377125/140571337-13a76a5f-bf64-4a1d-a2ef-783f413c2591.png)


![image](https://user-images.githubusercontent.com/87377125/140571279-df3b649f-a40b-4836-8ebd-19dec8adc78e.png)

2021-11-05 01:20 UTC, JonathanLefebvreV requested changes
Slide show doesn't work.
https://bifrost-front-end-library-git-ds-168-upgrade-404634-bifrost-vui.vercel.app/?path=/story/components-slideshow--drupal

Which is probably the same problem then Carousel as they used the same library.
Seeing the input increment failed too, the problem seem related to all JS file load

Le script vendors~bifrost-components.js n'est pas généré coté serveur:
![image](https://user-images.githubusercontent.com/87377125/140571017-0ceecb5d-67a1-441a-83b0-0c12edaaac26.png)

2021-11-11 12:36 UTC, JonathanLefebvreV approved these changes

2021-11-11 12:36 UTC, merged