Ds 199 new combo card variant
bifrost-vui/bifrost-front-end-library pull request #203
Opened 2021-11-09 19:16 UTC by ThalieVideotron

En prod, sur les sites de Videotron, les images de téléphone sont 128*128 centrées sur un fond transparent (ou gris clair) ce qui rend impossible le centrage visuel des éléments. Étienne pense qu'on n'aura pas le choix d'y aller comme ça pour le moment. @jfpoliquin a été tagué dans le jira et on va attendre son retour
![image](https://user-images.githubusercontent.com/82388009/140988940-ecf9cc32-f79f-4c5f-8feb-f76a7db1a999.png)
note : l'encadré jaune c'est juste pour la capture

2021-11-09 19:41 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/twig/index.twig
>      class='
la classe disabled n'est pas utilisée dans le css de la card.
@bibifrost tu vois un problème si on enlève ça?

2021-11-10 12:53 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/twig/index.twig
>      {% if isDisabled is defined and isDisabled is same as (true) %}disabled{% endif %}
la classe disabled n'est pas utilisée dans le css de la card.
@bibifrost tu vois un problème si on enlève ça?

2021-11-11 13:46 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
>      {% if isDisabled is defined and isDisabled is same as (true) %}disabled{% endif %}
Sans m'avoir penché dans le détails. C'est nécessaire d'avoir des cartes au style "disabled". @ThalieVideotron Peux tu faire une suggestion commit dans GitHub qu'on voit visuellement ce que tu veux dire?
J'ai un doute qu'on ai besoin d'enlever quelque chose

2021-11-11 13:53 UTC, JonathanLefebvreV requested changes
🛑 Visual regression

On master
![image](https://user-images.githubusercontent.com/75901368/141309813-f86551f2-347e-4592-a591-fb8cc87abc71.png)

On PR
![image](https://user-images.githubusercontent.com/75901368/141309770-725c7266-ea62-49ad-8bfa-6ba7d6d63f72.png)

Jo Edited: Validated

2021-11-11 13:57 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +
```suggestion
```

2021-11-11 14:00 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +{% set isCombo      = hasImage and image.comboLabel is defined and image.comboLabel %}
C'est pas grave. mais comme la classe que tu ajoute dans ton If est 
`bf-card__visual--combo` pour resté dans la même nomclature. Que penses-tu de nommé `isCombo` pour `hasVisualCombo`?

2021-11-11 14:17 UTC, JonathanLefebvreV requested changes

2021-11-11 14:17 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +    {% if isCombo %}
Il y a une logique de programation qui ne suit pas la logique structurel.
`hasVisual` est un peu le "parent" de `hasVisualCombo`. Le 2e ne peux pas être vrai si le premier ne l'es pas.

Dans ce genre de logic. Ta structure devrait suivre. 
C'est à dire qu'on ne parle pas d'un `IF/ELSE IF` mais d'un `IF` imbriqué.
```
 if hasVisual
   ....
   if hasVisualCombo
   ....
....
```

Ici on voit que tu duplique la `div` parent (not D.R.Y) au lieu d'injecté les nouvelle / bonne classe pour `hasVisualCombo`.

Bref, c'est juste le principe que je veux expliqué ici. que ton IF/ELSE ne devrait suivre la même logique.
Vu que `hasVisual` provient de `hasImage` ils y a certainement un refactor possible à faire ici pour que ca soit plus claire et plus "DRY"

2021-11-11 14:17 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +    {% if isCombo %}
En passant, si dans le travail, on se rends compte qu'on peut mettre un Icon comme image pour le Combo. Moi j'ai rien contre. Ce sera un feature :P

2021-11-11 14:17 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +{% set isCombo      = hasImage and image.comboLabel is defined and image.comboLabel %}
ou `hasImageCombo`? Entk la logique d'implementation doit être au plus simple pour être facile à lire par le référencement de la logique

2021-11-11 15:44 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/twig/index.twig
>      {% if isDisabled is defined and isDisabled is same as (true) %}disabled{% endif %}
on a un style (point de vu layout) disabled mais il est appliqué via l'attribut `disabled` (transformé en attribut `data-state='disabled'` dans un bug fix pour des raisons de validité HTML). 
Mon seul questionnement est à savoir si des sous-composants pourraient avoir besoin de ce style pcq quand je regarde le CSS j'ai l'impression qu'on adresse déjà tous les besoins. Je l'ai testé et ça ne semble pas avoir d'impact puis j'ai pensé au bloc éditable et c'est là que j'ai eu un doute. je serais à l'aise avec _if it ain't broken don't fix it_   et de le considérer comme du _bullet proofing_

2021-11-11 15:55 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +{% set isCombo      = hasImage and image.comboLabel is defined and image.comboLabel %}
`hasVisualCombo` me plait bien - vendu

2021-11-11 16:01 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +    {% if isCombo %}
d'après ce que je comprend c'est toujours une photo de téléphone dans les combos actuels mais effectivement on pourrait utiliser cette carte pour d'autres types de combos (des combos de add-ons par exemple) - intéressant - je regarde ça et je revois l'imbrication

2021-11-11 17:33 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +    {% if isCombo %}
![image](https://user-images.githubusercontent.com/82388009/141342895-6e5cff7a-31dc-4283-955b-cc485d8377d6.png)
effectivement cette nouvelle imbrication s'accommode très bien du nouveau _feature_

2021-11-11 17:41 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +    {% if isCombo %}
À ton avis, est-il nécessaire de documenter que le `comboLabel` n'est accessible que dans les cartes de type combo ou c'est évident?

2021-11-11 17:44 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/twig/index.twig
>      {% if isDisabled is defined and isDisabled is same as (true) %}disabled{% endif %}
> 🛑 Visual regression
> 
> On master ![image](https://user-images.githubusercontent.com/75901368/141309813-f86551f2-347e-4592-a591-fb8cc87abc71.png)
> 
> On PR ![image](https://user-images.githubusercontent.com/75901368/141309770-725c7266-ea62-49ad-8bfa-6ba7d6d63f72.png)

Raison de plus refactorer l'imbrication dans le index.twig. c'est en allant modifier le mauvais div que j'ai introduit la régression - fixed

2021-11-11 21:04 UTC, jfpoliquin commented
> En prod, sur les sites de Videotron, les images de téléphone sont 128*128 centrées sur un fond transparent (ou gris clair) ce qui rend impossible le centrage visuel des éléments. Étienne pense qu'on n'aura pas le choix d'y aller comme ça pour le moment. @jfpoliquin a été tagué dans le jira et on va attendre son retour ![image](https://user-images.githubusercontent.com/82388009/140988940-ecf9cc32-f79f-4c5f-8feb-f76a7db1a999.png) note : l'encadré jaune c'est juste pour la capture

@ThalieVideotron Effectivement. Je suis d'accord avec Etienne. J'en comprend qu'il n'y a pas de resize possible pour la photo de l'appareil?

2021-11-12 14:22 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
>      {% if isDisabled is defined and isDisabled is same as (true) %}disabled{% endif %}
J'ai pas tout compris... mais je suis d'accord avec "if it ain't broken don't fix it" pour le moment

2021-11-12 14:39 UTC, JonathanLefebvreV commented
Le texte réagi mal.

Je m'attendrais que la zone de texte reste en dessous de l'icone avec une largeur max et que le header s'agrandi par le bas.
![image](https://user-images.githubusercontent.com/75901368/141484056-9dfa2e2d-e4fa-4a26-a736-2fb5d8cc4d4e.png)

Voi en mobile, l'icone fini par être poussé trop haut
![image](https://user-images.githubusercontent.com/75901368/141484156-0bbce62e-63ce-48d7-9029-3c475aadf983.png)

2021-11-12 14:41 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +            class='bf-card__visual {{ hasVisualCombo ? 'bf-card__visual--combo' : '' }} bf-color-bg-underground  d-flex justify-content-center align-items-center p-3 p-sm-4'
```suggestion
            class='bf-card__visual {{ hasVisualCombo ? 'bf-card__visual--combo' : '' }} bf-color-bg-underground d-flex justify-content-center align-items-center p-3 p-sm-4'
```

2021-11-12 17:02 UTC, ThalieVideotron commented
> Le texte réagi mal.
> 
> Je m'attendrais que la zone de texte reste en dessous de l'icone avec une largeur max et que le header s'agrandi par le bas. ![image](https://user-images.githubusercontent.com/75901368/141484056-9dfa2e2d-e4fa-4a26-a736-2fb5d8cc4d4e.png)
> 
> Voi en mobile, l'icone fini par être poussé trop haut ![image](https://user-images.githubusercontent.com/75901368/141484156-0bbce62e-63ce-48d7-9029-3c475aadf983.png)

On sait qu'on jase théorie pcq Pour JF 250Go était déà un cas extrème. mais pour le fun, on passe sur 2 lignes, voir plus. les contenus doivent être alignés par le centre donc on ne peut pas pousser les contenus simplement vers le bas mais j'ai ajouté un petit padding pour que ça soit plus joli sur mobile avec du texte à profusion et sans que ça ne se voit trop quand on a un texte conforme (ex: 10 G0)

2021-11-15 15:46 UTC, JonathanLefebvreV approved these changes

2021-11-15 15:47 UTC, merged