Ds 202 card subtitle
bifrost-vui/bifrost-front-end-library pull request #204
Opened 2021-11-11 15:00 UTC by famareme

2021-11-12 15:34 UTC, JonathanLefebvreV requested changes
Il manque le changement du changelog

2021-11-12 15:34 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +            <{{ subTitleTag|default('h5') }} class='h5 mt-0 mb-1'>
La propriété `subTitleTag` est gérer dans le composant, mais indisponible dans l'api.
De plus, documenté dans storybook le default une fois gérer.
⚠️ Attendre la confirmation des @bifrost-vui/ui-designer pour savoir si c'est requis pour le SEO ou non.

2021-11-12 15:34 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/phone.twig
> +    subTitle                : subTitle|default(null),
Changer aussi la story  avec une valeur "SubTitle".

2021-11-12 16:32 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +            <{{ subTitleTag|default('h5') }} class='h5 mt-0 mb-1'>
Confirmé par JF, on n'A pas besoin de subTitleTag. Donc enlevé cette gestion du tag et mettre un p.
La description du Jira a été ajusté

2021-11-12 19:43 UTC, famareme commented on projects/front-end-library/src/lib/components/card/twig/phone.twig
> +    subTitle                : subTitle|default(null),
Vu que subTitle pourrait être utilisé sur n'importe quel Card, je l'ai rajouté dans tout les autres Card twig et dans toutes les stories

2021-11-15 15:48 UTC, JonathanLefebvreV commented
https://github.com/bifrost-vui/bifrost-front-end-library/pull/203 a été mergé.
Faire un update de cette branche avec Master et s'assurer que le subTitle est fonctionnel avec la nouvelle story de la carte Combo

2021-11-15 18:48 UTC, bibifrost commented on projects/front-end-library/src/lib/components/card/_doc/doc.stories.mdx
> +    subTitle        : 'subTitle',
**subtitle** est un mot en anglais, contrairement à **uppertitle**. Ce qui justifie le fait d'avoir un t masjucule pour upper**T**itle et non pour sub**t**itle :)
= remplacer subTitle par subtitle.
En générale, avant d'ajouter une variable, tu peux regarder si elle est utilisé dans un autre composant.

2021-11-15 18:48 UTC, bibifrost commented on projects/front-end-library/src/lib/components/card/angular/card.component.ts
> +    @Input() subTitle             : string;
aligner les  `:`

2021-11-15 18:48 UTC, bibifrost commented on projects/front-end-library/src/lib/components/card/_doc/doc.stories.mdx
>  {% include '@bf-components/card/twig/plan.twig' with {
@jfpoliquin  Est-ce vraiment une volonté d'avoir un subTitle?
J'ai le sentiment que ce rendu n'est pas idéal:
![image](https://user-images.githubusercontent.com/93746960/141837257-34aabc61-5e4d-41f3-a6b9-8c64b91e0b6f.png)
Je pose juste la question

2021-11-15 18:48 UTC, bibifrost commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +            <p class='h5 mt-1 mb-1'>
remplacer `mt-1 mb-1` par `my-1`

2021-11-17 14:57 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/_doc/doc.stories.mdx
>  {% include '@bf-components/card/twig/plan.twig' with {
Oui, c'est un besoin qui a été demandé. J'avais challengé pour utilisé peut être description à la place. mais ce n'était pas possible

2021-11-17 14:58 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/_doc/doc.stories.mdx
> +    subTitle        : 'subTitle',
corrigé

2021-11-17 14:59 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/angular/card.component.ts
> +    @Input() subTitle             : string;
corrigé

2021-11-17 15:00 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +            <p class='h5 mt-1 mb-1'>
valider

2021-11-17 15:04 UTC, JonathanLefebvreV requested changes
Ooups, il manque la story d'API Expose
Le ficheir `plan-api-exposed.stories.mdx est à modifier`

![image](https://user-images.githubusercontent.com/75901368/142225644-fae1456f-99ef-4846-b313-19c7697824de.png)

2021-11-17 21:11 UTC, JonathanLefebvreV approved these changes

2021-11-17 21:11 UTC, merged