Ds 198 add promotion badges in phone, plan and combo cards
bifrost-vui/bifrost-front-end-library pull request #205
Opened 2021-11-16 19:36 UTC by ThalieVideotron

2021-11-16 20:54 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +- Added promotion bages in `Card` using `promotionBadges`.
```suggestion
- Added promotion badges in `Card` using `promotionBadges`.
```

2021-11-16 20:56 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +- Added promotion bages in `Card` using `promotionBadges`.
bizarre... J'ai pu la capacité de commité a partir d'une suggestion...

2021-11-16 21:04 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +            <div class='d-flex  mx-3 mx-sm-4'>
```suggestion
            <div class='d-flex mx-3 mx-sm-4'>
```

2021-11-16 21:05 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +                'class'     : 'bf-card__content-badge mt-3  mx-3 mx-sm-4'
```suggestion
                'class'     : 'bf-card__content-badge mt-3 mx-3 mx-sm-4'
```

2021-11-16 21:18 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +            <div class='bf-card__content-badge bf-card__content-badge--promotion mt-3  mx-3 mx-sm-4'>
Ca me parrait bizarre à lire. J'ai l'impression c'est très BEM d'avoir 2 classes qui ce répète d'un le suffixe change

2021-11-16 21:24 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +            <div class='bf-card__content-badge bf-card__content-badge--promotion mt-3  mx-3 mx-sm-4'>
Ce que je veux dire, c'est pourquoi que `bf-card__content-badge--promotion` est pas une extention de `bf-card__content-badge` ?

2021-11-16 21:24 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +            <div class='bf-card__content-badge bf-card__content-badge--promotion mt-3  mx-3 mx-sm-4'>
@bibifrost Ton option?

2021-11-16 21:26 UTC, JonathanLefebvreV requested changes
Fixé les espacements et voir pour la nomemclarure CSS

2021-11-17 14:12 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +            <div class='bf-card__content-badge bf-card__content-badge--promotion mt-3  mx-3 mx-sm-4'>
juste au dessus le badge credit-retour utilise la classe  `bf-card__content-badge`
pour les badges de promotion, on utilise `bf-card__content-badge--promotion` qui simplement est une variante de `bf-card__content-badge` (donc en BEM on met les 2 classes : élément + modifier). 
j'aurais pu avoir une classe `bf-card__promotion-badge` si on préfère mais ça me semblait plus logique de faire une variante (modifier - pcq ç'est le même composant, dans la même zone de contenu)

2021-11-17 14:35 UTC, ThalieVideotron commented on CHANGELOG.mdx
> +- Added promotion bages in `Card` using `promotionBadges`.
moi je l'ai
PTI - et ça fait un resolve automatique si j'accepte le changement

2021-11-17 15:19 UTC, bibifrost requested changes

2021-11-17 15:19 UTC, bibifrost commented on projects/front-end-library/src/lib/components/card/scss/index.scss
>          width: min-content;
pour l'ellispis:
```
.bf-badge__label {
    overflow: hidden;
    text-overflow: ellipsis;
    display: -webkit-box;
    -webkit-line-clamp: 1;
    -webkit-box-orient: vertical;
    white-space: normal;
```

2021-11-17 15:33 UTC, bibifrost commented on projects/front-end-library/src/lib/components/card/twig/combo.twig
>      language                : language|default('en'),
Ne pas oublier d'ajouter :
`subtitle                : subtitle|default(null),`

2021-11-18 13:43 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/scss/index.scss
> +        &--promotion .bf-badge {
good point - de mon point de vue on devrait en faire un jira ou au moins une discussion d'équipe - ramené dans le channel teams pour ne pas que ça glisse sous le tapis : https://teams.microsoft.com/l/message/19:7ae85c04b6a64083a09b39217d1f1b33@thread.tacv2/1637242961083?tenantId=4fc25658-72c2-42bf-913c-cb9ae315a689&groupId=e036d4f9-db1f-4c18-85e9-3a2db08115ed&parentMessageId=1637242961083&teamName=Syst%C3%A8me%20de%20design&channelName=Demandes%20d%20ajout%20ou%20de%20modif&createdTime=1637242961083
par contre je ne suis pas certaine qu'on le règle dans cette branche

2021-11-18 13:45 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +            <div class='bf-card__content-badge bf-card__content-badge--promotion mt-3  mx-3 mx-sm-4'>
okidoo

2021-11-18 13:53 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/scss/index.scss
>          width: min-content;
Ce serait une décision de @bifrost-vui/ui-designer. 
Mon option UI serait "pas d'elipsis". Je crain que ca brise le référencement visuel de la promotion

2021-11-18 13:55 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/combo.twig
>      language                : language|default('en'),
C'est fait dans https://github.com/bifrost-vui/bifrost-front-end-library/pull/204
Vérifié si la branche est pas updaté avec Master ou si il y a eu une erreur de merge

2021-11-18 14:03 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/scss/index.scss
> +        &--promotion .bf-badge {
> Que veux-on en front-end? Est-on sur que ce style de Badge ne sera pas utilisé ailleurs?

Non, ils sont aussi à utilisé "très éventuellement" pour faire des filtres de sélection de promotion. mais c'est supposé être une "chip" quand elle sera clicable. 
On verra quand on sera rendu là.

> Si on en fait une variante de Badge
On en fait pas. La badge a un état rounded. 

> Ce style met beaucoup d'emphase sur le badge. 
Effectivement je suis d'accord, @bifrost-vui/ui-designer Qu'est-ce que ca doit avoir l'air dans une carte disabled? J'aurais pensé qu'il reste sur fond blanc

2021-11-18 14:46 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +        {% if promotionBadges is defined and promotionBadges is not empty %}
tout à fait d'accord je m'étais alignée sur ce qui existait mais j'ai fait le tour de la page et j'ai généralisé la pratique - il n'y a plus de `is not empty`

2021-11-18 15:57 UTC, jfpoliquin commented on projects/front-end-library/src/lib/components/card/scss/index.scss
>          width: min-content;
Je suis en accord avec @JonathanLefebvreV . Je serais plus à l'aise d'avoir des cas où ça se retrouverait sur 2 lignes.

2021-11-18 16:11 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/scss/index.scss
> +        &--promotion .bf-badge {
en attente d'une réponse @bifrost-vui/ui-designer pour intervenir
@JonathanLefebvreV 
pour le moment le statut disabled est défini par le disabled de Badge et ça donne ça
![image](https://user-images.githubusercontent.com/82388009/142452398-168b52bd-cc2e-40b2-9e1b-ee98e039a9fd.png) - est-ce un autre cas de jira distinct ou ça dépend de la réponse de @bifrost-vui/ui-designer ?

2021-11-18 16:18 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/scss/index.scss
> +        &--promotion .bf-badge {
@bifrost-vui/ui-designer 
Pour la carte seulement :  je viens de remarquer qu'en mode disabled le badge de promo en haut de la carte n'est plus visible. par contre les badge de contenu restent visibles (même chose pour les boutons). Est-ce que la solution simple et rapide ne serait pas de les faire disparaître (toutes les badges de contenu) ? 
![image](https://user-images.githubusercontent.com/82388009/142453693-cd79766a-cfc1-42dd-9690-16f1e428897d.png)
Nous nous pencherions sur les états des badges dans un second temps?

2021-11-21 16:18 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/scss/index.scss
>          width: min-content;
Resolved: TODO for https://videotron-design-system.atlassian.net/browse/DS-209

2021-11-21 16:19 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/scss/index.scss
> +        &--promotion .bf-badge {
Revolved: TODO for https://videotron-design-system.atlassian.net/browse/DS-210

2021-11-21 16:20 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/scss/index.scss
> +            & + .bf-badge{
```suggestion
            & + .bf-badge {
```

2021-11-21 16:21 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/scss/index.scss
> +        .bf-card__content-badge{
```suggestion
        .bf-card__content-badge {
```

2021-11-21 16:24 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +                        hierarchy   : 'terciary-ground',
Validate

2021-11-21 16:26 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/angular/card.component.ts
> +    @Input() promotionBadges        : string[];
@ThalieVideotron c'est pas fait. `note` sépare encore les 2 Property lié au Badge

2021-11-21 16:29 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +        {% if promotionBadges is defined and promotionBadges is not empty %}
validated

2021-11-21 16:30 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/combo.twig
>      language                : language|default('en'),
validated

2021-11-22 13:42 UTC, ThalieVideotron commented on CHANGELOG.mdx
> +- Added promotion badges in `Card` using `promotionBadges`. This option may be used in `plan`, `phone` and `combo` card variants
l'ajout de promotion badge  n'est disponible que dans plan, phone et combo. Ceci dit, aussi bien le rendre accessible dans input-increment et protection (done)

changelog harmonisé

2021-11-22 13:45 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/angular/card.component.ts
> +    @Input() promotionBadges        : string[];
position de contentBadge et promotionBadges  uniformisé
 leur place est toujours au-dessus de price (dans le .ts, les twig et la doc)

2021-11-22 14:22 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/_doc/doc.stories.mdx
> +    subtitle        : 'subtitle',
subtitle -> dans plans, increment ou protection ce libellé ne fait pas de sens - lorem Ipsum ça sera pour ces cartes-là

ceci dit ça aurait du être souligné dans le jira qui ajoute le sous-titres - il faut éviter de faire des demandes out of scope pcq ça détourne l'attention du scope en cours

2021-11-22 14:35 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/_doc/doc.stories.mdx
> +        'Lorem Ipsum promotion 1',
il y en a 1 en anglais  et  pour celui avec icône on peut broder/traduire celui en français dans figma (on a un iône qui correspond).

2021-11-22 16:29 UTC, ThalieVideotron commented
la propriété visualBackgroundColor crée un bug dans Storybook : j'ouvre un Jira pcq que c'est propablement lié à l'update storybook.

2021-11-23 00:51 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/angular/card.component.ts
> +    @Input() promotionBadges        : string[];
validated

2021-11-23 00:53 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +- Added promotion badges in `Card` using `promotionBadges`. This option may be used in `plan`, `phone` and `combo` card variants
C'était pas à faire. Le titre du Jira dit clairement "card phone, plan & combo"...
On va vivre avec

2021-11-23 00:57 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/_doc/doc.stories.mdx
> +    subtitle        : 'subtitle',
done

2021-11-23 01:00 UTC, JonathanLefebvreV approved these changes

2021-11-23 01:02 UTC, merged