Added title in Price Promotion
bifrost-vui/bifrost-front-end-library pull request #206
Opened 2021-11-17 14:00 UTC by famareme

Managed the css file
Added title in Card Promotion

2021-11-17 15:27 UTC, bibifrost commented on projects/front-end-library/src/lib/components/price/twig/index.twig
> +      {% if promotion.title is defined and promotion.title is not empty %}
tu peux remplacer
`{% if promotion.title is defined and promotion.title is not empty %}`
par
`{% if promotion.title is defined and promotion.title %}`
c'est le meme resultat

2021-11-18 04:27 UTC, bibifrost commented on projects/front-end-library/src/lib/components/card/_doc/doc.stories.mdx
>          cent            : 99,
Je viens de voir une legere regression:
Normalement quand tu passes `fullWidth` à true, le bloc promotion devrait se caler à droite. 

Ça marchait encore dans ta PR text-2-lines:
https://bifrost-front-end-library-git-ds-107-text-2-lines-bifrost-vui.vercel.app/?path=/story/components-price--drupal&args=fullWidth:true
![image](https://user-images.githubusercontent.com/93746960/142351298-13bbcf95-9f3b-4715-9e1f-29ae6e9bae78.png)

2021-11-18 04:27 UTC, bibifrost commented on projects/front-end-library/src/lib/components/price/angular/price.component.ts
> +  title  : string,
indentation

2021-11-18 04:27 UTC, bibifrost commented on projects/front-end-library/src/lib/components/price/twig/index.twig
> +        <p class="small mb-1">
double quote => single quote

2021-11-18 04:27 UTC, bibifrost commented on projects/front-end-library/src/lib/components/price/twig/index.twig
> +      <div class="d-flex flex-column">
single cote

2021-11-18 04:27 UTC, bibifrost commented on projects/front-end-library/src/lib/components/price/_doc/null.drupal.twig
> +                    title  : NULL,
indentation

2021-11-18 20:28 UTC, JonathanLefebvreV requested changes
regression:
On Master:
![image](https://user-images.githubusercontent.com/75901368/142490521-e4e321ae-620e-410a-8c10-83621bb60bca.png)

On branch:
![image](https://user-images.githubusercontent.com/75901368/142490558-ec004d70-1a9f-40ca-85cc-fd4a733871e9.png)

Bug:
![image](https://user-images.githubusercontent.com/75901368/142491229-304f6875-cd8b-4dc8-94b8-d69ebca756ca.png)
Le rendu n'est pas adéquant. Les espace identifié en rouge ne devrait pas existé
https://bifrost-front-end-library-git-ds-197-price-r-eb442a-bifrost-vui.vercel.app/?path=/story/components-price--drupal&args=hasAsterisk:true;size:large

@JonathanLefebvreV  Ceci n'est pas un bug; ils sont centrés; si on veut pas d'espace quand on rajoute beaucoup texte il faudra qu'il soit alignés au top, au bottom ou au centre. Alors comment souhaitez-vous qu'ils soient alignés?

2021-11-23 00:44 UTC, JonathanLefebvreV requested changes
La régression de l'astérix est encore présent

2021-11-23 20:00 UTC, famareme commented
> La régression de l'astérix est encore présent

voila ce que j'ai en local et remote:
![image](https://user-images.githubusercontent.com/87377125/143095081-b0beb225-da8c-4dde-b9e4-38395d900299.png)
Peux-tu être plus précis au niveau de l'astérisque

2021-11-23 23:24 UTC, bibifrost commented
> > La régression de l'astérix est encore présent
> 
> voila ce que j'ai en local et remote: ![image](https://user-images.githubusercontent.com/87377125/143095081-b0beb225-da8c-4dde-b9e4-38395d900299.png) Peux-tu être plus précis au niveau de l'astérisque

Tres cool pour les alignements 👍 
Jonathan parle du positionnement de l'asterisk je guess. Elle semble être plus basse que sur master. Elle l'était deja un peu trop avant cependant :)

2021-11-24 01:02 UTC, JonathanLefebvreV commented
> regression: On Master: ![image](https://user-images.githubusercontent.com/75901368/142490521-e4e321ae-620e-410a-8c10-83621bb60bca.png)
> 
> On branch: ![image](https://user-images.githubusercontent.com/75901368/142490558-ec004d70-1a9f-40ca-85cc-fd4a733871e9.png)
> 
Qu'est-ce qui a besoin d'être plus précis @famareme ?

2021-11-24 13:57 UTC, famareme commented
> > regression: On Master: ![image](https://user-images.githubusercontent.com/75901368/142490521-e4e321ae-620e-410a-8c10-83621bb60bca.png)
> > On branch: ![image](https://user-images.githubusercontent.com/75901368/142490558-ec004d70-1a9f-40ca-85cc-fd4a733871e9.png)
> 
> Qu'est-ce qui a besoin d'être plus précis @famareme ?

Ceci est déjà réglé; l'astérisque n'est pas plus aligné au centre

2021-11-25 01:28 UTC, JonathanLefebvreV approved these changes

2021-11-25 01:28 UTC, JonathanLefebvreV commented
✔️ tested on IPhone

2021-11-25 01:29 UTC, merged