ds-181 create showcase angular
bifrost-vui/bifrost-front-end-library pull request #209
Opened 2021-11-18 14:15 UTC by bibifrost

2021-11-22 06:34 UTC, bibifrost commented
@JonathanLefebvreV ,
Comment ça se passe avec Vercel? Si on le garde, alors on pourrait l'utiliser pour builder le showcase angular.

2021-11-23 19:53 UTC, JonathanLefebvreV commented
> @JonathanLefebvreV , Comment ça se passe avec Vercel? Si on le garde, alors on pourrait l'utiliser pour builder le showcase angular.

Bah, ca va, on paie pour 4 le temps qu'on est juste 4. Ca va redevenir une priorité de s'en débarassé, avec les collaborateur externe (que le PR ne se déploira pas). On va peut être aussi le gardé selon le budget du plan de restructuration 2022.

Mettre le show-case dans Vercel? Faudrait, je me joue un peu avec pour me faire une idée. Je ne sais pas si on devrait l'inclure dans le pipeline et si Vercel pour faire 2 sites avec 1 seul PR (J'ai un gros doute) C'est un doute qui confirme que si on veut le mettre procédure QC, il va peut être faloir le mettre dans ca propre strucutre npm/repo... 

A moins que le showcase soit "builder" avec storybook... (Je réfléchie à haute fois)

2021-11-23 23:20 UTC, bibifrost commented
> > @JonathanLefebvreV , Comment ça se passe avec Vercel? Si on le garde, alors on pourrait l'utiliser pour builder le showcase angular.
> 
> Bah, ca va, on paie pour 4 le temps qu'on est juste 4. Ca va redevenir une priorité de s'en débarassé, avec les collaborateur externe (que le PR ne se déploira pas). On va peut être aussi le gardé selon le budget du plan de restructuration 2022.
> 
> Mettre le show-case dans Vercel? Faudrait, je me joue un peu avec pour me faire une idée. Je ne sais pas si on devrait l'inclure dans le pipeline et si Vercel pour faire 2 sites avec 1 seul PR (J'ai un gros doute) C'est un doute qui confirme que si on veut le mettre procédure QC, il va peut être faloir le mettre dans ca propre strucutre npm/repo...
> 
> A moins que le showcase soit "builder" avec storybook... (Je réfléchie à haute fois)

Oui, je partage tes questionnements. Tout un sujet le build :)
Par rapport au repo, a noter que 100% des design-system que j'ai étudié sont en monorepo et gèrent donc les showcases dans le meme repo que les composants. Mais bon on fait comme on veux.

2021-11-24 01:06 UTC, JonathanLefebvreV commented
ok noté. On checkera ca 👍

2021-12-07 16:30 UTC, bibifrost commented
@JonathanLefebvreV , qu'est ce qui nous empêche de merger et de packager le badge Angular dans le prochain package pour que Etiya puisse tester?

2022-01-27 14:00 UTC, bibifrost commented
a mon avis, @JonathanLefebvreV Pour que Kursat puisse utiliser le package, il faudrait merger cette PR.

2022-01-30 13:53 UTC, JonathanLefebvreV requested changes
Les icones du composantes ne fonctionne pas.
![image](https://user-images.githubusercontent.com/75901368/151702555-acb336fb-9a09-45f2-a580-e7204724659d.png)

Expected:
![image](https://user-images.githubusercontent.com/75901368/151702610-779acfa3-2b67-4a7b-b4f9-d876e71e88eb.png)

2022-01-30 13:53 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/_doc/template.angular.html
> +        <div class='d-flex flex-column flex-sm-row justify-content-center gap-4 p-4' [ngClass]='{"reversed bf-color-bg-ground": template === 2}'>
`twig` and `html` file should have 2 spaces indent, not 4

2022-01-30 13:53 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/angular/badge.component.html
> +    <div class='bf-badge__inner position-relative d-flex align-items-center'>
`twig` and `html` file should have 2 spaces indent, not 4

2022-01-30 13:53 UTC, JonathanLefebvreV commented on projects/showcase-angular/src/app/app.component.html
> +    <div class='container py-5'>
`twig` and `html` file should have 2 spaces indent, not 4

2022-01-30 13:53 UTC, JonathanLefebvreV commented on projects/showcase-angular/src/app/app.component.ts
> +  title = 'showcase-angular';
Other file than `twig` and `html` should have 4 spaces indent, not 2

2022-01-30 13:53 UTC, JonathanLefebvreV commented on projects/showcase-angular/src/app/app.module.ts
> +  imports: [
Other file than `twig` and `html` should have 4 spaces indent, not 2

2022-01-30 13:53 UTC, JonathanLefebvreV commented on projects/showcase-angular/src/environments/environment.prod.ts
> +  production: true
Other file than `twig` and `html` should have 4 spaces indent, not 2

2022-01-30 13:53 UTC, JonathanLefebvreV commented on projects/showcase-angular/src/environments/environment.ts
> +};
Other file than `twig` and `html` should have 4 spaces indent, not 2

2022-01-30 13:53 UTC, JonathanLefebvreV commented on projects/showcase-angular/src/main.ts
> +}
Other file than `twig` and `html` should have 4 spaces indent, not 2

2022-01-30 13:53 UTC, JonathanLefebvreV commented on projects/showcase-angular/src/test.ts
> +} from '@angular/platform-browser-dynamic/testing';
Other file than `twig` and `html` should have 4 spaces indent, not 2

2022-01-30 13:53 UTC, JonathanLefebvreV commented on projects/showcase-angular/tsconfig.app.json
> +    "outDir": "../../out-tsc/app",
Other file than `twig` and `html` should have 4 spaces indent, not 2

2022-01-30 13:53 UTC, JonathanLefebvreV commented on projects/showcase-angular/tsconfig.spec.json
> +    "outDir": "../../out-tsc/spec",
Other file than `twig` and `html` should have 4 spaces indent, not 2

2022-01-30 13:53 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/angular/badge.component.ts
> +    @Input() classes        : string;
Même si je suis d'accord avec le principe. Ce n'est pas l'endroit pour faire cela, car ça introduit un breaking-change dans le composant, qui au minimum devrait être réflété dans le changelog et au mieux devrait suivre une procédure de deprecation. 

C'est quand même un petit composant que je ne crois pas que DXP utilise directement.

Pour évité qu'il ai maintenant une non uniformité dans les nom des variable "class" vs "classes" cela devrait être refactoré, sur tout le composante, en même temps, dans un autre PR

Ma recommendation:
- Revert la ligne et les implications
- Créer un Jira "refactor class property to classes for all component"

2022-02-03 09:35 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/angular/badge.component.html
> +    <div class='bf-badge__inner position-relative d-flex align-items-center'>
Bien vu.

2022-02-03 09:35 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/angular/badge.component.ts
> +    @Input() classes        : string;
Effectivement il y a un manquement ici. Plusieurs points de reflexion:
- Ceci va uniquement affecter la documentation et non le composant Twig (donc pas de breaking change).
- D'accord avec toi pour la PR a part. Dans l'idéal, Il faudra changer tous les `class` en `classes` pour tous les composants.
En attendant, pour que l'on puisse builder une lib Angular, je propose d'afficher les 2 comme ceci dans la doc:
```
/* Drupal only */
@Input() class          : string;
/* Angular only */
@Input() classes        : string;
```
Puis quand DXP sera prêt à merger la PR **classes**, on supprimera les `@Input class`.

2022-02-03 09:35 UTC, bibifrost commented on projects/showcase-angular/tsconfig.spec.json
> +    "outDir": "../../out-tsc/spec",
C'est Angular qui génère ces fichiers à la creation de la lib. Si on change l'indent, il faudra surement le rechanger quand on fera des update d'Angular. C'est rare mais est-ce vraiment pertinent?

2022-02-03 09:35 UTC, bibifrost commented on angular.json
> +            "scripts": []
Le genre de truc qui va revenir quand Kursat va importer le Badge. Meme si je ne suis pas sur que ce soit un enjeux car c'est très proche du UI-KIT.

2022-02-03 09:35 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/angular/badge.component.ts
> +    @Input() classes        : string;
Note: Je pense à changer `classes` pour `className`, car le terme `classes` présuppose que c'est un array. Or c'est une string.

2022-02-03 10:02 UTC, bibifrost commented
> Les icones du composantes ne fonctionne pas. ![image](https://user-images.githubusercontent.com/75901368/151702555-acb336fb-9a09-45f2-a580-e7204724659d.png)
> 
> Expected: ![image](https://user-images.githubusercontent.com/75901368/151702610-779acfa3-2b67-4a7b-b4f9-d876e71e88eb.png)

Oui. Il faudrait merger la [PR de lib icon](https://github.com/bifrost-vui/bifrost-front-end-library/pull/157) pour utiliser les icones dans Angular. Mais je vais regarder si on peux commencer plus simplement.

2022-02-03 13:53 UTC, JonathanLefebvreV commented
Malheureusement ça arrivera pas. Il y a aucune change qu'on puisse introduire ce breaking change chez DXP.
A moins que tu es un plan pour ne pas avoir le breaking- change?

2022-02-07 15:30 UTC, bibifrost commented
> Malheureusement ça arrivera pas. Il y a aucune change qu'on puisse introduire ce breaking change chez DXP. A moins que tu es un plan pour ne pas avoir le breaking- change?

Tu parles de la lib d'icones?
A voir effectivement le cout de la mise a jour. **Coté DXP,** c'est surtout des path à changer à mon avis. `include @component/icons/twig` => `include @icons/twig`.
**Pour Angular**, je réfléchi à une gestion des icônes qui affecterait le moins possible la structure actuelle.

2022-02-18 14:24 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
> +import { Canvas, Meta, Story, Props } from '@storybook/addon-docs';
```suggestion
import { moduleMetadata }             from '@storybook/angular';
import { Canvas, Meta, Story, Props } from '@storybook/addon-docs';
```

2022-02-18 14:31 UTC, JonathanLefebvreV requested changes
The changeLog is missing. Now we need to implement a differentiation with Twig and Angular component in ChangeLog.

And because it's a documented component here : https://bifrost-front-end-library-vui.vercel.app/?path=/docs/component-list-overview--page
The page need to be updated as well

2022-02-19 14:14 UTC, JonathanLefebvreV approved these changes

2022-02-19 14:14 UTC, merged