ds-189-adjust slideshow height
bifrost-vui/bifrost-front-end-library pull request #210
Opened 2021-11-19 17:09 UTC by bibifrost

2021-11-23 14:00 UTC, famareme requested changes
Le terme 'large' n'est pas approprié pour une hauteur. D'après le breackpoint qui ne s'applique qu'au media query md et up, desktop-height serait plus adéquat.
'large' pourrait être fixed-height et 'height' pourrait 'desktop-height'

2021-11-23 14:34 UTC, bibifrost commented
> Le terme 'large' n'est pas approprié pour une hauteur. D'après le breackpoint qui ne s'applique qu'au media query md et up, desktop-height serait plus adéquat. 'large' pourrait être fixed-height et 'height' pourrait 'desktop-height'

IMO, `large` est une abstraction qui doit être différencié du CSS. Car demain le CSS pourrait changer tout en gardant `size: large` valide.

2021-11-23 15:36 UTC, ThalieVideotron commented
> > Le terme 'large' n'est pas approprié pour une hauteur. D'après le breackpoint qui ne s'applique qu'au media query md et up, desktop-height serait plus adéquat. 'large' pourrait être fixed-height et 'height' pourrait 'desktop-height'
> 
> IMO, `large` est une abstraction qui doit être différencié du CSS. Car demain le CSS pourrait changer tout en gardant `size: large` valide.

moi aussi je trouve que large n'est pas adapté pour une hauteur et je suis plus à l'aise avec la notion de `fixedHeight` qui est exactement ce que fait la propriété

2021-11-23 15:42 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/slideshow/js/index.js
> +    adaptiveHeight: false,
pourquoi ne pas utiliser cette fonctionnalité du pluggin au profit d'une solution maison? Elle fonctionne très bien sur desktop. Je me serait attendu à une solution maison qui n'affecte que les mobiles

parallèlement, si cette propriété n'es plus utilisée, je la supprimerait plutôt que de la mettre à false

2021-11-23 15:42 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/slideshow/scss/index.scss
> +            gap: 0;
ce code devrait être dans un media query pour n'affecter que les mobiles et pour desktop on devrait utiliser la fonctionnalité de Slick

2021-11-25 15:43 UTC, JonathanLefebvreV commented
✔️ Testé et l'activation de la fonctionnalité slick fonctionne très bien sur desktop et mobile.

Le `height: large` proprety va maintenant servir à 1 hero simple dans une page qui a besoin d'un hauteur particulière. 
C'est à dire problablement jamais. Donc, pas besoin d'optimiser cette propriété dans cette PR

2021-11-26 00:54 UTC, JonathanLefebvreV approved these changes

2021-11-26 00:55 UTC, merged