DS-210-Badge-disabled-layout
bifrost-vui/bifrost-front-end-library pull request #211
Opened 2021-11-19 20:10 UTC by ThalieVideotron

2021-11-21 15:52 UTC, JonathanLefebvreV requested changes
https://videotron-design-system.atlassian.net/browse/DS-210?focusedCommentId=10563

2021-11-21 19:55 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/_doc/template.drupal.twig
>  {% set isRounded    = isRounded|json_parse %}
Je ne comprends pa pourquoi le style disabled de secondary est un outline. Le style disabled outline devrait s'afficher uniquement quand le badge est outline, soit promotionBadges pour le moment.
![image](https://user-images.githubusercontent.com/93746960/142776886-2f757124-12a5-410a-b0bd-a58e812944e9.png)
![image](https://user-images.githubusercontent.com/93746960/142776878-0bda5b78-5871-4a6c-a97e-1eea953dba0c.png)

2021-11-22 20:43 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/badge/_doc/template.drupal.twig
>  {% set isRounded    = isRounded|json_parse %}
c'est exactement comme bouton - je crois que c'est pour qu'il conserve une apparence de block mais j'ai simplement appliqué la recette comme tu l'as suggéré. 

![image](https://user-images.githubusercontent.com/82388009/142932145-7bca61a0-96b1-4dc4-95cc-f0fa0b8f4cfe.png)

souhaites-tu qu'on challenge cette bordure auprès de @jfpoliquin ?

2021-11-23 13:17 UTC, ThalieVideotron commented
> https://videotron-design-system.atlassian.net/browse/DS-210?focusedCommentId=10563

tel que discuté, l'état disabled est dans une nouvelle story : `Drupal - disabled usage example`

2021-11-23 14:30 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/_doc/template.drupal.twig
>  {% set isRounded    = isRounded|json_parse %}
Oui, je parlais de se rapprocher des styles disabled de bouton, mais je me suis auto-challenger par la suite :)
Le style disabled devrait être en fonction de l'état default du composant. Si **secondary** n'a pas de border par défaut, alors il ne devrait pas en avoir en disabled.
@bifrost-vui/ui-designer ?

2021-11-23 14:49 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
> +        name='Drupal - disabled usage example'
`usage example` = Exemple de composition de composants. Par exemple, une composition de plusieurs input pour montrer comment faire un form.
ici c'est juste `name='Drupal - Disabled`.
Et si demain on a plusieur states on pourrait ecrire: `name='Drupal - State disabled` pour les réunir ensemble.

2021-11-23 15:55 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/badge/_doc/template.drupal.twig
>  {% set isRounded    = isRounded|json_parse %}
en attente d'une décision design 

- Valider si on doit supprimer la bordure autour d'un badge secondary + disabled 
- Créer un nouveau Jira si le changement doit aussi être fait dans Button (pas obligé que les 2 composants aient le même comportement au disabled)

2021-11-23 16:04 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
> +        name='Drupal - disabled usage example'
@bibifrost. il n'y a pas de propriété disabled dans le composant et c'est ce qui me bug avec `name='Drupal - Disabled` c'est que ça laisse supposer que le badge puisse avoir un état `disabled` alors que c'est nécessairement un état hérité du parent - t'as une idée pour refléter cette nuance?

2021-11-23 17:15 UTC, baptistemac commented on projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
> +        name='Drupal - disabled usage example'
Bien vu.
Dans ce cas j'irais avec `State disabled`. Demain on pourrait avoir `State hover`, `State focus`,...

Je pose la question, pourquoi ne pas introduire un control `isDisabled` qui ajouterait une classe CSS .disabled au bf-badge? Car le badge pourrait par exemple s'afficher seul dans un style disabled.

2021-11-23 17:19 UTC, baptistemac commented on projects/front-end-library/src/lib/components/badge/_doc/template.drupal.twig
>  {% set isRounded    = isRounded|json_parse %}
Merci.

Je ne vois pas de raison de changer button cependant car ils respectent déjà cette règle.

2021-11-23 18:49 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
> +        name='Drupal - disabled usage example'
La propiété "class" permet d'injecté une classe "disabled" étant donner que ce n'est pas une struture html qui a besoin d'être gérer contrairement à un input... mais pourquoi pas pour standardisé les API.
Anyway, out of scope. C'est une idée à mettre dans le backlog

2021-11-23 18:53 UTC, JonathanLefebvreV requested changes

2021-11-23 18:53 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/scss/index.scss
> +        }
Refaire le style du cette ajout
(indentation, saut de ligne, espacement

2021-11-23 19:03 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/badge/_doc/template.drupal.twig
>  {% set isRounded    = isRounded|json_parse %}
bye bye bordure alors

2021-11-23 19:04 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
> +        name='Drupal - disabled usage example'
thecniquement c'est une composition. mais va pour `name='Drupal - Disabled`

Pourquoi aurait-on un contrôle  isDisabled? 
il n'y a aucune interaction utilisateur sur un badge - c'est ce qui me rend mal à l'aise avec l'usage du terme state et vraiment réticente à un contrôle. 

l'apparence disabled est toujours hérité du parent mais n'est pas un état du badge lui-même.  
il n'y aura jamais de focus sur un badge mais sur son parent et dans ce contexte, le badge ne devrait aucunement en être affecté, idem pour selected ou hover... il n'y a tout simplement pas d'état dans un badge

Point de vue HTML seul les tag interactifs on un état. On triche ici et là en mettant une classe disabled sur un composant plus complexe mais là encore, ces composants ont un comportement interactif (card, banner, selectionTile, block selection...) donc ça se justifie

2021-11-23 19:21 UTC, JonathanLefebvreV requested changes
Il y a de hiearchie a faire sur des badged, donc quand il sont disabled, les mettre tous sur le même style, ~~sauf le "rounded" pour qu'il ai ca bordure~~, je note que le border du badge "rounded" vient d'une customisation des style de badge pour les card uniquement.
Donc dans cette PR on ne devrait pas voir de border

Rappe: on cache les badges dans un carte disabled

2021-11-23 19:21 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/scss/index.scss
> +                background-color: transparent;
A enlevé que ca donne le même style que `primary`

2021-11-23 19:21 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/scss/index.scss
> +                    border-top: 1px solid  var(--bf-color-stroke-secondary);
A enlever, que ca donne juste le background sans bordure

2021-11-23 19:21 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/scss/index.scss
> +                    border-top: 1px solid  var(--bf-color-stroke-secondary);
A enlevé, que ca donne le background sans border

2021-11-23 19:21 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/scss/index.scss
> +            background-color: transparent;
A enlevé pour qu'il est l'effet background comme les autres.

2021-11-23 19:33 UTC, JonathanLefebvreV commented
Après, ces modif. la story devrait ressembler à ça 
![image](https://user-images.githubusercontent.com/75901368/143091568-b0388ce3-06db-4ddc-8031-81a3be69084b.png)

2021-11-23 19:39 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/_doc/template.drupal.twig
>  {% set isRounded    = isRounded|json_parse %}
Je ferme cette discussion. A suivre le reste de mes commentaire pour faire au plus simple maintenant. Et on verra dans le temps pour mettre une complémentarité de style sur les badges si on a plus de besoin lié au "disabled"

2021-11-23 20:45 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/badge/scss/index.scss
> +        }
gros nettoyage. excellente idée de faire disparaitre les hierarchies au disabled.

2021-11-23 22:44 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
> +        name='Drupal - disabled usage example'
Bon point. En fait, c'est la meme chose que les Cards, elles ont un **état disabled** qui correspond non pas au disabled des input HTML mais bien à l'apparence de la Card, par exemple ça fait disparaitre les boutons, les badges, l'opacité est réduite partout sauf sur le message... C'est la meme chose pour un Badge, l'état disabled correspond a un changement d'apparence car en gros, **control isDisabled != input Disabled**.
C'est un détails anyway, on pourra y revenir plus tard.

2021-11-23 22:48 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
> +    style = {{ height: '600px'}}
espace autour du `=` + apres `px'`

2021-11-23 22:48 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
> +        name='Drupal - disabled'
masjusule: Disabled

2021-11-23 22:48 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
> +        name='Drupal - disabled usage example'
A noter que tant qu'on aura pas de control `isDisabled`, on ne pourra pas faire de composant a l'état disabled contenant un badge non disabled. Car le badge dépend du parent.

2021-11-24 02:49 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
> +    style = {{ height: '600px'}}
`withSource='none'` est comme ca dans tous les mdx. Ca mérite sont propre refactor dans un autre autre PR.

2021-11-24 02:49 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
> +    style = {{ height: '600px'}}
```suggestion
    style = {{ height: '600px' }}
```

2021-11-24 02:50 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
> +    style = {{ height: '600px'}}
```suggestion
    style = {{ height: '600px' }}
```

2021-11-24 02:51 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/_doc/doc.stories.mdx
> +        name='Drupal - disabled'
```suggestion
        name='Drupal - Disabled'
```

2021-11-24 02:52 UTC, JonathanLefebvreV approved these changes
❤️

2021-11-24 02:54 UTC, merged