DS-207
bifrost-vui/bifrost-front-end-library pull request #217
Opened 2021-12-01 16:12 UTC by famareme

Create a story example of colors for selection-tile

2021-12-02 01:07 UTC, JonathanLefebvreV requested changes
L'example est inutilisable. 
La zone rouge doit être clickable (Ce qui n'est pas le cas présentement)
![image](https://user-images.githubusercontent.com/75901368/144339088-3299dc20-1b18-49e8-93ba-311b32b195ca.png)

✔️ Resolved

2021-12-02 01:07 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +          {{ content }}
De plus le nom du block a été choisi avec AppNovation. J'avais du snake_case parce qu'ils préfère cela et que le "uikit" était comme ca, mais vu qu'il faut monté cela en property et que nos property sont camelCase, on peut renommer le nom du block.

2021-12-02 01:14 UTC, JonathanLefebvreV requested changes

2021-12-02 01:14 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/_doc/example.drupal.twig
> +</style>
Le code est inutilisable si il n'est pas placé dans un scss. A déplacé proprement pour le rendre utilisable dans Drupal

2021-12-02 01:14 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/_doc/example.drupal.twig
> +                     </div>',
Ce rendu
![image](https://user-images.githubusercontent.com/75901368/144339501-8ed7c7e9-5ce8-4638-b0e9-abe54ebd1da8.png)


N'est pas égal à Figma en spacing et grosseur de la pastille
![image](https://user-images.githubusercontent.com/75901368/144339732-38eac0be-7daf-4f89-89a5-848e3d5525b9.png)

2021-12-02 17:02 UTC, famareme commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +          {{ content }}
> 
Twig-block-drupal template n'est jamais appelé dans Hero; La story appelle  template.drupal et hérite de ses propriétés par défaut puis rajoute un block.
Ce cas ci, je ne veux pas hérité des propriétés par défaut du template et je dois faire une loop pour afficher mon tableau de couleurs

2021-12-03 19:10 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/_doc/example.drupal.twig
> +</style>
@JonathanLefebvreV on se rapproche d'un variant en bonne et due forme non?

2021-12-03 19:19 UTC, ThalieVideotron requested changes

2021-12-03 19:19 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +<div class='bf-selection-tile bf-selection-tile--{{ orientation }} bf-selection-tile--{{ 'fit-' ~ fit }} {{ isInvalid ? 'color-warning' : '' }} {{ isDisabled ? 'disabled' }} {{ isSelected ? 'checked'
et si dans le twig block 'content' on a autre chose qu'une pastille de couleur?
je le mettrais davantage dans le example.twig  dans les arguments du include pour être safe
`class : 'bf-selection-tile--color-wrap ' ~ class`

2021-12-05 17:34 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/_doc/doc.stories.mdx
> +
```suggestion
```

2021-12-05 17:36 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
> +
```suggestion
```

2021-12-05 17:37 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/scss/index.scss
> +
```suggestion
```

2021-12-05 18:45 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +<div class='bf-selection-tile bf-selection-tile--{{ orientation }} bf-selection-tile--{{ 'fit-' ~ fit }} {{ isInvalid ? 'color-warning' : '' }} {{ isDisabled ? 'disabled' }} {{ isSelected ? 'checked'
Yes you're right

2021-12-05 18:49 UTC, JonathanLefebvreV approved these changes

2021-12-10 01:30 UTC, JonathanLefebvreV commented
@ThalieVideotron, un suivi sur le review?

2022-01-30 15:12 UTC, merged