ds-222-block-highlight-add-visualBackgroundFit
bifrost-vui/bifrost-front-end-library pull request #221
Opened 2021-12-02 17:34 UTC by bibifrost

2021-12-03 18:55 UTC, ThalieVideotron requested changes

2021-12-03 18:55 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/block-highlight/twig/index.twig
>      w-100 d-flex flex-column flex-sm-row overflow-hidden bf-border-radius-medium border bf-border-color-secondary
trop de classes à mon goût - plusieurs avec du important. Pourquoi on a un css? ( bf-block--highlight est vide dans le css)
les classes bf pourraient être dans le css avec un @extends
overflow-hidden n'est pas plus court que overflow: hidden dans le css ... 

bref, en général j'éviterais les classes bootstrap dans le index.twig parce qu'il faudra les remettre dans les composants anglular (sans en oublier) alors que les composants devraient avoir un css identique quel que soit le langage.  je ne conserverais que celles qui nous évitent de faire du media querry dans le scss

2021-12-03 18:55 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/block-highlight/twig/index.twig
> +    {{ reversed ? 'reversed' }}
ajouter le  ` and reversed is defined` ?

2021-12-03 18:55 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/block-highlight/twig/index.twig
>      {% if hasImage %}
ajouter le  ` and hasImage is defined` ?

2021-12-03 18:55 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/block-highlight/twig/index.twig
> +    bf-block bf-block--highlight {{ isFeatured ? 'bf-block--featured' }}
ajouter le  ` and isFeatured is defined` ?

2021-12-03 18:55 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/block-highlight/twig/index.twig
>      {% if hasImage %}
il y en a d'autres mais Git ne me permet pas de les commenter : 
ex : 
`{{ titleTag }}` : on ne check pas s'il est defined ou true et il n'y a pas de default et il n'est pas required... on pourrait avoir une balise qui resemble à ça `< class='text-break h2'></>` et je met ma main au feu que ce n'est pas valide

voir aussi
`{{ title }}`, `{{ button }}`, `{{ paragraph  }}`
`{% if paragraph is defined %}` devrait être `{% if paragraph is defined and paragraph %}`

2021-12-03 18:55 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/block-highlight/twig/index.twig
> +    <div class='d-flex flex-column {{ isFeatured ? 'justify-content-center' }} p-4 p-sm-5'>
ajouter le  ` and isFeatured is defined` ?

2021-12-03 18:55 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/block-highlight/twig/index.twig
ligne de trop

2021-12-03 18:55 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/block-highlight/_doc/doc.stories.mdx
> +            table: { defaultValue: { summary: 'contain' } },
ça serait cool de les mettre en select dans storybook - comme les autres

2021-12-03 18:55 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/block-highlight/_doc/doc.stories.mdx
> +                'storybook/docs/panel': { hidden: true }
cute comme feature mais  je laisserais les contrôles Storybook actifs à moins de les cacher dans toutes les stories d'exemple

2021-12-03 18:55 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/block-highlight/angular/block-highlight.component.ts
>      @Input() image                  : IImage;
pourquoi IImage ? c'est une image de Background (pas de alt)  et elle est toute seule (pas un array) donc string devrait suffire

2021-12-05 19:52 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/block-highlight/_doc/doc.stories.mdx
> +                'storybook/docs/panel': { hidden: true }
Faire un Jira avec le commentaire de @ThalieVideotron, parce que qu'elle a raison, mais ca n'a pas à être fait dans cette PR

2021-12-05 19:59 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/block-highlight/_doc/doc.stories.mdx
> +            table: { defaultValue: { summary: 'contain' } },
Les bouton radio sont acceptable comme type de contrôle dans storybook

2021-12-05 20:03 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/block-highlight/_doc/doc.stories.mdx
> +                'storybook/docs/panel': { hidden: true }
Ce qui est un vrai défaut dans storybook, C'est que ca cache le panel des propriété, mais pour toute la navigation dans storybook.
Donc, pour que cette modification soit valide il faudrait réactivé les propriété dans les storys
C'est pas trop le but de cette PR, donc le nouveau Jira doit aussi contenir la contrepartie.
- Activé le panneau dans les story
- désactivé le panneau dans les example qui en on pas besoin

2021-12-05 20:10 UTC, JonathanLefebvreV requested changes
Cette propriété ne fonctionne plus? (peu importe la combinaison de d'autre variable)
![image](https://user-images.githubusercontent.com/75901368/144762213-1354d4a7-0667-404c-9920-fc7e4aa311c4.png)

2021-12-06 19:29 UTC, bibifrost commented on projects/front-end-library/src/lib/components/block-highlight/twig/index.twig
>      {% if hasImage %}
`titleTag` est défini en haut de composant.
title, button, paragraph sont bien chéckés.

2021-12-06 19:38 UTC, bibifrost commented on projects/front-end-library/src/lib/components/block-highlight/_doc/doc.stories.mdx
> +            table: { defaultValue: { summary: 'contain' } },
oui quand il n'y a que 2 ou 3 choix, les radios sont interresssants.

2021-12-06 19:49 UTC, bibifrost commented on projects/front-end-library/src/lib/components/block-highlight/angular/block-highlight.component.ts
>      @Input() image                  : IImage;
Pour être consistent avec les autres API d'images. Mais c'est un bon point. J'ai longuement hésité.
Je vais y re-refléchir.

2021-12-06 20:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/block-highlight/twig/index.twig
> +    bf-block bf-block--highlight {{ isFeatured ? 'bf-block--featured' }}
validé ligne 3. Merci, je ne l'avais pas vu celui-la

2021-12-06 20:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/block-highlight/twig/index.twig
> +    <div class='d-flex flex-column {{ isFeatured ? 'justify-content-center' }} p-4 p-sm-5'>
done

2021-12-07 03:51 UTC, bibifrost commented
> Cette propriété ne fonctionne plus? (peu importe la combinaison de d'autre variable) ![image](https://user-images.githubusercontent.com/75901368/144762213-1354d4a7-0667-404c-9920-fc7e4aa311c4.png)

Ça fonctionne. C'est juste que l'opacité est à 0 dans le rgba :)

2021-12-07 14:00 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/block-highlight/twig/index.twig
>      w-100 d-flex flex-column flex-sm-row overflow-hidden bf-border-radius-medium border bf-border-color-secondary
le bout important c'est  : 'il faudra les **remettre dans les composants anglular** alors que les composants devraient avoir un css identique quel que soit le langage.
donc quand on aura un fix à faire on le fera dans les 2 langages et **bifrost.css s'éloigne de la source de vérité**

2021-12-07 14:04 UTC, ThalieVideotron commented
> > Cette propriété ne fonctionne plus? (peu importe la combinaison de d'autre variable) ![image](https://user-images.githubusercontent.com/75901368/144762213-1354d4a7-0667-404c-9920-fc7e4aa311c4.png)
> 
> Ça fonctionne. C'est juste que l'opacité est à 0 dans le rgba :)

je confirme : https://bifrost-front-end-library-git-ds-222-improve-4d4579-bifrost-vui.vercel.app/?path=/story/components-block-highlight--drupal&args=visualBackgroundColor:!rgba(176,188,217,0.5)

2021-12-07 16:27 UTC, bibifrost commented on projects/front-end-library/src/lib/components/block-highlight/twig/index.twig
>      w-100 d-flex flex-column flex-sm-row overflow-hidden bf-border-radius-medium border bf-border-color-secondary
On pourrait se faire un atelier la dessus. Mais en attendant, je t'invite à regarder des solutions comme [Tailwind](https://tailwindcss.com/), c'est perturbant au debut mais à l'usage, il y a beaucoup d'avantages. La plupart des Design-system sur lesquels je travaillent utilisent beaucoup les classes utilitaires et on y gagne en performance + maintenance. Malgré la répétition de certaines classes.
Pour les projets Vue ou React, je conseille aussi beaucoup l'usage de [styled-component](https://styled-components.com/) (efficace++) + Tailwind pour le system.
Pour Angular, je conseille d'utiliser la fonction native de `ViewEncapsulation` + Tailwind.
Actuellement, nous avons une Stack désuète: SASS + Bootstap, mais si on passe sur un system Angular uniquement, on sera bien content d'avoir pris les bons reflex.

2021-12-09 03:10 UTC, bibifrost commented
> > > Cette propriété ne fonctionne plus? (peu importe la combinaison de d'autre variable) ![image](https://user-images.githubusercontent.com/75901368/144762213-1354d4a7-0667-404c-9920-fc7e4aa311c4.png)
> > 
> > 
> > Ça fonctionne. C'est juste que l'opacité est à 0 dans le rgba :)
> 
> je confirme : https://bifrost-front-end-library-git-ds-222-improve-4d4579-bifrost-vui.vercel.app/?path=/story/components-block-highlight--drupal&args=visualBackgroundColor:!rgba(176,188,217,0.5) ,
> 
> @bibifrost si ça ne fonctionne pas avec RGB c'est à cause du `#` que Storybook ne digère pas? Si c'est le cas on peut mettre des exemples dans le commentaire du contrôle storybook `Ex.: rgba(176,188,217,0.5)` ?

Oui, je confirme que le `#` n'est jamais accepté dans notre architecture de Storybook. Par contre:
- Ça ne posera pas de probleme pour un environnement PHP. 
- Ça pourrait etre regler dans le server Express.
On peux écrire des rgba ou des [valeurs html](https://htmlcolorcodes.com/fr/noms-de-couleur/).

2022-01-30 16:31 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/block-highlight/scss/index.scss
> +        }
J'ai testé une image de la PROD qui est actuellement utilisé dans les BlockHighlight.
https://videotron.com/sites/default/files/styles/original/public/image/giguez-sans-retenu_730x360_FR.webp?itok=RaZN0Q3F

Source: https://videotron.com/mobilite

Le problème que nous on a vu dans Storybook qui a déclenché la modif avait été palié par du contenu approprié.

Je crois qu'on peu avancé, mais il faudra bien communiqué la situation à SN et DXP

2022-01-30 17:44 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/block-highlight/twig/index.twig
> +    <div class='d-flex flex-column {{ isFeatured ? 'justify-content-center' }} p-4 p-sm-5'>
Ce n'est pas Done, mais avec le default(false) de l'initialisation du début, on est ok

2022-01-30 17:49 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +- ⚠️ **[BREAK CHANGE]** ⚠️ Change default `background-size` to `contain` instead of `cover`, in order to avoid image cropped.
```suggestion
- ⚠️ **[BREAK CHANGE]** ⚠️ CSS change behavior. Change default `background-size` to `contain` instead of `cover`, in order to avoid image cropped.
```

2022-01-30 17:55 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/block-highlight/_doc/doc.stories.mdx
> +                'storybook/docs/panel': { hidden: true }
Ca semble reverté, mais pas de commentaire de @baptistemac. Est-ce que le Jira a été fait?
Mettre la référence ici qu'on ai une référence historique

2022-02-08 00:38 UTC, JonathanLefebvreV commented
Voir Jira pour la raison du "on hold"

2022-02-11 15:55 UTC, JonathanLefebvreV requested changes

2022-02-11 15:55 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +- Add a new property `visualBackgroundFit` in order to choose between `fit` (contain) and `fill` (cover).
Enlever le breaking change. 
Au travers de toute la PR. Le comportement actuel doit être conservé.
Il faut 
- Reverté la propriété CSS pour voir du "cover" plutot que du "contains"
- s'assurer que la valeur de la propriété soit "fill" par défaut et que ce soit documenter.

2022-02-19 15:35 UTC, JonathanLefebvreV submitted a review, later dismissed

2022-02-19 15:38 UTC, JonathanLefebvreV approved these changes

2022-02-19 15:42 UTC, merged