DS-221 - Badge is Multiline
bifrost-vui/bifrost-front-end-library pull request #222
Opened 2021-12-03 15:42 UTC by ThalieVideotron

Note :
pour les badges avec angle,  `text-overflow : ellipis` a besoin d'une taille fixe (px ou rem) pour fonctionner - la valeur que j'ai mise est ouverte pour discussion mais on pourrait peut-être l'ajouter en option dans une version subséquente si ça devient un enjeux

2021-12-03 22:24 UTC, bibifrost commented on CHANGELOG.mdx
> +- Enabled `badge`component to expand on multiple lines. Badges with `angle` will still display on one line but will display an ellipis if the text is larger than 15rem.
Mentionner que dans les cards disabled, les badges sont desormais visibles?

2021-12-03 22:24 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/scss/index.scss
> +            display: inline-block;
pas sur que ce display soit nécessaire, puisque le parent est un flex.
Pareil pour le line-height.

2021-12-03 22:24 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/scss/index.scss
> +        padding: 0px .75rem 0 .25rem;
Je privilégirai les `0` plutot que les `0px`.
Pour la simplicité de la lecture

2021-12-03 22:24 UTC, bibifrost commented on CHANGELOG.mdx
>  <br/><br/>
Afficher une page pour s'assurer que la feature est toujours valide?
Exemple:
![image](https://user-images.githubusercontent.com/93746960/144680814-5ed4e1ad-6c90-4c5b-b682-d8966fb14e69.png)

2021-12-05 20:35 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +- Enabled `badge`component to expand on multiple lines. Badges with `angle` will still display on one line but will display an ellipis if the text is larger than 15rem.
Attendre de voir si ces voulu tel que discuté dans Jira 
https://videotron-design-system.atlassian.net/browse/DS-221?focusedCommentId=10615

2021-12-05 20:36 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/scss/index.scss
> +        padding: 0px .25rem 0 .75rem;
ce `0` aussi

2021-12-05 20:37 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/scss/index.scss
> -        }
A confirmé : https://videotron-design-system.atlassian.net/browse/DS-221?focusedCommentId=10615

2021-12-06 13:53 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/badge/scss/index.scss
> +            display: inline-block;
`.bf-text-interface-small` gère le line-height donc effectivement, pas nécessaire non plus

2021-12-06 13:58 UTC, ThalieVideotron commented on CHANGELOG.mdx
>  <br/><br/>
@bibifrost  je me posais justement la question. Donc ajout d'une story pour afficher le multiline.

2021-12-06 14:21 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/scss/index.scss
> -        }
si @jfpoliquin confirme j'ajouterais aussi l'info dans le changelog 
@bibifrost nous a confirmé qu'à part le fait que le badge en disabled n'existait pas à l'époque, il n'y avait pas de mandat clair pour cacher les badges. 

Par contre le ligne-height qui passe de 1.5 à 1 rem c'est moins clair. Il faut dire que l'option multiligne n'était pas prévue non plus.  Donc c'est plus sur ce point où j'attend une confirmation de @jfpoliquin

2021-12-07 14:12 UTC, ThalieVideotron commented on CHANGELOG.mdx
> +- Enabled `badge`component to expand on multiple lines. Badges with `angle` will still display on one line but will display an ellipis if the text is larger than 15rem.
validé par @jfpoliquin dans Jira

2021-12-07 14:14 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/scss/index.scss
> -        }
validé par @jfpoliquin

2021-12-09 02:52 UTC, JonathanLefebvreV requested changes
l'angle de droit est pété

on Master
![image](https://user-images.githubusercontent.com/75901368/145325839-66cb7e58-3963-46a7-b627-1cc2e5007d23.png)


On this branch
![image](https://user-images.githubusercontent.com/75901368/145325736-fcfe6c53-536a-444f-940f-98dbdcf2db42.png)

2021-12-09 02:57 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +- Enabled `badge`component to expand on multiple lines. Badges with `angle` will still display on one line but will display an ellipis if the text is larger than 15rem.
```suggestion
- Enabled `badge` component to expand on multiple lines. Badges with `angle` will still display on one line but will display an ellipsis if the text is larger than 15rem.
```

2021-12-09 12:38 UTC, ThalieVideotron commented
> l'angle de droit est pété
> 
> on Master ![image](https://user-images.githubusercontent.com/75901368/145325839-66cb7e58-3963-46a7-b627-1cc2e5007d23.png)
> 
> On this branch ![image](https://user-images.githubusercontent.com/75901368/145325736-fcfe6c53-536a-444f-940f-98dbdcf2db42.png)

je répare

2021-12-09 14:04 UTC, JonathanLefebvreV approved these changes

2021-12-09 14:06 UTC, merged