Ds 228 create tile ksp
bifrost-vui/bifrost-front-end-library pull request #225
Opened 2021-12-03 23:09 UTC by bibifrost

2021-12-13 17:37 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-ksp/twig/index.twig
> +		<{{ titleTag }} class='bf-text-interface-large m-0'>
je me pose la question s'il ne serait pas prudent d'ajouter un `titleClass`

aussi pour tous ces cas de titleTag ; on devrait fournir une liste restreinte de tag admissibles. (h1, h2, h3, h4, h5, h6, p) - je ne voudrais pas qu'on se ramasse avec ul, section, nav, blockquote... qui risquent de faire sauter le layout ou produire du html invalide

2021-12-13 17:37 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-ksp/scss/index.scss
> +        // Specify color is required otherwise legacy CSS on `a, a:hover` takes precedence when tile is clickable.
tu veux vraiment garder le commentaire? 
moi je me dit que si le code est là c'est juste qu'on en a besoin.

2021-12-13 17:37 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-ksp/scss/index.scss
> +        background-image: var(--bf-background-image-src);
le background-image est setté via du inline-style - je ne comprend pas où est définie cette variable : `--bf-background-image-src`

2021-12-13 17:37 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-ksp/twig/index.twig
> +		{{ reversed ? 'reversed' }}
finalement on ajoute les `is defined` ?
Je suis d'accord que sur les booléens c'est overkill mais en mode strict ça fait planter twig

2021-12-13 17:37 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-ksp/angular/tile-ksp.component.html
> +Tile KSP
KSP c'est pas clair - on a mieux ?

2021-12-13 19:38 UTC, bibifrost commented on CHANGELOG.mdx
> +- New `Tile KSP` component.
Tellement d'accord avec toi. Ça fait parti des améliorations globales que je voulais proposer.

2021-12-19 01:27 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-ksp/twig/index.twig
> +		<{{ titleTag }} class='bf-text-interface-large m-0'>
- Si `titleClass`, n'est pas demandé je n'ouvrirais pas cette porte. Je ne vois pas encore ce qui le justifierais.
- Pour filter `titleTag`, pourquoi pas. Cependant, on n'est plus responsable si les intégrateurs font n'importe quoi en terme de HTML. Et c'est la responsabilité de l'Admin Drupal d'offrir une liste cohérente de titleTag.

2021-12-19 01:28 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-ksp/scss/index.scss
> +        // Specify color is required otherwise legacy CSS on `a, a:hover` takes precedence when tile is clickable.
Oui, c'est aussi pour signifier qu'on pourrait retirer cette propriété, le jour ou on se débarassera du legacy.

2021-12-19 01:59 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-ksp/angular/tile-ksp.component.html
> +Tile KSP
oui `Key` tout simplement :)
Fixed

2021-12-19 01:59 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-ksp/twig/index.twig
> +		{{ reversed ? 'reversed' }}
fixed

2021-12-19 01:59 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-ksp/scss/index.scss
> +        background-image: var(--bf-background-image-src);
bien vu. fixed

2021-12-19 02:01 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-ksp/angular/tile-ksp.component.ts
> +    color       : null | 'success' | 'neutral' | 'warning' | 'negative';
- `name` ajouté.
- Pour les `color`, on devrait toujours lister les couleurs disponibles. Ou est-ce que ça n'est pas le cas?

2021-12-19 02:01 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-ksp/_doc/template.drupal.twig
> +    .template-container {
oui vraiment.
le layout est fixé en moble

2021-12-19 02:02 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-ksp/_doc/template.drupal.twig
> +
fixed

2022-02-07 16:00 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-ksp/_doc/template.drupal.twig
> +    .template-container {
@ThalieVideotron à resolved

2022-02-07 16:00 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-ksp/angular/tile-ksp.component.ts
> +    color       : null | 'success' | 'neutral' | 'warning' | 'negative';
@ThalieVideotron à resolved

2022-02-07 16:00 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-ksp/twig/index.twig
> +		<{{ titleTag }} class='bf-text-interface-large m-0'>
@ThalieVideotron

2022-02-07 16:01 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-ksp/angular/tile-ksp.component.html
> +Tile KSP
@ThalieVideotron

2022-02-07 16:02 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-ksp/_doc/template.drupal.twig
> +
@ThalieVideotron

2022-02-07 16:02 UTC, bibifrost commented on CHANGELOG.mdx
> +- New `Tile KSP` component.
@ThalieVideotron

2022-02-10 19:52 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-ksp/_doc/doc.stories.mdx
> +    icon            : 'television',
Ok tu fais un merge dans le twig...

2022-02-10 20:00 UTC, ThalieVideotron commented on CHANGELOG.mdx
> +- New `Tile KSP` component.
vendu pour le nom... 
d'un autre côté dans le contexte actuel ce nouveau composant comporte plusieurs  breaking change par rapport à la card-ksp du UI-Kit. ça peut être un show stopper.

2022-02-10 20:02 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-ksp/_doc/template.drupal.twig
> +
`<div class='template-container'>
  {% for index in [1,2] %}
    <div class='flex-grow-1 d-flex align-items-center justify-content-center minh-100 py-4 {{ reversed|default(index == 2) ? 'reversed bf-color-bg-ground' }}'>
      {% include '@bf-components/tile-key/twig/index.twig' %}
    </div>
  {% endfor %}
</div>`

2022-02-10 20:15 UTC, ThalieVideotron requested changes

2022-02-10 20:15 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-key/_doc/template.drupal.twig
> +
ligne en trop

2022-02-10 20:15 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-key/_doc/template.drupal.twig
> +
ligne en trop

2022-02-10 20:15 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-key/_doc/template.drupal.twig
> +
ligne en trop

2022-02-10 20:15 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-key/angular/tile-key.component.ts
> +    src         : string;
src pas dans le composant icone

2022-02-10 20:40 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-ksp/_doc/template.drupal.twig
> +
je n'avais pas bien compris mais c'est fixé desormais.

2022-02-10 20:41 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-key/angular/tile-key.component.ts
> +    src         : string;
bien vu!

2022-02-10 20:47 UTC, bibifrost commented
> ne, il peut hériter de la couleur tant qu'elle

Du point de vue design, il y a 2 états:
- Image sombre => Texte blanc => C'est alors un cas de reversed. 
- Image clair => Texte noir.

Dans le gestionnaire d'image de Drupal, on pourrait ajouter un champ pour définir cet état (reversed ou non). Et ainsi le récupérer en meme temps que le `src` et le `alt`. Mais ça me semble un _nice to have_ pour le moment.

2022-02-10 20:47 UTC, bibifrost commented
> En jouant avec je constate qu'on a le même irritant que dans le hero quand vient le temps d'écrire sur une image.
> 
> Du coup, plus j'y pense et la solution quand on a une image de background serait d'avoir une propriété `textColor` qui précise en quelle couleur on doit écrire sur cette image. Cette couleur demeure imperméable aux couleurs/classes highlight/reversed/ground/underground et cie. On pourrait laisser le choix de la couleur libre mais on pourrait surtout définir un nombre limité de couleurs prédéfinies qu'on les préfixe à la sauce Bifrost: EX: `bf-text-on-image-COLOR-NAME`.
> 
> s'il y a un icône, il peut hériter de la couleur tant qu'elle n'est pas redéfinie dans `icon.color` - currentColor magic!
> 
> proposition : interface IImage { src : string; textColor : type à définir mais propablement string/options }

Du point de vue design, il y a 2 états:
- Image sombre => Texte blanc => C'est alors un cas de reversed.
- Image clair => Texte noir.
Dans le gestionnaire d'image de Drupal, on pourrait ajouter un champ pour définir cet état (reversed ou non). Et ainsi le récupérer en meme temps que le src et le alt. Mais ça me semble un nice to have pour le moment.

2022-02-10 22:05 UTC, ThalieVideotron commented
> > En jouant avec je constate qu'on a le même irritant que dans le hero quand vient le temps d'écrire sur une image.
> > Du coup, plus j'y pense et la solution quand on a une image de background serait d'avoir une propriété `textColor` qui précise en quelle couleur on doit écrire sur cette image. Cette couleur demeure imperméable aux couleurs/classes highlight/reversed/ground/underground et cie. On pourrait laisser le choix de la couleur libre mais on pourrait surtout définir un nombre limité de couleurs prédéfinies qu'on les préfixe à la sauce Bifrost: EX: `bf-text-on-image-COLOR-NAME`.
> > s'il y a un icône, il peut hériter de la couleur tant qu'elle n'est pas redéfinie dans `icon.color` - currentColor magic!
> > proposition : interface IImage { src : string; textColor : type à définir mais propablement string/options }
> 
> Du point de vue design, il y a 2 états:
> 
> * Image sombre => Texte blanc => C'est alors un cas de reversed.
> * Image clair => Texte noir.
>   Dans le gestionnaire d'image de Drupal, on pourrait ajouter un champ pour définir cet état (reversed ou non). Et ainsi le récupérer en meme temps que le src et le alt. Mais ça me semble un nice to have pour le moment.

oui mais reversed tu l'as peut-être hérité de la section et dessus ils ont mis une image claire et là on gère des imbrications de reverse à n'en plus finir. juste pour le fun change ton image pour une claire, du côté droit ton texte sera en blanc... cqfd. la couleur du texte sur l'image doit être déterminée par l'image et non par un état reversed qui peut venir à la limite du body. ceci dit ça veut dire qu'on doit continuer d'y penser. un jour on aura LA solution pour les contôler tous ;-)

2022-02-16 17:35 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-ksp/angular/tile-ksp.component.ts
> +    src         : string;
finalement t'as fait come IPrice dans card? nice .

2022-04-19 13:02 UTC, bibifrost commented
> > > En jouant avec je constate qu'on a le même irritant que dans le hero quand vient le temps d'écrire sur une image.
> > > Du coup, plus j'y pense et la solution quand on a une image de background serait d'avoir une propriété `textColor` qui précise en quelle couleur on doit écrire sur cette image. Cette couleur demeure imperméable aux couleurs/classes highlight/reversed/ground/underground et cie. On pourrait laisser le choix de la couleur libre mais on pourrait surtout définir un nombre limité de couleurs prédéfinies qu'on les préfixe à la sauce Bifrost: EX: `bf-text-on-image-COLOR-NAME`.
> > > s'il y a un icône, il peut hériter de la couleur tant qu'elle n'est pas redéfinie dans `icon.color` - currentColor magic!
> > > proposition : interface IImage { src : string; textColor : type à définir mais propablement string/options }
> > 
> > 
> > Du point de vue design, il y a 2 états:
> > 
> > * Image sombre => Texte blanc => C'est alors un cas de reversed.
> > * Image clair => Texte noir.
> >   Dans le gestionnaire d'image de Drupal, on pourrait ajouter un champ pour définir cet état (reversed ou non). Et ainsi le récupérer en meme temps que le src et le alt. Mais ça me semble un nice to have pour le moment.
> 
> oui mais reversed tu l'as peut-être hérité de la section et dessus ils ont mis une image claire et là on gère des imbrications de reverse à n'en plus finir. juste pour le fun change ton image pour une claire, du côté droit ton texte sera en blanc... cqfd. la couleur du texte sur l'image doit être déterminée par l'image et non par un état reversed qui peut venir à la limite du body. ceci dit ça veut dire qu'on doit continuer d'y penser. un jour on aura LA solution pour les contôler tous ;-)

oui, j'ai mis en place la propriété `textColor` sur `IImage`. Dis moi ce que tu en penses.

2022-04-20 00:44 UTC, JonathanLefebvreV requested changes

2022-04-20 00:44 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +- New `Twig Component Tile Key`.
Il manque le lien de la story

2022-04-20 00:45 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +
sert à rien?

2022-04-20 00:46 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +
sert à rien?

2022-04-20 00:50 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/tile-key/angular/tile-key.component.ts
> +    textColor   : 'light' | 'dark';
Je voudrais rappeler que c'est faux:
![image](https://user-images.githubusercontent.com/75901368/164124921-a087f9f1-07d3-4877-aa58-44c53428a532.png)

On gère toute ces couleurs et un texte jaune sur un background Noir pourrait très bien être une chose de Studio numérique ce serait demandé.

Est-ce qu'on peut faire simple, et juste laissé l'utilisateur mettre la classe de content qui "fit" sur l'image?

La meilleur facon serait de voir avec Studio Numérique actuellement leur problème avec le KSP du UIKIT voir si c'est un problème ou pas cette histoire de propriété.

Agreed @ThalieVideotron et @bibifrost ?

2022-04-20 17:41 UTC, ThalieVideotron requested changes

2022-04-20 17:41 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-key/angular/tile-key.component.ts
> +    textColor   : 'light' | 'dark';
oui laisser l'utilisateur gérer ça avec une classe semble plus simple mais j'ai des doutes à savoir si c'est clair à utiliser. Vont-il comprendre que si leur image est foncée qu'il doivent mettre la tuile en reversed pour obtenir du texte blanc?

Consulter Studio me semble une bonne idée.

2022-04-20 17:41 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-key/angular/tile-key.component.ts
> +    /** Expected format: `{ src: "my-image.png" }` */
et le textColor ils le devine?
Modifier le expected format si tu le gardes
backgroundImage devient une string si textColor est abandonné

2022-04-20 17:41 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-key/twig/index.twig
> +		'
je commence à trouver que ça fait beaucoup de logique dans l'attribut class. Ça vaudrait la peine de la mettre ailleurs histoire d'améliorer la lisibilité et le code généré?
![image](https://user-images.githubusercontent.com/82388009/164289831-064d42f8-8aae-4e0f-b9b4-8c745b676842.png)

2022-04-20 17:41 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-key/scss/index.scss
> +        // Specify color is required otherwise legacy CSS on `a, a:hover` takes precedence when tile is clickable.
tu peux supprimer ces commentaires.

2022-04-21 12:54 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-key/twig/index.twig
> +		'
Oui, je m'étais penché dessus. Il y a la solution de setter une variable qui agrège tout ça, mais on perd beaucoup en liibilité si on doit le faire pour tous les div qui contiennent de la logique. 
De mémoire, Il existe un filter twig qui `trim`. À voir.
Je propose de logger un ticket JIRA pour en parler car ça concerne tous les composants.

2022-04-21 12:54 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-key/angular/tile-key.component.ts
> +    /** Expected format: `{ src: "my-image.png" }` */
> et le textColor ils le devine? :D

2022-04-21 13:05 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-key/angular/tile-key.component.ts
> +    textColor   : 'light' | 'dark';
> Je voudrais rappeler que c'est faux:
Je ne comprends pas. Qu'est-ce qui est faux?
Sauf erreur, à date le langage visuel n'inclut pas la possibilité d'écrire en jaune.

> Est-ce qu'on peut faire simple, et juste laissé l'utilisateur mettre la classe de content qui "fit" sur l'image?
Pourquoi pas un classe CSS a appliquer mais je ne suis pas sur de que ce soit plus simple qu'une propriété.
Une classe CSS deviendra impossible a changer par la suite. Alors qu'une propriété défini un pattern, libre a nous de changer la solution Front-end par la suite.
Je dis ça comme ça, mais on s'en jase ça sera plus simple.

> La meilleur facon serait de voir avec Studio Numérique actuellement leur problème avec le KSP du UIKIT voir si c'est un problème ou pas cette histoire de propriété.
Oui excellente idée.

2022-04-21 14:21 UTC, bibifrost commented on CHANGELOG.mdx
> +- New `Twig Component Tile Key`.
Done

2022-04-21 14:21 UTC, bibifrost commented on CHANGELOG.mdx
> +
supprimé

2022-04-21 14:23 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-key/scss/index.scss
> +        // Specify color is required otherwise legacy CSS on `a, a:hover` takes precedence when tile is clickable.
supprimé

2022-04-25 16:03 UTC, bibifrost commented on projects/front-end-library/src/lib/components/icon/scss/index.scss
> +    // Property color is inherit.
Done

2022-04-28 12:21 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/tiles-key/_doc/doc.stories.mdx
> +        hasFeaturedLayout: {
done

2022-04-28 12:21 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/tiles-key/_doc/doc.stories.mdx
> +
done

2022-04-28 12:21 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/tiles-key/_doc/doc.stories.mdx
> +
done

2022-04-28 12:21 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/tiles-key/scss/index.scss
> +            grid-column: 1 / 10 !important;
merci :) 
Done

2022-04-28 12:21 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/tiles-key/scss/index.scss
> +
done

2022-04-28 12:21 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-key/_doc/template.drupal.twig
> +{% set reversed         = reversed|json_parse %}
done

2022-04-28 12:21 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-key/_doc/template.drupal.twig
> +{% set isDisabled       = isDisabled|json_parse %}
done

2022-04-28 12:21 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-key/_doc/template.drupal.twig
> +{% set icon             = icon|json_parse %}
done

2022-04-28 12:21 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-key/_doc/template.drupal.twig
> +{% set isClickable      = isClickable|json_parse %}
done

2022-04-28 12:21 UTC, bibifrost commented on CHANGELOG.mdx
> +### Tile Key
Mention ajoutée.
done

2022-04-28 18:21 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-key/_doc/doc.stories.mdx
> +
```suggestion
```

2022-04-28 18:21 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-key/_doc/doc.stories.mdx
> +
```suggestion
```

2022-04-28 18:21 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-key/scss/index.scss
> +
```suggestion
```

2022-04-28 18:21 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-key/scss/index.scss
> +
```suggestion
```

2022-04-28 18:21 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/tiles-key/_doc/template.drupal.twig
> +	{% for index in [1,2] %}
2 espaces dans les twig

2022-04-28 19:45 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-key/_doc/doc.stories.mdx
> +<br/>
en MDX, le nombre de ligne n'a pas d'impact. C'est surtout pour faire des groupes que je rajoute des espaces. Ma logique d'espacement:
`
Titre 1 _(2 espaces en dessous)_


Titre 2 _(1 espace en dessous)_

Element _(1 espace en dessous)_

Element _(1 espace en dessous)_


Titre 2 _(2 espaces en dessus)_

Element _(1 espace en dessous)_

Element _(1 espace en dessous)_
...
`

2022-04-28 19:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-key/_doc/doc.stories.mdx
> +    ]}
il arrive :)

2022-04-28 19:56 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/tiles-key/twig/index.twig
> +    <ul class='bf-section-tiles-key__list list-unstyled'>
done

2022-04-28 19:58 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-key/_doc/doc.stories.mdx
> +    ]}
done

2022-05-06 19:08 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-key/_doc/doc.stories.mdx
> +<br/>
toi t'en veux plus moi moins ;-)

2022-05-06 19:09 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-key/_doc/template.drupal.twig
> +  @media (max-width: 768px) {
makes sens

2022-05-06 19:13 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-key/twig/index.twig
> +		'
jira : https://videotron-design-system.atlassian.net/browse/DS-372

2022-05-06 19:18 UTC, ThalieVideotron requested changes

2022-05-06 19:18 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-key/twig/index.twig
> +				{% set icon = { name: icon } %}
indent

2022-05-06 19:18 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-key/twig/index.twig
> +		{% if description is defined and description %}
indent

2022-05-06 19:18 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/tiles-key/scss/index.scss
> +            grid-column: 1 / 10 !important;
grrr

2022-05-08 00:20 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/tile-key/angular/tile-key.component.ts
> +    textColor   : 'light' | 'dark';
> Je ne comprends pas. Qu'est-ce qui est faux?

Que le composant permets seulement 2 jeux de couleur de texte.

> Sauf erreur, à date le langage visuel n'inclut pas la possibilité d'écrire en jaune.

Revoir le fichier de couleur de content dans Figma pour toute les variations. Dont voici un extrait.
![image](https://user-images.githubusercontent.com/75901368/167276206-bdd0ad73-d645-4989-93cd-5d033697bd04.png)
Et j'ai déjà mis la référence de Storybook qui réflète Figma.

Suite à la rencontre avec Jean Sebastien : 
- Il a exprimer d'avoir 100% du jeu de couleur du language visuel de videotron.
  -  On va lui offrir : Donc faire en sorte de `textColor` puisse supporté tout nos jeux de couleur (enum de nom de couleur ou une string qui accepte les classe couleur) 
- avoir un moment de jouer avec l'opacité de textes selon les images
  - On ne vas pas lui faire.

2022-05-09 15:45 UTC, JonathanLefebvreV requested changes

2022-11-26 10:52 UTC, JonathanLefebvreV reviewed
✔️ self reviewed

2022-11-26 10:53 UTC, JonathanLefebvreV approved these changes

2022-11-26 10:54 UTC, merged