Ds 232 systemize headings
bifrost-vui/bifrost-front-end-library pull request #228
Opened 2021-12-04 20:08 UTC by bibifrost

2021-12-06 16:59 UTC, ThalieVideotron reviewed
Nice. ça va être + simple quand ceux de VSA vont s'ajouter

2021-12-07 13:11 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/scss/themes/business/_headings.scss
> +@mixin business-headings {
on n'a pas besoin des variables `sm` pour business ?

2021-12-07 13:14 UTC, ThalieVideotron commented on CHANGELOG.mdx
> +- Add new CSS variables in order to define headings styles. E.g. `--bf-h1-size`, `--bf-h1-leading`, `--bf-h1-weight`, ...
j'aurais mis l'emphase sur la création du thème plutôt que sur la moulinette en dessous. pas certaine qu'on veuille qu'il utilise ces nouvelles variables

2021-12-07 15:18 UTC, bibifrost commented on projects/front-end-library/src/lib/scss/themes/business/_headings.scss
> +@mixin business-headings {
non

2021-12-13 16:12 UTC, ThalieVideotron commented on CHANGELOG.mdx
> +- Make Headings style themable.
+ creates headings for `business` theme? 

c'est quand même ça non?

2021-12-13 20:05 UTC, ThalieVideotron approved these changes

2022-02-19 15:01 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/scss/themes/business/_color.scss
> -@mixin business-color {
Ca va pas servir plus tard ça?

2022-02-19 15:05 UTC, JonathanLefebvreV requested changes
Cette documentation devrait être updaté en même temps 
https://bifrost-front-end-library-git-ds-232-systemi-dde386-bifrost-vui.vercel.app/?path=/docs/implementation-theme--page

et 

dans https://bifrost-front-end-library-git-ds-232-systemi-dde386-bifrost-vui.vercel.app/?path=/docs/styles-headings--page
![image](https://user-images.githubusercontent.com/75901368/154806512-fa3e7b3a-793e-4c95-94fd-43e79c82ce6c.png)

2022-02-23 16:53 UTC, bibifrost commented
<img width="833" alt="image" src="https://user-images.githubusercontent.com/93746960/155367199-93ef989e-9fa3-40a7-8c64-6ed3a926deed.png">
Peut-être, mais au meme titre que tous les autres styles. J'avais utilisé `colors` au debut pour les tests, mais ça ne fait pas de sens de le garder a mon avis.

2022-02-23 16:53 UTC, bibifrost commented
> Cette documentation devrait être updaté en même temps https://bifrost-front-end-library-git-ds-232-systemi-dde386-bifrost-vui.vercel.app/?path=/docs/implementation-theme--page
> 
> et
> 
> dans https://bifrost-front-end-library-git-ds-232-systemi-dde386-bifrost-vui.vercel.app/?path=/docs/styles-headings--page ![image](https://user-images.githubusercontent.com/75901368/154806512-fa3e7b3a-793e-4c95-94fd-43e79c82ce6c.png)

Done. Bien vu

2022-03-31 13:45 UTC, JonathanLefebvreV approved these changes

2022-03-31 13:46 UTC, merged