ds-242 create text-image section
bifrost-vui/bifrost-front-end-library pull request #231
Opened 2021-12-07 20:33 UTC by bibifrost

2021-12-15 15:20 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/text-image/twig/index.twig
> +				<div class='bf-list bf-list--divider border-top border-bottom bf-border-color-secondary' data-animate='fade-in'>
`bf-list bf-list--divider` : le refactoring de list va avoir un impact : s'assurer que ça ne casse rien au merge 
du coup faudrait prendre une décision sur la stratégie de list

2021-12-15 15:20 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/text-image/twig/index.twig
> +{% set titleTag					= titleTag|default('p') %}
revoir l'indentation du fichier à 2 espaces
il y a aussi des lignes vides et des sur-indentations à corriger 

rappel des normes adoptées en équipe : 
- pas de lignes vides pour les balises fermantes, 
- pas de ligne vide si on a une indentation, 
- seuls les éléments de même niveau sont séparés par une ligne vide.

2021-12-15 15:20 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/text-image/scss/index.scss
> +
pas de lignes vides - quoi que je comprend que ça facilite la lecture mais c'est pas standard par rapport au reste du code
et si on veut être puriste :  le min-height après les flex, le display:flex avant les autres attributs flex

2021-12-15 15:20 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/text-image/_doc/doc.stories.mdx
> +    <Story
les `:` ne sont pas alignés mais personnellement ça ne me dérange pas, j'ai  même l'impression qu'on aurait moins de problème d'alignement/indentation si on faisait comme ça partout

2021-12-15 15:20 UTC, ThalieVideotron commented on api/server.js
> +        'bf-sections'   : path.resolve(__dirname, '../projects/front-end-library/src/lib/sections'),
c'est sections qu'on voulais appeler démo ou c'est les exemples?

2022-01-29 22:48 UTC, bibifrost commented on api/server.js
> +        'bf-sections'   : path.resolve(__dirname, '../projects/front-end-library/src/lib/sections'),
La c'est bien une section.

Le terme **Demo** fait référence à des éléments non publiés dans le package NPM.

2022-01-29 22:48 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/text-image/_doc/doc.stories.mdx
> +    <Story
Ça depend de la quantité d'elements dans l'objet et d'imbrications.
C'est un peu subjectif mais l'idée est toujours de privilégier la lisibilité.

2022-01-29 22:48 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/text-image/angular/text-image.component.ts
> +    @Input() layout                 : 'text-image' | 'image-text';
oui effectivement :)

2022-01-29 22:48 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/text-image/scss/index.scss
> +
De quels cas d'affichage parles-tu?

2022-01-29 22:48 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/text-image/twig/index.twig
> +				<div class='bf-list bf-list--divider border-top border-bottom bf-border-color-secondary' data-animate='fade-in'>
oui parlons en la prochaine fois

2022-02-10 21:33 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/text-image/twig/index.twig
> +{% set titleTag					= titleTag|default('p') %}
J'ai laissé des indentations qui me semblait utile à la lisibilité. Tu me dira ce que tu en penses.

2022-02-10 21:33 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/text-image/twig/index.twig
> +<article class='
On va tomber dans d'autres problème de lisibilité en éloignant les classes CSS de leur DOM.
Si on ne veux pas accepter les sauts de ligne en HTML, je propose de laisser sur une ligne.

2022-02-10 21:33 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/text-image/twig/index.twig
> +				class='
Comment nommerais-tu cette variable?

2022-02-10 21:33 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/text-image/_doc/doc.stories.mdx
> +                    imagePosition: 'left'
reflexion en cours: `image.position` ou `imagePosition`.

2022-02-16 17:47 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/basic-content/_doc/doc.stories.mdx
> +<iframe width='100%' height='450' src='https://www.figma.com/file/7bTmk29aCBl7rCFszffYPr/DS---Components-%26-styles?node-id=9210%3A11314' frameBorder='0' allowFullScreen></iframe>
```suggestion
<iframe width='100%' height='450' src='https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2F7bTmk29aCBl7rCFszffYPr%2FDS---Components-%2526-styles%3Fnode-id%3D9210%253A11314' frameBorder='0' allowFullScreen></iframe>
```

2022-02-16 17:47 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/text-image/_doc/doc.stories.mdx
> +</Canvas>
le figma ne s'affiche pas.

2022-02-16 18:10 UTC, ThalieVideotron requested changes

2022-02-16 18:10 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/basic-content/twig/index.twig
> +	bf-section-basic-content d-block d-md-flex
ne pas mettre les classes sur des lignes différentes. le codes généré est terrible. Ça nuit à la lisibilité
![image](https://user-images.githubusercontent.com/82388009/154328108-0f98c2d3-96d6-4052-8d3e-431dd9fd1a4d.png)

2022-02-16 18:10 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/basic-content/twig/index.twig
> +	bf-section-basic-content d-block d-md-flex
que chaque propriété soit sur sa propre ligne oui. séparer les valeurs d'une propriété sur plusieurs lignes non.
la lisibilité du code ne doit pas mettre en péril celle du code généré.

2022-02-16 18:13 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/text-image/twig/index.twig
> +{% set titleTag					= titleTag|default('p') %}
on est passé à 8 espaces presque partout. pas certaine que ce soit ce que tu voulais faire

2022-02-16 18:36 UTC, ThalieVideotron requested changes

2022-02-16 18:36 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/basic-content/scss/index.scss
> +        justify-content: center !important;
si tu as besoin de `!important` c'est qu'il y a une solution + clean. On devrait les banir de bifrost.css. dans ce cas-ci  il y en a 2 (bootstrap all the way ou bifrost css only)  
1 -  ne pas mettre la classe justify-content-between dans le twig sans condition si en bout de ligne tu dois l'overrider avec un important dans le css.  donc créer le context `.bf-section-basic-content .container-fluid {justify-content: space-between; }` dans le css. 
2- mettre une condition autour de la classe   justify-content-between dans le twig et sortir `justify-content: center !important;`

2022-02-16 18:36 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/basic-content/scss/index.scss
> +            justify-content: center !important;
!important - choisir ta solution pour le faire disparaître

2022-02-16 18:36 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/basic-content/scss/index.scss
> +            max-width: none;
pour moi pas de soucis avec le overwrite pour les petits - mais si on est mobile first on devrait probablement prendre l'habitude de définir la valeur pour `@include media-breakpoint-up(md)`. Du moins quand l'overwrite fait un reset d'une propriété . Pas un CR, juste une réflexion. t'es autorisé à faire un resolve tout seul une fois que t'en aura pris connaissance

2022-04-10 18:06 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/basic-content/_doc/doc.stories.mdx
> +<Meta
```suggestion
import { moduleMetadata } from '@storybook/angular';
import { ArgsTable, Canvas, Meta, Story } from '@storybook/addon-docs';
import { TwigContainerComponent } from '../../../../utils/twig-container/twig-container.component';
import { BasicContentComponent } from '../angular/basic-content.component';

<Meta
```

2022-04-10 18:08 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/basic-content/_doc/template-multiple.drupal.twig
> +{% set reversed             = reversed|json_parse %}
```suggestion
{% set _items = _items|json_parse %}
{% set reversed = reversed|json_parse %}
```

2022-04-10 18:09 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/basic-content/_doc/template.drupal.twig
> +{% set reversed             = reversed|json_parse %}
```suggestion
{% set image = image|json_parse %}
{% set buttons = buttons|json_parse %}
{% set rowButtons = rowButtons|json_parse %}
{% set links = links|json_parse %}
{% set reversed = reversed|json_parse %}
```

2022-04-10 18:14 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/basic-content/twig/index.twig
> +{% set iconPosition     = hasIcon ? image.icon.position %}
```suggestion
{% set titleTag = titleTag|default('p') %}
{% set imagePosition = imagePosition|default('left') %}
{% set hasIcon = image is defined and image.icon %}
{% set iconPosition = hasIcon ? image.icon.position %}
```

2022-04-10 18:16 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/basic-content/twig/index.twig
> +    {% if image is defined and image.src %}
```suggestion
  <div class='container-fluid d-flex flex-column flex-md-row gap-4'>
    {% if image is defined and image.src %}
```

2022-04-26 17:26 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/basic-content/_doc/doc.stories.mdx
> +    textAlign: 'left',
pourquoi le définir. c'est l'alignement par défaut non? dans twig on ne fait rien si textAlign = left

2022-04-26 17:28 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/basic-content/_doc/doc.stories.mdx
> +<Canvas withSource='none'>
ça fait beaucoup de stories juste pour 4 positions d'icône

2022-04-26 17:31 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/basic-content/angular/basic-content.component.ts
> +    @Input() buttons                : object[];
tu ne voulais pas importer de IButton et faire un IButton­[] ?

2022-04-26 17:37 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/basic-content/_doc/doc.stories.mdx
> +    textAlign: 'left',
1 exemple 12 stories... j'aurais fait moins de stories et plus d'exemples

2022-04-27 13:15 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/basic-content/_doc/doc.stories.mdx
> +<Canvas withSource='none'>
Oui, avant j'avais une version avec une seule story pour toutes les iconPosition.
Mais ça ne marchait pas avec les controls.

2022-04-27 13:15 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/basic-content/_doc/doc.stories.mdx
> +                src: `${window.location.origin}/images/_docs/hero-helix-reversed.png`,
Bien vu. les 2 marchent.
Mais le plus simple, le mieux.

2022-04-27 13:15 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/basic-content/_doc/doc.stories.mdx
> +    textAlign: 'left',
C'est le drupal implementtaion example, je met un exemple complet de props à chaque fois.

2022-04-28 21:12 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/basic-content/angular/basic-content.component.ts
> +    @Input() buttons                : object[];
Bien vu! Done

2022-05-06 19:03 UTC, ThalieVideotron reviewed
Go pour Moi - tout mes commentaires à resolved

2022-05-07 23:32 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/row-button/angular/api.model.ts
> +export interface IImage {
```suggestion
export interface IImage {
```

2022-05-07 23:47 UTC, JonathanLefebvreV requested changes
Dans son état actuel, je note 2 choses.
- Les 2 story d'examples doivent avoir le panneau de contrôle désactivé.
- Le basic-content n'est pas une Section. Même si c'est un "god component" Il va dans la section Composant. 1- il est pas fait pour être fullwidth 2- un de ces but est d'être utilisé dans des composant, donc point de vue architecture, inclure une section dans un composant, ne fait pas de sens, 3- il est pas "plug-and-play"

2022-05-08 11:40 UTC, bibifrost commented
> * Les 2 story d'examples doivent avoir le panneau de contrôle désactivé.
Je pense qu'il y a un malentendu autour de ça. Je voulais t'en parler à l'oral pour que ce soit plus simple.
Ici, j'ai besoin des controls pour montrer au consommateur comment repro + pour pouvoir jouer dans cette stories sans avoir à la refaire.
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/93746960/167294413-5374fbc5-1d87-4a67-9ef8-60a0f6aaa437.png">

> * Le basic-content n'est pas une Section. Même si c'est un "god component" Il va dans la section Composant. 1- il est pas fait pour être fullwidth 2- un de ces but est d'être utilisé dans des composant, donc point de vue architecture, inclure une section dans un composant, ne fait pas de sens, 3- il est pas "plug-and-play"
Je crois qu'on ne parle pas de la meme chose? Quand tu dis _il est pas "plug-and-play"_, peux tu préciser?

2022-11-28 10:40 UTC, JonathanLefebvreV approved these changes

2022-11-28 10:41 UTC, merged