DS 252 Section Tiles Post
bifrost-vui/bifrost-front-end-library pull request #235
Opened 2021-12-11 06:45 UTC by bibifrost

2022-01-30 15:35 UTC, JonathanLefebvreV requested changes

2022-01-30 15:35 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/tile-post/_doc/template.drupal.twig
> +    {% endfor %}
Ca manque de description afin de bien documenté les 2 variantes que tu démontres
![image](https://user-images.githubusercontent.com/75901368/151705898-83ec01d5-3487-4ad6-b7a5-907842d72990.png)

2022-01-30 15:35 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/tile-post/angular/tile-post.module.ts
> +  exports: [TilePostComponent]
Indentation à 4 space dans un `ts` au lieu de 2

2022-01-30 15:35 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/tile-post/twig/index.twig
> +                bf-tile-post__visual
indentation à 2 spaces dans un `twig`. remplacé par le 4 actuels

2022-01-30 15:35 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/tile-post/twig/index.twig
> +            </a>
Remplacé pour le composant Button pour avoir 100% de power sur tout les attribut possible HTML et ne pas blocké la Cybermétrie avec ce lien réduit

2022-01-30 15:35 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/tiles-post/_doc/template.drupal.twig
> +		{% include '@bf-sections/tiles-post/twig/index.twig' with {
indentation à 2 spaces dans les `twig`

2022-01-30 15:35 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/tiles-post/_doc/template.drupal.twig
> +		{% include '@bf-sections/tiles-post/twig/index.twig' with {
De plus, même problème dans ce composante que dans l'autre PR avec une section.
Ici l'utilisation des variable et à partir de StoryBook change tous les composante. Chaque "carte" doit être indépendante dans la section

2022-01-30 15:35 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/tiles-post/angular/section-tiles-post.module.ts
> +  imports: [],
indendation à 4

2022-01-30 15:35 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/tiles-post/twig/index.twig
> +</section>
indentation à 2

2022-01-30 15:35 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/tile-post/angular/tile-post.component.ts
> +export class TilePostComponent implements OnInit {
Conceptuellement, je ne comprends pas le nom de ce composant. "tilePost" As-tu des références pour le naming?

2022-02-10 21:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-post/_doc/template.drupal.twig
> +    {% endfor %}
Pas sur de te suivre. C'est le cas **default** et le cas **reversed** qui s'affichent ici.
De quelle description parles-tu?

2022-02-10 21:42 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/tiles-post/_doc/template.drupal.twig
> +		{% include '@bf-sections/tiles-post/twig/index.twig' with {
C'est un bug de Storybook. Je regarde si il a été fixé.

2022-02-10 21:43 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-post/angular/tile-post.component.ts
> +export class TilePostComponent implements OnInit {
On se fait un appel pour parler de tout ça.

2022-02-10 22:13 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-post/twig/index.twig
> +            </a>
Bien vu.
- A date, le composant **Button** peux afficher un lien `<a>` mais pas un **style** de lien.
- le composant **Link** ne peux qu'afficher un lien `<a>` avec un **style** de lien.
- Ici, dans Tile Post, on veux afficher un style de lien mais potentiellement un `<button>` avec toutes les propriétés de `Button`, right?
Dans ce cas, je propose d'améliorer le composant **link** pour qu'il puisse permettre ceci. Quitte à faire un _master_ pour éviter le duplicata de code.
@JonathanLefebvreV ça t'irait?

2022-02-16 17:15 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/tiles-post/_doc/template.drupal.twig
> +		{% include '@bf-sections/tiles-post/twig/index.twig' with {
Fixed.

2022-02-26 21:09 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/tile-post/_doc/template.drupal.twig
> +    {% endfor %}
Wow. J'Avais pas réalisé. CA l'air de de 2 variante de carte ou d'une feature. 

Anyway, si c'est le mode reverse, Il y a quelque chose de brisé.
![image](https://user-images.githubusercontent.com/75901368/155859132-4e56681c-dd3e-4b32-a12f-227f5cc32009.png)

2022-02-26 21:17 UTC, JonathanLefebvreV requested changes
Ajouter la documentation Figma (si elle est prête) dans
[components/tile-post/_doc/doc.stories.mdx](https://github.com/bifrost-vui/bifrost-front-end-library/pull/235/files#diff-347bdcee7f749c8c9d7fff6ebe4bafc30ac5f4c8fd75bfbe7532b3829c6da519)

2022-02-26 21:17 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/tiles-post/_doc/template.drupal.twig
> +</div>
indentation

2022-02-26 21:23 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/tile-post/twig/index.twig
> +            </a>
J'avais oublié la différence Visuel entre Link et Button. On pourra avoir le sujet d'optimisation plus tard.

Pour cette PR, mettre le composant Link,.

2022-03-01 16:14 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-post/_doc/template.drupal.twig
> +    {% endfor %}
Fixed

2022-03-01 16:14 UTC, bibifrost commented
> Ajouter la documentation Figma (si elle est prête) dans [components/tile-post/_doc/doc.stories.mdx](https://github.com/bifrost-vui/bifrost-front-end-library/pull/235/files#diff-347bdcee7f749c8c9d7fff6ebe4bafc30ac5f4c8fd75bfbe7532b3829c6da519)

Done

2022-03-01 16:26 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-post/twig/index.twig
> +            </a>
Done

2022-03-02 13:42 UTC, JonathanLefebvreV requested changes

2022-03-02 13:42 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/tile-post/twig/index.twig
> +    {% endif %}
Desolé.. J'avais raison originalement en metionnant que ca devrait être le composante `button`.
Dans la tuile c'est attendu dans OC11 de pouvoir mettre des bouton de style secondaire.
![image](https://user-images.githubusercontent.com/75901368/156372464-8205f16d-f846-4332-bdc9-77b88ff70ae0.png)

2022-03-02 13:49 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/tile-post/twig/index.twig
> +    {% endif %}
Ahh lala... Le dossier OC11 dans Figma est même pas le vrai composant...
Je vois dans la bibliothèque c'est seulement un lien comme tu l'as fait

Laisse tombé

2022-03-02 13:52 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/tile-post/twig/index.twig
> +    {% endif %}
et ils ont mis des liens présentement en PROD
![image](https://user-images.githubusercontent.com/75901368/156374565-7f18a6fb-1fbd-442a-a21d-68b9fc69792d.png)

2022-03-02 13:54 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/tiles-post/_doc/doc.stories.mdx
> +Check the [Figma](https://www.figma.com/file/7bTmk29aCBl7rCFszffYPr/DS---Components-%26-styles?node-id=2806%3A9236) for more details.
```suggestion
<iframe width='100%' height='450' src='https://www.figma.com/embed?embed_host=share&url=https://www.figma.com/file/7bTmk29aCBl7rCFszffYPr/DS---Components-%26-styles?node-id=2806%3A9236' frameBorder='0' allowFullScreen></iframe>
```

2022-03-02 13:55 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/tile-post/_doc/doc.stories.mdx
> +Check the [Figma](https://www.figma.com/file/7bTmk29aCBl7rCFszffYPr/DS---Components-%26-styles?node-id=2806%3A9236) for more details.
```suggestion
<iframe width='100%' height='450' src='https://www.figma.com/embed?embed_host=share&url=https://www.figma.com/file/7bTmk29aCBl7rCFszffYPr/DS---Components-%26-styles?node-id=2806%3A9236' frameBorder='0' allowFullScreen></iframe>
```

2022-03-02 13:59 UTC, JonathanLefebvreV approved these changes

2022-03-02 14:21 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +## Next version vX.X.X
```suggestion
## Next Version vX.X.X
```

2022-03-02 14:22 UTC, merged