ds-254 init section buttons nav
bifrost-vui/bifrost-front-end-library pull request #236
Opened 2021-12-12 04:06 UTC by bibifrost

2022-01-30 14:10 UTC, JonathanLefebvreV commented
@baptistemac Conflit à fixé

2022-02-26 23:34 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/button-nav/_doc/doc.stories.mdx
> +            iconName    : 'placeholder',
```suggestion
            iconName    : 'placeholder'
```

2022-02-26 23:40 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/button-nav/scss/index.scss
> +            line-height: 1.5rem; // TODO: Replace by `var(--bf-h3-leading)` in order to be themable.
Est-ce que tous ces "todos" devrait être fait maintenant ou tagger avec un Jira?

2022-02-26 23:44 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +  {% set backgroundClass  = 'bf-color-bg-highlight' %}
```suggestion
  {% set backgroundClass = 'bf-color-bg-highlight' %}
```

2022-02-26 23:44 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +  {% set backgroundClass  = 'reversed bf-color-bg-ground' %}
```suggestion
  {% set backgroundClass = 'reversed bf-color-bg-ground' %}
```

2022-02-26 23:46 UTC, JonathanLefebvreV requested changes
Missing updated ChangeLog and this is good to go

2022-03-01 15:37 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button-nav/scss/index.scss
> +            line-height: 1.5rem; // TODO: Replace by `var(--bf-h3-leading)` in order to be themable.
non bien vu! Ça peux etre fait maintenant. Je m'en occupe :)

2022-03-02 12:35 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +- New `Section Button Nav` (see [Component API](?path=/docs/sections-buttons-nav--drupal)).
```suggestion
- New [Section Button Nav](?path=/docs/sections-buttons-nav--drupal)) twig component.
```

2022-03-02 12:37 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/button-nav/scss/index.scss
> +            line-height: 1.5rem; // TODO: Replace by `var(--bf-h3-leading)` in order to be themable.
```suggestion
        font-size: 1.5rem; // TODO DS-232: Replace by `var(--bf-h3-font-size)` in order to be themable.
        line-height: 1.75rem; // TODO DS-232: Replace by `var(--bf-h3-leading)` in order to be themable.
        margin-top: var(--bf-spacer-2);

        @include media-breakpoint-down(sm) {
            font-size: 1.25rem; // TODO DS-232: Replace by `var(--bf-h3-font-size-sm)` in order to be themable.
            line-height: 1.5rem; // TODO DS-232: Replace by `var(--bf-h3-leading)` in order to be themable.
```

2022-03-02 12:52 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +{% endif %}
Cette gestion du background color, permet seulement de reproduire 3 valeur sur 5. 
Il manque le `bf-color-bg-underground`. 
Ca pourrait être considérer comme une régression du composant actuel de DXP.
Mais pour OC11, c'est sensé être un highligh... Je vais voir si il y a d'autre change pour la version avant de dire que c'est un bug.

2022-03-02 13:09 UTC, JonathanLefebvreV requested changes

2022-03-02 13:09 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +  <div class='container-fluid d-flex flex-column align-items-center'>
Je viens d'essayer un test pour reproduire purement en HTML le vrai visuel attendu pour voir si DXP sont capable d'utilsé cette section en créant de facon custom la zone grise marketing.
C'est pas le cas à cause du choix des classe et tag dans le composant.

Je rappel que la section doit représenté cela au final
![image](https://user-images.githubusercontent.com/75901368/156367072-edbfcc0d-3ed9-4e67-b9e0-7be2971af6b1.png)

Je vois 2 solutions.
Soit 
- le composant est moins "fullwidth"(donc pas une section) et qu'on fait une vrai section pour gérer la réalité du "rabbit-hole + la zone grise marketing
- ce composant section introduit dans ces paramètres le choix de la  zone grise avec Title, Description, background-color.

Qu'est-ce que t'en penses?

2022-03-02 13:14 UTC, JonathanLefebvreV requested changes
![image](https://user-images.githubusercontent.com/75901368/156367941-3679b65f-01db-4334-9cea-06c3215b1c0d.png)

C'est quoi `isFeature`?  (Je n'ai jamais entendu parler de cette déviation dans Figma ou de JF)

Pourquoi la propriété `isFeature` est pas dans la section des propriété du composant?

2022-03-02 13:24 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +{% endif %}
A date, j'ai considéré que `bg-underground` et `bg-ground` donnaient un rendu sensiblement similaire.
Mais on pourrait effectivement ajouter les 5 variantes pour chaque story.

2022-03-02 13:25 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +  <div class='container-fluid d-flex flex-column align-items-center'>
Je regarde.

2022-03-02 13:32 UTC, bibifrost commented
> ![image](https://user-images.githubusercontent.com/75901368/156367941-3679b65f-01db-4334-9cea-06c3215b1c0d.png)
> 
> C'est quoi `isFeature`? (Je n'ai jamais entendu parler de cette déviation dans Figma ou de JF)
> 
> Pourquoi la propriété `isFeature` est pas dans la section des propriété du composant?

Le composant Button Nav peux afficher un titre _featured_ ou _non-featured_, comme tu peux le voir dans Figma:
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/93746960/156371263-05ff95aa-e128-488b-8d43-ad0c1caf9e1d.png">
Je regarde pourquoi le control est mal placé.

2022-03-02 18:33 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button-nav/_doc/doc.stories.mdx
> +        height='300px'
ça n'a aucun effet de changer la taille dans story (il y a un overwrite à 100vh) . Honnêtement on ne devrait plus le générer. Pour contrôler la taille du Iframe dans l'onglet docs de Storybook il faut utiliser style dans Canvas

2022-03-02 18:33 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button-nav/_doc/template.drupal.twig
> +  {% set backgroundClass  = 'reversed bf-color-bg-ground' %}
donc on n'as pas la possibilité de faire du `reversed bf-color-bg-undeground`?  c'est juste une question

2022-03-02 18:33 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/_doc/doc.stories.mdx
> +
ça fait pas mal de lignes vides - 2 devraient suffire pour la lisibilité du code mais le MDX ignore les lignes vides superflues (+ que 1) - preuve , on est obligé de mettre un `br` au dessus

2022-03-02 18:33 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/_doc/doc.stories.mdx
> +                { label: 'Mobility',        iconName: 'mobility',               description: 'Maecenas faucibus mollis interdum integer posuere erat a ante venenatis. Maecenas faucibus mollis interdu
si on met sur plusieurs lignes on les aligne mais sur la même ligne je trouve que ça nuit plus que d'autre chose.  On est obligé d'activer la vue avec des soft wrap pour voir le code sans scroll horizontal et ça a l'air tout croche.

2022-03-02 18:33 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/_doc/doc.stories.mdx
> +                { label: 'Mobility',        iconName: 'mobility',               description: 'Maecenas faucibus mollis interdum integer posuere erat a ante venenatis. Maecenas faucibus mollis interdu
un bon exemple de ça a l'air tout croche (git fait du soft wrap)
![image](https://user-images.githubusercontent.com/82388009/156423270-214fc5c5-ff37-4947-8de9-db0778ccae59.png)

2022-03-02 18:33 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/_doc/template.drupal.twig
> +{% set variants = [
dans la section on a les 5 combinaisons de background mais juste 3 dans le composant ?

2022-03-02 18:33 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/angular/section-buttons-nav.component.ts
> +    @Input() buttons        : object[];
`object[]`  ou `buttons[]` 
on a une règle? devrait-on en avoir?

2022-03-02 18:33 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/scss/index.scss
> +
une ligne vide de trop

2022-03-02 18:33 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/scss/index.scss
> +        width: 100%;
le width 100% va être ignoré avec flex - inutile

2022-03-02 18:33 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/scss/index.scss
> +                display: flex !important;
pourquoi le `!important`? Si tu en as vraiment besoin c'est parce que tu utilises une classe bootstrap  dans ton twig sans respecter le mobile first

2022-03-02 18:33 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +<section class='bf-section-buttons-nav py-6 {{ class|default('') }} {{ backgroundClass|default('') }}'>
point de vue HTML une `<section>` doit contenir une balise de titre `<hx>` - je recommande un simple `div` même si c'est vraiment très tentant d'utiliser  `<section>`

2022-03-02 20:20 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +  <div class='container-fluid d-flex flex-column align-items-center'>
Je propose la solution 1. Car il vaut mieux rendre nos composants/sections plus malléables à la composition plutôt que de rendre les composants non-agnostiques.

Voici les changements necessaires pour recréer cette section:
Les changements dev:https://github.com/bifrost-vui/bifrost-front-end-library/compare/ds-254-section-button-nav...ds-254-videotron-home-page

2022-03-02 20:45 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +<section class='bf-section-buttons-nav py-6 {{ class|default('') }} {{ backgroundClass|default('') }}'>
Ça serait vraiment dommage car c'est véritablement une section sémantiquement et fonctionnellement.
A propos du heading:
[Voici ce que dis](https://stackoverflow.com/questions/8544671/is-it-necessary-to-have-a-heading-of-section-in-html5#:~:text=No%2C%20it%20is%20not%20required,warning%20is%20not%20an%20error.)

2022-03-02 20:48 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/angular/section-buttons-nav.component.ts
> +    @Input() buttons        : object[];
Tant qu'on n'a pas le composant Angular, ça n'a pas d'importance.
Je vois qu'on a IButton dans les Cards, mais on devrait externaliser cette interface dans Button et l'importer pour chaque include de Buttons. A moins que ça ne soit pas la meme API evidemment.
Dans un autre JIRA, Je dirais.

2022-03-02 20:50 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/_doc/doc.stories.mdx
> +
Bien vu. J'ai corrigé.
La logique que je propose
2 lignes au dessus d'un titre, sinon 1 ligne:
```


# Title 1

<canvas>
</canvas>

<canvas>
</canvas>


# Title 2
```

2022-03-02 20:51 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button-nav/_doc/template.drupal.twig
> +  {% set backgroundClass  = 'reversed bf-color-bg-ground' %}
Fixé

2022-03-02 20:51 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button-nav/_doc/doc.stories.mdx
> +        height='300px'
retiré

2022-03-02 20:51 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/scss/index.scss
> +
fixé

2022-03-02 20:52 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/scss/index.scss
> +        width: 100%;
fixé

2022-03-02 20:52 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +{% endif %}
fixé.
les 5 templates sont affichés

2022-03-02 20:56 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +<section class='bf-section-buttons-nav py-6 {{ class|default('') }} {{ backgroundClass|default('') }}'>
Mais d'ailleurs, la section contient un title optionnel.

2022-03-02 20:56 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/scss/index.scss
> +                display: flex !important;
Bien vu. Merci

2022-03-02 21:03 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/_doc/doc.stories.mdx
> +                { label: 'Mobility',        iconName: 'mobility',               description: 'Maecenas faucibus mollis interdum integer posuere erat a ante venenatis. Maecenas faucibus mollis interdu
fixé

2022-03-02 21:03 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/_doc/doc.stories.mdx
> +                { label: 'Mobility',        iconName: 'mobility',               description: 'Maecenas faucibus mollis interdum integer posuere erat a ante venenatis. Maecenas faucibus mollis interdu
fixé

2022-03-04 03:26 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +  <div class='container-fluid d-flex flex-column align-items-center'>
Tu dis choisir 1, mais ton autre PR n'est pas une section utilisable pour nos consommateurs. 
Dans le Jira, le but était faire une section déjà composé avec les propriétés nécessaire.

Meaning :
- 1 rabbit hole avec ces propriété qui gère les 5 backgrounds comme le Hero.
- une parti qui gère un Titre, description et lien centrer. + les 5 background.

J'ai pas de nom intelligent à suggérer pour cette section qui fait du sens. On peut brainstormer en gang.

(Je sais ce que tu es entrain de pensé : mais on fait un design system, et les section composé d'une aussi faible valeur de réusabilité, on rien à faire dans Bifrost.... Et je suis assez d'accord avec toi. Par contre, si tu te souviens, on a jaser plusieurs fois de ce que UIKIT offrait avec les "template" qui sont des "section" et qu'on va devoir un jours voir comment on gère ca... 
Ce qui est sur c'Est que DXP nous on demandé de plus les aidez pour les composition compliqué qui prenne des semaines de leur coté, avec leur savoir à faire... ET ce Jira est le début des sections dans ce sens qu'on leur offre de la composition... ou que ce soit nous qui aillons faire de la composition dans Drupal en temps que membre DXP. Sujet qu'on a parler encore mercredi après tu sois partie. Je penses que je vous ai pas assez parler de ça... On en parle lundi)

2022-03-04 03:27 UTC, JonathanLefebvreV commented
> Le composant Button Nav peux afficher un titre _featured_ ou _non-featured_, comme tu peux le voir dans Figma: <img alt="image" width="1324" src="https://user-images.githubusercontent.com/93746960/156371263-05ff95aa-e128-488b-8d43-ad0c1caf9e1d.png"> Je regarde pourquoi le control est mal placé.

As tu le lien Figma de ton screenshot?

2022-03-07 18:13 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +<section class='bf-section-buttons-nav py-6 {{ class|default('') }} {{ backgroundClass|default('') }}'>
excellent! On garde Section. Je vois que le validator n'en fait plus qu'un warning et non une erreur et tout à fait d'accord qu'il s'agit d'une section point de vue sémantique

2022-03-22 16:20 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/scss/index.scss
> +                display: flex !important;
@ThalieVideotron à resolved

2022-03-23 13:30 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +        {{ content|default('') }}
lui par contre on ne test pas s'il existe. dans ce cas c'est ok d'avoir un default mais pas cohérent avec ce qui est fait plus haut

2022-03-23 13:30 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/_doc/template.drupal.twig
> +  { background: background|default('highlight'), reversed: reversed|default(true) },
le dernier est problématique 
![image](https://user-images.githubusercontent.com/82388009/159705866-c2901302-ea57-443a-a482-d9a6d7a99e43.png)
 juste une question : est-ce que ça va se résorber au merge de la branche DS-294 (higlight+reverse) ?

2022-03-23 13:30 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +  {% set backgroundClass = 'bf-color-bg-highlight highlight' %}
pourquoi 2 classes pour faire une couleur de background ?  bf-color-bg-highlight est suffisant non?

2022-03-23 13:30 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +      <{{ titleTag }} class='h2 mb-4 text-center' style='max-width: 40rem'>
j'insiste. pas de inline style hardcodé dans les `index.twig`. On a une feuille de styles pour ça.
le seul cas où c'est ok c'est quand on a besoin d'une variable pour setter le style : 
`style='max-width: {{ twigVar }}px'`

2022-03-23 13:30 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +              highlight: buttonNavHighlight|default(false)
![image](https://user-images.githubusercontent.com/82388009/159709511-ff64e8a2-2ddf-46e3-a718-3711c2f81055.png)
il y a un truc qui ne fonctionne pas.  j'ai jamais réussi à avoir des boutons jaunes comme dans button nav
![image](https://user-images.githubusercontent.com/82388009/159710218-bf5de7b2-00b9-410a-9178-89d6a5e1ae18.png)

2022-03-23 21:03 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +              highlight: buttonNavHighlight|default(false)
c'est normal. c'est bridé. Si tu veux un style highlight dans ta **Section Button Nav**, tu dois faire `background: highlight`.

2022-03-23 21:05 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +  {% set backgroundClass = 'bf-color-bg-highlight highlight' %}
La classe highlight sera necessaire quand on aura mergé DS-294. En attendant, elle ne devrait effectivement pas etre la :)

2022-03-27 19:12 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +  {% set backgroundClass = 'bf-color-bg-highlight highlight' %}
DS-294 a été mergé, donc à retesté si tout est beau

2022-03-27 19:21 UTC, JonathanLefebvreV requested changes
retesté les "hightlight"

2022-03-27 19:21 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +
N'est pas à la bonne place. Mettre à jour avec Master

2022-03-27 19:22 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/buttons-nav/_doc/template.drupal.twig
> +{% set variants = [
celui ci a été fixé ![image](https://user-images.githubusercontent.com/75901368/160297270-177d47f0-b0b1-4f09-b0c3-fcf34b5e38c6.png)

2022-03-28 13:57 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +              {{ label|default('') }}
oui, il n'a rien a faire la :)

2022-03-28 13:58 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +        {{ content|default('') }}
Il n'a pas de div qui wrap. Donc on peux le |default au lieu de le tester avec if.

2022-03-28 14:12 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +  {% set backgroundClass = 'bf-color-bg-highlight highlight' %}
hum la PR ne semble pas mergée.
https://github.com/bifrost-vui/bifrost-front-end-library/pull/273

2022-03-28 14:14 UTC, bibifrost commented on CHANGELOG.mdx
> +
Fixed

2022-03-28 14:27 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +      <{{ titleTag }} class='h2 mb-4 text-center' style='max-width: 40rem'>
Fixed. 
J'en parlais, j'ai créé 2 classes utilitaires pour maitriser la largeur maximum des textes:
<img width="205" alt="image" src="https://user-images.githubusercontent.com/93746960/160420237-1cb8b5e7-1c98-4fbd-acb3-5e5c9de47381.png">

N'hésites pas à les utiliser.

2022-03-28 18:10 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/scss/base/_typography.scss
> +.title-max-w {
cool mais on aurait aussi pu y aller avec `max-w-40rem` et `max-w-35rem` (voir même un mixin avec nos largeur max les plus populaires) - ça aurait comblé le vide de bootstrap qui ne nous offre que des versions en pourcentage. On verra si ça revient et on y pensera à ce moment-là

-------------------------------

Considérer comme resolved c'est juste une piste de réflexion

2022-04-04 00:12 UTC, JonathanLefebvreV requested changes
bug on reverse mode for button-nav
![image](https://user-images.githubusercontent.com/75901368/161455215-2ddc9f3d-1647-4e7e-b7c6-14a96a6c814b.png)

2022-04-04 00:14 UTC, JonathanLefebvreV requested changes
Bug with disabled property and highlight
![image](https://user-images.githubusercontent.com/75901368/161455280-8149eba3-72fc-4e4e-8cc7-4f433dfcb6fa.png)

2022-04-04 00:21 UTC, JonathanLefebvreV requested changes
In the Section, it's really hard to test in mobile with all these colors.
Can you make a suggestion to separate each "section" rendered?

Also, a highlight reverse state needs to be fixed.
![image](https://user-images.githubusercontent.com/75901368/161455541-97675a1c-e3ed-44fa-95d8-89f73ea5143b.png)

2022-04-04 12:42 UTC, bibifrost commented
> light reverse sta

Cet état n'a pas encore designé.
Je viens d'améliorer le template de Button pour qu'on s'en rende compte.

2022-04-04 12:43 UTC, bibifrost commented
> In the Section, it's really hard to test in mobile with all these colors.

Hum oui. Je pourrai ajouter un padding entre les sections, mais il sera difficile pour un consommateur de savoir si le padding appartient au composant ou au template. Je vais voir

2022-04-04 12:44 UTC, bibifrost commented
> bug on reverse mode for button-nav ![image](https://user-images.githubusercontent.com/75901368/161455215-2ddc9f3d-1647-4e7e-b7c6-14a96a6c814b.png)

Fixed

2022-04-10 19:42 UTC, JonathanLefebvreV requested changes
Le state de "reversed" et "disabled" ne donne pas un résultat uniforme.
![image](https://user-images.githubusercontent.com/75901368/162636799-11141a03-d845-46a4-b964-4e26b9de8c30.png)

"Disabled" devrait primé sur les autre style selon moi.

2022-04-18 19:37 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button-nav/scss/index.scss
> +        font-size: 1.5rem; // TODO DS-232: Replace by `var(--bf-h3-font-size)` in order to be themable.
non, ce n'est pas encore mergé.

2022-04-18 19:42 UTC, bibifrost commented on CHANGELOG.mdx
> +- New [Twig Section Button Nav](?path=/docs/sections-buttons-nav--drupal).
done

2022-04-18 19:45 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/_doc/template.drupal.twig
> +{% set variants = [
> Le state de "reversed" et "disabled" ne donne pas un résultat uniforme. ![image](https://user-images.githubusercontent.com/75901368/162636799-11141a03-d845-46a4-b964-4e26b9de8c30.png)
> 
> "Disabled" devrait primé sur les autre style selon moi.

Je n'ai pas le meme rendu. Ou en tout cas, la derniere version est correcte:
<img width="1756" alt="image" src="https://user-images.githubusercontent.com/93746960/163867064-327b78cc-7ea4-4960-b4c8-eedf5a755ed1.png">

2022-04-18 20:10 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/scss/index.scss
> +.reversed .bf-button--primary:not(.disabled) {
done

2022-04-25 17:37 UTC, bibifrost commented
> Le state de "reversed" et "disabled" ne donne pas un résultat uniforme. ![image](https://user-images.githubusercontent.com/75901368/162636799-11141a03-d845-46a4-b964-4e26b9de8c30.png)
> 
> "Disabled" devrait primé sur les autre style selon moi.

Ça devrait etre fixed

2022-04-26 16:26 UTC, ThalieVideotron requested changes

2022-04-27 10:15 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button-nav/_doc/doc.stories.mdx
> +            defaultValue: 'placeholder',
Bien vu. je vais regarder ça.

2022-04-27 10:15 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button-nav/scss/index.scss
> +            font-size: .875rem; // font-size exception: 14px
Pourquoi? Il me semble utile de préciser que c'est une exception et donc volontairement pas une variable CSS.
Pour la maintenance.

2022-04-27 10:15 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +<section class='bf-section-buttons-nav d-flex flex-column flex-lg-row {{ backgroundClass }} {{ reversed|default(false) ? 'reversed' }} {{ class|default(NULL) }}' {{ extraAttribute|default(NULL) }}>
`twig.js` est case insensitive aussi.
Il faut juste s'entendre sur `null` ou `NULL`. `null` me va très bien.

2022-04-27 10:15 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/_doc/doc.stories.mdx
> +        name='Drupal - With rightSection'
Pourquoi? Que proposes-tu?

2022-04-27 10:28 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button-nav/twig/index.twig
>  {% include '@bf-components/button/twig/index.twig' with {
Done

2022-04-27 10:28 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button-nav/_doc/doc.stories.mdx
> +            defaultValue: 'placeholder',
done

2022-04-27 10:29 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +<section class='bf-section-buttons-nav d-flex flex-column flex-lg-row {{ backgroundClass }} {{ reversed|default(false) ? 'reversed' }} {{ class|default(NULL) }}' {{ extraAttribute|default(NULL) }}>
done

2022-04-27 12:49 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/_doc/doc.stories.mdx
> +        name='Drupal - With rightSection'
Aussi, a chaque fois, je prefere mettre `Drupal - With + nom de la props`. Ça permet de connaitre exactement le nom de la props responsable du rendu de la story.
Donc je garderais `rightSection`, si tu n'y vois pas d'objection.

2022-04-27 12:50 UTC, bibifrost commented
> là c'est le reversed qui ne répond plus : https://bifrost-front-end-library-git-ds-254-section-2e57b8-bifrost-vui.vercel.app/?path=/story/components-button-nav--drupal&args=reversed:true

Fixed. Merci

2022-05-05 11:57 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/button-nav/scss/index.scss
> +            font-size: .875rem; // font-size exception: 14px
commentaire valide - resolved

2022-05-05 12:04 UTC, JonathanLefebvreV requested changes

2022-05-05 12:04 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/buttons-nav/angular/section-buttons-nav.component.ts
> +    @Input() rightSection   : object;
Ajouter la documentation de la définition de l'objet

2022-05-05 12:04 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +          {% include '@bf-components/link/twig/index.twig' with rightSection.link %}
Il y a un problème avec link et le hover tooltip
Je n'arrive pas à comprends. Ca vient de ou, et il faudrait gérer cela dans la doc
![image](https://user-images.githubusercontent.com/75901368/166919336-362c2193-ee95-444c-bc4d-033d37826123.png)


Ce qui touche directement à Link pourrait être fait dans un autre PR. Je souhaite ici juste que la section soit simple en utilisation et "plug-and-play"

2022-05-05 12:15 UTC, JonathanLefebvreV requested changes

2022-05-05 12:15 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +      <div class='bf-section-buttons-nav__right-section__inner'>
Il y a une zone d'espacement de trop en mobile ici
![image](https://user-images.githubusercontent.com/75901368/166920858-fada8930-3c83-403f-bdaf-124a5e916155.png)

2022-05-05 17:13 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +          {% include '@bf-components/link/twig/index.twig' with rightSection.link %}
Bien vu! Il manquait simplement un `only` au link.
Fixed

2022-05-05 17:14 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/angular/section-buttons-nav.component.ts
> +    @Input() rightSection   : object;
Done

2022-05-05 17:47 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +      <div class='bf-section-buttons-nav__right-section__inner'>
Fixed

2022-05-05 17:49 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button-nav/_doc/doc.stories.mdx
> +    label: 'Default',
comme tu le suggérais ailleurs je mettrais un exemple concret - suggestion/ pas demande de changement

2022-05-05 17:49 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button-nav/angular/api.model.ts
> +    reversed       : boolean;
je ne crois pas que ça soit le bouton qui soit reversed.  
à repenser dans nos  prochaines améliorations  - il y aurait une analyse à faire sur ce qui peut être reverse ou non - next version - un Jira pour évaluer la situation suivra sous peu. En attente des réflexion de Kathleen sur higlight/reversed pour le pondre

2022-05-05 17:49 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button-nav/angular/button-nav.module.ts
>  import { ButtonNavComponent } from './button-nav.component';
il faudrait se faire un micro jira pour nettoyer les templates de composants - c'est pas long mais ça va élminer ce genre de procédure redondante

2022-05-05 17:49 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/angular/section-buttons-nav.component.ts
> +interface IRightSection {
d'habitude on met les interfaces en début de fichier suite aux imports. pour la lisibilité, quand on arrive au composant on sait ce qu'est IRightSection

2022-05-05 17:49 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/scss/index.scss
> +
```suggestion
```

2022-05-05 17:54 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +    <div class='bf-section-buttons-nav__right-section d-flex flex-column justify-content-center align-items-center bf-color-bg-underground text-center p-6'>
https://developer.mozilla.org/fr/docs/Web/HTML/Element/aside
et moi qui pensait que tu nous proposerait une vrais `<aside>`  ;-) 
ça aurait été valide et même pertinent point de vue sémantique mais pas essentiel.

2022-05-05 20:52 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +    <div class='bf-section-buttons-nav__right-section d-flex flex-column justify-content-center align-items-center bf-color-bg-underground text-center p-6'>
oui j'y ai penser. Visuellement, **le contenu** est aside aux button nav. Mais est-il vraiment **aside** sémantiquement? Je ne crois pas.

2022-05-05 21:04 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button-nav/angular/api.model.ts
> +    reversed       : boolean;
oui, on en parlait.
A repenser globalement.

2022-05-05 21:04 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button-nav/angular/button-nav.module.ts
>  import { ButtonNavComponent } from './button-nav.component';
oui, l'indentation est ok dans les templates. pas les nouveaux alignement avec `=` et `:`.
C'est un vieux composant fait a partir des anciens templates.

2022-05-05 21:05 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/buttons-nav/angular/section-buttons-nav.component.ts
> +interface IRightSection {
done

2022-05-05 21:05 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button-nav/_doc/doc.stories.mdx
> +    label: 'Default',
done

2022-05-06 18:32 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button-nav/angular/api.model.ts
> +    reversed       : boolean;
resolved - Jira créé  : https://videotron-design-system.atlassian.net/browse/DS-371
- on le modifiera suite à la réflexion des couleurs
- se servir des commentaires du jira si on veux y stocker des pistes de réflexion en attendant

2022-05-06 18:36 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/twig/index.twig
> +    <div class='bf-section-buttons-nav__right-section d-flex flex-column justify-content-center align-items-center bf-color-bg-underground text-center p-6'>
le premier c'est des services, le second c'est de la pub. 
Je veux bien que c'est de la pub sur des services. 

c'est pas essentiel anyway.

2022-05-06 18:44 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/buttons-nav/_doc/doc.stories.mdx
> +        titleTag: {
@bibifrost  je trouve ça étrange que ça soit des h1 par défault,
une fois qu'on les met en troupeau, il peut y avoir un titre... quel va être le niveau de ce titre?

il ne s'agit pas de le changer mais se mettre une note pour le challenger - ça me semble vraiment excessif pour un bouton. il y a toujours un débat sur le fait  qu'on ne doive avoir qu'un seul h1 par page alors imagine 5 ou 6 dans une section.

2022-05-06 18:47 UTC, ThalieVideotron reviewed
@bibifrost  et @JonathanLefebvreV  : Good pour moi - 
j'ai fait des resolved et 1 jira ;-)

2022-05-07 18:40 UTC, JonathanLefebvreV commented
> @bibifrost et @JonathanLefebvreV : Good pour moi - j'ai fait des resolved et 1 jira ;-)

Ecris le pas @ThalieVideotron. Dis le en fesant "approve" sur la pull-request

2022-05-07 18:43 UTC, JonathanLefebvreV approved these changes

2022-05-07 18:43 UTC, merged