DS-253 init section keys
bifrost-vui/bifrost-front-end-library pull request #237
Opened 2021-12-12 04:10 UTC by bibifrost

2021-12-13 16:01 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/keys/_doc/doc.stories.mdx
> +        { href: '',        label: 'Button',     hierarchy: 'primary-alt' },
d'habitude quand on met sur une ligne on supprime les espaces - ça ne me choque pas mais...

2021-12-13 16:39 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/keys/_doc/doc.stories.mdx
> +        { href: '',        label: 'Button',     hierarchy: 'primary-alt' },
C'est pour la lisibilité.

2021-12-13 16:39 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/keys/_doc/template.drupal.twig
> +    {},
ici il faut un `{}`

2021-12-13 16:39 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/keys/twig/index.twig
> +{% set titleTag = titleTag|default('h1') %}
fixed

2021-12-13 16:39 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/keys/twig/index.twig
> +        {% if buttons is defined and buttons %}
fixed

2021-12-13 16:39 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/keys/twig/index.twig
> +            <header style='max-width: 40rem'>
`pcq il n'est pas affecté par une variable twig` comment ça?

2021-12-13 16:39 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/keys/_doc/template.drupal.twig
> +{% set keys         	    = keys|json_parse %}
bien vu! fixed

2022-01-30 14:44 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/keys/_doc/doc.stories.mdx
> +        { href: '',        label: 'Button',     hierarchy: 'primary-alt' },
Même commentaire que Nath,
Splitter les propriété de objects en plusieur ligne. 
C'est un standard d'écriture

2022-01-30 14:50 UTC, JonathanLefebvreV requested changes

2022-01-30 14:50 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/keys/_doc/doc.stories.mdx
> +            ],
pareil ici. Chaque propriété sur une ligne

2022-01-30 14:50 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/keys/_doc/template.drupal.twig
> +{% set keys         	    = keys|json_parse %}
C'est pas fixé. On voit encore une indentation sur 4 au lieu de 2

2022-01-30 14:50 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/keys/angular/section-keys.module.ts
> +  declarations: [SectionKeysComponent],
4 indent au lieu de 2 dans les fichier 'ts'

2022-01-30 14:50 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/keys/angular/section-keys.component.ts
> +    @Input() highlight      : boolean;
Il faudrait, mais il faudrait refactoré tout en même temps.
Ca mérite son propre Jira pour uniformisé les API en même temps, et synchroniser le breaking change avec DXP. 
Laissons comme ca pour le moment

2022-01-30 14:56 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/keys/twig/index.twig
> +				<li class='bf-section-keys__item d-flex flex-row flex-md-column align-items-start gap-4 p-0'>
On fait pas un composant avec l'intérieur de ce `for` ?

2022-01-30 15:00 UTC, JonathanLefebvreV commented
S itu peux faire un update avec Master et testé ce que https://videotron-design-system.atlassian.net/browse/DS-256 fonctionne aussi dans ta section. Ca devrait, mais juste s'en assurer

2022-01-30 15:04 UTC, JonathanLefebvreV commented
Il y a un bug avec la Section dans Storybook.

Reproduction:
- Allez à https://bifrost-front-end-library-git-ds-253-init-fe-1ccdcb-bifrost-vui.vercel.app/?path=/story/sections-keys--drupal
- Trouvé la propriété `keys`
- Prendre le premier élément et supprimé `iconName`
Result:
- Tout les Icon disparaisse et les autre "keys" object n'ont plus d'iconName

Expected: change objet key est indépendant et possède ces propre propriété.

2022-02-10 22:46 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/keys/twig/index.twig
> +				<li class='bf-section-keys__item d-flex flex-row flex-md-column align-items-start gap-4 p-0'>
A date, je ne vois pas de raison de le faire, car le composant seul n'existe pas en tant que tel.

2022-02-14 17:11 UTC, bibifrost commented
> Il y a un bug avec la Section dans Storybook.
> 
> Reproduction:
> 
> * Allez à https://bifrost-front-end-library-git-ds-253-init-fe-1ccdcb-bifrost-vui.vercel.app/?path=/story/sections-keys--drupal
> * Trouvé la propriété `keys`
> * Prendre le premier élément et supprimé `iconName`
>   Result:
> * Tout les Icon disparaisse et les autre "keys" object n'ont plus d'iconName
> 
> Expected: change objet key est indépendant et possède ces propre propriété.

bien vu. Fixed

2022-02-26 20:20 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/keys/_doc/doc.stories.mdx
> +Check the [Figma](https://www.figma.com/file/7bTmk29aCBl7rCFszffYPr/DS---Components-%26-styles?node-id=10057%3A180) for more details
```suggestion
## Design Guidelines
<iframe width='100%' height='450' src='https://www.figma.com/embed?embed_host=share&url=https://www.figma.com/file/7bTmk29aCBl7rCFszffYPr/DS---Components-%26-styles?node-id=10057%3A180' frameBorder='0' allowFullScreen></iframe>
```

2022-02-26 20:53 UTC, JonathanLefebvreV requested changes
C'est quelle API ou classe qu'il faut utilisé pour faire la version "center" du composant?
Il faut documenter comme il faut

2022-02-26 20:54 UTC, JonathanLefebvreV commented
Pourquoi tu l'as appeler `Keys` si dans Figma c'est `Feature List`? C'est discuté avec JF?

2022-03-01 16:32 UTC, bibifrost commented
> C'est quelle API ou classe qu'il faut utilisé pour faire la version "center" du composant? Il faut documenter comme il faut

Je n'avais pas vu la version `center` dans Figma ou alors elle n'existait pas.
Quoi qu'il en soit, je vais la faire :)

2022-03-02 10:58 UTC, bibifrost commented
> > C'est quelle API ou classe qu'il faut utilisé pour faire la version "center" du composant? Il faut documenter comme il faut
> 
> Je n'avais pas vu la version `center` dans Figma ou alors elle n'existait pas. Quoi qu'il en soit, je vais la faire :)

DOne

2022-03-02 13:20 UTC, JonathanLefebvreV requested changes

2022-03-02 13:20 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/keys/twig/index.twig
> +{% endif %}
Cette gestion de background permet de reproduire seulement 3 background sur 5.
Dans OC11, c'est attendu qu'il soit underground.

2022-03-02 13:25 UTC, JonathanLefebvreV requested changes

2022-03-02 13:25 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/keys/twig/index.twig
> +				{% endif %}
La gestion du `align` n'est pas comme attendu.
Le titre passe à gauche au lieu de resté "center"
![image](https://user-images.githubusercontent.com/75901368/156370241-999f9260-253f-413e-bae4-cd1d64ac10bb.png)

2022-03-02 17:18 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/keys/twig/index.twig
> +				{% endif %}
c'est fixé

2022-03-02 17:22 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/keys/twig/index.twig
> +{% endif %}
Done. affichage des 5 templates.

2022-03-02 17:24 UTC, bibifrost commented
> Pourquoi tu l'as appeler `Keys` si dans Figma c'est `Feature List`? C'est discuté avec JF?

C'est validé avec JF à l'instant.

2022-03-02 19:52 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/keys/angular/section-keys.component.ts
> +    @Input() buttons        : object[];
button[] ?

2022-03-02 19:56 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/keys/twig/index.twig
> +            <header style='max-width: 40rem'>
` <header style='max-width: {{ headerWidth }}'>` ça a sa place dans un template, dans les template.twig qui sont dans la doc, ok aussi , mais règle générale pas de inline styles alors qu'on a une feuille de style par composant.

2022-03-03 13:29 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/keys/angular/section-keys.component.ts
> +    @Input() buttons        : object[];
C'est quoi ta suggestion @ThalieVideotron ?
Je comprends par parce que c'est notre standard de définition de array... As-tu une place en tête qu'on fait mieux?

2022-03-03 13:36 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/keys/twig/index.twig
> +{% endif %}
Ce n'est pas le template qu'il faut changer, mais la section. Il faut que la section possède un API qui permet à l'intégrateur de choisir parmi les 5 choix de background.

Reproduire le même APIs que le composant Hero pour le choix de color background

2022-03-07 14:05 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/keys/scss/index.scss
> +    &__item {
```
.bf-section-keys {
    header {
        max-width: 40rem;
    }
    &__item {
```
pour remplacer le inline style dans le template twig

2022-03-07 14:05 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/sections/keys/twig/index.twig
> +
ligne vide

2022-03-07 15:09 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/keys/angular/section-keys.component.ts
> +    @Input() buttons        : object[];
Oui effectivement

2022-03-07 15:11 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/keys/angular/section-keys.component.ts
> +    @Input() buttons        : object[];
Done

2022-03-07 15:11 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/keys/twig/index.twig
> +
DOne

2022-04-03 22:37 UTC, JonathanLefebvreV requested changes
Vu que je viens de mergé https://github.com/bifrost-vui/bifrost-front-end-library/pull/273
Peux tu mettre à jour la PR e fixé aussi le problème de Reversed HighLight dans cette section?

2022-04-03 22:47 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/sections/keys/twig/index.twig
> +		{% endif %}
Is that the expected default buttons hiearchy?
![image](https://user-images.githubusercontent.com/75901368/161451990-29d18737-8eea-48b7-b57f-dfb7bdd9d6eb.png)

I only see 1 button example in Figma

2022-04-04 13:14 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/keys/twig/index.twig
> +		{% endif %}
Good question. I am going to ask JF.

2022-04-05 07:11 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/keys/twig/index.twig
> +		{% endif %}
well. No buttons anymore :)

2022-04-10 19:19 UTC, JonathanLefebvreV approved these changes

2022-04-21 19:58 UTC, merged