DS-269: Status component
bifrost-vui/bifrost-front-end-library pull request #251
Opened 2022-02-05 14:30 UTC by JonathanLefebvreV

2022-02-07 01:21 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/status/twig/index.twig
> +  <p class='bf-status bf-status-{{ color|default('') }} {{ class|default('') }}'>{{ label }}</p>
@ThalieVideotron, est-ce que tu as une suggestion sur l'accessibilité à propos du `::before` qui affiche la couleur du status visuellement seulement?

2022-02-07 14:02 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/status/scss/index.scss
> +.bf-status {
Invalid modif. By removing the original scss of the component in UIKIT, now the result is `status` and `status-color-` are missing for the existing component used.

Need to set both classes definitions in this file.

2022-02-07 14:05 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/_doc/1-Introduction/5-components-list.stories.mdx
> +| **Status**            | Bifrost   | Drupal        | ✅            | ⬜ |
ça me fait penser : est-ce que je devrait faire cette mise à jour dans mes stories?

2022-02-09 15:21 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/status/scss/index.scss
> +        @extend .position-absolute--center-left;
Ichh.... On a du bootstrap littéralement partout. Pas sur que cette argument soit valide. Et la réalité de changer Bootstrap est  presque à 0.

Je vais quand même changer le extent et mettre la définition directement.

2022-02-09 15:23 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/status/scss/index.scss
> +        background-color: $gray-100;
C'est qu'il n'y a pas de couleur Design système qui réflète ce gris qui en plus n'est pas indiqué dans Storybook. C'est un genre de "nullproofing". Je me demandais si ça ne devait pas être autre chose, mais ca pas d'impacte, pas de valeur, dont je me suis dit:  "pareto rule".

Par contre, je veux bien mettre la bonne variable, C'est laquelle selon toi?

2022-02-09 15:24 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/status/scss/index.scss
> +            background-color: $gray-300;
même chose, je n'ai pas trouvé. 
Laquelle je dois mêttre?

2022-02-09 15:33 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/status/scss/index.scss
> +    @each $color, $value in $theme-colors {
1- Ok, mais ça vient du UIKIT et comme le commentaire indique. C'est du UIKIT Legacy qu'on va enlever un moment donner.

2- Je voulais changer le composante pour avoir la nomenclature "bf-" dans les classe.
Par contre, vu que je peux refactoré le vieux fichier SCSS du uikit, il faut garder la vielle nomenclature. Sinon, le composante UIKIT va brisé au déploiment de la prochaine version Bifrost. Autrement dit, ca crée un "breaking-change" et il faut absolument les évité dans le contexte actuel. Donc, on doit garder "status" mais j'aimerais avoir aussi "bf-status".

3- C'est vrai que ca règle le problème, mais je trouve ca wierd de bifrostisé le composante twig et pas rappatrié le CSS.
Mais tu as raison que sur la définition des classe, la mixin devrait pas être associé à "bf-" Je vais refactoré ca

2022-02-09 15:33 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/_doc/1-Introduction/5-components-list.stories.mdx
> +| **Status**            | Bifrost   | Drupal        | ✅            | ⬜ |
oui ca aiderait, mais pas obligatoire pour le moment. Ce pourquoi je te l'ai pas mentionné

2022-02-10 12:40 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/status/scss/index.scss
> +        background-color: $gray-100;
`background-color: var(--bf-color-neutral-tertiary)`

PTI je ne vois pas pourquoi on défini la BG color ici et dans la classe default mais il n'y a pas de raison pour que ça soit différent de la couleur avec la classe default (le nom le dit, c'est le défaut). je remet surtout en cause la classe default  qui ne fait pas de sens. juste mettre ce gris bifrost à la place. ce n'est pas la même teinte mais c'est la couleur BF qui devrait être là

2022-02-10 12:50 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/status/twig/index.twig
> +  <p class='bf-status bf-status-{{ color|default('') }} {{ class|default('') }}'>{{ label }}</p>
`role=alert`  pour le fail seulement pourrait s'appliquer (sur le p).
en passant, je trouve que ça ressemble étrangement à une liste et du coup je suis suis très surprise de voir une liste de `<p>` 
je ne crois pas que ce soit un breaking change de mettre une structure HTML plus pertinente sur le plan sémantique et ça viendrais  améliorer l'accessibilité (le ul c'est la sauce qui uni les li... pour le lecteur d'écran - et les moteurs de recherche - on comprend que ce sont des choses qui sont liées) .

2022-02-10 15:26 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/status/twig/index.twig
> +  <p class='bf-status bf-status-{{ color|default('') }} {{ class|default('') }}'>{{ label }}</p>
bon, je mettrais rien alors.

T'as l'air d'être entrain de confondre le Template de la Story versus le Ccomposant. 
Le composant est un `p` parce que son utilisé est être inclus uniquement, Il s'affiche jamais avec d'autre

2022-02-11 19:56 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/status/twig/index.twig
> +  <p class='bf-status bf-status-{{ color|default('') }} {{ class|default('') }}'>{{ label }}</p>
oups effectivement pour la liste, c'est la strory, pas le composant!!! ça change tout! 


alors oui, on peut rendre le tout acessible : 

Étape 1 : 
sur le P,  on utilise `role=status` sauf si c'est une erreur alors c'est `role-alert`. 
de plus, comme ce ne sont pas des éléments interactifs qui peuvent recevoir le focus,  ils ont besoin d'un ID pour que le champs qui affiche le statuts puisse y référer dans un attribut `aria-controls` 

Étape 2 : pour les rôle `status` au moins : Le message devrait indiquer le statut en clair (comme dans ton exemple) sinon il n'y a pas moyen de voir la différence entre les différents statuts (avec le rôle alert  ils se doutent que c'est une erreur) 

il faudrait éviter de l'utiliser comme dans la gestion de mots de passe parce que le statut n'est pas clair pour le lecteur d'écran 
![image](https://user-images.githubusercontent.com/82388009/153657760-54aa9e76-cbea-419f-a127-b1fb8cdd1dcc.png)

pour que ça reste accessible, il faut créer à l'intérieur du `p` un `span`  visible uniquement pour les lecteurs d'écran qui écrirait le statuts en clair mais ça implique des variables pour le labeling de ces statuts  et éventuellement une gestion de langue

voir exemple ici  pour le texte visible par des lecteur d'écrans uniquement : https://www.anysurfer.be/fr/documentation/articles/detail/cacher-du-texte#screenreader - la solution avec clip, pas le positionnement hors écran 

On pourrait voir à implémenter la seconde étape seulement dans une next version si il n'est pas possible d'afficher clairement les statuts pour tous (avec des mots) mais un peu d'éducation pourrait nous éviter l'étape 2.

2022-02-12 15:01 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/status/scss/index.scss
> +            background-color: $gray-300;
J'image que c'est pour du nullproofing le background par default, c'est la couleur sans satus
T'as dit que "default" est le status neutre.
JE vais le renommé.

Ta suggestion de couleur est pas la bonne. CA devrait être "secondary" en reverse mode....

2022-02-12 15:20 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/status/twig/index.twig
> +  <p class='bf-status bf-status-{{ color|default('') }} {{ class|default('') }}'>{{ label }}</p>
Corrigé dans ba87108538c3d8b36f61a750cf8e91e571810187.
(Pas besoin de dire que c'est pas parfait, mais on doit faire 80% valeur avec 20% d'effort)

2022-02-12 15:21 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/status/scss/index.scss
> +        @extend .position-absolute--center-left;
corrigé dans baa55e246f94b6f304d2328c3743d6818bbe4c46

2022-02-12 15:23 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/status/scss/index.scss
> +        background-color: $gray-100;
Ta variable suggérer n'est pas la bonne couleur. 
On garde comme c'était dans le UIKIT et la définition Figma jusqu'a que un moment donner on en reparle avec les UI.

Tu as raison, "default" porte a confusion, renommer dans 193cd6da3b1256c7078a8d8bb9c779998f24fe23

2022-02-12 15:24 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/status/scss/index.scss
> +            background-color: $gray-300;
enlever la confusion en renommant la classe 193cd6da3b1256c7078a8d8bb9c779998f24fe23

2022-02-12 15:25 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/status/scss/index.scss
> +.bf-status {
Corrigé dans : e511eb90a8720d0e59bef5e1bce4b0b0bebe87fe

2022-02-17 13:16 UTC, ThalieVideotron requested changes

2022-02-17 13:16 UTC, ThalieVideotron commented on CHANGELOG.mdx
> +- New [Status](?path=/story/components-status--drupal) twig component.
me semble qu'il manque un titre du genre `### New components`

2022-02-17 13:16 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/status/_doc/doc.stories.mdx
> +[Design Documentation](https://zeroheight.com/79f1d3365/) not available
si c'est pas disponible et qu'on pense laisser tomber Zeroheight est-ce pertinent?

2022-02-17 13:16 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/status/scss/index.scss
> +            background-color: $gray-300;
un problème pour la next version

2022-02-17 13:16 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/status/twig/index.twig
> +    <span class='visuallyInvisible' role='status'>{{ color }}</span>
le rôle doit aller sur le `<p>` et je m'attend à une condition pour mettre à `role='alert'` quand la couleur est `failed`

2022-02-17 13:18 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/status/scss/index.scss
> +    @each $color, $value in $theme-colors {
on revera les couleur dans une next version. le renaming me convient

2022-02-17 13:21 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/status/_doc/doc.stories.mdx
> +        reversed: {
beurk. gérer le reverse comme un background comme les autres - voir proposition dans le template.twig

2022-02-17 13:21 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/status/_doc/doc.stories.mdx
> +            reversed    : false
ne serait plus nécessaire

2022-02-17 13:22 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/status/_doc/doc.stories.mdx
> +[Design Documentation](https://zeroheight.com/79f1d3365/) not available
la décision est pas encore finale, donc pas un enjeux pour le moment. Je le mets pour qu'on le laisse

2022-02-17 13:28 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/status/twig/index.twig
> +    <span class='visuallyInvisible' role='status'>{{ color }}</span>
Le p ne donne pas le status. Le p c'est pour écrire le nom de l'item. Entk ca dépends des cas d'utilisation, c'est flexible.
Donc, 80/20.

Pas de conditionnement non plus. ça aussi c'est du 80/20 qu'on reverra une autre fois.
(parce que c'était déjà pas un feature du UIKIT, donc on a progressé un peu, mais ça n'a pas à être parfait, 80/20)

2022-02-17 13:29 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/status/_doc/doc.stories.mdx
> +        reversed: {
80/20 sur la gestion du thème à faire plus tard. C'est pour ç que c'est une variable de story seulement

2022-02-17 16:50 UTC, ThalieVideotron commented
@JonathanLefebvreV  à part le titre manquant dans le changelog tout est OK pour moi

2022-02-19 18:56 UTC, merged