DS-265 - Checkbox
bifrost-vui/bifrost-front-end-library pull request #252
Opened 2022-02-05 19:24 UTC by ThalieVideotron

2022-02-07 01:53 UTC, JonathanLefebvreV requested changes

2022-02-07 01:53 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/doc.stories.mdx
> +            url     : 'https://www.figma.com/file/FkPUN7xRQi0wJrXXdDIoO4/DS-Library-DONT-YOU-DARE-USING-IT?node-id=3240%3A619',
C'est pas le bon lien figma

2022-02-07 01:53 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/doc.stories.mdx
> +<iframe width='100%' height='450' src='https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2F7bTmk29aCBl7rCFszffYPr%2FDS---Components-%2526-styles%3Fnode-id%3D16890%25
TODO et mauvais lien figma

2022-02-07 01:53 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/template.drupal.twig
> +{% set backgrounds = ['bf-color-bg-ground','bf-color-bg-underground','reversed bf-color-bg-ground','reversed bf-color-bg-underground', 'bf-color-bg-highlight'] %}
```suggestion
{% set isRequired = isRequired|json_parse %}

{% set backgrounds = ['bf-color-bg-ground','bf-color-bg-underground','reversed bf-color-bg-ground','reversed bf-color-bg-underground', 'bf-color-bg-highlight'] %}
```

2022-02-07 01:53 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/template.drupal.twig
> +{% set isInvalid = isInvalid|json_parse %}
```suggestion
{% set isInvalid  = isInvalid|json_parse %}
```

2022-02-07 01:53 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-checkbox/angular/input-checkbox.component.ts
> +
can be removed

2022-02-07 01:53 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-checkbox/scss/index.scss
> +            color : var(--bf-color-feedback-negative);
```suggestion
            color: var(--bf-color-feedback-negative);
```

2022-02-07 01:53 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +  >
ajouter `extraAttribute` pour cette élément de form

2022-02-07 02:00 UTC, JonathanLefebvreV commented
La taille du checkbox est plus grande que ce Figma expect... 
Actual
![image](https://user-images.githubusercontent.com/75901368/152713282-4617c67a-154d-45be-8955-ef897407b9ea.png)
Expect
![image](https://user-images.githubusercontent.com/75901368/152713368-f9b9ef1e-69a8-41a1-ab0b-b2ea44f43d2a.png)

2022-02-07 15:21 UTC, ThalieVideotron commented
je fais les changements requis mais je crois qu'on devrait prévoir le message d'erreur sur ce composant. un checkbox seul qui est required mais non coché devrait avoir un message d'erreur.

2022-02-10 13:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/doc.stories.mdx
> +    name  : 'myInputName'
revoir l'indentation et uniformiser les valeurs de variables
```
    label: { text : 'label', class : '' },
    id: 'id',
    value: 'value',
    name: 'name'
    ```
Attention a ne pas oublier les virgules.

2022-02-10 13:38 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/angular/input-checkbox.component.ts
> +    /** will be used if no label is defined */
a retirer a mon avis

2022-02-10 13:39 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +  <input type="checkbox" class='bf-checkbox {{ isInvalid ? 'bf-checkbox--isInvalid' }}'
remplacer `--isInvalid` par `--invalid`

2022-02-11 15:46 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +  >
done + rapatrié toutes les propriétés du UI-Kit

2022-02-11 15:48 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/angular/input-checkbox.component.ts
> +    /** will be used if no label is defined */
non - mais modifié - jamais mauvais de rappeler qu'un input sans label doit avoir un aria-label.

2022-02-12 16:45 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +  >
Pourquoi mélanger les commentaire. Je t'ai pas parler des autre chose. Le processus de deprecation allait venir après.

2022-02-13 16:14 UTC, bibifrost commented
> je fais les changements requis mais je crois qu'on devrait prévoir le message d'erreur sur ce composant. un checkbox seul qui est required mais non coché devrait avoir un message d'erreur.

La responsabilité de ce composant devrait se limiter à ses différents affichages possible. Mais il ne devrait pas être responsable d'afficher un message.

2022-02-13 16:27 UTC, bibifrost commented
Très cool! J'ai vu 2/3 trucs:
 - un click sur le label n'affecte pas la checkox.
 - l'alignement top pourra poser des probleme (voir image). Test de l'aligner horizontalement avec un autre input de 24px de hauteur. 
![image](https://user-images.githubusercontent.com/93746960/153762603-9356258a-b9ed-4a82-88e6-7cc93973df64.png)
- Afficher le `cursor: hand`. Ça aide à comprendre que le label est cliquable.

2022-02-13 16:50 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +<div class='bf-input-checkbox  {{ class|default('') }} {{ isInvalid ? 'bf-input-checkbox--invalid' }}'>
2 espaces entre `checkbox  {{ `

2022-02-13 16:50 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +    {{ isChecked ? 'checked' }}
Je ne crois pas être favorable à `strict_variables`, mais on a pris cette direction alors on devrait faire:
```
{{ isChecked|default(false) ? 'checked' }}
{{ isDisabled|default(false) ? 'disabled' }}
```

2022-02-13 16:50 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +    <label for="{{ id }}" class='bf-text-display-sub-medium {{ labelClass|default('') }}' {{ labelExtraAttribute|default(NULL) }}>
double quote autour du id

2022-02-13 16:50 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/scss/index.scss
> +             border-color: rgba(var(--bf-color-stroke-tertiary-rgb),.75);
```suggestion
             border-color: rgba(var(--bf-color-stroke-tertiary-rgb),.75);
```
```suggestion
             border-color: rgba(var(--bf-color-stroke-tertiary-rgb), .75);
```

2022-02-13 16:50 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/scss/index.scss
> +                 filter: opacity(0.3);
```suggestion
                 filter: opacity(0.3);
```
```suggestion
                 filter: opacity(.3);
```

2022-02-13 16:50 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/scss/index.scss
> +        filter: opacity(0.5) grayscale(100) invert(1);
```suggestion
        filter: opacity(0.5) grayscale(100) invert(1);
```
```suggestion
        filter: opacity(.5) grayscale(100) invert(1);
```

2022-02-13 16:50 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/angular/input-checkbox.component.ts
> +    @Input() value              : string;
`value` est-il pertinent ici?

2022-02-13 16:50 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +    {% if value is defined and value %} value='{{ value }}' {% endif %}
`value` est-il pertinent?

2022-02-13 16:50 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/scss/index.scss
> +.bf-color-bg-highlight .bf-checkbox {
J'ai eu le meme problème sur **Button-nav**, le style n'est pas le meme sur fond jaune (le bg au survol):
![image](https://user-images.githubusercontent.com/93746960/153765356-75e7039c-99b4-4b22-a2a8-a5c867963b34.png)

Ça me semble plus safe d'utiliser une propriété `highlight` pour le changement de couleur sur fond jaune. Car `bf-color-bg-highlight` n'est peut-être pas le seul moyen d'avoir un fond jaune. Et ça peut créer des effets de bord non désiré.
Nous avons donc 3 contextes:
- **Default**
- **Reversed** qui s'applique soit via la propriété `reversed` du composant, soit via un tag parent `.reversed`.
- **Highlight**  qui ne s'applique que via la propriété `highlight` du composant, pour le moment. Quand elle est disponible.
Si on est ok avec ça, il faudrait mieux le documenter.

2022-02-13 16:51 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/template.drupal.twig
> +<div class='mt-6 px-2 d-flex flex-row flex-wrap gap-1'>
retirer le `gap-1` pour harmoniser avec les autres templates.

2022-02-14 14:23 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +    {% if value is defined and value %} value='{{ value }}' {% endif %}
je ne sais pas. je n'ai pas à savoir je suis agnostique ;-) 

ceci dit c'est pertinent  et ça a une fonction et il n'est pas mauvais de le prévoir : 

https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/checkbox : 
"L'attribut value est partagé par l'ensemble des éléments <input> mais il a un rôle spécifique pour les champs de type checkbox : lorsqu'un formulaire est envoyé, seules les cases à cocher qui sont cochées sont envoyées au serveur et c'est la valeur de l'attribut value qui est envoyée. Si l'attribut value n'est pas renseigné, ce sera la chaîne de caractères "on" qui sera envoyée par défaut."

2022-02-14 14:28 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +    {{ isChecked ? 'checked' }}
dans le cas des boolean undefined returns false. je ne mettrais pas defaut mais on peut rendre plus robuste 

https://twig.symfony.com/doc/3.x/filters/default.html : 
Using the default filter on a boolean variable might trigger unexpected behavior, as false is treated as an empty value. Consider using ?? instead:
{{ foo ?? true }} {# false #}

2022-02-14 15:02 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/scss/index.scss
> +            color: rgba(var(--bf-color-neutral-secondary-rgb),.35);
> Très cool! J'ai vu 2/3 trucs:
> 
> * un click sur le label n'affecte pas la checkox.
> * l'alignement top pourra poser des probleme (voir image). Test de l'aligner horizontalement avec un autre input de 24px de hauteur.
>   ![image](https://user-images.githubusercontent.com/93746960/153762603-9356258a-b9ed-4a82-88e6-7cc93973df64.png)
> * Afficher le `cursor: hand`. Ça aide à comprendre que le label est cliquable.

- pour le label:    le for aurait dû contenir `{{ inputId }}` et non {{ id }} - mais je vais aussi ajouter le curseur (cursor: pointer)
- pour l'alignement top : pas vraiment le choix pcq le label doit pouvoir passer sur 2 lignes et le tout est aligné top. ça sera au container d'aligner tous ces éléments middle (ou top). ceci dit, si on affiche un message d'erreur au champs texte à droite on se ramasse tout désaligné aussi.

2022-02-14 15:15 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/scss/index.scss
> +             border-color: rgba(var(--bf-color-stroke-tertiary-rgb),.75);
> Standardiser cette PR avec les commentaire de #254
> 
> De plus, la propriété "isChecked" ne marche pas avec "isDisabled". isDisabled à "true" uncheck l'input.

aucune idée du pourquoi ça faisait ça mais en réparant le label ça a réparé ça aussi. pas une bonne idée de mettre les id à `''` je crois que c'est ce qui causait le bug. 

pour la standrdisation noté. je suppose que tu fais référence à  la rétrocompatibilité :  id = inputId pour , idem pour name & inputName

2022-02-14 15:44 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/scss/index.scss
> +            color: rgba(var(--bf-color-neutral-secondary-rgb),.35);
pour être cohérente j'ajoute aussi le 0

2022-02-14 15:51 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/scss/index.scss
> +.bf-color-bg-highlight .bf-checkbox {
la proprété hightlight peu aussi venir du composant parent - justement dans un cas comme celui-ci. mais je vois où tu veut en venir.

2022-02-14 18:00 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/template.drupal.twig
> +{% set label          = label|json_parse %}
**extraAttribute**, **label** et **id** ne devrait pas etre json_parse

2022-02-14 18:00 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/scss/index.scss
> +        filter: opacity(0.5) grayscale(100) invert(1);
A date on le met null part. Pourquoi le mettre dans les **opacity**. Ça complexifie, non?

2022-02-14 18:00 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +  {% set id= inputId %}
```suggestion
  {% set id = inputId %}
```

2022-02-14 18:00 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +    {{ isChecked ? 'checked' }}
Mais donc on assume qu'on ne souhaite pas être valide au `strict_variables` ?

2022-02-14 18:00 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/scss/index.scss
> +                filter: opacity(1) grayscale(100) invert(1)
```suggestion
                filter: opacity(1) grayscale(100) invert(1);
```

2022-02-14 18:00 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +  {% set name= inputName %}
```suggestion
  {% set name = inputName %}
```

2022-02-14 18:07 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +    {{ isChecked ? 'checked' }}
oui. et c'est pourquoi je l'ai changé pour  {{ (isChecked is defined and isChecked) ? 'checked' }} mais pas de default sur les boolean

2022-02-14 18:12 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/scss/index.scss
>          color: rgba(var(--bf-color-neutral-primary-rgb), 0.32);
désolé j'avais mal compris le changement + haut je croyais que pour opacity tu me faisais ajouter le `0` pour ça que je l'ai mis dans `rgba()`. on les basarde partout. moi aussi je suis plus à l'aise avec sans les 0.

2022-02-14 18:16 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/scss/index.scss
> +        filter: opacity(0.5) grayscale(100) invert(1);
j'avais compris que tu souhaitais le contraire et je trouvais que ça complexifiais - done

2022-02-14 18:31 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/template.drupal.twig
> +{% set label          = label|json_parse %}
extraAttribute non plus : string,  donc pas nécessaire.
je n'ai pas encore de pattern clair mais je me rappelle avoir vu des string ne pas être naturellement parsée. Est-ce que ça serait seulement les string qui sont dans des selects/options?

2022-02-14 18:43 UTC, ThalieVideotron commented
> > Très cool! J'ai vu 2/3 trucs:
> > 
> > * un click sur le label n'affecte pas la checkox.
> > * l'alignement top pourra poser des probleme (voir image). Test de l'aligner horizontalement avec un autre input de 24px de hauteur.
> >   ![image](https://user-images.githubusercontent.com/93746960/153762603-9356258a-b9ed-4a82-88e6-7cc93973df64.png)
> > * Afficher le `cursor: hand`. Ça aide à comprendre que le label est cliquable.
> 
> pour le label: le for aurait dû contenir {{ inputId }} et non {{ id }} - mais je vais aussi ajouter le curseur (cursor: pointer) - on retourne à id donc ça refonctionne. 
pour l'alignement top entre les 2 éléments du composant (input + label)  : pas vraiment le choix pcq le label doit pouvoir passer sur 2 lignes et le tout est aligné top. Le composant dans son ensemble devrait pouvoir s'aligner middle même si les deux élément qui le compose sont alignés au top

2022-02-15 17:52 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +  <input type="checkbox" class='bf-checkbox {{ isInvalid ? 'bf-checkbox--invalid' }}'
j'ai trouvé le moyen de changer le setting dans mon IDE - on ne devrait plus en voir des comme ça à l'avenir

2022-02-15 18:00 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +    {{ isChecked ? 'checked' }}
quand Twig dit de ne pas utiliser `{{ isChecked|default(false) ? 'checked' }}` , je serais portée à le croire et j'éviterais de tenter le diable et surtout d'en faire un standard.
De là à dire qu'on va aller le changer partout c'est une autre chose. ceci dit maintenant qu'on sait,  on devrait éviter de le faire dans les nouveaux composant et on se crée un un Jira dette technique pour les autres puisque de toute évidence ça ne nous a pas encore explosé au visage, donc il n'y a pas d'urgence.

2022-02-15 18:09 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/doc.stories.mdx
> +    }}
je me demandais où documenter et surtout comment.  Avec cette solution l'argument est présent dans la liste mais ne peut être renseigné c'est ça?
Moi je serais à l'aise avec ça. @JonathanLefebvreV ? 
est-ce qu'on doit aussi le documenter dans le changelog ou on a suffisamment documenté avec cette solution?

2022-02-15 18:24 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/doc.stories.mdx
> +        height = '300px'
la story n'a pas besoin de height c'est juste le canvas (dans ce cas-ci) ça évite d'avoir l'onglet doc inutilement long.

2022-02-15 18:32 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +{% endif %}
idem pour `name` 
c'est juste que ça fait étrange de mettre un default dans un champs qui est required.

2022-02-16 00:15 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/doc.stories.mdx
> +    }}
discuté en plani - le champ swera rensigné dans storybook. 
Note : pour Id & inputId, la valeur de inputId ne sera jamais utilisée (pcq id est un champs obligatoire et donc il est renseigné dans le canvas du mdx) mais on pourra valider la mécanique  avec name et inputName

2022-02-17 21:09 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/template.drupal.twig
> +{% set label          = label|json_parse %}
Les **boolean**, les **array** et les **objects** doivent être parsé.
Les autres ça ne devrait pas etre necessaire.

2022-02-17 21:12 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +    {{ isChecked ? 'checked' }}
J'aimerais en discuter en équipe avant de prendre une décision.

2022-02-18 13:35 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +    {{ isChecked ? 'checked' }}
discuter du strict ou d'utiliser du code identifié comme dangereux par twig?

2022-04-10 19:58 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +- Fix `disabled`property of [Button Icon](/story/components-button-icon--drupal) Twig component
```suggestion
- Fix `disabled` property of [Button Icon](/story/components-button-icon--drupal) Twig component
```

2022-04-10 19:59 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +- New [Input Checkbox](?path=/story/components-input-checkbox--drupal) twig component.
```suggestion
- New [Input Checkbox](/story/components-input-checkbox--drupal) twig component.
```

2022-04-10 20:07 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +{% set name = name|default(inputName) %}
```suggestion
{% set id = id|default(inputId) %}
{% set name = name|default(inputName) %}
```

2022-04-10 20:11 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/doc.stories.mdx
> +        },
C'est malheureux, parce que ca marche seulement dans CANVAS et pas dand DOC pour le listing API. C'est quand même une amélioration qu'on va gardé. Je dis juste que ces pas au points comme je pensais.

2022-04-10 20:12 UTC, JonathanLefebvreV approved these changes

2022-04-10 20:14 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +    {{ isChecked ? 'checked' }}
Avec ce qu'on a parler sur le bug de Menu cette semaine et la facon que Twig (pas twigJS) manage les boolean, il faut mettre le `is defined`. Je suis en interrogation à savoir si ca ne prends pas en plus pour la vérification du boolean en lui même, mais allons-y comme ca et on verra pour amélioré plus tard

2022-04-10 20:15 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-checkbox/twig/index.twig
> +    {{ isChecked ? 'checked' }}
et on peut faire la discussion que Baptiste tu voulais si c'est encore d'actualité

2022-04-10 20:17 UTC, JonathanLefebvreV commented
Je trouve cette PR à un nouveau acceptable, dans les tests et dans la validation avec les input de uikit, pour mergé et revoir au besoin dans le futur

2022-04-10 20:17 UTC, merged