DS-266- bouton radio - nature
bifrost-vui/bifrost-front-end-library pull request #254
Opened 2022-02-07 21:42 UTC by ThalieVideotron

2022-02-08 01:00 UTC, JonathanLefebvreV requested changes
Me semble qu'on a discuté que le background devait être "jaune" comme le checkbox. Que c'est une erreur figma de pas le représenté.
![image](https://user-images.githubusercontent.com/75901368/152896928-025a8a7e-1fcf-435d-a099-7d7a28be0a89.png)
---
✔️ Resolved

2022-02-08 01:00 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio-only/angular/input-radio-only.component.html
> +</div>
T'as oublié le clean-up du fichier

2022-02-08 01:00 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio-only/_doc/doc.stories.mdx
> +**// TODO**: Add a link to the component in Figma file.
todo à enlever

2022-02-08 01:00 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio-only/_doc/doc.stories.mdx
> +    ariaLabel : 'input label'
alignment of all `:`

2022-02-08 01:00 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio-only/angular/input-radio-only.component.ts
> +
a retirer si on en mets pas

2022-02-08 01:00 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio-only/angular/input-radio-only.component.ts
> +  selector: 'bf-input-radio-only',
A renommer pour enlever le "-only". ça fait pas de sens en terme de structure.
C'est un 'input-radio' c'est le nom du type de tag en HTML.

2022-02-08 14:13 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio-only/angular/input-radio-only.component.ts
> +  selector: 'bf-input-radio-only',
ça vient de là : https://www.figma.com/file/7bTmk29aCBl7rCFszffYPr/DS---Components-%26-styles?node-id=19741%3A264867

je serais pas mal d'accord avec toi mais je me suis entendue avec @bibifrost pour utiliser ce nom en attendant qu'il en discute avec toi. Idéalement, il faut que vous ayez cette discussion avant de merger pour éviter des breaking changes après publication. Si j'ai bien saisi, l'objectif de Batiste est de se distancier du HTML et d'être plus près des besoins des consommateurs de composant. Personnellement la liste s'appellerait input-radio-list laissant ainsi le nom input-radio disponible pour le bouton radio. Idéalement, il faut que vous ayez cette discussion avant de merger pour éviter des breaking changes après publication.

Si je fais le changement dans radio, je le ferais également dans checkbox... pour la cohérence

2022-02-10 01:30 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio-only/angular/input-radio-only.component.ts
> +  selector: 'bf-input-radio-only',
On ne doit pas faire d'optimisation du composante @bibifrost. Notre mission dans les tâches de migration du UIKIT est de reproduire le composant le plus possible "as-is". On doit créer le moins possible (pour ne pas dire aucun) breaking-change et générer moins travail coté DXP pour la migration. C'est un context bugdétaire imposé.

Ce qui comprends qu'on ne peut pas changer le nom ou les propriété du composante.

2022-02-10 01:36 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio/_doc/doc.stories.mdx
> +# Input Radio Only
```suggestion
# Input Radio
```

2022-02-10 01:38 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio/scss/index.scss
> +    max-width : auto;
```suggestion
    flex-flow: row nowrap;
    align-items: top;
    max-width: auto;
```

2022-02-10 01:38 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio/scss/index.scss
> +        margin : 0;
```suggestion
        margin: 0;
```

2022-02-10 01:39 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio/scss/index.scss
> +        min-width:1rem;
```suggestion
        min-width: 1rem;
```

2022-02-10 01:40 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio/twig/index.twig
> +<div class='bf-input-radio {{ isInvalid ? 'bf-input-radio--isInvalid' }} {{ isDisabled ? 'bf-input-radio--disabled' }} {{ class }}'>
```suggestion
<div class='bf-input-radio {{ isInvalid ? 'bf-input-radio--isInvalid' }} {{ isDisabled ? 'bf-input-radio--disabled' }} {{ class }}'>
```

2022-02-10 01:40 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio/twig/index.twig
> +         id='{{ id }}'
```suggestion
       id='{{ id }}'
```

2022-02-10 01:41 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio/scss/index.scss
> +*  Input Radio Only
```suggestion
*  Input Radio
```

2022-02-10 01:54 UTC, JonathanLefebvreV requested changes
Erreur
C'est pas le point qui doit être jaune.
C'est son background, l'intérieur du cercle. Comme le checkbox
![image](https://user-images.githubusercontent.com/75901368/153322152-3e6da010-a400-46dc-882a-82ab50fed50b.png)

2022-02-10 12:24 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio-only/angular/input-radio-only.component.ts
> +  selector: 'bf-input-radio-only',
oh... donnée que je n'avais pas : _On doit créer le moins possible (pour ne pas dire aucun) breaking-change_

2022-02-10 13:23 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio-only/angular/input-radio-only.component.ts
> +  selector: 'bf-input-radio-only',
@JonathanLefebvreV , je ne savais pas non plus. Mais dans ce cas, je ne comprend pas l'intérêt de bifrostiser. À part apporter la gestion des themes. Ça va aussi amener d'autres problèmes. Mais je comprends les raisons budgétaires.

2022-02-10 13:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/twig/index.twig
> +<div class='bf-input-radio {{ isInvalid ? 'bf-input-radio--isInvalid' }} {{ isDisabled ? 'bf-input-radio--disabled' }} {{ class }}'>
Jusqu'a present on n'écrit pas en camelcase dans les classes CSS.
Aussi, on devrait surement retirer le `is`:
`bf-input-radio--isInvalid` => `bf-input-radio--invalid`

2022-02-10 13:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/twig/index.twig
> +    {% endif %}
Pour éviter les 2 if, ceci serait plus propre, non?
```
{% set ariaLabel = ariaLabel|default(label) %}

{% if ariaLabel is defined and ariaLabel %}
      aria-label='{{ ariaLabel }}'
{% endif %}
```

2022-02-10 13:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/twig/index.twig
> +    <label for='{{ id }}' class='bf-text-display-sub-medium'>{{ label}}</label>
espace manquant apres label dans `{{ label}}`

2022-02-10 13:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/_doc/doc.stories.mdx
> +    name      : 'myRadioName'
virgule manquante a la fin

2022-02-10 13:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/_doc/doc.stories.mdx
> +    name      : 'myRadioName'
Aussi, essayons d'être consistant:
```
    id        : 'id',
    value     : 'value',
    name      : 'name'
    label     : 'label'
    ```

2022-02-10 13:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/angular/input-radio.component.ts
> +    /** will be used if no label is defined */
Cette phrase n'est pas tout a fait exact car on devrait pouvoir specifier un label pour le UI et un ariaLabel pour les lecteur d'écran. Je retirerais simplement le commentaire.

2022-02-10 21:07 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio-only/angular/input-radio-only.component.ts
> +  selector: 'bf-input-radio-only',
j'ai récupéré les nom des propriétés et rapatriée celle que j'avais volontairement omise. Il n'y a plus de breaking changes  bien qu'il y ait quelques nouvelles propriétés disponibles (histoire de justifier un peu notre travail). 
j'ai aussi corrigé l'erreur de html (pas de `p` dans un `label`) parce qu'il faudrait éviter de bifrostiser des erreurs mais ça sera transparent.

2022-02-10 21:11 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio/twig/index.twig
> +    {% endif %}
sexy. j'adopte!

2022-02-10 21:11 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio/twig/index.twig
> +    <label for='{{ id }}' class='bf-text-display-sub-medium'>{{ label}}</label>
vu! j'ai ajouté la classe aussi comme c'était dans le UI-kit

2022-02-10 21:14 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio/_doc/doc.stories.mdx
> +    name      : 'myRadioName'
oki. 
+ rappatrié le nom de propriété ui-KIT (inputId et inputName) pcq `id`et `name` c'est un breaking change

2022-02-10 21:34 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio/angular/input-radio.component.ts
> +    /** will be used if no label is defined */
alors je dois revoir la logique dans le twig aussi. parce que là je force label dans aria-label avant de voir si j'ai un aria-label de défini. Mais comme ni Label ni aria-label ne peuvent être rendus obligatoires, je crois qu'il est pertinent de garder un commentaire pour rappeler la nécessité d'avoir un ou l'autre pour rester accessible. 

Ce que je comprend de https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label

- si on a un label, on n'a pas besoin du aria label à moins que le label ne soit pas clair
- si label n'est pas clair alors on a un autre problème d'accessibilité mais c'est pas le notre - de notre côté il ne faut pas ouvrir la porte à l'utilisation du aria-label dans un contexte de aria-description
- si le label est absent je dois absolument avoir un aria-label

2022-02-10 21:36 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio/twig/index.twig
> +    {% endif %}
oui mais bon ça sera pas ça à cause du commentaire plus bas 
https://github.com/bifrost-vui/bifrost-front-end-library/pull/254#discussion_r803678837

2022-02-12 16:12 UTC, JonathanLefebvreV requested changes
@ThalieVideotron , Test tes PR: 
Ton storybook est brisé. avec des propriété en double et d'autre qui sont pas identifié pour le composant mais qu'il le sont.

![image](https://user-images.githubusercontent.com/75901368/153718971-91ac0a27-eef4-46bd-a53f-786fa7aa3300.png)

----------------------------

done and Improved 
![image](https://user-images.githubusercontent.com/82388009/161550930-a4209aca-362c-42cf-aeaa-d1636fc9d844.png)

2022-02-12 16:51 UTC, JonathanLefebvreV requested changes
Pourquoi dans cette PR, la classe du radio button est gérer uniquement avec sont parent, au lieu d'avoir fait comme le checkbox dans https://github.com/bifrost-vui/bifrost-front-end-library/pull/252, et faire un classe `.bf-checkbox`

C'est à uniformiser.

2022-02-14 17:43 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/angular/input-radio.component.ts
> +    @Input() inptuId        : string;
**input** pas **inptu** :)

2022-02-14 17:43 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/angular/input-radio.component.ts
> +    @Input() InputName      : string;
retirer la masjucule à InputName

2022-02-14 17:43 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/angular/input-radio.component.ts
> +    @Input() labelTxtClass  : string;
À date, on n'utilise jamais d'abbreviation. Ça a plusieurs avantage.
~~btn~~ => **button**
~~descr~~ => **description**

On devrait alors avoir:
**labelTxtClass** => **labelTextClass**

Note: vérifier si ce n'est pas plutôt **textLabelClass** ou **classTextLabel**. Voir ce qui a été fait ailleurs pour etre consistent.
[Edit] De mon point de vue, ça devrait etre simplement **labelClass**.

2022-02-14 17:43 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/twig/index.twig
> +    type="radio"
double quote

2022-02-14 17:43 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/twig/index.twig
> +    <label for='{{ id }}' class='bf-text-display-sub-medium {{ labelTxtClass|default('') }}'>{{ label|raw }}</label>
ce nest pas plutot `for={{ inputId }}` ici ?

2022-02-14 17:43 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/_doc/doc.stories.mdx
> +    inputId   : 'id',
`id` ou `inputId`?
Faire une verification globale dans les fichiers.

2022-02-14 17:43 UTC, bibifrost commented on CHANGELOG.mdx
> +- Improve `link` component (see [Component API](?path=/docs/components-link--drupal)).
Puisque les nom de composants sont écrit en _humanize_ (ex: `Input Radio` au lien de `inputRadio`), je propose de garder la majuscule.
Dans l'idéal, ça devrait etre la meme norme que le nom dans la sidebar Storybook.
![image](https://user-images.githubusercontent.com/93746960/153916271-81f5f448-f302-4fa7-b677-57d6fb60699e.png)

2022-02-14 17:43 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/_doc/template.drupal.twig
> +{% set ariaLabel      = ariaLabel|json_parse %}
Supprimer la ligne. ariaLabel est une string et n'a donc pas besoin d'etre json_parsé.

2022-02-14 17:43 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/_doc/template.drupal.twig
> +{% set isRequired     = isRequired|json_parse %}
Dans l'idéal, mettre les **set** dans le meme ordre que dans le fichier `angular/input-radio.component.ts`.

2022-02-14 17:43 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/_doc/template.drupal.twig
> +    <div class='p-3 {{ background }}' style="flex:1">
double quote

2022-02-14 17:43 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/_doc/template.drupal.twig
> +    <div class='p-3 {{ background }}' style="flex:1">
```suggestion
    <div class='p-3 flex-grow-1 {{ background }}'>
```

2022-02-14 17:43 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/scss/index.scss
> +        color: rgba(var(--bf-color-neutral-secondary-rgb),.35);
```suggestion
        color: rgba(var(--bf-color-neutral-secondary-rgb), .35);
```

2022-02-14 17:43 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/_doc/doc.stories.mdx
> +    name      : 'myRadioName'
Pas sur de tout suivre, donc @ThalieVideotron je te laisse le soin de resolve cette discussion quand ça sera ok pour toi.

2022-02-14 18:56 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio/_doc/doc.stories.mdx
> +    name      : 'myRadioName'
@JonathanLefebvreV  je viens de voir qu'on a inputId dans increment - faudra peut-être refaire un tour à la fin.
 
pour  la rétrocompatibilité : je j'ai fait dans checkbox aussi et je vais repasser dans mes branches en cors pour que ça soit ainsi partout.

2022-02-14 19:45 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio/angular/input-radio.component.ts
> +    @Input() inptuId        : string;
dyslexie du clavier. mais ça explique des choses...

2022-02-14 19:45 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio/angular/input-radio.component.ts
> +    @Input() InputName      : string;
name tout court finalement et ça explique l'autre bug. merci

2022-02-14 19:52 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio/angular/input-radio.component.ts
> +    @Input() labelTxtClass  : string;
vendu :  labelClass avec rétrocompatibilité pour labelTxtClass (UI-Kit) dans le twig

2022-02-14 19:55 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio/twig/index.twig
> +    type="radio"
done - voir le style-guide recommandé par Chrome à ce sujet (t'as déjà le lien dans une autre branche). comme toi je croyais qu'il n'y avait pas de différence.

2022-02-14 19:55 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio/twig/index.twig
> +    <label for='{{ id }}' class='bf-text-display-sub-medium {{ labelTxtClass|default('') }}'>{{ label|raw }}</label>
oui mais plus maintenant ;-)

2022-02-14 19:57 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio/_doc/doc.stories.mdx
> +    inputId   : 'id',
finalement on y va avec id partout. mais on assure une rétrocompatibilité avec inputId dans le twig (idem pour inputName ou tout autre propriété renommées à partir du UI-Kit)

2022-02-14 20:10 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio/_doc/template.drupal.twig
> +    <div class='p-3 {{ background }}' style="flex:1">
contexte  blanc bonnet et bonnet blanc

2022-02-14 21:00 UTC, bibifrost commented on CHANGELOG.mdx
> +- new `Input Radio` component (see [Component API](?path=/docs/components-input-radio--drupal)) - single radio-button with label
```suggestion
- new `Input Radio` component (see [Component API](?path=/docs/components-input-radio--drupal))
```

2022-02-14 21:00 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/_doc/doc.stories.mdx
> +    style = {{ height: '400px' }}
```suggestion
    style={{ height: '400px' }}
```

2022-02-14 21:00 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/_doc/template.drupal.twig
> +    <div class='p-3 {{ background }}' style='flex:1'>
```suggestion
    <div class='p-3 flex-grow-1 {{ background }}'>
```

2022-02-14 21:00 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/angular/input-radio.component.ts
> +    @Input() labelClass     : string;
remonter `labelClass` en dessous de `label`.

2022-02-14 21:00 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/scss/index.scss
> +    color: var(--bf-color-neutral-primary) ;
```suggestion
    color: var(--bf-color-neutral-primary);
```

2022-02-14 21:00 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/twig/index.twig
> +{% endif %}
```suggestion
{% set id = id|default(inputId) %}
```

2022-02-17 19:12 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio/_doc/template.drupal.twig
> +    <div class='p-3 {{ background }}' style='flex:1'>
je l'ai fait mais ça ne fait pas tout à fait ce que je voulais. d'un autre côté c'est ce qui risque d'être utilisé alors...

2022-02-17 21:40 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/_doc/template.drupal.twig
> +    <div class='p-3 {{ background }}' style='flex:1'>
Oui j'ai eu le meme probleme. `flex: 1` est super utile pour la composition, il mérite d'avoir sa classe utilitaire.
Peut-etre que quand tu fera un pull de master, elle sera disponible:
https://github.com/bifrost-vui/bifrost-front-end-library/pull/259/files

2022-02-17 21:43 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/_doc/template.drupal.twig
> +<div class='mt-6 px-2 d-flex flex-row flex-wrap gap-1'>
```suggestion
<div class='mt-6 px-2 d-flex flex-row flex-wrap'>
```

2022-02-18 13:20 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio/_doc/template.drupal.twig
> +    <div class='p-3 {{ background }}' style='flex:1'>
nice.  mais est-ce que tu peux faire resolve du coup?

2022-04-10 20:46 UTC, JonathanLefebvreV requested changes

2022-04-10 20:46 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio/twig/index.twig
> +  class='bf-input-radio {{ isInvalid ? 'bf-input-radio--invalid' }} {{ isDisabled ? 'bf-input-radio--disabled' }} {{ class }}'>
Missing `is defined and ...` for isInvalid and isDisabled

2022-04-10 20:46 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio/scss/index.scss
> +            position: absolute;
T'as pas besoin du `position`, Ca bug le rendu de 1px sur certain niveau de zoom
https://moderncss.dev/pure-css-custom-styled-radio-buttons/

2022-04-10 20:46 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio/_doc/template.drupal.twig
> +  </div>
Je suggère de mettre le regroupement vertical au lieu d'être dans 2 div. 

Ca rends le fonctionnement difficile à saisir entre celui-ci et celui du Input-Checkbox.

2022-04-11 12:48 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio/scss/index.scss
> +            position: absolute;
niveau de zoom ? 
Pas pensé à tester ça. c'est à ajouter à ma liste. je regarde.

2022-04-11 13:25 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-radio/_doc/template.drupal.twig
> +  </div>
done.

2022-04-17 17:56 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
>  ### Bug fix
```suggestion
## [Next Version](https://bifrost-front-end-library-vui.vercel.app/)
### Bug fix
```

2022-04-17 18:02 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio/scss/index.scss
> +            position: absolute;
Effectivement, je vois encore le bug de glitch, mais merci de l'amélioration.
On va y aller comme ça

2022-04-17 18:04 UTC, JonathanLefebvreV approved these changes
Il y a "isRequired" qui ne marche pas, mais ca pas besoin de marché maintenant et c'est quand on fera le composante de Input-radio-list) qu'on arrangera ca.

2022-04-17 18:04 UTC, merged