DS -  267  switch (input toggle)
bifrost-vui/bifrost-front-end-library pull request #255
Opened 2022-02-09 21:22 UTC by ThalieVideotron

2022-02-10 02:03 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/switch/_doc/doc.stories.mdx
> +        name='Drupal - Switch'
C'Est plein de mix entre "switch" et "input toogle".
De toute façon, je nom du UIKIT s'appelais : "input toggle switch"...
C'est laite, mais faut pas changer le nom du composant.
Et il faut suivre figma...

Doesn't compute 🤖 💥 

@ThalieVideotron, change rien on en reparle lundi

2022-02-10 02:26 UTC, JonathanLefebvreV requested changes
Je comprends pas comment ça peut être plus laid que l'existant du UIKIT
A refaire. 
Actual
![image](https://user-images.githubusercontent.com/75901368/153324038-313d3314-9f55-41bb-8f6f-d23df66e9f56.png)

Expected
![image](https://user-images.githubusercontent.com/75901368/153324131-1d5c0561-acc1-4deb-a5fa-d5a739c6ca9f.png)

On a perdu l'animation du click de la switch aussi.

2022-02-10 02:26 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/switch/angular/switch.component.ts
> +    @Input() innerLabels   : object;
Breaking Change du UIKIT: LabelOn & LabelOff non supporté dans cette implémentation

2022-02-10 02:26 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/switch/twig/index.twig
> +<div class='bf-switch {{ isDisabled ? 'disabled' }} {{ class|default('') }}'>
```suggestion
<div class='bf-switch {{ isDisabled ? 'disabled' }} {{ class|default('') }}'>
```

2022-02-10 02:26 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/switch/angular/switch.component.ts
> +    @Input() size           : number;
Impossible qu'un intégrateur utilise cela. (Mot Anglais/Francais pas de même longueur)
C'est pas un feature du composant du UIKIT, donc même si c'Est une amélioration ça créer du travail supplémentaire dans le Drupal pour supporter cela anyway.
Comme on a discuté, la 2e version de la switch aura problablement même pas de label à l'intérieur anyway.

Bref, peu de valeur, Coute cher à faire: On revert et on gère pas cela.

2022-02-11 21:05 UTC, ThalieVideotron commented
> Je comprends pas comment ça peut être plus laid que l'existant du UIKIT A refaire. Actual ![image](https://user-images.githubusercontent.com/75901368/153324038-313d3314-9f55-41bb-8f6f-d23df66e9f56.png)
> 
> Expected ![image](https://user-images.githubusercontent.com/75901368/153324131-1d5c0561-acc1-4deb-a5fa-d5a739c6ca9f.png)
> 
> On a perdu l'animation du click de la switch aussi.

Animation réparée. j'ai repris ce qu'il y avait plutôt que d'essayer de réparer/optimiser.
et j'ai enfin trouvé pourquoi elle avait l'air aussi dodu (toi tu dis laitte moi je dis dodu) . réparé aussi. 
Si tu vois d'autre laideurs (non approuvée par design) fais-moi signe  ;-)

2022-02-16 15:42 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/switch/angular/switch.component.ts
> +    @Input() size           : number;
my bad. 
InputSize dans le UI-kit gère la taille du texte des labels. Dans la bifrostisation la variable size aura la même utilité (ne gère plus la taille du input) .

2022-02-16 17:04 UTC, bibifrost commented on projects/front-end-library/src/lib/components/switch/_doc/doc.stories.mdx
> +            ariaLabel    : 'aria label'
```suggestion
            inputId      : 'inputId',
            ariaLabel    : 'ariaLabel'
```

2022-02-16 17:06 UTC, bibifrost commented on projects/front-end-library/src/lib/components/switch/_doc/doc.stories.mdx
> +    title='Components/Switch'
```suggestion
    title='Components/Input Switch'
```

2022-02-16 18:57 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/switch/_doc/doc.stories.mdx
> +    title='Components/Switch'
contrairement au input-checkbox, au input-text, au input-radio.... il n'y a pas de label dans ce composant (et je parle bien de la balise HTML), je garderais input-switch pour le composant + complexe. Cette switch "nature" pourrait être intégrée dans un composant qui contient déjà un label. 
je ne suis pas fermée à l'idée toutefois. @JonathanLefebvreV ta vision?

2022-02-16 18:57 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/switch/scss/index.scss
> +.bf-switch {
ça va dépendre de https://github.com/bifrost-vui/bifrost-front-end-library/pull/255#discussion_r808246505

2022-02-16 19:04 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/switch/angular/switch.component.ts
> +    @Input() innerLabels   : object;
récupéré la propriétés du UI-Kit. En espérant que ces on-off vont disparaître un jour.

2022-02-17 19:01 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/switch/angular/switch.component.ts
> +    @Input() innerLabels   : object;
j'avais déja changé pour les variables UIKit mais depuis on a parlé de gérer en rétrocompatibilité -> Si cette variation avec du texte dans la switch demeure quand Design repassera dessus on en fera un objet innerLabels/inner/text (label porte à confusion)  et on gèrera la rétrocompatibilité

2022-02-23 14:59 UTC, ThalieVideotron commented
@JonathanLefebvreV 
j'aimerais un retour 
 - sur le nom final du composant (il s'appelle switch pour le moment)
 - est-ce que tu le veux dans une section UI-Kit ou dans Components (il a été légèrement bifrostiosé même si on assure la rétrocompatibilité)

2022-03-02 21:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/switch/_doc/template.drupal.twig
> +{% set _background = _background |json_parse %}
supprimer la ligne _background et inputSize

2022-03-02 21:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/switch/twig/index.twig
> +{# UIK - Legacy #}
`UIK` ? :p

2022-03-02 21:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/switch/scss/index.scss
> +                background : var(--bf-color-bg-action-disabled);
```suggestion
                background: var(--bf-color-bg-action-disabled);
```

2022-03-02 21:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/switch/scss/index.scss
> +        background: var(--bf-color-bg-ground);
```suggestion
        background-color: var(--bf-color-bg-ground);
```

2022-03-02 21:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/switch/scss/index.scss
> +                background : var(--bf-color-bg-action-primary );
```suggestion
                background-color: var(--bf-color-bg-action-primary);
```

2022-03-02 21:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/switch/scss/index.scss
> +                    background: var(--bf-color-primary-irreversible);
```suggestion
                    background-color: var(--bf-color-primary-irreversible);
```

2022-03-02 21:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/switch/scss/index.scss
> +                background: #fff; // add this irreversible color in _colors.scss
```suggestion
                background-color: #fff; // add this irreversible color in _colors.scss
```

2022-03-02 21:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/switch/scss/index.scss
> +                    background : var(--bf-color-feedback-negative);
```suggestion
                    background-color: var(--bf-color-feedback-negative);
```

2022-03-02 21:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/switch/scss/index.scss
> +                transform: translate(0, -50%);
```suggestion
                content: '';
                display: block;
                height: 1.5rem;
                width: 1.5rem;
                position: absolute;
                left: .25rem;
                top: 50%;
                border-radius: 50%;
                background-color: var(--bf-color-neutral-secondary);
                transform: translate(0, -50%);
                @include transitions(left .2s ease-in-out);
                cursor: pointer;
```

2022-03-02 21:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/switch/angular/switch.component.ts
> +    @Input() labelOn        : string;
labelOn => labelChecked
labelOff => labelUnchecked

Pour renforcer la sémantique.

2022-03-02 21:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/switch/angular/switch.component.ts
> +    @Input() size           : 'sm'|'lg';
```suggestion
    @Input() size           : 'sm' | 'lg';
```

2022-03-02 21:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/switch/scss/index.scss
> +        padding: 0 .5rem;
ajouter `cursor: pointer;` au input et le retirer au disabled

2022-03-03 13:15 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/switch/twig/index.twig
> +{# UIK - Legacy #}
lapsus du clavier. Apparemment je le décommissionne lettre par lettre ;-)

2022-03-03 13:25 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/switch/angular/switch.component.ts
> +    @Input() labelOn        : string;
non.  parce que : 
1- ça vient diu UI-Kit `as-is`
2-  ce ne sont pas des labels donc si je dois changer de nom ça exclurait toute mention de label  (comme on est dans un input je ne veux pas ajouter de la confusion)
3- si on devais le modifier j'en aurait fait un objet avec on/off ou checked/unchecked puisqu'ils vont de pair
4 - notre ami Pareto ne serait pas d'accord ;-)

PTI à terme je crois que ça devrait disparaître parce que ça n'a pas sa place dans un switch (CF bootstrap & Material) et aussi parce que ça amène une complexité qui n'ajoute rien à l'expérience utilisateur.

2022-03-03 13:41 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/switch/scss/index.scss
> +        padding: 0 .5rem;
PTI - malgré ton oeil de lynx il restait quelques background au lieu de background-color et je suis repassée par dessus pour l'ordre des propriétés (copiés du UI-Kit) qui étaient encore mal ordonnée - Merci

2022-03-23 15:35 UTC, closed without merging