Ds 263 improve component generation script
bifrost-vui/bifrost-front-end-library pull request #258
Opened 2022-02-16 17:25 UTC by bibifrost

2022-02-17 19:37 UTC, ThalieVideotron requested changes

2022-02-17 19:37 UTC, ThalieVideotron commented on scripts/generate/index.js
> +    // .then(appendPublicAPI) // Note: Uncomment this line in order to add component in Angular API entry point.
`// Note: Uncomment this line in order to add component in Angular API entry point.`

par expérience préciser  : 
que la ligne décommentée ne doit pas être poussée ?
que le changement ne doit être fait que localement?
choisis ta formulation.  
 j'ai vu des env=dev passer en prod comme ça

2022-02-17 19:37 UTC, ThalieVideotron commented on scripts/generate/templates/component/_doc/template.drupal.twig
> +{% set reversed = reversed|json_parse %}
merci

2022-02-17 19:37 UTC, ThalieVideotron commented on scripts/generate/index.js
>          shell.exec( 'echo "' + strinImportStyle + '" >> projects/front-end-library/src/lib/scss/index.scss' );
cette ligne n'as pas été modifiée mais pourtant elle crée une erreur à chaque fois dans la feuille de style : 
`"@import '../${typePlural}/${name}/scss/index';"`
et il faut le corriger pour que ça génère
`@import '../${typePlural}/${name}/scss/index';`

Tu me diras, l'erreur nous force à mettre le css du composant à sa place dans la liste mais pas nécessaire de générer une erreur pour ça.

2022-02-17 20:25 UTC, bibifrost commented on scripts/generate/index.js
> +    // .then(appendPublicAPI) // Note: Uncomment this line in order to add component in Angular API entry point.
Je ne comprends pas. 
Ce commentaire indique que si l'on veut populer le composant dans l'entry point, alors il faut décommenter la ligne.

2022-02-18 13:40 UTC, ThalieVideotron commented on scripts/generate/index.js
> +    // .then(appendPublicAPI) // Note: Uncomment this line in order to add component in Angular API entry point.
je dis juste d'étoffer ton commentaire. Si on commence à avoir des invités dans le bifrost, la ligne décommentée va se retrouver en prod et la note va rester là et ça ne fera plus de sens.

2022-02-18 13:49 UTC, ThalieVideotron commented on scripts/generate/index.js
>          shell.exec( 'echo "' + strinImportStyle + '" >> projects/front-end-library/src/lib/scss/index.scss' );
moi je l'ai à chaque création de composant. ça touche 2 fichiers : 
![image](https://user-images.githubusercontent.com/82388009/154694485-5b6dcba6-df1d-448f-ba6f-3402b38c40ee.png)
et 
![image](https://user-images.githubusercontent.com/82388009/154694751-07ebb4fe-3143-4531-baa3-525f1320abfe.png)

2022-02-19 14:46 UTC, JonathanLefebvreV approved these changes

2022-02-19 14:46 UTC, merged