DS-271 - progress - component
bifrost-vui/bifrost-front-end-library pull request #261
Opened 2022-02-18 15:01 UTC by ThalieVideotron

https://bifrost-front-end-library-git-ds-271-progress-bar-bifrost-vui.vercel.app/?path=/story/ui-kit-progress--drupal

migration as-is de : https://labcx-marvel-uikit.etiya.com/?p=atoms-progress

2022-02-19 15:47 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/scss/index.scss
> +@import '../components/progress/scss/index';
```suggestion
@import "../components/progress/scss/index";
```

2022-02-19 16:03 UTC, JonathanLefebvreV requested changes
On sait tous entendu que les composant migré du UIKIT "non bifrostisé" allait dans une nouvelle sections
Quelque chose comme ça.
![image](https://user-images.githubusercontent.com/75901368/154808638-75d3341a-ee2e-4c4b-b17c-3caa49ecb263.png)

2022-02-19 16:06 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +- new `Progress` component (see [Component API](?path=/docs/components-progress--drupal)).
Ne pas appeler ça "new Components" mais "migration UIKIT"

2022-02-21 13:44 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/progress/angular/progress.component.ts
> +    @Input() progressColor          : 'default'|'success'|'warning'|'danger';
effectivement mais `progressColor` ne devrait juste pas être documentée du tout parce que c'est `progressPercentValue` qui fait changer la couleur. c'est donc une variable interne template uniquement et il n'est pas utile de la documenter dans le doc.

2022-02-21 13:49 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/progress/twig/index.twig
> +       aria-valuemin="{{ progressMinValue|default(0) }}"
Variable**s** - Effectivement il en manque 2
merci

2022-02-21 14:32 UTC, ThalieVideotron commented
> On sait tous entendu que les composant migré du UIKIT "non bifrostisé" allait dans une nouvelle sections Quelque chose comme ça. ![image](https://user-images.githubusercontent.com/75901368/154808638-75d3341a-ee2e-4c4b-b17c-3caa49ecb263.png)

Oui. Dès que j'arrive à le faire. 
J'ai demandé l'aide de Baptiste parce que c'est légèrement plus complexe que ce que je croyais.

2022-02-23 13:50 UTC, ThalieVideotron commented on CHANGELOG.mdx
> +- new `Progress` component (see [Component API](?path=/docs/components-progress--drupal)).
j'ai mis `UI-Kit (migrations)` pcq `UI-Kit migration` (en anglais) était juste un peu trop long pour le menu Storybook sur un écran de portable et tombait sur 2 lignes.

2022-02-25 00:43 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +### UI-Kit (migrations)
```suggestion
### UIKit (migrations)
```

2022-02-25 00:51 UTC, JonathanLefebvreV requested changes

2022-02-25 00:51 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/progress/twig/index.twig
> +{% if isMonochromeColor is defined and isMonochromeColor is same as (true) %}
isMonochromeColor Variable non documenté

2022-02-25 00:53 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/progress/angular/progress.component.ts
> +    @Input() progressColor          : 'default'|'success'|'warning'|'danger';
Ce que je parlait de documenté est le régime des couleur. De documenter que plus grand que 90% dans `ProgressPercentValue`, ça donne `danger` et etc.

2022-02-25 13:17 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/progress/angular/progress.component.ts
> +    @Input() progressColor          : 'default'|'success'|'warning'|'danger';
ah... ben oui

2022-02-25 13:32 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/progress/angular/progress.component.ts
> +    @Input() progressColor          : 'default'|'success'|'warning'|'danger';
done

2022-02-25 13:32 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/progress/twig/index.twig
> +{% if isMonochromeColor is defined and isMonochromeColor is same as (true) %}
done

2022-02-25 13:38 UTC, ThalieVideotron commented
@JonathanLefebvreV  - Suite au backmerge je constate qu'il n'y a pas de mention du image lazy load dans le changelog.  je m'attendait à avoir à résoudre un conflit.

2022-02-25 13:41 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/progress/angular/progress.component.ts
> +    @Input() isMonochromeColor      : boolean;
added missing variable

2022-02-26 16:11 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/progress/_doc/doc.stories.mdx
> +                options : [null, 'bf-color-bg-ground','bf-color-bg-underground','reversed bf-color-bg-ground','reversed bf-color-bg-underground', 'bf-color-bg-highlight']
```suggestion
                options : ['', 'bf-color-bg-ground','bf-color-bg-underground','reversed bf-color-bg-ground','reversed bf-color-bg-underground', 'bf-color-bg-highlight']
```

2022-02-26 16:13 UTC, JonathanLefebvreV approved these changes

2022-02-26 16:22 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +- Migrated `Image Lazy Load` component (see [Component API](/?path=/story/ui-kit-image-lazy-load--drupal)).
```suggestion
- Migrated [Progress](?path=/story/ui-kit-progress--drupal).
- Migrated [Image Lazy Load](?path=/story/ui-kit-image-lazy-load--drupal).
```

2022-02-26 16:35 UTC, JonathanLefebvreV approved these changes

2022-02-26 16:36 UTC, merged