DS-290- Progress-Multi Component
bifrost-vui/bifrost-front-end-library pull request #262
Opened 2022-02-18 17:24 UTC by ThalieVideotron

https://bifrost-front-end-library-git-ds-290-multi-p-2f35b6-bifrost-vui.vercel.app/?path=/story/ui-kit-progress-multi--drupal

migration _as-is_  de https://labcx-marvel-uikit.etiya.com/?p=atoms-progress-multi  incohérences inclues

2022-02-19 16:10 UTC, JonathanLefebvreV requested changes

2022-02-19 16:10 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/progress-multi/twig/index.twig
> +           role="progressbar"
indent 2

2022-02-19 16:10 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/progress-multi/scss/index.scss
> +    }
Comment ça la classe est pas vide?

2022-02-21 13:22 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/progress-multi/scss/index.scss
> +    }
parce que le CSS n'avait pas été tout rapatrié et que ça cassait (rien ne s'affichait). je l'ai donc rapatrié du UI-KIT mais dans une classe bf pour éviter tout risque de casser autre chose en ramenant du code pour tout le monde.

2022-02-21 13:29 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/progress-multi/twig/index.twig
> +           role="progressbar"
pour la lisibilité les propriétés sont alignées (option de l'IDE). Batiste suggérait cette approche (propriétés seulement). tiens-tu au 2 espaces partout? 
Maintenant que mon IDE ne plante plus, il insiste pour m'aligner les propriétés mais si tu tiens au 2 espaces, je peux m'obstiner avec mon IDE.

2022-02-25 13:48 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/progress-multi/twig/index.twig
> +           role="progressbar"
done -> 2 spaces

2022-02-26 16:47 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/progress-multi/_doc/data.ts
> +    {
```suggestion
        maxValue:2
    },
    {
```

2022-02-26 16:48 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/progress-multi/_doc/data.ts
> +        maxValue:""},
```suggestion
        maxValue:""
    },
```

2022-02-26 16:50 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/progress-multi/twig/index.twig
> +      <div class="progress-bar  {{ data.cssClass }}"
```suggestion
      <div class="progress-bar {{ data.cssClass }}"
```

2022-02-26 16:51 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/progress-multi/_doc/doc.stories.mdx
> +        maxValue:''},
```suggestion
        maxValue:''
    },
```

2022-02-26 16:52 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/progress-multi/_doc/doc.stories.mdx
> +        maxValue:2},
```suggestion
        maxValue:2
    },
```

2022-02-28 14:49 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/progress-multi/scss/index.scss
> +    }
Bien reçu. J'aimerais le voir en ligne. On sait où il est utilisé?

2022-02-28 15:56 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/progress-multi/twig/index.twig
> +           role="progressbar"
bon ben je refait alors. Ça va faire plaisir à @bibifrost ;-)

2022-02-28 18:11 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/progress-multi/scss/index.scss
> +    }
j'ai gardé les couleurs de la drop 5 (my account je crois) mais j'ai mis les couleurs originales en commentaire dans le fichier des variables boostrap pour les avoir à portée de main si nécessaire.

2022-03-02 21:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/progress-multi/_doc/data.ts
> +        maxValue:2
```suggestion
        label: 'Flex-go',
        cssClass: 'bg-flex-go',
        percent: 30,
        currentValue: 1,
        minValue: 2,
        maxValue: 2
```

2022-03-02 21:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/progress-multi/_doc/doc.stories.mdx
> +        },
```suggestion
        _background: {
            control: {
                type: 'select',
                options: [ null, 'bf-color-bg-ground', 'bf-color-bg-underground', 'reversed bf-color-bg-ground', 'reversed bf-color-bg-underground', 'bf-color-bg-highlight' ]
            },
            description: 'Preview the component on selected background'
        },
```

2022-03-02 21:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/progress-multi/_doc/doc.stories.mdx
> +        maxValue:2
```suggestion
        label: 'Flex-go',
        cssClass: 'bg-flex-go',
        percent: 30,
        currentValue: 1,
        minValue: 2,
        maxValue: 2
```

2022-03-02 21:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/progress-multi/_doc/template.drupal.twig
> +{% set _backgrounds = _backgrounds|json_parse %}
ligne 2 a supprimer

2022-03-02 21:22 UTC, bibifrost commented on projects/front-end-library/src/lib/scss/dependencies/bootstrap/overwrite/_progress.scss
> +/* *****************************************************************************
Ce CSS n'existait pas deja? Il aurait du etre rappatrié non?

2022-03-02 21:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/progress-multi/scss/index.scss
> +.bf-progress-multi {}
cette class n'existe pas encore. On supprime le fichier?

2022-03-13 14:55 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/progress-multi/scss/index.scss
> +    }
> Sauf que J'aimerais le voir en ligne. On sait où il est utilisé?

Ca va être très dur/impossible à te montrer en prod. Je ne sais pas qui faire intervenir pour te trouvé un compte.

C'est dans UIKIT Drop-5 que tu vas être capable de trouvé ca référence (search inclusion in code)
https://drop5-marvel-uikit.etiya.com/?p=Pages-Summary

2022-03-13 15:08 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/progress-multi/scss/index.scss
> +.bf-progress-multi {}
Dans les autres, "migration" on a laissé le fichier. Personnellement, ca me dérange pas l'un ou l'autre...

Lors que les "migration" seront "bifrostisé" on peut imaginé qu'on va re faire le composant anyway sous un autre nom... ou gardé celui actuel, mais le mettre au bonne pratique Bifrost, ou même jamais rien faire avec ...

Donc, si vous préférez gardé les classes CSS disponible. Ca fait du sens aussi et on peut le deleter.

2022-03-15 15:46 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/progress-multi/scss/index.scss
> +    }
https://drop5-marvel-uikit.etiya.com/?p=templates-hero-block-service-detail
c'est pour Etya dans tous les cas

2022-03-15 16:01 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/progress-multi/scss/index.scss
> +.bf-progress-multi {}
deleted :  justement pour garder la classe CSS disponible à la bifrostisation

2022-03-15 16:10 UTC, ThalieVideotron commented
j'ai des gros doutes sur les pourcentages de progressions que ça affiche. ce n'est pas le template qui fait les calculs mais le data dans progress data.

2022-03-28 15:24 UTC, bibifrost commented on projects/front-end-library/src/lib/components/progress-multi/angular/progress-multi.component.ts
> +    maxValue    :number
```suggestion
    maxValue    : number
```

2022-03-28 15:24 UTC, bibifrost commented on projects/front-end-library/src/lib/components/progress-multi/_doc/doc.stories.mdx
> +        maxValue:4
```suggestion
        label: 'Data-bloc',
        cssClass: 'bg-data-bloc',
        percent: 40,
        currentValue: 3,
        minValue: 4,
        maxValue: 4
```

2022-03-28 15:29 UTC, bibifrost commented on projects/front-end-library/src/lib/components/progress-multi/scss/index.scss
> +.bf-progress-multi {}
A discuter

2022-03-30 18:10 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/progress-multi/scss/index.scss
> +    }
Le CSS a été supprimé
Pour les couleurs j'ai remis celles qu'on trouve partout ailleurs dans le UI-KIT PCQ DXP ne l'utilise pas le progress bar (multi ou autre) et n'utilise pas ces couleurs dans l'absolu

2022-04-03 23:54 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
>  ## Badge
```suggestion
### Badge
```

2022-04-03 23:55 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
>  ## Angular Showcase
```suggestion
### Angular Showcase
```

2022-04-04 00:02 UTC, JonathanLefebvreV approved these changes

2022-04-04 00:02 UTC, merged