ds-293 add drupal showcase documentation
bifrost-vui/bifrost-front-end-library pull request #272
Opened 2022-02-24 09:55 UTC by bibifrost

2022-04-17 17:23 UTC, JonathanLefebvreV requested changes

2022-04-17 17:23 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/_doc/showcases/showcases-drupal.stories.mdx
> +### 1. Install Drupal
It misses pre-requirements software installed, like PHP and its compatible version. with Composer? Do we recommend in install an Apache server?
Write quick step to install on a Mac or a Window

2022-04-18 15:39 UTC, bibifrost commented on projects/front-end-library/src/lib/_doc/showcases/showcases-drupal.stories.mdx
> +### 1. Install Drupal
Que penses-tu si je redirige vers cette doc, uniquement pour le step 1, l'installation de PHP:
https://www.drupal.org/docs/installing-drupal/drupal-quick-start-command

2022-04-20 00:21 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/_doc/showcases/showcases-drupal.stories.mdx
> +### 1. Install Drupal
Quand je regarde une doc d'installation, j'aime la réfléchir en me posant la question: "Qu'est-ce qu'un nouveau collaborateur à besoin de suivre comme étapes, étant clair, précise, et facile à reproduire?"

Je suis personnellement contre de faire de la doc de doc. Donc, mettre des liens externes est très bien.
Par contre, celle que tu pointes, est intéressante, mais est pas "follow-and-play".

C'est sur que je réfléchir à 80% de valeur avec 20% d'effort. Donc faut faire quelque chose de bien, sans trop en faire.

Je voudrais voir au minimum dans la doc, qu'on a besoin d'installer php8 (ce qui n'est pas écrit dans la doc que tu pointes) et si il faut installé Composer séparément ou pas.

@ThalieVideotron, tu peux peut-être nous parler de ton expérience. Qu'est-ce qui a été intéressant quand tu l'as fait fonctionné? 

Pour info: moi je suis biaisé: Je dois faire roulé php5.6 et php8 sur mon poste. Ce n'est pas une mince affaire de configuration. Je ne l'ai pas commencé encore...

2022-04-25 17:44 UTC, bibifrost commented on projects/front-end-library/src/lib/_doc/showcases/showcases-drupal.stories.mdx
> +### 1. Install Drupal
Concernant le showcase Drupal, la config necessaire semble etre documentée ici (version de php incluse):
https://www.drupal.org/docs/installing-drupal/drupal-quick-start-command
<img width="676" alt="image" src="https://user-images.githubusercontent.com/93746960/165144074-488c654b-e273-4697-90bb-491fd7fe7660.png">
Et je ne saurais pas mieux faire.

A ne pas confondre avec la config necessaire pour consommer notre librairie de composant Twig. 
Car ce n'est pas une config propre à Bifrost mais simplement au Twig. Twig est la seule techno que nous utilisons qui n'est pas native au browser.

2022-08-20 15:08 UTC, merged