ds-294 add  non-reversed class
bifrost-vui/bifrost-front-end-library pull request #273
Opened 2022-02-25 11:27 UTC by bibifrost

2022-03-23 12:30 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/_doc/2-Implementation/6-reversed-and-highlight.stories.mdx
> +<div class='highlight'>
pas cohérent avec la mise à jour des couleurs de background. On leur dit d'utiliser la classe Highlight pour les contents

2022-03-23 20:53 UTC, bibifrost commented on projects/front-end-library/src/lib/_doc/2-Implementation/6-reversed-and-highlight.stories.mdx
> +<div class='highlight'>
Non pas la peine.
La class `'highlight` n'a qu'un seul intérêt: Indiquer que l'on est dans un contexte qui a le meme rendu reversed ou pas.
Elle ne change donc pas la valeur des variables CSS. C'est ce qui n'es pas clair ici. Je vais revoir le copy.

2022-03-27 18:47 UTC, JonathanLefebvreV requested changes
Missing the change Log. 
Ensure to merge with the master before doing it.

The PR is good, it will at least set the base to test and fix other component than the hero that have the same problem

2022-03-28 13:26 UTC, bibifrost commented
> Missing the change Log. Ensure to merge with the master before doing it.
> 
> The PR is good, it will at least set the base to test and fix other component than the hero that have the same problem

Changelog added. I am about to test merge with master.

2022-04-03 21:52 UTC, JonathanLefebvreV approved these changes

2022-04-03 21:53 UTC, merged