ds-289-create-angular-icons
bifrost-vui/bifrost-front-end-library pull request #274
Opened 2022-02-28 10:03 UTC by bibifrost

2022-02-28 18:55 UTC, ThalieVideotron commented on scripts/generate-svg-ts/index.js
>  // This file is generated automatically with command:
on dirait que les 4 lignes (70-74) sont mal alignés.
Personnellement les commentaires précèderaient la fonction generateFile, 
c'est cool de savoir ce que ça fait et comment l'exécuter sans avoir avoir à lire la fonction.

2022-02-28 18:55 UTC, ThalieVideotron commented on scripts/generate-svg-ts/index.js
> +    // shell.echo( '-> svgList  ' + JSON.stringify(svgList) );
je supprimerais le code en commentaire (code qui n'est plus utilisé) - il vient un peu polluer les autres commentaires qui viennent enrichir ou faciliter la lecture du code.

2022-02-28 19:43 UTC, bibifrost commented on scripts/generate-svg-ts/index.js
>  // This file is generated automatically with command:
Ces commentaires font parti du fichier généré. Dans ces circonstances, l'alignement doit se faire ainsi.

2022-02-28 19:49 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/badge/_doc/template.angular.component.html
ligne superflue

2022-02-28 19:49 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/badge/angular/badge.component.ts
> +    selector: 'bf-badge',
l'as-tu changé dans le template de génération?

2022-02-28 19:49 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/icon/_doc/template.drupal.twig
>    {% if name is defined and name is not same as ('undefined') and name is not same as ('All icons') %}
`name is defined and name is not same as ('undefined')` : une totologie non?

2022-02-28 19:49 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/icon/angular/icon.component.ts
> +            // this.element.nativeElement.innerHTML = svg;
code en commentaire - retirer?

2022-02-28 19:49 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/icon/svg/svg.ts
> +
est-ce qu'on devrait déployer les fichiers générés ou est-ce qu'on devrait les générer sur le serveur
De mon point de vue ça ne devrait pas être comité et on devrait s'assurer que le script roule au déploiement (et au start dev pour le local)

2022-02-28 20:01 UTC, ThalieVideotron commented
- si tu arrivais à centrer les story Angular de Icône comme tu l'as fait dans Badge ça serait cool 
 - Je note toute une architecture dans la doc des composants pour l'affichage dans storybook. Est-ce qu'il y aurait matière à l'ajouter dans les templates de génération de composants?

2022-03-01 09:54 UTC, bibifrost commented on projects/front-end-library/src/lib/components/icon/svg/svg.ts
> +
Veux-t-on rouler le script a chaque build? J'avais tendance à répondre non, car je voyais ce script comme un helper au meme titre que les autres scripts de generation de components. Mais c'est comme vous voulez.

2022-03-01 09:58 UTC, bibifrost commented on projects/front-end-library/src/lib/components/icon/_doc/template.drupal.twig
>    {% if name is defined and name is not same as ('undefined') and name is not same as ('All icons') %}
C'est nécessaire car si storybook envoie `undefined` on veux que cette condition renvoie false.

2022-03-01 10:01 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/angular/badge.component.ts
> +    selector: 'bf-badge',
Je crois oui, c'est un vieux composant qui n'avait pas été mis a jour.

2022-03-01 13:27 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/icon/svg/svg.ts
> +
En fait ça dépend qui consomme le fichier au final. Si c'est juste Storybook (pour l'affichage dans Storybook), effectivement ce n'est pas nécessaire mais si il fait partie de la librairie (qu'il est consommé) alors il devrait être généré. 
ce qui m'inquiète c'est que le fichier soit consommé sans avoir été généré localement alors que les json source ont été modifiés et que des icones aient été ajoutés/supprimés

2022-03-01 13:30 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/icon/_doc/template.drupal.twig
>    {% if name is defined and name is not same as ('undefined') and name is not same as ('All icons') %}
Il y a un contexte ou storybook retourne `undefined` ET qu'il retourne true à `is defined` ?

2022-03-01 14:31 UTC, bibifrost commented on projects/front-end-library/src/lib/components/icon/_doc/template.drupal.twig
>    {% if name is defined and name is not same as ('undefined') and name is not same as ('All icons') %}
oui de mémoire, c'était ça le probleme. Quand le control `icons` n'est pas définie. On pourrait l'améliorer dans une autre PR.

2022-03-01 15:06 UTC, bibifrost commented on projects/front-end-library/src/lib/components/icon/angular/icon.component.ts
> +            // this.element.nativeElement.innerHTML = svg;
done

2022-03-01 15:20 UTC, bibifrost commented on scripts/generate-svg-ts/index.js
> +    // shell.echo( '-> svgList  ' + JSON.stringify(svgList) );
> * si tu arrivais à centrer les story Angular de Icône comme tu l'as fait dans Badge ça serait cool
> * Je note toute une architecture dans la doc des composants pour l'affichage dans storybook. Est-ce qu'il y aurait matière à l'ajouter dans les templates de génération de composants?

- Oui, le width de la story est trop petit à cause d'un flex au root. Je crains de passer trop de temps à règler ce problème. Je propose de merger comme ça et d'améliorer plus tard.
- Architecture ajoutée. 👍

2022-03-01 15:20 UTC, bibifrost commented
> * si tu arrivais à centrer les story Angular de Icône comme tu l'as fait dans Badge ça serait cool
> * Je note toute une architecture dans la doc des composants pour l'affichage dans storybook. Est-ce qu'il y aurait matière à l'ajouter dans les templates de génération de composants?

- Oui, le width de la story est trop petit à cause d'un flex au root. Je crains de passer trop de temps à règler ce problème. Je propose de merger comme ça et d'améliorer plus tard.
- Architecture ajoutée. 👍

2022-03-01 15:28 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/icon/svg/svg.ts
> +
merci. je sais que je suis chicken mais je trouve ça plus sur.

2022-03-08 16:23 UTC, ThalieVideotron requested changes
j'ai un fail au stard dev
le fichier svg.ts se génère  dans projects/front-end-library/src/lib/components/icon/ (pas dans le répertoire svg du composant) 
si dans icon.component.ts je remplace `import iconList from '../svg/svg';` par `import iconList from '../svg';` ça marche.  
Il reste donc à générer le ts au bon endroit ou changer le path dans le  icon.component.ts  

----------------

je pense que c'est pour ça que ça ne build pas sur Vercel : 
voir ln 94 dans scripts/generate-svg-ts/index.js :
      const buildFilePath = 'projects/front-end-library/src/lib/components/icon/svg/svg.ts';

2022-03-08 16:54 UTC, ThalieVideotron commented
pour le bug d'affichage storybook :  testé sur mon poste et sans impact sur les autres composant (onglets canvas et doc) 

sur .storybook/preview-head.html (autour de la ligne 34)
```
    /**************************************************************************/
    /* Else the root takes the size of the component and fullWidth is not working.
    */
    #root {
        width: 100%;
        /*display: flex;*/
    }
```

2022-03-15 12:37 UTC, ThalieVideotron commented
> > * si tu arrivais à centrer les story Angular de Icône comme tu l'as fait dans Badge ça serait cool
> > * Je note toute une architecture dans la doc des composants pour l'affichage dans storybook. Est-ce qu'il y aurait matière à l'ajouter dans les templates de génération de composants?
> 
> * Oui, le width de la story est trop petit à cause d'un flex au root. Je crains de passer trop de temps à règler ce problème. Je propose de merger comme ça et d'améliorer plus tard.
> * Architecture ajoutée. 👍

j'ai trouvé le fix. un flex inutile à supprimer. testé et ça n'impact aucun autre affichage dans storybook

2022-03-15 12:45 UTC, ThalieVideotron submitted a review, later dismissed

2022-03-15 19:28 UTC, ThalieVideotron reviewed
Pour moi c'est ready to go - je laisse @JonathanLefebvreV  se prononcer. 
- aussi testé en local - le fichier svg.ts se génère bien et a été ajouté au .gitignore
- le pages de composants Angular s'affichent aussi bien que les Drupal (mise en forme très similaire) - pas mal plus beau

2022-03-27 13:12 UTC, JonathanLefebvreV requested changes
Il manque le Change Log

2022-03-27 13:12 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/_doc/template.angular.component.html
> +    <div class='d-flex flex-column flex-sm-row justify-content-center gap-4 p-4' [ngClass]='{ "reversed bf-color-bg-ground": template === 2, "disabled": _disabled }'>
Le mode reversed ne fonctionne pas dans aucune story angular pour le badge.

![image](https://user-images.githubusercontent.com/75901368/160282730-6b40b29f-0f41-4d04-b04b-69ce62c89133.png)

2022-03-27 13:12 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/_doc/template.angular.component.ts
> +@Component({
ligne vide de trop

2022-03-27 13:12 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/_doc/template.angular.component.ts
> +    templates               : number[] = [1,2];
comme on a voté, on aligne pu les valeur des variables.
Stun peu le chaos la dessus dans tes PR. Je bloquerai pas la PR pour ca. On va mettre ca clean avec le temps, mais comme ici c'est un ajout pur

2022-03-27 13:17 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/twig/index.twig
> +          class : 'pr-2',
Je pense que c'est bien d'avoir enlevé le hack, mais il faut, au moins, corrigé la taille de l'icone

2022-03-28 12:18 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/_doc/template.angular.component.ts
> +    templates               : number[] = [1,2];
Oui, et je me demande si ce fichier ne ferait pas exception. On s'en jase.

2022-03-28 12:26 UTC, bibifrost commented on projects/front-end-library/src/lib/components/icon/angular/icon.component.ts
> +    }
done

2022-03-28 12:27 UTC, bibifrost commented on scripts/generate/templates/component/_doc/template.angular.component.ts
> +@Component({
ok avec toi. Il va effectivement falloir faire une passe globale our harmoniser.

2022-03-28 12:33 UTC, bibifrost commented on projects/front-end-library/src/lib/components/icon/angular/icon.component.ts
> +    @Input() color              : null | 'success' | 'neutral'| 'warning' | 'negative';
Pour les composants Angular, c'est pas mal plus propre d'avoir un état à null plutôt qu'une string vide. Car en javascript, c'est littéralement un vrai cas de `null`.

D'ailleurs, de mon coté, storybook n'offre pas de control éditable dans le cas d'une string vide:
Avec `null |` ...
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/93746960/160398062-0ea68b6a-f4de-42d7-bc2d-76848e32be2f.png">
Avec `'' | `...
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/93746960/160398253-8b8c3163-facd-4f78-b132-97c235fe99ac.png">

2022-03-28 12:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/_doc/template.angular.component.ts
> +@Component({
fixed

2022-03-28 12:54 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/twig/index.twig
> +          class : 'pr-2',
T'as l'oeil! :) Je regarde ça

2022-03-28 13:07 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/twig/index.twig
> +          class : 'pr-2',
Mais alors, la taille de l'icone devrait etre 24px par 24px ? C'est le cas dans Figma.
Dans ce cas, ce n'était pas correct avant non plus? A moins qu'on ai volontairement réduit à 20px?
<img width="194" alt="image" src="https://user-images.githubusercontent.com/93746960/160403917-dc3fc98e-010e-48d2-81c8-711350cd2f37.png">

2022-03-28 13:10 UTC, bibifrost commented on projects/front-end-library/src/lib/components/badge/_doc/template.angular.component.html
> +    <div class='d-flex flex-column flex-sm-row justify-content-center gap-4 p-4' [ngClass]='{ "reversed bf-color-bg-ground": template === 2, "disabled": _disabled }'>
Fixed. Merci

2022-03-28 17:50 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/icon/angular/icon.component.ts
> +    @Input() color              : null | 'success' | 'neutral'| 'warning' | 'negative';
@bibifrost je me souviens d'avoir eu un problème similaire avec la string vide mais c'est parce qu'il faut que les options soient définies à la fois dans dans le mdx et dans le fichier typescript pour que Storybook les affiche.

Si ça doit être `null` ou `''` je vous laisse en débattre. On a fait l'allez retrour là dessus dans une autre branche pour un cas similaire et on a opté pour la string vide. 

juste souligner qu'on traine cette valeur simplement pour accomoder l'utilisateur Storybook (pour supprimer une couleur) et qu'elle n'est pas nécessaire. On peut tout simplement supprimer cette option et le forcer à utiliser le bouton `controls reset` pour supprimer la couleur. -> ni  `null` ni `''`

2022-03-28 17:50 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/icon/angular/icon.component.ts
> +    @Input() className          : string;
On c'est déjà posé la question mais est-ce qu'on ne devrait pas dès maintenant ajouter `className` de façon systématique à nos api pour à terme, pouvoir déprécier `class`.  (IE  pour le moment on met les 2 dans tous les nouveaux composants)

2022-03-28 17:50 UTC, ThalieVideotron commented on scripts/generate/templates/component/_doc/template.angular.component.ts
> +export class %ComponentName%TemplateComponent implements OnInit {
on saute une ligne avant le export aussi?

2022-03-29 11:16 UTC, bibifrost commented on scripts/generate/templates/component/_doc/template.angular.component.ts
> +export class %ComponentName%TemplateComponent implements OnInit {
non, c'est une norme Angular d'avoir le décorateur juste au dessus du component.

2022-03-29 11:21 UTC, bibifrost commented
> @bibifrost je me souviens d'avoir eu un problème similaire avec la string vide mais c'est parce qu'il faut que les options soient définies à la fois dans dans le mdx et dans le fichier typescript pour que Storybook les affiche.
> 
> Si ça doit être null ou '' je vous laisse en débattre. On a fait l'allez retrour là dessus dans une autre branche pour un cas similaire et on a opté pour la string vide.
> 
> juste souligner qu'on traine cette valeur simplement pour accomoder l'utilisateur Storybook (pour supprimer une couleur) et qu'elle n'est pas nécessaire. On peut tout simplement supprimer cette option et le forcer à utiliser le bouton controls reset pour supprimer la couleur. -> ni null ni ''
> 
> PVI cas 2 est dans Badge (angle)
> 

- Peux-tu m'indiquer un cas qui nécessite de dupliquer la liste des options dans MDX et le composant Angular? Je ne vois pas de cas pertinent.
- La nous n'avons plus le choix d'utiliser `null` car **Icon** et **Badge** sont maintenant des vrais composants Angular exposés dans la library Angular. Et le `null` correspond exactement à l'usage qu'on en a.

2022-03-29 11:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/icon/angular/icon.component.ts
> +    @Input() color              : null | 'success' | 'neutral'| 'warning' | 'negative';
- @ThalieVideotron, peux-tu m'indiquer un cas qui nécessite de dupliquer la liste des options dans MDX et le composant Angular? Je ne vois pas de cas pertinent.
- La nous n'avons plus le choix d'utiliser null car Icon et Badge sont maintenant des vrais composants Angular exposés dans la library Angular. Et le null correspond exactement à l'usage qu'on en a.

2022-03-30 15:06 UTC, ThalieVideotron commented on scripts/generate/templates/component/_doc/template.angular.component.ts
> +export class %ComponentName%TemplateComponent implements OnInit {
merci pour l'info

2022-03-30 15:28 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/icon/angular/icon.component.ts
> +    @Input() color              : null | 'success' | 'neutral'| 'warning' | 'negative';
@bibifrost si je me souviens bien,  la duplication était nécessaire quand tu avais un string vide, le `null` ne fait pas ça... et effectivement c'est contre productif
 Pour ma culture : est-ce qu'il y a une distinction entre null et undefined dans Angular ?

2022-03-30 18:10 UTC, bibifrost commented on projects/front-end-library/src/lib/components/icon/angular/icon.component.ts
> +    @Input() color              : null | 'success' | 'neutral'| 'warning' | 'negative';
Ce n'est pas lié à Angular, mais au Javascript:
- `Null`: It is the intentional absence of the value. It is one of the primitive values of JavaScript.
- `Undefined`: It means the value does not exist in the compiler. It is the global object.

2022-03-30 18:25 UTC, bibifrost commented
> à peaufiner dans les prochaines versions : ![image](https://user-images.githubusercontent.com/82388009/160868633-70498ff7-7885-41db-a4e2-05a469053932.png)
> 
> les stories Angular s'affichent mal dans la doc - minor issue- pas un bloquant mais ça serait cool de le fixer

Fixed

2022-03-31 12:20 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/twig/index.twig
> +          class : 'pr-2',
Je me suis rendu compte aussi en fesant le test qu'il était à 20x24 sur master.
Allons y avec la réalité de 24x24 et on en reparle avec les UI en Demo

2022-03-31 12:31 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/icon/angular/icon.component.ts
> +        {
```suggestion
        if (iconName && iconList[`${iconName}`]) {
```

2022-03-31 12:45 UTC, JonathanLefebvreV requested changes
⚠️ il manque encore la modificatoin du ChangeLog

2022-03-31 12:45 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/_doc/template.angular.component.ts
> +@Component({
le double ligne est encore présent

2022-03-31 12:45 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/badge/_doc/template.angular.component.html
> +    <div class='d-flex flex-column flex-sm-row justify-content-center gap-4 p-4' [ngClass]='{ "reversed bf-color-bg-ground": (template === 2 || reversed), "disabled": _disabled }'>
Le mode background a été réparé, mais est différents en rendu par rapport à sa story équivalente en Drupal. C'est à unifié

2022-03-31 12:45 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/icon/angular/icon.component.ts
> +    @Input() color              : null | 'success' | 'neutral'| 'warning' | 'negative';
Si dans ce cas on veut reproduire des comportement d'injection de variable.
Pourquoi on fait pas le contrôle comme les définition optionnel des story?

Je parle que si on veut tester que "null" est injecté (faire du null-proofing) et voir le comportement, il faudrait aussi le comportement quand la variable n'existe pas dans le context, Je parle de ce fonctionnement
![image](https://user-images.githubusercontent.com/75901368/161057402-5baa8006-2e59-48a1-97de-267d0df4df21.png)

2022-03-31 12:47 UTC, bibifrost commented on projects/front-end-library/src/lib/components/icon/angular/icon.component.ts
> +        {
Fixed

2022-03-31 12:47 UTC, JonathanLefebvreV commented on scripts/generate/templates/component/_doc/template.angular.component.ts
> +@Component({
Sans faire une passe globale, au moins fixé les nouveau fichier de cette PR

2022-04-02 20:48 UTC, bibifrost commented
> On master (expected) ![image](https://user-images.githubusercontent.com/75901368/161084782-3b12888c-2568-44f2-92b6-6061d4942fdb.png)
> 
> Here (to fix) ![image](https://user-images.githubusercontent.com/75901368/161085065-a92eb1d7-3f28-4814-8a54-c75d0f9a42c9.png)
> 
> Huge Icon has no value to be the first story listed, so On master we rename the story so Illustration is the first. Ensure to merge with Master and do the same with the Angular Story, bu putting "huge" at the end of the name

done

2022-04-03 21:58 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/icon/angular/icon.component.ts
> +        {
You miss the space

2022-04-03 22:08 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/icon/angular/icon.component.ts
> +        if(iconName && iconList[`${iconName}`]) {
```suggestion
        if (iconName && iconList[`${iconName}`]) {
```

2022-04-03 22:10 UTC, JonathanLefebvreV approved these changes

2022-04-03 22:10 UTC, merged