DS-299 Card Header Bug - fixed bootstrap classes in template
bifrost-vui/bifrost-front-end-library pull request #276
Opened 2022-03-02 14:03 UTC by ThalieVideotron

PVI - le bug vient du fait qu'on soit `mobile fisrt` et que les classe bootstrap  `p-sm` et `m-sm` sont dans un media query `(min-with : 576px)` -> sont sans effets sur les mobile  -
conclusion :  à nous de penser `mobile firts` en utilisant ces classes

2022-03-02 14:05 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/badge/scss/index.scss
> -            max-width: 15rem;
évite le débordement des badges en mobile - bug devenu évident en faisant les tests responsives de la carte

2022-03-04 02:27 UTC, JonathanLefebvreV requested changes
Change log missing

2022-03-04 02:27 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +  <header class='bf-card__header px-3 py-4'>
```suggestion
  <header class='bf-card__header px-3 py-4 p-sm-4'>
```
la classe de `xx-sm-4` est à remettre partout pour garder le style desktop.
C'est juste le mobile qui était à fixé

2022-03-04 13:51 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +  <header class='bf-card__header px-3 py-4'>
réparé. j'ai pas pris ton commit pcq il fallait les remettre partout mais done.

2022-03-04 13:55 UTC, ThalieVideotron commented
longueur de 13 rem pour la longueur max du badge va s'appliquer seulement sur les mobiles de moins de 576px (le beakpoint le + petit que nous ayons) - on reste à 15 pour les autres... un peu out of scope 
avant : 
![image](https://user-images.githubusercontent.com/82388009/156775830-cd895df4-c4c2-4204-ad78-c1242da5cde3.png)
après: 
![image](https://user-images.githubusercontent.com/82388009/156775932-5368dca9-2dcf-4793-9765-75b8f126154a.png)

2022-03-04 15:30 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/card/twig/index.twig
> +          'class'     : 'bf-card__content-badge mt-3 mx-3'
```suggestion
          'class'     : 'bf-card__content-badge mt-3 mx-3 mx-sm-4'
```

2022-03-04 15:32 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +### bug-fix
```suggestion
### Bug fix
```

2022-03-04 15:48 UTC, JonathanLefebvreV approved these changes

2022-03-04 15:48 UTC, merged