DS-273: Add new television-plus icon
bifrost-vui/bifrost-front-end-library pull request #280
Opened 2022-03-05 22:06 UTC by JonathanLefebvreV

2022-03-08 00:06 UTC, ThalieVideotron commented on CONTRIBUTING.mdx
> +1. Open those SVG files and replace all hardcoded color for `currentColor`
il y a eu un cas de ID à enlever mais on updatera la doc si je retrouve un contexte

2022-03-08 00:27 UTC, JonathanLefebvreV commented on CONTRIBUTING.mdx
> +1. Create svg-twig file for small and large size.
ok, j'ai fait de quoi de semblable

2022-03-08 00:28 UTC, JonathanLefebvreV commented on CONTRIBUTING.mdx
> +1. Receive the small and large file from designer exported from Figma
je vais voir

2022-03-08 00:32 UTC, JonathanLefebvreV commented on CONTRIBUTING.mdx
> +1. Open those SVG files and replace all hardcoded color for `currentColor`
oui, c'est une doc directionnel... pas une procédure de bombe nucléaire avec toute les cas d'exception à gérer :P

2022-03-08 12:28 UTC, bibifrost commented
`television-plus` ou `tv-plus` ? Je propose d'opter pour `tv-plus` pour rester cohérent avec la catégorie.
Mais bon, à date, on n'est pas tres consistent car les 2 termes existent:
<img width="993" alt="image" src="https://user-images.githubusercontent.com/93746960/157238040-b42bb415-4880-4bd2-90da-4e1bec602b93.png">
<img width="368" alt="image" src="https://user-images.githubusercontent.com/93746960/157238140-a9d55410-6f08-4bd5-a1f2-8f8464df630d.png">

2022-03-08 13:26 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/icon/_doc/doc.stories.mdx
> +                type: 'select',
alignement ?

2022-03-08 20:41 UTC, JonathanLefebvreV commented
> `television-plus`, `tv-plus` ou `tv-plan-plus` ? Je propose d'opter pour `tv-plan-plus` pour rester cohérent avec la catégorie. Mais bon, à date, on n'est pas tres consistent car les 2 termes existent: <img alt="image" width="993" src="https://user-images.githubusercontent.com/93746960/157238040-b42bb415-4880-4bd2-90da-4e1bec602b93.png"> <img alt="image" width="368" src="https://user-images.githubusercontent.com/93746960/157238140-a9d55410-6f08-4bd5-a1f2-8f8464df630d.png">

Je crois que la Réflextion des UI est que les noms ne sont pas trouvé par "catégorie" mais par genre d'icone.
La "télévision" s'appel "television" et "television-plus" c'est le même icone avec un + à l'intérieur. Pour moi c'est adéquant.

2022-03-08 20:53 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/icon/_doc/doc.stories.mdx
> +                type: 'select',
fix in https://github.com/bifrost-vui/bifrost-front-end-library/pull/280/commits/48cee25bc3b2ea23024017d5afccacb52f927571

2022-03-08 22:29 UTC, ThalieVideotron approved these changes

2022-03-10 21:24 UTC, ThalieVideotron requested changes

2022-03-10 21:24 UTC, ThalieVideotron commented on public/icons/list/illustrations.json
> +      "tv-plan-plus",
ordre alpha ;)

2022-03-10 21:29 UTC, ThalieVideotron approved these changes

2022-03-10 21:30 UTC, merged