DS-309 - Banner Advanced - new component
bifrost-vui/bifrost-front-end-library pull request #282
Opened 2022-03-08 20:59 UTC by ThalieVideotron

2022-03-09 15:39 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/banner-advanced/_doc/doc.stories.mdx
> +} only %}
```suggestion
{% include '@bf-components/banner-advanced/twig/index.twig' with {
    title       : 'Mobile discount of $10 with an Internet plan',
    subtitle    : 'Combine a Mobile plan to an Internet plan and get a $10 monthly discount.',
    services    : [
        {
            icon    : 'mobility',
            label   : 'Mobile plan'
        },
        {
            icon    : 'bundle-1',
            label   : 'Internet plan'
        }
    ]
} only %}
```

2022-03-09 15:44 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/banner-advanced/scss/index.scss
> +}
```suggestion
    flex-flow: row wrap;
    justify-content: space-between;
    align-items: center;
    border: 1px solid var(--bf-color-stroke-secondary);
    @extend .bf-border-radius-small;
    background-color: var(--bf-color-bg-ground);

    @include media-breakpoint-down(sm) {
        flex-flow: column;
    }

    &__header {
        flex: 1;
        min-width: 15rem;

        h3, p {
            @include media-breakpoint-down(sm) {
                text-align: center;
            }
        }
    }
    &__body {
        display: flex;
        flex-flow: row nowrap;
        justify-content: space-around;
        align-items: start;
        text-align: center;

        .bf-icon.size-small {
            margin-top: var(--bf-spacer-4);
        }
        &.downscale-icons {
            .bf-icon.size-large {
                @include media-breakpoint-down(sm) {
                    width: 3rem;
                    height: 3rem;
                    min-width: 3rem;
                }
            }
            .bf-icon.size-small {
                @include media-breakpoint-down(sm) {
                    margin-top: var(--bf-spacer-2);
                }
            }
        }
    }
}
```

2022-03-09 15:45 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/banner-advanced/_doc/template.drupal.twig
> +</section>
```suggestion
<section class='pt-4 px-3'>
  {% include '@bf-components/banner-advanced/twig/index.twig'  %}
</section>
```

2022-03-09 16:08 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/scss/index.scss
> +
ligne de trop

2022-03-09 19:27 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/icon/svg.ts
> +    "sm": "",
effectivement.
1- ce fichier doit être ajouté au gitignore car il est généré. 
2- en plus il n'est pas généré au bon endroit. 
3- il ne se génère pas dans cette branche mais dans une autre tâche de Baptiste. 
aucune idée de comment il a réussi à se faufiler. je vais simplement le supprimer.

2022-03-09 19:30 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +  </header>
done - fait seulement sur le paragraphe (subtitle) 
testé. et c'est pas nécessaire de le faire sur le titre

2022-03-10 01:00 UTC, JonathanLefebvreV approved these changes

2022-03-10 14:24 UTC, JonathanLefebvreV requested changes
En review UI, tout les icones en mobile doivent être en medium

Changer l'attribut "subtitle" pour "description"

2022-03-10 16:19 UTC, ThalieVideotron commented on CHANGELOG.mdx
> +- Fix MegaMenu in [Navigation Header](/?path=/docs/components-navigation-header--drupal) with the width sizing section
on met Fix partout ou Fixed partout ?

2022-03-10 20:49 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +- Fix MegaMenu in [Navigation Header](/?path=/docs/components-navigation-header--drupal) with the width sizing section
ca me va

2022-03-10 20:52 UTC, JonathanLefebvreV approved these changes

2022-03-10 20:54 UTC, merged