DS-292 Background colors improve documentation
bifrost-vui/bifrost-front-end-library pull request #283
Opened 2022-03-09 16:54 UTC by ThalieVideotron

draft

2022-03-11 15:54 UTC, bibifrost reviewed
Bien joué pour la section dédiée aux backgrounds actions, pour le déplacement de Brand et pour le déplacement de la catégorie Feedback.
Avec la description en plus. Belle amélioration 👍

2022-03-11 15:54 UTC, bibifrost commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +                label            : 'Highlight (not reversible)',
Je retirerai `(not reversible)` ou je le mettrai partout ou c'est pertinent, car c'est le cas de plusieurs couleurs.

2022-03-11 15:54 UTC, bibifrost commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +                UtilityClassName : 'bf-border-color-highlight'
Peux tu me partager le figma ou le besoin derriere ce stroke?
Juste pour m'assurer que le namming est ok.

2022-03-11 15:54 UTC, bibifrost commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: 'Use the stroke colors for borders only',
```suggestion
        description: 'Use the stroke colors for borders only.',
```

2022-03-11 15:54 UTC, bibifrost commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: 'These background colors are meant to be used on interactive components',
```suggestion
        description: 'These background colors are meant to be used on interactive components.',
```

2022-03-11 16:12 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +                label            : 'Highlight (not reversible)',
c'est seulement parce qu'il y a 2 hightlight - pour les différencier surtout qu'ils sont dans la même "catégorie" de background (un en dessous de l'autre)
et du coup ça fait partie de mes questions : pourquoi 2 highlight et est-ce qu'il y a des contexte d'application différents - si moi je ne saisi pas, imagines les dev ;-)

2022-03-11 16:49 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +                label            : 'Highlight (not reversible)',
vérifié et `--bf-color-highlight` n'est utilisée que dans les logos - tout comme brand par ailleurs. je vais le mettre dans les content et supprimer le irreversible du `Highlight` background

la notion de highlight est donc ainsi un peu clarifiée - reste à expliquer qu'on ne peut pas les combiner ;-)

2022-03-11 17:04 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +                label            : 'Highlight (not reversible)',
pour bf-border-color-highlight
il sert au hover dans les selections tiles (uniquement) - l'autre option était de se servir des couleurs de background pour faire des bordures. 
En regardant le contexte je me souviens vaguement d'une discussion à ce sujet - l'optimal serait de revoir notre logique parce que les tuiles mais aussi d'autres éléments interactifs pourraient avoir des actions qui sont des bordures plutôt que des background - je te propose qu'on le fasse dans une prochaine étape(pas ce jira) 
je crois que les éléments de formulaires qu'on est en train de migrer bénéficieraient d'une telle réflexion

2022-03-13 14:11 UTC, JonathanLefebvreV requested changes

2022-03-13 14:11 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +
Le changelog c'est pour les modification du code (css,composant, etc) On ne documente pas les changements de la documentation (storybook)

Reverté le fichier

2022-03-13 14:30 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/_doc/styles/1-colors/doc.stories.mdx
> +                        <p class='bf-text bf-color-neutral-secondary small maxw-75'>{category.description}</p>
Si je suis tous seul que ca agresse ok...
Moi la combinaison `bf-text-color-neutral-secondary` et `small` rend le texte très mineur et j'ai de la difficulté à le lire.
C'est sensé être un texte de description/explication qu'on veut que les gens lisent, et ne pas être considéré comme une "option" visuellement parlant.

Je ce que j'exprime, c'est que ça pas assez de poids visuel et mes yeux le skip parce que c'est pas facile à lire.

2022-03-13 14:33 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: 'Feedback colors are used to indicate a status and may apply to content or borders (never use as a background)',
Ca me parrait faux. Le background d'un callout ou des bullet du composant `Status`.

2022-03-13 14:33 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: 'These background colors are meant to be used on interactive components.',
```suggestion
        description: 'These background colors are meant to be used on interactive visual element.',
```

2022-03-13 14:36 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: 'Theses background colors are meant to be used on non-interactive elements. The Highlight isn\'t compatible with the Reversed option',
```suggestion
        description: 'These background colors are meant to be used on non-interactive elements.',
```
ça me parrait faux. C'Est compatible, c'est juste le même effet. Dire que quelque chose est pas compatible, c'est que ca crée un problème

2022-03-13 14:38 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: 'The brand color is mostly used by logos and shouldn\'t be used in non-reversed context on text or icons. The Highlight color shoudn\'t be used in combination with the Highlight
tu n'est pas entrain d'expliqué la section ici. Tu expliques les exceptions et les "don't"

A refaire comme tu as fait pour les autre : "quelle est le bug des classe de couleur Content"?

2022-03-13 14:42 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/_doc/styles/1-colors/doc.stories.mdx
> +                                <div class='pr-6 pb-6 my-2 reversed ' style={{ backgroundColor: `var(--bf-color-${c.name})` }}></div>
super pour les margins, mais qu'-est-ce qui avait de mal avec les padding?
Un peu le même commentaire que tantôt. Étant le top 3 des éléments important dans la page, je ne comprends pas pourquoi on réduit son visuel

2022-03-14 12:39 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/_doc/styles/1-colors/doc.stories.mdx
> +                        <p class='bf-text bf-color-neutral-secondary small maxw-75'>{category.description}</p>
ça s'arrange. je ne veut pas que ça crie non plus. il y a certainement un compromis possible

2022-03-14 12:47 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: 'Feedback colors are used to indicate a status and may apply to content or borders (never use as a background)',
bullet, c'est du `content`  rendu là (c'est un icone). La seule exception où c'est un background c'est certains éléments de formulaires (checkbox, radio et switch)  sinon, c'est clair Il ne faut pas utiliser ces couleurs en background. règle général c'est pour du contenu ou des bordures

2022-03-14 12:51 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: 'Theses background colors are meant to be used on non-interactive elements. The Highlight isn\'t compatible with the Reversed option',
reverse + highlight produit un bug visuel où on écrit en blanc sur fond jaune. c'est incompatible point de vue UX car ça n'offre pas le contraste nécessaire. si pour toi ce n'est pas un problème, mes yeux ne partagent pas ton avis. par ailleurs il existe plusieurs bugs/tâches jira qui soulèvent cet enjeux.

2022-03-14 13:25 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: 'The brand color is mostly used by logos and shouldn\'t be used in non-reversed context on text or icons. The Highlight color shoudn\'t be used in combination with the Highlight
Certaines couleurs de contenu (vérifié dans le code) étaient citées comme couleurs de BG alors que ce sont des couleurs de contenus. Et en l'absence de zeroHeight il me semble nécessaire de préciser certains contextes d'utilisation. or je n'ai qu'une seule description

personnellement j'aurais ajouté une description aux couleurs pour ces précisions mais je me suis retenue : 
1 - Brand est effectivement réservé au logo et s'il était utilisé comme couleur de contenu, il devrait être ne reversed (pas de jaune sur fond blanc et inversment)
2 - la couleur de contenu highlight n'est effectivement pas compatible avec le background highlight

Nous pourrions aussi combiner cette information soit au début soit à la fin du tableau mais il me semble nécessaire de formuler ces recommentations

2022-03-15 15:29 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/_doc/styles/1-colors/doc.stories.mdx
> +                        <p class='bf-text bf-color-neutral-secondary small maxw-75'>{category.description}</p>
done

2022-03-15 15:29 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +                label            : 'Highlight (not reversible)',
done - retirer les recommandations - juste descriptif

2022-03-15 15:31 UTC, ThalieVideotron commented on CHANGELOG.mdx
> +
mentions dans le changelog retirée - fait dans la résolution de conflit du backmerge

2022-03-17 06:52 UTC, bibifrost commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        name: 'Background (action)',
```suggestion
        name: 'Background Action',
```

2022-03-17 06:52 UTC, bibifrost commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: 'These background colors are meant to be used on interactive visual elements.',
```suggestion
        description: 'Meant to be used on interactive visual elements.',
```
Pour aller droit au but.

2022-03-17 06:52 UTC, bibifrost commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: "Theses background colors are meant to be used on non-interactive visual elements.",
```suggestion
        description: "Meant to be used on non-interactive visual elements.",
```

2022-03-17 06:52 UTC, bibifrost commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: 'The content colors are used on text and svg (logos & icons)',
```suggestion
        description: 'Meant to be used on text and SVG.,
```

2022-03-17 06:52 UTC, bibifrost commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: 'Use the stroke colors for borders only.',
Je pense que cette phrase n'apporte pas de valeur car:
border = terme CSS
stroke = terme générique ou terme UX

Mais border et stroke sont la meme chose. Jusqu'a present les descriptions étais sur l'usage UX et la on parle de l'usage CSS.

2022-03-17 06:52 UTC, bibifrost commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: 'Feedback colors are used to indicate a status and generally apply to content or borders',
Pas sur que ça apporte de la valeur.
Status = autre mot pour feedback.
generally apply to content or borders = pas sur que ça soit pertinent ici.

2022-03-17 06:52 UTC, bibifrost commented on projects/front-end-library/src/lib/_doc/styles/1-colors/doc.stories.mdx
> +> Bifrost defines 4 groups of colors: **Content, Background, Stroke** and **Feedback**.
Avec la nouvelle découpe, tu peux ajouter `Background Action`.

2022-03-17 06:52 UTC, bibifrost commented on projects/front-end-library/src/lib/_doc/styles/1-colors/doc.stories.mdx
> +                                <div class='pr-6 pb-6 my-2 reversed ' style={{ backgroundColor: `var(--bf-color-${c.name})` }}></div>
```suggestion
                                <div class='pr-6 pb-6 my-2 reversed' style={{ backgroundColor: `var(--bf-color-${c.name})` }}></div>
```

2022-03-17 13:15 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: 'Use the stroke colors for borders only.',
on ne s'adresse pas qu'à des UX. et se rappelle que c'est aussi un outils  pour des dev avec peu de connaissance frontend et des PO encore moins de connaissances. Pour moi `content`  c'est évident que c'est du texte et des images mais on le précise quand même.

2022-03-17 14:00 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: "Theses background colors are meant to be used on non-interactive visual elements.",
fait en local à cause des doubles quotes -> single

2022-03-17 14:01 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: 'The brand color is mostly used by logos and shouldn\'t be used in non-reversed context on text or icons. The Highlight color shoudn\'t be used in combination with the Highlight
Ok next version et on verra où on met l'info

2022-03-17 15:07 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/_doc/styles/1-colors/colors.js
> +        description: 'Theses background colors are meant to be used on non-interactive elements. The Highlight isn\'t compatible with the Reversed option',
supprimé - remplacé par une description simple

2022-03-17 15:36 UTC, ThalieVideotron reviewed
une des suggestion a fait planter le déploiement pcq'uil manque un`'` et depuis je n'arrive plus à mettre à jour (les push sont rejected) - my bad mais il va probablement falloir créer une seconde branche et supprimer celle-ci

2022-03-17 15:48 UTC, ThalieVideotron commented
désolée je dois closer cette PR - la branche se met à jour mais pas la PR

2022-03-17 15:48 UTC, closed without merging

2022-03-27 18:07 UTC, JonathanLefebvreV commented
Closed in favor of https://github.com/bifrost-vui/bifrost-front-end-library/pull/292