ds-315 improve banner advanced
bifrost-vui/bifrost-front-end-library pull request #290
Opened 2022-03-15 21:18 UTC by bibifrost

2022-03-16 13:34 UTC, ThalieVideotron reviewed
pourquoi ne pas avoir fait de commentaires sur la PR avant la mise en production de la bannière et avoir choisis de faire une nouvelle branche après coup ? Y a-t-il un bug côté dxp?

on introduit un régression visuelle alors que le résultats précédent avait été validé par design. Je crois que nous aurions du en discuter en équipe avant que le travail ne commence.

2022-03-16 13:34 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/scss/index.scss
> +        align-items: center;
pas une bonne idée - je comprend mais revoir la solution
![image](https://user-images.githubusercontent.com/82388009/158600143-cdc0b671-9559-431d-bad0-2e0f9697a221.png)
le + est supposé être centré par rapport aux icones et quand le texte sous les icones passent sur 2 lignes on n'est plus alligné. pour ma part c'est une régression pas un fix

2022-03-16 13:34 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/scss/index.scss
> -        .bf-icon.size-small {
positionnait le + au centre par rapport aux autres icônes

2022-03-16 13:34 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +    <div class='bf-banner-advanced__body gap-0 gap-sm-2 {{ iconMobileClass|default('') }}'>
retirer {{ iconMobileClass|default('') }}. n'est plus nécessaire. il a été oublié là

2022-03-16 13:34 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +              class   : 'mb-4'
si c'est pas cassé on ne répare pas : 
![image](https://user-images.githubusercontent.com/82388009/158597801-ad0cc59f-17f4-4417-90f1-f587cb3704d3.png)
le plus n'est plus centré par rapport aux icones : c'est une régression pas un fix

2022-03-17 06:17 UTC, bibifrost commented
> pourquoi ne pas avoir fait de commentaires sur la PR avant la mise en production de la bannière et avoir choisis de faire une nouvelle branche après coup ? Y a-t-il un bug côté dxp?
> 
> on introduit un régression visuelle alors que le résultats précédent avait été validé par design. Je crois que nous aurions du en discuter en équipe avant que le travail ne commence.

Ce sont des ajustements mineurs que je n'avais pas eu le temps de t'indiquer avant le merge.
Je l'ai fait en 2min, c'était plus rapide de le faire et d'en discuter après pour qu'on ai la meme comprehension.

2022-03-17 06:19 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +              class   : 'mb-4'
ici j'ai surtout simplifier le code en appliquant des `gap` a la place des `margin-left`.

2022-03-17 06:19 UTC, bibifrost commented
> > pourquoi ne pas avoir fait de commentaires sur la PR avant la mise en production de la bannière et avoir choisis de faire une nouvelle branche après coup ? Y a-t-il un bug côté dxp?
> > on introduit un régression visuelle alors que le résultats précédent avait été validé par design. Je crois que nous aurions du en discuter en équipe avant que le travail ne commence.
> 
> Ce sont des ajustements mineurs que je n'avais pas eu le temps de t'indiquer avant le merge. Je l'ai fait en 2min, c'était plus rapide de le faire et d'en discuter après pour qu'on ai la meme comprehension. Je ne l'ai pas mis en review dev car je voulais t'en parler avant.

2022-03-17 06:26 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/_doc/doc.stories.mdx
> +## Drupal implementation example
done dans [cette PR](https://github.com/bifrost-vui/bifrost-front-end-library/pull/291)

2022-03-17 06:31 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/scss/index.scss
> +    border-radius: var(--bf-border-radius-small);
Les classes utilitaires dans le HTML mais pas dans le CSS. 
Le rendu n'est pas le meme car à chaque fois que tu fais un extend, tu génères une entrée dans un tableau qui s'affiche ainsi:
<img width="482" alt="image" src="https://user-images.githubusercontent.com/93746960/158750196-261d2219-ec2e-4c0e-91db-056b30453eb5.png">

2022-03-17 06:32 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/scss/index.scss
> +    border-radius: var(--bf-border-radius-small);
on n'est pas a ça près, mais je l'ai ajusté par automatisme.

2022-03-17 06:39 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/scss/index.scss
> +        align-items: center;
l'alignement n'etait pas correct avant, je pense que le gap l'améliore:
<img width="260" alt="image" src="https://user-images.githubusercontent.com/93746960/158751318-1f2e483b-0e46-4793-8158-65987101444d.png">
Tu ne penses pas?

2022-03-17 06:39 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/scss/index.scss
> -    @include media-breakpoint-down(sm) {
on s'en parle

2022-03-24 15:26 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/_doc/doc.stories.mdx
> +## Drupal implementation example
merci

2022-03-24 15:28 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/scss/index.scss
> +        align-items: center;
laissé actif pour la question au design - mais discuté et resolved pour moi

2022-03-31 12:54 UTC, JonathanLefebvreV approved these changes

2022-03-31 12:55 UTC, JonathanLefebvreV requested changes
Il manque la modification du ChangeLog

2022-03-31 13:01 UTC, bibifrost commented
> Il manque la modification du ChangeLog

De mon point de vue, aucun changelog n'est pertinent. Car il n'y a aucun changement d'API, ni de rendu visuel important.

2022-04-03 22:14 UTC, JonathanLefebvreV approved these changes

2022-04-03 22:15 UTC, merged