Ds 252 improve tile post
bifrost-vui/bifrost-front-end-library pull request #293
Opened 2022-03-22 18:04 UTC by bibifrost

2022-03-23 14:17 UTC, ThalieVideotron reviewed
à voir avec design : quand on ajoute une classe de background le contenu se ramasse très collé au bord et ça a l'air cassé. est-ce qu'on ne devrait pas prévoir le coup et s'ajouter une propriété pour éviter ce genre de problème? ![image](https://user-images.githubusercontent.com/82388009/159719204-1214ad04-e784-4465-af47-dbfe31e7c812.png)

si reversed est appliqué comme classe plutôt que comme propriété c'est pire : 
![image](https://user-images.githubusercontent.com/82388009/159720021-1f5df889-24ad-453c-b1cf-42b0758162b0.png)

@baptistemac  ce dernier comportement ne me semble pas normal le reversed et la classe reversed devrait avoir le même effet non?

2022-03-23 14:17 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-post/twig/index.twig
>        style='background-image: url({{ image.src|default('') }});
la aussi on utilise le default au lieu de tester si on a src. ce qui veut dire qu'on a créé le div même s'il n'y a pas de src.

2022-03-23 14:17 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-post/twig/index.twig
>          {% if image.backgroundColor is defined and image.backgroundColor %}
pas très cohérent ici on test avant d'appliquer la couleur de background - pas de default. du coup je pourrait avoir un div background uni (disons rouge puisque c'est entièrement libre).

2022-03-23 20:27 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-post/_doc/doc.stories.mdx
>          backgroundColor: 'grey'
Non mais c'est pour indiquer que l'on peux ajouter n'importe quelle couleur. C'est ce que je fais pour tous les props `backgroundColor`.

2022-03-23 20:28 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-post/angular/tile-post.component.ts
> +    isFill          : boolean;
le boolean offre une interface facile a implementer et a changer.

2022-03-23 20:29 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-post/angular/tile-post.component.ts
> +    /** API: `{ src, alt, isFill, backgroundColor }` */
pourquoi? je ne vois pas vraiment ce que ça apporte. Le mieux serait d'offrir l'API plus détaillée. Mais ce n'est pas le bon endroit il me semble.

2022-03-23 20:30 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-post/scss/index.scss
> +        background-size: contain;
je ne comprend pas. Tu dis que si isFill est à false, on ne sait pas ce qui va se passer?

2022-03-23 20:31 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-post/twig/index.twig
> +      class='bf-tile-post__visual {{ image.isFill|default(true) ? 'bf-tile-post__visual--fill' }}'
Ça permet pourtant de clarifier le code.

2022-03-23 20:33 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-post/twig/index.twig
>        style='background-image: url({{ image.src|default('') }});
Oui. On pourrait checker la presence de `src` dans `{% if image is defined and image %}` et retirer ce default.

2022-03-23 20:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-post/twig/index.twig
>          {% if image.backgroundColor is defined and image.backgroundColor %}
oui totalement. Chaque props est responsable de sa seule application. Si dans l'API d'image, tu entres une mauvaise url dans `src` et `red` dans `backgroundColor` alors tu aura un aplat rouge. C'est ce qui est attendu.

2022-03-23 20:45 UTC, bibifrost commented
> à voir avec design : quand on ajoute une classe de background le contenu se ramasse très collé au bord et ça a l'air cassé. est-ce qu'on ne devrait pas prévoir le coup et s'ajouter une propriété pour éviter ce genre de problème? ![image](https://user-images.githubusercontent.com/82388009/159719204-1214ad04-e784-4465-af47-dbfe31e7c812.png)
> 
> si reversed est appliqué comme classe plutôt que comme propriété c'est pire : ![image](https://user-images.githubusercontent.com/82388009/159720021-1f5df889-24ad-453c-b1cf-42b0758162b0.png)
> 
> @baptistemac ce dernier comportement ne me semble pas normal le reversed et la classe reversed devrait avoir le même effet non?

1. C'est normal que ce soit collé. On peux s'appeler pour en parler.
2. La difference de reversed est normal aussi: 
- Quand on toggle la props `reversed`, storybook ajoute un `bf-color-bg-ground` au div parent du component. Ceci pour simuler un rendu dans un environnement reversed.
- Cependant, si tu ajoute la class `.reversed` sur le composant, ça ne va pas automatiquement ajouter `bf-color-bg-ground`.

2022-03-24 15:32 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-post/angular/tile-post.component.ts
> +    /** API: `{ src, alt, isFill, backgroundColor }` */
je disais ça simplement pcq on fait comme ça partout ailleurs - comment on ferait pour mieux détailler l'API?

2022-03-24 15:36 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-post/scss/index.scss
> +        background-size: contain;
non finalement ça me va - faudrait utiliser cette façon de faire (et le nom de variable) partout où on a ce comportement - mais comme tu disais c'est peut être propre aux images  quoiqu'on a des composant qui peuvent aussi adopter ce comportement

2022-03-24 15:40 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-post/twig/index.twig
>        style='background-image: url({{ image.src|default('') }});
je serais plus à l'aise - surtout pour ce cas là.

2022-03-24 15:41 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/tile-post/twig/index.twig
>          {% if image.backgroundColor is defined and image.backgroundColor %}
beurk mais bon...

2022-03-24 19:03 UTC, ThalieVideotron commented
mes questions et irritants ont été adressés - c'est Ok pour moi.

2022-03-24 20:56 UTC, bibifrost commented on projects/front-end-library/src/lib/sections/tiles-post/scss/index.scss
> +}
```suggestion
```

2022-03-27 19:05 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/tile-post/_doc/doc.stories.mdx
> +        isFill: true,
C'est pas vraiment ça qu'on a dit en Demo... C'était que la propriété était sur l'Image plutot que sur le composant comme on a fait pour block-Highlight. vu qu'il est le standard étant le seul à gérer cette situation.
Comme c'est ce qui a été entendu, c'est ça je m'attendais à voir.

Cela dit, comme on a aussi réfléchir à que BlockHighlight est à réécrire en Banner éventuellement, on pourra revoir son fonctionnement...

Sauf que là, il faut s'entendre : On fait comme le standard ou on établie que ceci est le standard?

2022-03-28 11:55 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-post/_doc/doc.stories.mdx
> +        isFill: true,
Ici, la propriété `isFill` est bien un enfant de l'objet `image`. Ce n'est effectivement pas le cas du BlockHighlight qui a `isVisualBackgroundFill` en props du composant.
Mais effectivement, je propose que le `image.isFill` soit la nouvelle norme.
Est-ce bien ça dont tu parlais?

2022-04-03 22:17 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/tile-post/_doc/doc.stories.mdx
> +        isFill: true,
oui ok

2022-04-03 22:28 UTC, JonathanLefebvreV reviewed
Je n'arrive pas à comprendre cette PR. C'est quoi l'amélioration? DAns le Jira, tu décris que tu as mis un "isFill" mais on dirait tu l'as enlever.

J'ai l'impression c'est pas documenté proprement de comment l'image est gérer

2022-04-03 22:52 UTC, baptistemac commented
> Je n'arrive pas à comprendre cette PR. C'est quoi l'amélioration? DAns le Jira, tu décris que tu as mis un "isFill" mais on dirait tu l'as enlever.
> 
> 
> 
> J'ai l'impression c'est pas documenté proprement de comment l'image est gérer

En fait, l'image n'est pas un background-image mais carrément une balise ´<img>´ et la ratio de l'image est toujours respectée donc pas de isFill ici.

2022-04-04 13:54 UTC, bibifrost commented
> > Je n'arrive pas à comprendre cette PR. C'est quoi l'amélioration? DAns le Jira, tu décris que tu as mis un "isFill" mais on dirait tu l'as enlever.
> > J'ai l'impression c'est pas documenté proprement de comment l'image est gérer
> 
> En fait, l'image n'est pas un background-image mais carrément une balise img et la ratio de l'image est toujours respectée donc pas de isFill ici. Ceci dit ça pourrait etre documentée.

[DONE] C'est documenté dans la page Docs.

2022-04-10 19:12 UTC, JonathanLefebvreV requested changes

2022-04-10 19:12 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/tile-post/_doc/doc.stories.mdx
> +- **Ratio:** Image displayed will respect the ratio of the original image source.
Je trouve pas cette documentation clair. A quoi tu fais référence en GRAS?  C'est des API de Image?

2022-04-10 19:12 UTC, JonathanLefebvreV requested changes
Need the ChangeLog

2022-04-18 19:11 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-post/_doc/doc.stories.mdx
> +- **Ratio:** Image displayed will respect the ratio of the original image source.
Non, c'est juste mot clés. Je vais tenter de renommer.

2022-04-18 19:21 UTC, bibifrost commented on projects/front-end-library/src/lib/components/tile-post/_doc/doc.stories.mdx
> +- **Ratio:** Image displayed will respect the ratio of the original image source.
En fait, ça me semble assez clair que ce n'est pas l'API, non?
<img width="725" alt="image" src="https://user-images.githubusercontent.com/93746960/163863630-c83779b4-f6f9-4eea-b6f9-993e95c6f92f.png">

2022-04-18 19:23 UTC, bibifrost commented
> Need the ChangeLog to said we remove a property

Done

2022-04-20 00:29 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/tile-post/_doc/doc.stories.mdx
> +- **Ratio:** Image displayed will respect the ratio of the original image source.
Personnellement non, car une des recommandation qu'on va faire dans le Changelog est de référé les API en Gras. Ca serait bien de gardé la même nomenclature au travers de storybook, mais j'ai pas d'autre opinion pour backé que ce n'est pas clair. Alors on garde.

2022-04-20 00:29 UTC, JonathanLefebvreV approved these changes

2022-04-20 00:30 UTC, merged