Ds 320 modal
bifrost-vui/bifrost-front-end-library pull request #297
Opened 2022-03-29 21:57 UTC by ThalieVideotron

DRAFT - MIgration option

2022-03-31 19:01 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/modal/_doc/template.drupal.twig
> +    modalId: 'exampleModal1',
Comme on en a besoin pour provoquer l'ouverture du modale, ça aurait fait du sens de le mettre required mais il ne l'est pas dans UI-Kit

2022-03-31 19:15 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/modal/twig/index.twig
> +          {% if block('modal_body_subcontainer') is defined %}
possibilité de mettre 2 blocks successifs dont seul le second est scrollable : pas compatible avec les nouveaux designs.

2022-03-31 19:17 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/modal/twig/index.twig
> +<div class='modal  modal-theme--{{ modalTheme|default('light') }} {{ modalAnimation|default('fade') }} {{ class }}'
ModalTheme : ouvre la porte à une modale en mode `dark` - Touteles modales sont sur fond blanc dans les nouveaux designs

2022-03-31 19:19 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/modal/angular/modal.component.ts
> +    @Input() modalBudy: string;
`modalBudy`  modalCeci, modalCela... il y a du travail à faire pour avoir un nommage plus cohérent avec ce qui existe.

2022-04-08 22:03 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +export const contentDemo = `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dictum diam metus, et eleifend orci vulputate et. Phasellus metus risus, feugiat at eros et, venenatis s
@bibifrost 
pour une raison qui m'échappe, plus rien ne s'affiche quand je fait un saut de ligne dans ce bout de code ou le suivant. il n'y a évidement aucune erreur, le body du Iframe reste juste vide.  t'as une idée pourquoi? ça marche ailleurs.

2022-04-10 08:15 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +export const contentDemo = `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dictum diam metus, et eleifend orci vulputate et. Phasellus metus risus, feugiat at eros et, venenatis s
Bizarre. Les templates html semblent mal encodés pour passer dans l'url. Le serveur express ne les renvoie donc simplement pas.
On peux faire un ticket JIRA pour le régler plus tard?

2022-04-11 14:38 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +export const contentDemo = `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dictum diam metus, et eleifend orci vulputate et. Phasellus metus risus, feugiat at eros et, venenatis s
TODO dans : https://videotron-design-system.atlassian.net/browse/DS-336

2022-04-18 14:31 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +<ArgsTable of={ModalComponent}/>
```suggestion
<ArgsTable of={ModalComponent} 
/>
```

2022-04-18 14:31 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +    } %}
indent

2022-04-18 14:31 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +    } %}
indent

2022-04-18 14:31 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/template.drupal.twig
> +{% set modal_body_scroll_container = modal_body_scroll_container|json_parse|default('') %}
```suggestion
{% set modal_body_subcontainer = modal_body_subcontainer|json_parse %}
{% set modal_body_scroll_container = modal_body_scroll_container|json_parse %}
```

Pour mieux détecter les problèmes qu'il pourrait y avoir si un **default** n'est pas défini.

2022-04-18 14:31 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/template.drupal.twig
> +{% set modal_footer = modal_footer|json_parse %}
Est-ce vraiment necessaire?

2022-04-18 14:31 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/angular/modal.component.ts
> +    @Input() modalContentCLass: string;
```suggestion
    @Input() modalContentClass: string;
```

A moins que ce soit comme ça dans le UI-Kit?

2022-04-18 14:31 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/twig/index.twig
> +    <div class='modal-content position-relative {{ modalContentCLass|default('') }}'
```suggestion
    <div class='modal-content position-relative {{ modalContentClass|default('') }}'
```

2022-04-18 14:35 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +        name='Drupal - scrollable content'
Je me demande si ce ne serait pas plus simple, d'avoir une seule story qui affiche les 2 modals:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/93746960/163823719-73dc003d-9cad-462b-8df5-319db9cce45d.png">

2022-04-19 13:04 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/modal/_doc/template.drupal.twig
> +{% set modal_footer = modal_footer|json_parse %}
les json_parse pour des bolck twig - oui, pour les string non. 
quand on va avoir la possibilité des block twig ça sera nécesssaire.  j'ai peur qu'on ne les oublie après le retrait du serveur express. Tu les supprimerais en attendant?

2022-04-19 13:06 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/modal/angular/modal.component.ts
> +    @Input() modalContentCLass: string;
c'est du copié-collé de UIKit. perso ça serait contentClass tout court. à la bifrostisation on fait un gros ménage de namming. garde tes idées pas trop loin

2022-04-19 13:14 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +    modalBudy: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. ',
UI-Kit legacy - namming à revoir pour l'ensemble de l'œuvre. Garde tes idées pas trop loin ça va servir

2022-04-19 13:21 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/modal/twig/index.twig
> +    <div class='modal-content position-relative {{ modalContentCLass|default('') }}'
idem.  copié-collé de UIKit.  
fautes et bavures inclues. 
si je fait un rename de celle-là, il faut faire les autres et on va se ramasser avec beaucoup de depricated et de retro-compatibilité. on sort du 80/20. 
100% d'accord sur le fond par contre

2022-04-19 13:22 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +        name='Drupal - scrollable content'
je regarde ça - c'est certain que c'est possible de le faire.  je trouvais ça plus clair de faire en 2 story parce que tu vois bien quel contrôle est rempli pour chaque cas de figure alors que les 2 contrôles ont du contenu si tu le fais en 1 seule story. 

Si c'étais bifrostisé on n'aurait pas ce problème parce qu'on aurait 1 seul container et que la scrolabilité serait une option (comme ça aurait dû être dès le départ)

2022-04-20 13:51 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +        name='Drupal - scrollable content'
Ok testé mais ça me force à mettre le contenu des modales dans le template.twig alors que ce n'est pas sa place
du coup, next version?

2022-04-21 14:47 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +        name='Drupal - scrollable content'
Compris. Merci pour l'explication :)

2022-04-22 11:57 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +/>
```suggestion
<ArgsTable of={ModalComponent} />
```

2022-04-22 12:10 UTC, JonathanLefebvreV requested changes
Il manque le changelog de la migration

2022-04-22 12:10 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/scss/dependencies/bootstrap/overwrite/_modal.scss
> +}
Je penses pas que dans une "migration" tu devrais changer du SCSS. Peux tu me mettre des screenshot du problème et du rendu ? (aka: before/after)

2022-04-22 12:10 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +export const footerDemo =`<div class='d-flex'><a href='https://www.example.com' class='bf-button bf-button--primary ml-4 mb-3' data-title='primary'><span class='bf-button__label'><span class='bf-butt
```suggestion
export const footerDemo =`<div class='d-flex'><a href='https://www.example.com' class='bf-button bf-button--primary ml-4 mb-3' data-title='primary'><span class='bf-button__label'><span class='bf-button__label__text'>Primary</span></span></a></div>`;
```

2022-04-22 12:10 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +        name='Drupal - non scrollable content'
```suggestion
        name='Drupal'
```
On ne nomme pas les story de base

2022-04-22 12:10 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/modal/_doc/template.drupal.twig
> +</div>
I don't see value in this part of the story. Can be removed if I'm right

2022-04-22 12:10 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/modal/_doc/template.drupal.twig
> +    id: 'launchBtn2',
2?

2022-04-22 14:29 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/scss/dependencies/bootstrap/overwrite/_modal.scss
> +}
Si par hasard le modal; est dans un contexte reversed ça donne ça : 
![image](https://user-images.githubusercontent.com/82388009/164732805-5606fd87-704b-47d7-8547-65faa3edf417.png)

avec le fix ça donne ça: 
![image](https://user-images.githubusercontent.com/82388009/164733112-fde333f5-49e5-49df-9618-7292b12c8689.png)

Le UI-kit n'avait pas la notion de reversed il utilise des thèmes (dark/light) mais le thème light ne réagit pas comme voulu en reversed.  On introduirait un bug assez majeur qui empêche l'accès au contenu si il y a cohabitation entre les composant UI-Kit et le CSS de Bifrost. 

Le thème dark est également cassé en mode non reversed mais comme on n'est plus sensé avoir de thème dark pour les modales je n'ai pas corrigé. voici ce que ça donne : (non reversed + modale thème dark) 
![image](https://user-images.githubusercontent.com/82388009/164733587-39392512-bd6b-43ca-a677-62e2a1806876.png)

On en a discutté avec Baptiste et il nous faudra revoir l'overwrite de bootstrap modal au grand complet quand on bifrostera pour vrai. on traine beaucoup de variables de couleur non UI-Kit

2022-04-22 14:39 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/modal/_doc/template.drupal.twig
> +</div>
pis? t'as raison? 
moi j'appelle ça se protéger mais si tu crois que ça n'arrivera jamais on peut l'enlever (et on peut aussi retirer le fix css que j'ai été forcée d'implémenter) 
mais si on veut rester agnostique on est mieux de prévoir le cas - maintenant que tu comprend mieux l'enjeux c'est ton choix

2022-04-22 16:41 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/modal/_doc/template.drupal.twig
> +{% set modal_footer = modal_footer|json_parse %}
discuté avec Baptiste et on les garde pour les block twig

2022-04-26 14:20 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/scss/dependencies/bootstrap/overwrite/_modal.scss
> +}
@JonathanLefebvreV : ce qui a été expliqué en weekly. 
Cette modification ne fait que permettre aux modales UI-Kit de répondre adéquatement en mode reversed  et donc la cohabitation entre le css Bifrost et celui des modale UI-Kit legacy

2022-05-03 22:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +            control: { type: 'text' },
```suggestion
```

2022-05-03 22:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +            control: { type: 'text' },
```suggestion
```

2022-05-03 22:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +            table: { category: 'Deprecated Inputs'}
```suggestion
            table: { category: 'Deprecated Inputs' }
```

2022-05-03 22:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +            table: { category: 'Deprecated Inputs'}
```suggestion
            table: { category: 'Deprecated Inputs' }
```

2022-05-03 22:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +        moduleMetadata({declarations: [ModalComponent, TwigContainerComponent]}),
```suggestion
        moduleMetadata({ declarations: [ModalComponent, TwigContainerComponent] }),
```

2022-05-03 22:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +            }
On pourrait ecrire tout le temps sur une seule ligne, car on utilise rarement d'autre propriété de table.
```suggestion
            table: { defaultValue: { summary: 'fade' } }
```

2022-05-03 22:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +export const contentDemo = `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dictum diam metus, et eleifend orci vulputate et. Phasellus metus risus, feugiat at eros et, venenatis s
Renommer `contentDemo` en `modalBodyProps`

2022-05-03 22:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +export const footerDemo =`<div class='d-flex'><a href='https://www.example.com' class='bf-button bf-button--primary ml-4 mb-3' data-title='primary'><span class='bf-button__label'><span class='bf-butt
Renommer `footerDemo` en `modalFooterProps`.

2022-05-03 22:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +        frameBorder='0' allowFullScreen></iframe>
```suggestion
<iframe
        width='100%' height='450' frameBorder='0' allowFullScreen
        src='https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2F7bTmk29aCBl7rCFszffYPr%2FDS---Components-%2526-styles%3Fnode-id%3D12732%253A87435%0A'
></iframe>
```

Sur une ligne ou bien comme comme ici en mode React. Mais évitons l'entre deux.

2022-05-03 22:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/template.drupal.twig
> +  {# buttons are for DEMO only #}
Je pense que tu peux retirer ce commentaire.
Tout est demo car on est dans un fichier nommé **template**.

2022-05-03 22:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +            control: { type: 'text' },
```suggestion
```

2022-05-03 22:34 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +        name='Drupal - scrollable content'
```suggestion
        name='Drupal - With scrollable content'
```

2022-05-05 16:05 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +export const footerDemo =`<div class='d-flex'><a href='https://www.example.com' class='bf-button bf-button--primary ml-4 mb-3' data-title='primary'><span class='bf-button__label'><span class='bf-butt
done

2022-05-05 16:08 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/modal/_doc/doc.stories.mdx
> +            control: { type: 'text' },
si je ne met pas de type, on ne peut pas renseigner la variable dans storybook et on ne peut pas s'assurer que la rétrocompatibilité est fonctionnelle.

2022-05-05 22:01 UTC, bibifrost commented on projects/front-end-library/src/lib/components/modal/twig/index.twig
> +{% set class = class|default(modalClass) %}
Si `modalId` n'existe pas, `id` n'a toujours pas de default.
On ne respecte pas le strict_variable.

2022-05-07 20:00 UTC, JonathanLefebvreV approved these changes

2022-05-07 20:00 UTC, merged