Ds 321 input button submit
bifrost-vui/bifrost-front-end-library pull request #304
Opened 2022-04-11 12:59 UTC by ThalieVideotron

STILL IN DRAFT

2022-04-11 13:07 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/angular/button.component.ts
> +    @Input() formTarget: null | '_self' | '_blank' | '_parent' | '_top';
null ou '' ?
uniformiser

2022-04-11 13:07 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +    {% if label is not empty %}data-title='{{ label }}'{% endif %}
if  non difined = is not empty ? 
ajouter de la robustesse?

2022-04-11 13:07 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/twig/index.twig
>      {% if ariaLabel is defined %}aria-label='{{ ariaLabel|default(NULL) }}'{% endif %}
and ariaLabel (pas de string vides)

2022-04-18 14:23 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/angular/button.component.ts
> +    @Input() hasLoading: boolean;
L'ordre que je propose:
```suggestion
    @Input() label: string;
    @Input() hierarchy: null | 'primary' | 'primary-alt' | 'secondary' | 'tertiary';
    /** A button will become a link if `href` is defined as long as it is not Disabled or a submit button. */
    @Input() href: string;
    @Input() fullWidth: boolean;
    @Input() class: string;
    @Input() id: string;
    @Input() extraAttribute: string;

    @Input() isDisabled: boolean;
    @Input() isAutofocus: boolean;
    @Input() isLoading: boolean;
    @Input() hasLoading: boolean;
    
    @Input() iconName: string;
    @Input() iconPosition: null | 'left' | 'right';
    /** Changing the size of the icon is not recommended. */
    @Input() iconSize: string;
    
    @Input() ariaLabel: string;
    @Input() ariaControls: string;
    @Input() ariaExpanded: string;
    
    @Input() dataDismiss: string;
    @Input() dataToggle: string;
    @Input() dataTarget: string;
    
    @Input() isSubmit: boolean;
    @Input() formId: string;
    @Input() formAction: string;
    @Input() formEncryptionType: null | 'application/x-www-form-urlencoded' |'multipart/form-data' | 'text/plain';
    @Input() formTarget: null | '_self' | '_blank' | '_parent' | '_top';
    @Input() formMethod: string;
    @Input() formNoValidate: boolean;
```

2022-04-18 14:23 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +    {% if isSubmit %}
C'est déroutant de ne pas avoir de changement HTML quand tu ajoutes un `formId` et que tu n'a pas activé `isSubmit`.
Je propose la logique inverse:
- Si on ajoute un control qui commence par `form`, alors le composant twig ajoute automatiquement `type='submit'`. Car de toute façon, rien ne se passera sans ça.

2022-04-18 14:23 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +      {% if formNoValidate|default(false) %}formnovalidate='formnovalidate'{% endif %}
```suggestion
      {% if formNoValidate|default(false) %}formnovalidate{% endif %}
```

2022-04-18 14:23 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +      {% if formMethod|default('') %}formmethod='{{ formMethod }}'{% endif %}
```suggestion
      {% if formAction|default(null) %}formaction='{{ formAction }}'{% endif %}
      {% if formEncryptionType|default(null) %}  formenctype='{{ formEncryptionType }}' {% endif %}
      {% if formTarget|default(null) %}formtarget='{{ formTarget }}'{% endif %}
      {% if formMethod|default(null) %}formmethod='{{ formMethod }}'{% endif %}
```

2022-04-18 14:23 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +    {% if id|default('') %}id='{{ id }}'{% endif %}
```suggestion
    {% if id|default(null) %}id='{{ id }}'{% endif %}
```

2022-04-18 14:23 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/_doc/template.drupal.twig
> +<div class='d-flex flex-column justify-content-center flex-grow-1 {{ _background }}'>
indent

2022-04-19 13:36 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +    {% if isSubmit %}
oui j'y ait pensé mais aucun des arguments form n'est requis pour que ça fonctionne et que ça soit valide. Tout ce que ça prend c'est que le bouton soit dans le form et qu'il ne soit pas de type button (s'il n'y a pas de type et que c'est dans le form et il est automatiquement un submit) .  Mais je comprend où tu veux en venir alors je vais chercher une solution.

2022-04-19 21:08 UTC, bibifrost commented on CHANGELOG.mdx
> +- Improved [Twig Button Component](/story/components-button--drupal) to handle submit functionalities.
```suggestion
- Improved [Twig Component Button](/story/components-button--drupal) to handle submit functionalities.
```

2022-04-19 21:08 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/_doc/template.drupal.twig
> +{% set formEncryptionType = formEncryptionType|json_parse %}
Vraiment utiles ces 2 la?

2022-04-20 18:16 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +    {% if isSubmit %}
done

2022-04-20 18:20 UTC, ThalieVideotron commented on CHANGELOG.mdx
> +- Improved [Twig Button Component](/story/components-button--drupal) to handle submit functionalities.
j'ai des doute sur la qualité de la syntaxe.

2022-04-20 18:38 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/_doc/template.drupal.twig
> +{% set formEncryptionType = formEncryptionType|json_parse %}
formEncryptionType je l'ai déjà vu utilisé dans des formulaires de contact qui permet l'upload - si le bouton est à l'extérieur du form c'est lui qui doit l'avoir. mais je pourrais supprimer l'option text/plain qui n'est pas recommandée parce que mal interpétée. 

formTarget, je ne l'ai pas vu utilisé depuis des lunes ;-) mais il est valide et standard. 

Comme tous les autres arguments form ils sont là au cas où...  et settés à null ou false par défaut parce que je ne crois pas qu'ils soient nécessaires - en principe si le bouton est dans le form c'est la responsabilité du form. Je les ai mis parce que je suis sensée être agnostique et que c'est des arguments du submit standards et valides.

2022-04-20 21:27 UTC, bibifrost commented on CHANGELOG.mdx
> +- Improved [Twig Button Component](/story/components-button--drupal) to handle submit functionalities.
Comment ça? Quels doutes?

2022-04-20 21:28 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/_doc/template.drupal.twig
> +{% set formEncryptionType = formEncryptionType|json_parse %}
Je parlais de l'utilité des jsonparse.

2022-04-22 12:19 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +- Improved [Twig Button Component](/story/components-button--drupal) to handle submit functionalities.
hors sujet pour la PR

2022-04-22 12:22 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
>  import { Canvas, Meta, Story, Props }  from '@storybook/addon-docs';
Update "props" pour "argsTables"

2022-04-22 12:25 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/button/_doc/template.drupal.twig
> +    {% for _hierarchy in hierarchyList %}
Changement du template de la story pour les bouton a aussi été fait dans un autre Jira. Ca va générer des conflit. Dans mon souvenir c'est l'autre qui était mieux, mais je ne me rappel pu c'est laquelle. A revoir une fois tout ca mergé

2022-04-22 12:27 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/button/scss/index.scss
> +/* TODO: Find a more elegant wy to give access to initial css variables in reversed. #DS-338 */
```suggestion
/* TODO DS-338: Find a more elegant wy to give access to initial css variables in reversed. */
```

2022-04-22 16:55 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/_doc/template.drupal.twig
> +{% set formEncryptionType = formEncryptionType|json_parse %}
oui parce que c'est des select et non des contôles de type texte. c'est l'exception des strings qu'on doit parser.

2022-04-22 16:57 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/_doc/template.drupal.twig
> +    {% for _hierarchy in hierarchyList %}
@baptistemac  Tu saurais de quelle branche Jonathan parle? 
je crois n'avoir que simplifié le code en ajoutant un `for` pour les backgrounds et dans le fond si ça m'overwrite c'est pas bien grave

2022-04-22 16:59 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/scss/index.scss
> +/* TODO: Find a more elegant wy to give access to initial css variables in reversed. #DS-338 */
donc t'es Ok si je commence à associer les ToDo avec des JIra quand je les rencontre?

2022-04-28 20:52 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
>      argTypes={{
Comme indiqué à l'oral, je le garderais dans un coin de la tete, mais je ne l'appliquerais pas.

2022-04-28 20:52 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/_doc/template.drupal.twig
> +    {% for _hierarchy in hierarchyList %}
Il parle de https://github.com/bifrost-vui/bifrost-front-end-library/pull/236.
Le dernier a merger devra régler les conflits. On peux se faire un appel rapide si necessaire a ce moment la.

2022-04-28 20:53 UTC, bibifrost requested changes
A part les sous-catégorie a retirer, tout est ok pour moi.

2022-05-02 19:01 UTC, ThalieVideotron commented
> A part les sous-catégorie a retirer, tout est ok pour moi.

Done - c'était intense!!!

2022-05-03 22:16 UTC, bibifrost commented
Pour valider le tout, il serait pertinent de recréer un **usage example** d'un form avec un input et un button submit.

2022-05-03 22:45 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +{%  endif %}
```suggestion
{% set isSubmitBtn = isSubmit or formNoValidate or
  (formId is defined and formId) or
  (formAction is defined and formAction) or
  (formEncryptionType is defined and formEncryptionType) or
  (formTarget is defined and formTarget) or
  (formMethod is defined and formMethod)
%}
```

2022-05-03 22:45 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +{%  endif %}
Je remplacerai `isSubmitBtn` par `isSubmitButton` pour éviter les abréviations.
[EDIT] Encore mieux: tu peux tout simplement le remplacer par `isSubmit`.

2022-05-03 22:45 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +{% set autofocus = autofocus|default(false) %}
```suggestion
{% set isAutofocus = isAutofocus|default(false) %}
```

2022-05-03 22:45 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +      {{ autofocus ? 'autofocus' }}
```suggestion
      {{ isAutofocus ? 'autofocus' }}
```

2022-05-03 22:45 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
> +        isAutofocus:{ table: { defaultValue: { summary: false }}},
Au vue de la tres faible compatibilité, je n'offrirai pas l'Autofocus an API:
https://developer.mozilla.org/fr/docs/Web/HTML/Element/Button#compatibilit%C3%A9_des_navigateurs

2022-05-05 15:03 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +{%  endif %}
c'était pour une variable interne mais on devrait y arriver avec isSubmit tout court

2022-05-05 15:05 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +{% set autofocus = autofocus|default(false) %}
disparu. s'il y tiennent il la passeront avec ExtraAttribute
mal supportée par certains browsers/devices

2022-05-05 15:05 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +      {{ autofocus ? 'autofocus' }}
idem

2022-05-05 15:14 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +{% set reversed = reversed|default(false) %}
https://github.com/bifrost-vui/bifrost-front-end-library/pull/304#discussion_r856182019 : c'est pas ce qui est demandé 
je crois que l'objectif est d'augmenter la visibilité des booléen avec des valeurs par défaut - mais ton commentaire fait pas mal de sens 

affecte : le false est setté là où c'est appelé dans le code.
{% set reversed = reversed|default(false) %}
{% set fullWidth = fullWidth|default(false) %}
{% set hasLoading = hasLoading|default(false) %}

2022-05-05 15:47 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +{%  endif %}
> Pour valider le tout, il serait pertinent de recréer un **usage example** d'un form avec un input et un button submit. Mais ça peut etre next version.

il n'y a pas d'input submit on a juste un button submit

2022-05-05 21:53 UTC, bibifrost commented on CHANGELOG.mdx
> +- New arguments are available: `isSubmit`, `isAutofocus`, `id`, `formId`, `formAction`, `formEncryptionType`, `formTarget`, `formMethod` , `formNoValidate`
```suggestion
- New properties to handle submit functionalities on [Twig Component Button](/story/components-button--drupal). `isSubmit`, `isAutofocus`, `id`, `formId`, `formAction`, `formEncryptionType`, `formTarget`, `formMethod` , `formNoValidate`.
```

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
> +            table: { defaultValue: { summary: `null` }},
```suggestion
```
Ne pas documenter de defaut, si c'est null.

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
> +                options: [null, 'placeholder', ...interfaceIcons.map(a => a.list).flat().sort()]
T'as vérifié si ça n'amenait pas de regression dans le select du panneau controls?

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
> +            table: { defaultValue: { summary: `null` }},
```suggestion
```

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
> +// a regular button
```suggestion
// Button
```

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
> +// the link button
```suggestion
// Link
```

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
> +// the submit button
```suggestion
// Submit button
```

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
> +// the isLoading button
```suggestion
//  Loading button
```

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
> +    label           : 'Submit form',
```suggestion
    label           : 'Button label',
```

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
> +<Canvas withSource='none' style={{height: '400px'}}>
```suggestion
<Canvas withSource='none' style={{ height: '400px' }}>
```

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
> +<Canvas withSource='none' style={{height: '700px'}}>
```suggestion
<Canvas withSource='none' style={{ height: '700px' }}>
```

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/scss/index.scss
> +    width: fit-content;
Je garderais le commentaire pour éviter de changer le fit-content sans vérifier ce cas particulier.

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +{# conditions that turns a button into a link #}
Le terme `isLink` me semble assez parlant pour éviter ce commetaire.

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +{# set booleans to false if the are undefined #}
retirer ce commentaire

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +{# conditions that turn a regular button into a submit button #}
Gloablement, les commentaires prennent du temps de lecture obligatoire car on ne sait pas la pertinence de l'information qu'ils contiennent. Attention donc a ne pas en mettre de commentire si c'est évident. 
Tout est dans le bon namming des variables.

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +    {% if dataDismiss|default(null) %}data-dismiss='{{ dataDismiss}}'{% endif %}
```suggestion
    {% if dataDismiss|default(null) %}data-dismiss='{{ dataDismiss }}'{% endif %}
```

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +    {% if ariaLabel is defined and ariaLabel %}aria-label='{{ ariaLabel }}'{% endif %}
```suggestion
    {% if label|default(null) %}data-title='{{ label }}'{% endif %}
    {% if ariaLabel|default(null) %}aria-label='{{ ariaLabel }}'{% endif %}
```

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +    {% if isDisabled %}disabled='disabled' aria-disabled='true' {% endif %}
```suggestion
    {% if isDisabled %}disabled='disabled' aria-disabled='true'{% endif %}
```

2022-05-05 21:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +{% set isLink = href is defined and href is not empty and not isSubmitBtn and not isDisabled %}
```suggestion
{% set isLink = href is defined and href is not empty and not isSubmit and not isDisabled %}
```

2022-05-06 13:11 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
> +                options: [null, 'placeholder', ...interfaceIcons.map(a => a.list).flat().sort()]
ça met un null - j'ai remis la string vide

2022-05-06 13:11 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/scss/index.scss
> +    width: fit-content;
done

2022-05-06 13:12 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +{# conditions that turns a button into a link #}
done - removed all comments

2022-05-06 13:12 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +{# set booleans to false if the are undefined #}
done

2022-05-06 13:12 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +{# conditions that turn a regular button into a submit button #}
le commentaires aident aussi à découper le code - mais je les ai enlevé

2022-05-07 19:53 UTC, JonathanLefebvreV commented
@ThalieVideotron  conflit

2022-05-11 12:13 UTC, bibifrost submitted a review, later dismissed
Tout bon pour moi

2022-11-27 21:21 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
> +        iconSize: { table: {defaultValue: { summary: 'small' }}},
iconSize on a button?

2022-11-27 21:23 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +%}
not sure the use of this `isSubmit` and the programming around it

2022-11-28 08:23 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/button/_doc/doc.stories.mdx
> +        iconSize: { table: {defaultValue: { summary: 'small' }}},
Was since Button-nav exist. The property is set there to use a large icon. 
Has this is an internal property and should not be used in consumption, the documentation is removed.

2022-11-28 08:24 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/button/twig/index.twig
> +%}
let go with it.

2022-11-28 08:24 UTC, JonathanLefebvreV approved these changes

2022-11-28 08:24 UTC, merged