DS-267 input switch
bifrost-vui/bifrost-front-end-library pull request #307
Opened 2022-04-15 12:28 UTC by ThalieVideotron

Input Switch : 

composant bifrostisé
comprends: le input + un label
Si un label est défini, il apparaît à gauche avec option de le positionner à droite. Il est également possible de lui attribuer une classe

comme pour le checkbox et le radio on a la switch + le label qui utilisent la classe bf-input-switch ainsi qu'un classe utilitaire (bf-switch) pour permettre l'utilisation de la switch seule dans un autre contexte

2022-04-17 18:20 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +    {% else %}
```suggestion
      {% set labelPosition = label.position|default(null) %}
    {% else %}
```

2022-04-17 18:21 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-switch/angular/input-switch.component.ts
> +    @Input() id: string;
```suggestion
    constructor() {}

    @Input() id: string;
```

2022-04-17 18:22 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-switch/angular/input-switch.component.ts
> +@Component({
```suggestion
import { Component, ViewEncapsulation, OnInit, Input } from '@angular/core';

@Component({
```

2022-04-17 18:30 UTC, JonathanLefebvreV requested changes
C'est super. Juste quelques ajustements nécessaire

2022-04-17 18:30 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-switch/_doc/template.drupal.twig
> +  <div class='d-flex flex-align-center-space-between gap-4 {{ _background }} flex-wrap p-4'>
One indentation too much all around the file

2022-04-17 18:30 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-switch/_doc/template.drupal.twig
> +      <p class='text-center'> Checked</p>
```suggestion
      <p class='text-center'>Checked</p>
```

2022-04-17 18:30 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-switch/_doc/template.drupal.twig
> +      <p class='text-center'> Disabled</p>
```suggestion
      <p class='text-center'>Disabled</p>
```

2022-04-17 18:30 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-switch/_doc/template.drupal.twig
> +      <p class='text-center'> Disabled + checked</p>
```suggestion
      <p class='text-center'>Disabled + checked</p>
```

2022-04-19 17:03 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +    name='{{ name|default(null)}}'
```suggestion
    name='{{ name|default(null) }}'
```

2022-04-19 17:03 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/_doc/template.drupal.twig
> +    <p class='text-center'> Default</p>
```suggestion
    <p class='text-center'>Default</p>
```

2022-04-19 17:22 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/angular/input-switch.component.ts
> +    @Input() label: string|object;
t'as compris que ce n'est pas le label en gras avec la description? c'est un cas particulier où on a une position + une class mais je crois qu'on a plusieurs endroit où effectivement on avait dit que label devait pouvoir être un objet pour éviter label, labelClass, labelTag.... Si tu crois qu'on peut le faire là, ayons la discussion et faisons-le là.

2022-04-19 17:40 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/angular/input-switch.component.ts
> +    @Input() id: string;
pourquoi? `id` c'est clair et surtout c'est cohérent avec checkbox et radio... inputId est dans les "depricated" dans ces 2 cas et on leur demande d'utiliser `id`.  
je vois qu'on a utilisé `inputId` dans  `Input increment` mais c'est parce qu'il y a plusieurs élément de type controle (les 2 boutons) et qu'il a y une bonne raison de spécifier que c'est l'ID du input et non des boutons.

2022-04-19 17:43 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +    {% endif %}
nice catch. Pour éviter l'imbrication de single et double quotes je te propose celle de aria-label
on garde les ternaire quand aucune imbrication est nécessaire. t'est OK avec ça? ça a l'avantage d'être plus près de ce qui a été fait à date.

2022-04-19 17:46 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/angular/input-switch.component.ts
> +    @Input() name: string;
ben non. pour les même raisons que pour `id` vs `inputId`
on est dans un truc qui s'appelle input_... alors on se doute bien que le name et le id c'est pour un input. on met class, pas InputClass non?

2022-04-19 17:47 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/angular/input-switch.module.ts
> +  exports: [InputSwitchComponent]
tout à fait! d'où il vient ce saut de ligne? il est généré?

2022-04-19 17:49 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +      class='bf-input-switch__label bf-text-display-sub-medium {{ labelPosition is same as ('right') ?'bf-input-switch__label--right' }} {{ label.class|default(null) }}'
pas sur pour le `==`mais j'accepte et je teste ensuite

2022-04-19 18:06 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +      class='bf-input-switch__label bf-text-display-sub-medium {{ labelPosition is same as ('right') ?'bf-input-switch__label--right' }} {{ label.class|default(null) }}'
testé : et finalement c'est ` {{ labelPosition|default(null) == 'right' ?` c'est juste que finalement il n'est pas à droite par défaut. 
c'est probablement un test qui est résté en place et que je n'aurais pas vu à cause du {% set labelPosition = label.position|default(null) %} que j'avais défini dans le else.  thx

2022-04-19 18:33 UTC, ThalieVideotron commented on CHANGELOG.mdx
> +- new [Twig component Input Switch](/story/components-input-switch--drupal-input-switch-with-label-as-string).
ça va casser si je fais ça.  j'ai voulu faire 2 stories mais je vais n'en faire qu'une. c'est l'histoire du label qui peut être une string ou un objet mais je vais documenter que ça peut être une string comme tu a fait dans badge je crois. à ce moment là je n'ai besoin que d'une story et ça règle le problème. On it

2022-04-19 19:00 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/angular/input-switch.component.ts
> +    @Input() label: string|object;
en attendant c'est un objet qui peut accepter une string comme le badge dans dans cards.  ça me permet de ne faire qu'1 story et donc d'avoir une URL standard dans le changelog

2022-04-19 19:01 UTC, ThalieVideotron commented on CHANGELOG.mdx
> +- new [Twig component Input Switch](/story/components-input-switch--drupal-input-switch-with-label-as-string).
ok on a 1 seule story donc on a un lien standardisé - j'ai documenté comme tu l'a fait dans cards pour le badge

2022-04-19 20:11 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/angular/input-switch.component.ts
> +    @Input() name: string;
Je ne comprend pas. Dans `input.inputName`, l'objet `input` n'existe pas. Tu parles de l'objet qui sera passé dans Drupal ? C'est 2 choses différentes:
- Dans le nom `input-switch`, `input` correspond à la famille de composant. Tu peux imaginer que c'est l'equivalent de `form-control`.
- Dans la props `inputId`, on parle bien de l'input HTML.

Dans tous les cas, c'est pour la cohérence de l'API:
- `class` : s'applique au premier div.
- `id`: pourrait exister et appliquerait un `id` au premier div.
- `inputId`: s'applique à l'input
- `inputName`: s'applique à l'input. `name` tout seul, ne permet pas de comprendre qu'on parle du name de l'input.
- `inputClass` : pourrait exister et s'appliquerait à l'input.

2022-04-19 20:11 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +    {% if isChecked is defined and isChecked  %}checked aria-checked='true'{% endif %}
```suggestion
    {% if isChecked is defined and isChecked %}checked aria-checked='true'{% endif %}
```

2022-04-19 20:11 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +    {{ extraAttribute|default(null) }}
Je mettrais extraAttribute en dessous de ariaLabel.

2022-04-19 20:11 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +      for='{{ id }}'
Je ne rendrais pas l'id obligatoire.
```suggestion
      {% if id is defined and id %}for='{{ id }}'{% endif %}
```
et pareil pour le id du input.

2022-04-19 20:11 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/_doc/doc.stories.mdx
> +        id: { type: { required: true }}
L'id devrait-il vraiment etre required?

2022-04-19 20:13 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/angular/input-switch.module.ts
> +  exports: [InputSwitchComponent]
C'était par défaut, dans la generation de composant via le Angular CLI.
Mais on peux tres bien le retirer du template.

2022-04-19 20:14 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/_doc/doc.stories.mdx
> +        name='Drupal - Input Switch with label as string'
C'est problematique mais j'en parle avec JF.

2022-04-19 20:50 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +      for='{{ id }}'
ce qui m'embête c'est qu'il en a besoin pour que le label soit cliquable.  Est-ce qu'on veut permettre que le label ne soit pas cliquable?

2022-04-19 20:51 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/_doc/doc.stories.mdx
> +        id: { type: { required: true }}
re :  Est-ce qu'on veut permettre que le label ne soit pas cliquable?

2022-04-19 21:12 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +      for='{{ id }}'
Si le consommateur ne met pas d'id alors le label n'est pas cliquable. Ça me semble correct. 
En pratique, je dirais que Bifrost conseil d'avoir un id mais ne l'oblige pas. Car dans tous les cas, si l'id n'est pas renseigné alors le composant s'affiche quand même.

2022-04-19 23:29 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-switch/angular/input-switch.component.ts
> +    @Input() id: string;
Notre notion de [tag-definition][Property name] est pour quand il y a une propriété multiple dans le composant sur le même nom. 
(example relativement fictif très présent dans le UIKIT)
- class : qui est le `class` du premier tag qui utilise l'attribut.
- lableClass : est le ``class` attribute d'un tag `label` dans le composant d'une 2e utilisation

Ce qui est important ici c'Est le nombre d'utilisation et la séquence d'utilisation.
Ici, il y a juste 1 utilisation, c'est pas important de mettre [tagDefinition]

2022-04-19 23:48 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-switch/angular/input-switch.component.ts
> +    @Input() name: string;
Je crois que Nath parle de `input.inputName` en pensant à  la référence d'un futur parent  component qui aura le `inputSwitch` comme composition. (ex: a banner-advance, row-item, etc)

Ce qui ce traduira par un objet et donc des déclaration possible comme `inputSwtich.something`.

Anyway, notre nomenclature est si il y a une répétion. Ce qui n'est pas le cas de `id` et `name`.

Je rappel que si on fait une règle, on la fait pour toute les propriété.
Et, nous ne fesons pas par défaut. Donc pas de raison de le faire pour les "input" (KISS - keep it simple and stupid).
Example sinon de ce que ca donnerai partout :  buttonDataTrigger, buttonIconName, inputValue, inputIsDisabled, buttonExtraAttribute.  Je ne verrais aucune valeur avec plus d'effort de faire cela comme ça.

Pour finir sur le sujet de : que `id` soit un jour sur div. C'est probable si on jour si les "sélecteur e2e" seront nécessaire, mais on parlera plus de "extra-attribute" à mon avis pour rester agnostique des technos.

Donc dans notre contexte actuel, avec les informations que nous avons pour resté dans le 80/20 - YAGNI (you ain't gonna need it)

2022-04-19 23:55 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +      for='{{ id }}'
Répondu plus haut:

2022-04-19 23:56 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +    {{ extraAttribute|default(null) }}
Ca fait du sens de toujours finir avec "extraAttribute. Le uikit fesait ça et ca simplifie la lecture à mon avis.
@ThalieVideotron , commentaire valide à fixé

2022-04-20 00:03 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-switch/angular/input-switch.component.ts
> +    @Input() label: string|object;
Rappel de procédure de discussion:
Faite un Jira sur les sujet que vous voulez parler. On prends 10 min au Weekly quand on fait le tour des Jira créer dans la semaine précédente. Si on en défini un besoin, on priorise et redéfini le besoin. Si ca prends plus que 10 min, on en parle dans un autre meeting (si on a d'autre chose à jaser au weekly)

Perso: je me rappel pas qu'on ai un autre objet "label" quelque part. De ce point de vue, celui de Nath sers à définir la norme. Mais peut être qu'on parle de la propriété "position" qui a été utilisé ailleur. 

Anyway C'est un autre discussion en dehors de la PR.

2022-04-20 00:08 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-switch/_doc/doc.stories.mdx
> +        name='Drupal - Input Switch with label as string'
Nathalie a clairement expliqué la situation actuel.

L'image que tu montres Batiste a évolué en besoin UI et tant qu'elle n'est pas officiellement à développé, ça reste du nuage.

Donc, effectivement, le Figma n'est pas 100% à jour. Je le confirme

2022-04-20 12:31 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +    {{ extraAttribute|default(null) }}
oui effectivement et done

2022-04-21 12:44 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/angular/input-switch.component.ts
> +    @Input() label: string|object;
on s'en jase mais la solution proposée ici fonctionne tres bien.

2022-04-21 12:47 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/_doc/doc.stories.mdx
> +        id: { type: { required: true }}
Ok pour moi

2022-04-21 19:13 UTC, baptistemac commented
il y a un bug sur safari iOS
![image](https://user-images.githubusercontent.com/845412/164536015-f28d1647-cf87-42f4-80f6-13fd4f027e4b.png)

2022-04-21 19:16 UTC, bibifrost commented
Il y a un bug sur Safari iOS
![image](https://user-images.githubusercontent.com/93746960/164536463-4b0d3743-4774-4782-9c43-43d7cf5cf3fb.png)

2022-04-21 19:17 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +      for='{{ id }}'
ok pour moi

2022-04-21 20:23 UTC, ThalieVideotron commented
> Il y a un bug sur Safari iOS ![image](https://user-images.githubusercontent.com/93746960/164536463-4b0d3743-4774-4782-9c43-43d7cf5cf3fb.png)

@bibifrost. Safari c'est le Nouveau IE, tu peux pas t'en débarrasser et chaque version a ses glitches. T'es sur un iPhone ou un desktop en émulation du mobile?  Quelle version ?
je n'arrive pas à le reproduire.  ci-dessous vu sur mon Ipad Mini (IOS 15.4.1. )
![switch-Safari-Ipad-15-4-1](https://user-images.githubusercontent.com/82388009/164545519-78319444-e629-47cf-8013-fd093a8e2406.PNG)

2022-04-21 23:08 UTC, bibifrost commented
> > Il y a un bug sur Safari iOS ![image](https://user-images.githubusercontent.com/93746960/164536463-4b0d3743-4774-4782-9c43-43d7cf5cf3fb.png)
> 
> @bibifrost. Safari c'est le Nouveau IE, tu peux pas t'en débarrasser et chaque version a ses glitches. T'es sur un iPhone ou un desktop en émulation du mobile?  Quelle version ?
> je n'arrive pas à le reproduire.  ci-dessous vu sur mon Ipad Mini (IOS 15.4.1. )
> ![switch-Safari-Ipad-15-4-1](https://user-images.githubusercontent.com/82388009/164545519-78319444-e629-47cf-8013-fd093a8e2406.PNG)
> 
> 

Je suis sur un vrai iPhone XR iOS 14. Browser safari.

2022-04-22 12:23 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +      for='{{ id }}'
le validateur m'indique que Name est obligatoire. Id ne l'est plus vu la structure HTML modifiée

2022-04-22 13:27 UTC, ThalieVideotron commented
![switch-safari12-5-5-ipodTouch](https://user-images.githubusercontent.com/82388009/164723467-5938c33a-5e2e-4959-883f-0c8054740dbf.jpg)
safari 12.5.5 sur mon vieux iPod

2022-04-22 14:21 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +  for='{{ id|default(null) }}'
Ca n'avais pas à changer. Vous avez signaler en commentaire que vous étiez d'accord à avoir l'id required. Pourquoi ça change au travers d'un commit qui fix le rendu Safari?

2022-04-23 19:47 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +  for='{{ id|default(null) }}'
name est obligatoire mais pas id quand le label est autour du input. par contre ce n'est pas fixé comme il faut

2022-04-23 22:16 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +  for='{{ id|default(null) }}'
Le id|default permet d'éviter une erreur twig en strict-variable dans le cas où id n'est pas passée. 

Ceci pose une question que je me pose depuis longtemps : quel rendu veux on quand une props required n'est pas passée?

- une error dans la console? ( Le cas de la plupart des framework js)
- Un affichage avec un message d'erreur dans le twig?
- aucun message?

2022-04-24 12:27 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +  for='{{ id|default(null) }}'
@bibifrost bonne question.  Pour le moment seul storybook sait que c'est required et nous on passe une valeur donc j'ai aucune idée de ce qui se passe quand on ne passe pas de valeur et encore moins une fois que le template est utilisé dans drupal... je suppose donc que c'est twig qui devrait faire quelque chose... définitivement à discuter

2022-04-25 12:01 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +  for='{{ id|default(null) }}'
finalement définir le type required dans le MDX ne fait qu'afficher un `*` à côté du nom du champs dans la liste des contrôles storybook. aucune erreur en console.  même Storybook ne le renforce pas

2022-04-25 13:33 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/scss/index.scss
> +    // TODO : DS-174 - focus-visible style
DS-174 n'est pas mergée mais j'ai récupéré le style du focus-visible pcq le span n'est pas un élément qui reçoit naturellement le focus et on risque de l'oublier.  documenté en TODO pour qu'on vérifie que ce code est toujours valide quand on mergera la DS-174

2022-04-27 09:44 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/_doc/doc.stories.mdx
> +>
```suggestion
<Canvas withSource='none' style={{ height: '400px' }}>
```

2022-04-27 09:44 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/scss/index.scss
> +        top: -100vh
```suggestion
        top: -100vh;
```

2022-04-27 09:44 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/scss/index.scss
> +        margin-right: var(--bf-spacer-3);
```suggestion
        margin-block: var(--bf-spacer-2);
        margin-right: var(--bf-spacer-3);
        cursor: pointer;
        line-height: 1em;
```

mais le mieux reste d'appliquer les classes `my-2 mr-3` sur le label.

2022-04-28 12:30 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +  for='{{ id|default(null) }}'
Storybook ne peux pas le renforcer, ce n'est pas vraiment son role.
Si la notion de **props required** n'est pas visible dans l'admin Drupal, alors les cas d'oubli seront inévitables et l'intégrateur n'aura pas les moyen de comprendre pourquoi ça marche pas comme prévu. A moins de le rediriger vers la doc Storybook, mais rendu la, c'est dommage.

2022-04-28 18:07 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/angular/input-switch.component.ts
> +    @Input() id: string;
@bibifrost  faire resolve

2022-04-28 18:08 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-switch/angular/input-switch.component.ts
> +    @Input() name: string;
@bibifrost faire resolve

2022-04-28 20:41 UTC, bibifrost commented
Le bug Safari est réglé. GG @ThalieVideotron !

2022-05-02 17:24 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +  for='{{ id|default(null) }}'
Je pense que oui :) On le reprendra dans un autre ticket si necessaire.

2022-05-04 23:22 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-switch/twig/index.twig
> +  for='{{ id|default(null) }}'
Oui, sujet hors scope à mettre dans un Jira si vous voulez en reparler

2022-05-04 23:27 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-switch/_doc/doc.stories.mdx
> +        allowFullScreen></iframe>
```suggestion
<iframe width='100%' height='450' src='https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2F7bTmk29aCBl7rCFszffYPr%2FDS---Components-%2526-styles%3Fnode-id%3D13846%253A114546' frameBorder='0' allowFullScreen></iframe>
```

2022-05-04 23:30 UTC, JonathanLefebvreV approved these changes
Tested on most concerned Safari version.

2022-05-04 23:30 UTC, merged