Ds 310 footer in banner
bifrost-vui/bifrost-front-end-library pull request #308
Opened 2022-04-15 17:46 UTC by ThalieVideotron

DRAFT

2022-04-15 17:55 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/angular/banner-advanced.component.ts
> +    @Input() inputSwitch: ISwitch;
je ne peux pas faire `@Input() switch: ISwitch;`
switch est un mot réservé (comme class)
Ouverte aux suggestions

2022-05-05 18:08 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/banner-advanced/angular/banner-advanced.component.ts
> +    @Input() inputSwitch: ISwitch;
Le nom de la classe devrait être InputSwitch

2022-05-05 18:14 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-switch/angular/api.model.ts
> +export interface ISwitch {
rename `IInputSwitch`

2022-05-05 18:19 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/angular/banner-advanced.component.ts
> +    @Input() inputSwitch: ISwitch;
tellement préoccupée par le nom de la variable que je me suis planté sur le nom de la classe.... désolée.

2022-05-05 18:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/angular/banner-advanced.component.ts
> +import {HTMLElement} from '@webcomponents/custom-elements/src/Patch/Native';
remove this line

2022-05-05 18:22 UTC, bibifrost commented on CHANGELOG.mdx
> +- Made the `inputSwitch` option available on [Banner Advanded twig component](/story/components-banner-advanced--drupal).
```suggestion
- New property `footer` in order to add Twig Block on [Twig Component Banner Advanced](/story/components-banner-advanced--drupal).
- New property `inputSwitch` on [Twig Component Banner Advanced](/story/components-banner-advanced--drupal).
```

2022-05-05 18:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/_doc/doc.stories.mdx
> +<Canvas withSource='none' style={{height: '600px'}} >
```suggestion
<Canvas withSource='none' style={{ height: '600px'}}>
```

2022-05-05 18:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/_doc/doc.stories.mdx
> +                ariaLabel: 'I\'m already an Helix client',
```suggestion
                ariaLabel: `I'm already an Helix client`,
```

2022-05-05 18:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/_doc/doc.stories.mdx
> +                    text: 'I\'m an Helix client',
```suggestion
                    text: `I'm an Helix client`,
```

2022-05-05 18:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/angular/banner-advanced.component.ts
> +import { ISwitch } from '../../input-switch/angular/api.model';
renommer ISwitch en IInputSwitch

2022-05-05 18:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/scss/index.scss
> +    &__inner{
```suggestion
    &__inner {
```

2022-05-05 18:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +  <div class='bf-banner-advanced__inner flex-column flex-md-row gap-3 gap-sm-4  p-3 p-sm-4 '>
```suggestion
  <div class='bf-banner-advanced__inner flex-column flex-md-row gap-3 gap-sm-4 p-3 p-sm-4'>
```

2022-05-05 18:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +            {# conditional plus sign between Icons #}
Pas sur que ce soit pertinent de préciser. Car si on suit cette logique, on décrirait tout le UI.

2022-05-05 18:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +  {% set hasFooter = (block('footer') is defined or (footer is defined and footer) or (inputSwitch is defined and inputSwitch)) ? true : false %}
```suggestion
  {% set hasFooter = (block('footer') is defined or (footer is defined and footer) or (inputSwitch is defined and inputSwitch)) %}
```

2022-05-05 18:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +  <div class='bf-banner-advanced__footer p-3 p-sm-4 pt-0 border-top'>
indent

2022-05-05 18:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +      {% include '@bf-components/input-switch/twig/index.twig' with inputSwitch %}
```suggestion
      {% include '@bf-components/input-switch/twig/index.twig' with inputSwitch only %}
```

2022-05-05 18:27 UTC, JonathanLefebvreV requested changes
Il y a un margin-bottom de 8 sous la switch qui casse l'exactitude du center du footer
![image](https://user-images.githubusercontent.com/75901368/166991829-b636bcfe-6269-4b47-b9c2-14db24ff5f65.png)

Soit enlever le 8px ou s'assurer que le padding bottom inclus de 8 px

2022-05-05 18:27 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +            {# conditional plus sign between Icons #}
moi ça m'ai à le retrouver

2022-05-05 18:27 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/angular/banner-advanced.component.ts
> +import { ISwitch } from '../../input-switch/angular/api.model';
done

2022-05-05 18:32 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +      {% include '@bf-components/input-switch/twig/index.twig' with inputSwitch %}
ici c'est dire 'met seulement tout' non?
comme ça ne change rien...

2022-05-05 18:33 UTC, JonathanLefebvreV requested changes

2022-05-05 18:33 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/banner-advanced/angular/banner-advanced.component.ts
> +    @Input() inputSwitch: IInputSwitch;
honnetement cette solution pour moi est pauvre...
Le inputSwitch doit faire parti du footer. Il n'est pas un élément de même niveau.

En plus, footer ne semble pas marché
![image](https://user-images.githubusercontent.com/75901368/166995392-fd5f79e5-9c5e-4c92-bc75-2fc3d2aab9ee.png)

2022-05-05 18:36 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/angular/banner-advanced.component.ts
> +    @Input() inputSwitch: IInputSwitch;
j'ai dû oublié le json_parse

2022-05-05 19:27 UTC, bibifrost commented
Je ne comprend pas la presence de switch dans l'API de ce composant.
On devrait présenter un **usage exemple** de footer block avec une switch.
Car si demain il y a un autre input au footer, on ne va pas ajouter une property à l'API...

2022-05-05 19:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +            {# conditional plus sign between Icons #}
retrouver quoi? le code qui affcihe le + ?
Le `{% include '@bf-components/icon/twig/index.twig' with { name: 'plus', ...` me semble suffisant, non?

2022-05-05 19:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/_doc/doc.stories.mdx
> +            text: 'I\'m an Helix client',
```suggestion
            text: `I'm an Helix client`,
```

2022-05-05 19:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/_doc/doc.stories.mdx
> +        ariaLabel: 'I\'m already an Helix client',
```suggestion
        ariaLabel: `I'm already an Helix client`,
```

2022-05-05 19:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/_doc/template.drupal.twig
> +        label: icons[0].label|default('Mobile plan')
Ces valeurs par défaut devrait se retrouver dans Storybook.
Dans l'ideal le template n'affecte pas les props.

2022-05-05 19:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +  {% set hasFooter = (block('footer') is defined or (footer is defined and footer) or (inputSwitch is defined and inputSwitch)) %}
```suggestion
  {% set hasFooter = block('footer') is defined or (footer is defined and footer) or (inputSwitch is defined and inputSwitch) %}
```

2022-05-05 19:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-switch/angular/api.model.ts
> +    label: string|object;
```suggestion
    label: string | object;
```

2022-05-05 19:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/_doc/doc.stories.mdx
> +<Canvas withSource='none' style={{ height: '600px'}}>
```suggestion
<Canvas withSource='none' style={{ height: '600px' }}>
```

2022-05-05 19:36 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/_doc/doc.stories.mdx
> +<Canvas withSource='none' style={{height: '450px'}} >
```suggestion
<Canvas withSource='none' style={{ height: '450px'}}>
```

2022-05-06 12:23 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/angular/banner-advanced.component.ts
> +import { ISwitch } from '../../input-switch/angular/api.model';
mais on n'importe plus

2022-05-06 12:24 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +            {# conditional plus sign between Icons #}
je préférais le commentaire - mais je l'ai enlevé

2022-05-06 12:25 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/angular/banner-advanced.component.ts
> +    @Input() inputSwitch: IInputSwitch;
réparé - ajouté une story

2022-05-06 12:26 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/_doc/template.drupal.twig
> +        label: icons[0].label|default('Mobile plan')
j'avais laissé comme tu l'avais fait - mais done.

2022-05-06 12:58 UTC, bibifrost requested changes

2022-05-06 12:58 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/_doc/doc.stories.mdx
> +        name='Drupal - with HTMLElement in footer'
```suggestion
        name='Drupal - With custom footer'
```

2022-05-06 12:58 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/_doc/doc.stories.mdx
> +        name='Drupal - with inputSwitch in footer'
```suggestion
        name='Drupal - With inputSwitch in footer'
```

2022-05-06 12:58 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +      {% else  %}
```suggestion
      {% elseif footer is defined and footer is iterable and footer is not empty %}
```

2022-05-06 12:58 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +      {% elseif footer is iterable and footer.inputSwitch is defined and footer.inputSwitch is not empty %}
```suggestion
      {% elseif footer is defined and footer is iterable and footer.inputSwitch is defined and footer.inputSwitch is not empty %}
```

2022-05-06 12:58 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +      {% elseif footer is iterable and footer.inputSwitch is defined and footer.inputSwitch is not empty %}
Un peu bizarre ce if.
pourquoi ne pas faire:
```
if block(footer)
   block
elseif footer
    if footer.inputSwitch
        inputSwich
    else
        footer
```

2022-05-06 12:58 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/_doc/template.drupal.twig
>    {% include '@bf-components/banner-advanced/twig/index.twig'  %}
```suggestion
  {% include '@bf-components/banner-advanced/twig/index.twig' %}
```

2022-05-06 13:01 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/banner-advanced/_doc/doc.stories.mdx
> +        name='Drupal - with HTMLElement in footer'
html Element is fine

2022-05-06 13:04 UTC, bibifrost requested changes

2022-05-06 13:04 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +    {% if icons is defined and icons %}
```suggestion
    {% if icons is defined and icons is not empty %}
```

2022-05-06 13:04 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +<div class='bf-banner-advanced {{ class|default('') }}'>
```suggestion
<article class='bf-banner-advanced {{ class|default('') }}'>
```
puis `</article>`

Si tu as un header, il te faut un conteneur semantique.

2022-05-06 13:39 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +      {% elseif footer is iterable and footer.inputSwitch is defined and footer.inputSwitch is not empty %}
non pas come ça - mais il y a un glitch de condition.

2022-05-06 13:40 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +      {% elseif footer is iterable and footer.inputSwitch is defined and footer.inputSwitch is not empty %}
c'est ce que je disais... j'ai copié collé trop vide

2022-05-06 13:53 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/angular/banner-advanced.component.ts
> +    /** See [Input Switch](/?path=/story/components-input-switch--drupal) */
```suggestion
```

2022-05-06 13:58 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +      {% elseif footer is iterable and footer.inputSwitch is defined and footer.inputSwitch is not empty %}
vous préférez qu'on duplique le div - possible aussi  - laissesz-moi savoir

2022-05-06 16:14 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +      {% elseif footer is iterable and footer.inputSwitch is defined and footer.inputSwitch is not empty %}
?
Pas besoin de dupliquer le div.
```
if footer
   <div class='footer'>
      if block(footer)
         block
      elseif footer
          if footer.inputSwitch
              inputSwich
          else
              footer
   </div>
endif
```

2022-05-06 16:15 UTC, bibifrost requested changes
Juste le cmmentaire sur la condition et c'est ok pour moi

2022-05-06 17:00 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +      {% elseif footer is iterable and footer.inputSwitch is defined and footer.inputSwitch is not empty %}
- ahhh. c'est plus tordu que 
```
 if footer
   <div class='footer'>
      if block(footer)
         block
      else if footer.inputSwitch
              inputSwich
       else
              footer
       endif
   </div>
endif
```

2022-05-06 17:13 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +      {% elseif footer is iterable and footer.inputSwitch is defined and footer.inputSwitch is not empty %}
C'est pour t'éviter de valider 2 fois `footer is defined and is iterate`.
C'est donc plus simple à lire/maintenir mais comme tu veux.
C'est un details. On verra ça plus tard.

2022-05-06 17:13 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +  {% if footer is defined and footer %}
Jusqu'a présent je considérais que cette condition ne passait pas si footer est un twigBlock mais je me trompe peut-etre.
Il faudrait tester sur Drupal Showcase.
Ou next version.

2022-05-06 17:22 UTC, bibifrost commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +  {% if footer is defined and footer %}
```suggestion
  {% if block('footer') is defined or (footer is defined and footer is not empty) %}
```

2022-05-06 18:50 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +  {% if footer is defined and footer %}
done

2022-05-06 18:52 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/banner-advanced/twig/index.twig
> +  {% if footer is defined and footer %}
oui mais on met `{% if block('footer') is defined or (footer is defined and footer is not empty) %}`  tel que suggéré
next version c'est les block et des vrai embed ;-)

2022-05-07 18:50 UTC, JonathanLefebvreV approved these changes

2022-05-07 18:50 UTC, merged