ds-337 fix Footer border color
bifrost-vui/bifrost-front-end-library pull request #309
Opened 2022-04-18 15:34 UTC by bibifrost

2022-04-28 18:04 UTC, ThalieVideotron submitted a review, later dismissed
Tout est ok pour moi.

2022-05-05 01:13 UTC, JonathanLefebvreV requested changes
manque le changelog,

2022-05-05 13:47 UTC, bibifrost commented
> manque le changelog,

Je ne l'avait pas ajouté volontairement car c'est un ajustement visuel très mineure.
Qu'en penses-tu?

2022-05-06 18:56 UTC, ThalieVideotron reviewed
Go pour moi

2022-05-07 20:29 UTC, JonathanLefebvreV commented
> > manque le changelog,
> Je ne l'avait pas ajouté volontairement car c'est un ajustement visuel très mineure. Qu'en penses-tu?

Tous changement visuel doit être réflété dans le Changelog - car les QA de DXP (si il le voit, vont identifié le changement et faire un bloqueur sur l'intégration du package - ce qui génère un meeting - et il y a pas de lien dans le changelog pour leur monttré que c'est "expected".

2022-05-08 11:29 UTC, bibifrost commented
> > > manque le changelog,
> > > Je ne l'avait pas ajouté volontairement car c'est un ajustement visuel très mineure. Qu'en penses-tu?
> 
> Tous changement visuel doit être réflété dans le Changelog - car les QA de DXP (si il le voit, vont identifié le changement et faire un bloqueur sur l'intégration du package - ce qui génère un meeting - et il y a pas de lien dans le changelog pour leur monttré que c'est "expected".

Done

2022-05-09 23:01 UTC, JonathanLefebvreV approved these changes

2022-05-09 23:01 UTC, merged