ds-342 improve global documentation
bifrost-vui/bifrost-front-end-library pull request #311
Opened 2022-04-21 21:15 UTC by bibifrost

2022-04-26 14:48 UTC, ThalieVideotron commented on browserslist
> +not IE 11
IE All versions?

2022-04-26 15:07 UTC, ThalieVideotron requested changes

2022-04-27 07:35 UTC, bibifrost commented
@ThalieVideotron 
Il faut absolument commit le package-lock.

2022-06-12 13:42 UTC, JonathanLefebvreV approved these changes

2022-06-12 13:46 UTC, merged