DS-307 - underline tertiary button
bifrost-vui/bifrost-front-end-library pull request #314
Opened 2022-04-25 13:01 UTC by ThalieVideotron

Added underline style for tertiary buttons
Made sure the hover state still is underlined
https://bifrost-front-end-library-git-ds-307-underli-6a22b8-bifrost-vui.vercel.app/?path=/story/components-button--drupal

2022-04-25 13:09 UTC, bibifrost commented
> Intervention minimale pour faciliter les backmerges (plusieures branches en cours sur les boutons)
> 
> pas touché au codestyle en place (sera récupéré au backmerge) ajout du underline et l'option pour supprimer le padding pour les boutons tertiaires seulement (mimic du lien primary)

Je ne comprends pas l'interet et j'ai peur qu'on ajoute de la complexité.
Aussi, ça me semble dangereux d'offrir une props comme hasNoPadding uniquement pour tertiary.

2022-04-27 07:30 UTC, bibifrost commented
> > > Intervention minimale pour faciliter les backmerges (plusieures branches en cours sur les boutons)
> > > pas touché au codestyle en place (sera récupéré au backmerge) ajout du underline et l'option pour supprimer le padding pour les boutons tertiaires seulement (mimic du lien primary)
> > 
> > 
> > Je ne comprends pas l'interet et j'ai peur qu'on ajoute de la complexité. As-tu des Figma qui expliqurait? Aussi, ça me semble dangereux d'offrir une props comme hasNoPadding uniquement pour tertiary.
> 
> je ne me souviens plus des détails mais c'était un problème d'alignement quand le bouton tertiaire était utilisé comme lien. On remettait aussi en question l'existence de bf-link mais je crois qu'on avait convenu de le conserver.

Ce genre de décision me fait un peu peur, car on risque de créer des difficultés a maintenir le system. Il faudrait repartir du besoin avec des jira à l'appui. Je pressent que la solution n'est pas de modifier les button.

2022-04-27 17:58 UTC, ThalieVideotron commented
> > > > Intervention minimale pour faciliter les backmerges (plusieures branches en cours sur les boutons)
> > > > pas touché au codestyle en place (sera récupéré au backmerge) ajout du underline et l'option pour supprimer le padding pour les boutons tertiaires seulement (mimic du lien primary)
> > > 
> > > 
> > > Je ne comprends pas l'interet et j'ai peur qu'on ajoute de la complexité. As-tu des Figma qui expliqurait? Aussi, ça me semble dangereux d'offrir une props comme hasNoPadding uniquement pour tertiary.
> > 
> > 
> > je ne me souviens plus des détails mais c'était un problème d'alignement quand le bouton tertiaire était utilisé comme lien. On remettait aussi en question l'existence de bf-link mais je crois qu'on avait convenu de le conserver.
> 
> Ce genre de décision me fait un peu peur, car on risque de créer des difficultés a maintenir le system. Il faudrait repartir du besoin avec des jira à l'appui. Je pressent que la solution n'est pas de modifier les button.

ex très concret : dans le hero des intégrateurs voulaient mettre un bouton tertiaire dans l'array de bouton et ça crée un gap avec le texte

2022-04-27 21:11 UTC, bibifrost commented
> > > > > Intervention minimale pour faciliter les backmerges (plusieures branches en cours sur les boutons)
> > > > > pas touché au codestyle en place (sera récupéré au backmerge) ajout du underline et l'option pour supprimer le padding pour les boutons tertiaires seulement (mimic du lien primary)
> > > > 
> > > > 
> > > > Je ne comprends pas l'interet et j'ai peur qu'on ajoute de la complexité. As-tu des Figma qui expliqurait? Aussi, ça me semble dangereux d'offrir une props comme hasNoPadding uniquement pour tertiary.
> > > 
> > > 
> > > je ne me souviens plus des détails mais c'était un problème d'alignement quand le bouton tertiaire était utilisé comme lien. On remettait aussi en question l'existence de bf-link mais je crois qu'on avait convenu de le conserver.
> > 
> > Ce genre de décision me fait un peu peur, car on risque de créer des difficultés a maintenir le system. Il faudrait repartir du besoin avec des jira à l'appui. Je pressent que la solution n'est pas de modifier les button.
> 
> ex très concret : dans le hero des intégrateurs voulaient mettre un bouton tertiaire dans l'array de bouton et ça crée un gap avec le texte.  il y a probablement un jira DXP ou ailleurs puisque Jean-François a remonté le problème. 

Mais le bouton sera alors plus petit que le bouton d'a côté? La solution est d'utiliser un lien ou un bouton secondary.
Le bouton tertiary est a privilégier a coté d'un primary ou secondary.

2022-05-05 20:49 UTC, bibifrost requested changes
le underline est ok pour moi.
Mais le noPadding est problematique. Il faudrait repartir du besoin et de la solution UI.

2022-05-07 20:25 UTC, JonathanLefebvreV requested changes
Faire le changelog

2022-05-07 20:25 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/button/angular/button.component.ts
> +    @Input() hasNoPadding   : boolean;
Je confirme que ceci, n'est pas un besoin UI.
Ça été une discussion entre moi et JF quand on parlait du besoin.
Je parlait que tant qu'a avoir un bouton tertiaire qui allait avoir le même look qu'un Link Primary ont devrait juste avoir 1 composant bouton qui fait tout, dont enlevé le padding.
Ce que bootstrap avait gérer avec le size du bouton.

Je ne peut pas dire que que JF a compris et pourquoi il est allez mettre ca dans le Jira, mais le noPadding c'est invalide.

Je confirmeIl y a aucun besoin UI relié à cela. L'example de mettre un tercery dans un Hero, ne suis pas les règle du Language Visuel.

Donc option à retirer

2022-05-07 20:25 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/button/scss/index.scss
> +        text-decoration-color: var(--bf-color-stroke-secondary);
C'est pas la bonne couleur. CA doit être comme un underline de Link.
C'est à dire couleur text primary

Testé que l'effet "hover" continu d'affiché le underscore

2022-05-10 15:35 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/button/scss/index.scss
> +        text-decoration-color: var(--bf-color-stroke-secondary);
La couleur du underline n'est pas accessible dans le figma (et le color picker ne voit pas la ligne) donc valider la couleur utilisée : bf-color-stroke-primary (le text primary est noir et ça flash ben plus que dans le figma)  

j'ai dû  l'affichage du underline au hover (sinon il disparaît quelque soit la couleur)

2022-05-22 18:14 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/button/scss/index.scss
> +        text-decoration-color: var(--bf-color-stroke-primary);
```suggestion
        text-decoration: underline;
```

2022-05-22 18:15 UTC, JonathanLefebvreV approved these changes

2022-05-22 18:15 UTC, merged