Ds 347 fix link hover style on highlight
bifrost-vui/bifrost-front-end-library pull request #315
Opened 2022-04-25 17:09 UTC by bibifrost

2022-04-26 19:44 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/link/_doc/doc.stories.mdx
>          height='600px'
SVP ajouter le lien vers le figma : https://www.figma.com/file/7bTmk29aCBl7rCFszffYPr/DS---Components-%26-styles?node-id=9196%3A0

2022-04-26 19:44 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/scss/themes/videotron/_color.scss
> +    & .highlight .reversed {
à votre avis: 
dans figma : 
![image](https://user-images.githubusercontent.com/82388009/165376785-8efe5948-2640-41b8-95ce-550d5069301e.png)
dans la PR il manque le underline et on a un background qui lui donne pratiquement plus d'importance qu'un lien ordinaire 
![image](https://user-images.githubusercontent.com/82388009/165376947-37bd095d-6e49-4bcf-a334-571d45624bd9.png)

out of scope mais on en fait un JIra pour la _next version_?

2022-04-28 21:04 UTC, bibifrost commented on projects/front-end-library/src/lib/components/link/_doc/template.drupal.twig
> +
Oui mais a faire dans un autre JIRA, car ça va venir avec quelques discussions et il nous faudra le penser globalement.

2022-04-28 21:04 UTC, bibifrost commented on projects/front-end-library/src/lib/components/link/_doc/template-css-only.drupal.twig
>  {% set reversed     = reversed|json_parse %}
On veux vraiment le faire dans toutes les PR? Ça créer beaucoup de pollution visuelle. Le mieux serait de le faire one shot.

2022-04-28 21:04 UTC, bibifrost commented on projects/front-end-library/src/lib/components/link/_doc/doc.stories.mdx
> +import { withDesign }                           from 'storybook-addon-designs'
On veux vraiment le faire dans toutes les PR? Ça créer beaucoup de pollution visuelle. Le mieux serait de le faire one shot.

2022-05-05 12:22 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/link/_doc/doc.stories.mdx
> +import { withDesign }                           from 'storybook-addon-designs'
Oui se serait mieux. Mais tant qu'elle est pas fait. C'est ok de faire les alignement dans les fichiers au "vieux format"
Et si vous voulez faire le "nouveau format" quand vous ouvrez des fichier, je n'ai rien contre. 
C'est polluant, mais c'est un moment à passer

2022-05-05 12:35 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/link/_doc/template.drupal.twig
> +
Invalide pour cette PR. resolved

2022-05-05 12:36 UTC, JonathanLefebvreV commented
@bibifrost conflit to solved

2022-05-05 18:04 UTC, bibifrost commented
> @bibifrost conflict to solved

Done

2022-05-05 19:17 UTC, JonathanLefebvreV requested changes

2022-05-05 19:17 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/link/_doc/doc.stories.mdx
> -        parameters={{ options: { showPanel: false } }}
T'as perdu le "showPanel false" dans ton back-merge

2022-05-05 19:17 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/link/_doc/doc.stories.mdx
> -        parameters={{ options: { showPanel: false } }}
T'as perdu le "showPanel false" dans ton back-merge

2022-05-05 19:53 UTC, bibifrost commented on projects/front-end-library/src/lib/components/link/_doc/doc.stories.mdx
> -        parameters={{ options: { showPanel: false } }}
C'est volontaire. J'en au besoin pour m'assurer que tout est correct sur ces stories.

2022-05-07 23:54 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/link/_doc/doc.stories.mdx
> -        parameters={{ options: { showPanel: false } }}
L'utilisateur a la story pour jouer avec et faire les tests nécessaire. 
On a standardisé que les example non pas de panneau par défaut dans https://videotron-design-system.atlassian.net/browse/DS-285

2022-11-26 17:26 UTC, JonathanLefebvreV approved these changes

2022-11-26 17:29 UTC, merged