DS-285 - hide control panel in example stories
bifrost-vui/bifrost-front-end-library pull request #317
Opened 2022-04-26 13:13 UTC by ThalieVideotron

Composants/sections qui ont des stories qui n'affichent plus le control panel Storybook: 

Components : 
- block-highlight
- breadcrumb
- button
- button-nav
- carousel
- link
- selection-tile
- tile

Sections : 
- tiles-post

2022-04-27 06:32 UTC, bibifrost commented on CHANGELOG.mdx
> +
```suggestion
### Documentation
- Storybook: Hide by default the Control Panel on *Example* stories.

```

2022-04-27 06:32 UTC, bibifrost commented on .storybook/preview.ts
> +        showPanel: true
C'est pas true par défaut?

2022-04-27 06:32 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/_doc/doc.stories.mdx
>          name='Example - Selection Color'
```suggestion
        name='Drupal - Example Selection Color'
```

2022-05-05 01:05 UTC, JonathanLefebvreV requested changes

2022-05-05 03:02 UTC, ThalieVideotron commented on .storybook/preview.ts
> +        showPanel: true
oui mais si je veux pouvoir le cacher dans les stories il faut que ça soit explicite dans le preview.ts.

2022-05-05 12:17 UTC, JonathanLefebvreV approved these changes

2022-05-05 12:18 UTC, merged