DS-340 - increment on Safari
bifrost-vui/bifrost-front-end-library pull request #318
Opened 2022-04-27 14:37 UTC by ThalieVideotron

draft

2022-05-02 17:20 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-increment/scss/index.scss
> +    &__feedback{
```suggestion
    &__feedback {
```

2022-05-02 17:20 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-increment/scss/index.scss
> +    &.disabled{
```suggestion
    &.disabled {
```

2022-05-02 17:20 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-increment/scss/index.scss
> +        .bf-input-increment__feedback{
```suggestion
        .bf-input-increment__feedback {
```

2022-05-02 17:20 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-increment/scss/index.scss
> +    &.is-invalid {
un truc qu'on fera plus tard:
Remplacer `is-invalid` par `invalid` our etre consistent avec `disabled`.

2022-05-02 17:20 UTC, bibifrost commented on CHANGELOG.mdx
> +- Fix [Input Increment](/story/components-input-increment--drupal) layout on Safari
```suggestion
- Fix [Twig Component Input Increment](/story/components-input-increment--drupal) layout on Safari.
```

2022-05-02 18:38 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/input-increment/scss/index.scss
> +    &.is-invalid {
non. j'achète. On le fait là

2022-05-05 20:42 UTC, bibifrost submitted a review, later dismissed
Ok pour moi.
Par contre, Je viens de voir qu'on ne peux pas remettre à 0.
C'est pas idéal niveau UX de cliquer sur + puis sur - et de ne pas revenir au 0 initial. Next version.

2022-05-06 20:51 UTC, ThalieVideotron commented
> Ok pour moi. Par contre, Je viens de voir qu'on ne peux pas remettre à 0. C'est pas idéal niveau UX de cliquer sur + puis sur - et de ne pas revenir au 0 initial. Next version.



> Ok pour moi. Par contre, Je viens de voir qu'on ne peux pas remettre à 0. C'est pas idéal niveau UX de cliquer sur + puis sur - et de ne pas revenir au 0 initial. Next version.

étrange,  à part de l'indentation et de l'espacement je n'ai que modifié le CSS. le bug était là avant sur safari - je veux dire si tu va voir le premier release sur safari, le bug est la? et juste sur safari?

2022-05-07 23:14 UTC, JonathanLefebvreV requested changes
iOS safari: OK
Mac Safari : v12 - 13 - 14 - 15
![image](https://user-images.githubusercontent.com/75901368/167274944-1604185a-3e72-40a9-8d5d-c1a215f389cb.png)

2022-05-09 20:15 UTC, ThalieVideotron commented
> iOS safari: OK Mac Safari : v12 - 13 - 14 - 15 ![image](https://user-images.githubusercontent.com/75901368/167274944-1604185a-3e72-40a9-8d5d-c1a215f389cb.png)

c'est exactement ce que je voyais sur Firefox et que j'avais réussi à fixer. je regarde si j'arrive à le reproduire (des fois si je demande au Ipad d'afficher la version ordi...). sinon ben je réfléchit. c'est le type number qui fait ça.

2022-06-30 01:03 UTC, JonathanLefebvreV approved these changes

2022-06-30 01:25 UTC, merged