DS-240-variable-hors-API : search, car (api exposed), footer & header
bifrost-vui/bifrost-front-end-library pull request #319
Opened 2022-05-02 12:11 UTC by ThalieVideotron

2022-05-02 12:14 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/card/_doc/plan-api-exposed.stories.mdx
> +            description_html: '<em>description</em>_html',
la variable description a été supprimée au profit de celle de description_html, la story api Exposed n'avait juste pas été mise à jour

2022-05-02 17:10 UTC, bibifrost commented on projects/front-end-library/src/lib/components/navigation-header/angular/header.component.ts
> +import { Component, ViewEncapsulation, OnInit, Input, Output, EventEmitter} from "@angular/core";
```suggestion
import { Component, ViewEncapsulation, OnInit, Input, Output, EventEmitter} from '@angular/core';

```

2022-05-05 01:25 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/navigation-footer/angular/footer.component.ts
> +}
```suggestion
}
```

2022-05-05 01:29 UTC, JonathanLefebvreV commented
Conflit à gérer @ThalieVideotron

2022-05-05 02:55 UTC, ThalieVideotron commented
> Conflit à gérer @ThalieVideotron

back merged master and fixed conflict.

2022-05-05 11:08 UTC, JonathanLefebvreV requested changes
Pourquoi dans le composant `Status`, la propriété `reversed` n'est pas avec un `_`?

2022-05-05 12:23 UTC, ThalieVideotron commented
> Pourquoi dans le composant `Status`, la propriété `reversed` n'est pas avec un `_`?

t'as ben raison. Done. activé le contrôle dans storybook aussi

2022-05-05 19:14 UTC, JonathanLefebvreV approved these changes

2022-05-05 19:14 UTC, merged