DS-327 - Selection tile with footer
bifrost-vui/bifrost-front-end-library pull request #325
Opened 2022-05-03 23:43 UTC by ThalieVideotron

2022-05-05 00:26 UTC, JonathanLefebvreV requested changes
Il manque le CHANGELOG

2022-05-05 00:26 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/scss/index.scss
> +        margin: 0 .5rem;
4px. Pas 8

2022-05-05 00:26 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/scss/index.scss
> +}*/
pourquoi gardé ce code?

2022-05-05 00:26 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +    </footer>
Faire un Objet Footer tel que décrit dans le Jira et faire des propriété de l'objet de chacune de celle-ci

2022-05-05 00:26 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +          <div class='bf-selection-tile__bottom'>
si ca s'appel "bottom" changer le commentaire

2022-05-05 00:26 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
> +
En orienté Objet.

2022-05-05 00:39 UTC, JonathanLefebvreV requested changes
C'est rendu brisé au niveau du prix
![image](https://user-images.githubusercontent.com/75901368/166848604-9adf0271-c684-4204-a5b4-1ab9033bb5ca.png)

2022-05-05 01:33 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
> +
j'ai hésité pcq footer contient déjà 2 objets mais okidou

2022-05-05 02:28 UTC, ThalieVideotron commented
> C'est rendu brisé au niveau du prix ![image](https://user-images.githubusercontent.com/75901368/166848604-9adf0271-c684-4204-a5b4-1ab9033bb5ca.png)

![image](https://user-images.githubusercontent.com/82388009/166855443-4530d822-920e-4694-a240-3a0737f9ddfa.png)
je vais pouvoir jouer avec les marge du checkbox sur les petits devices pour laisser plus de place mais j'aimerais mieux le faire dans le fix de la checkbox si c'est ok avec toi - c'est une capture d'un 320px donc normal qu'on soit un peu tassé

2022-05-05 11:15 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
> +
Hesite pas prochaine fois.. C'est ça de l'orienté objet.  Objet -> objet -> objet -> etc.

2022-05-05 11:21 UTC, JonathanLefebvreV commented
> je vais pouvoir jouer avec les marge du checkbox sur les petits devices pour laisser plus de place mais j'aimerais mieux le faire dans le fix de la checkbox si c'est ok avec toi - c'est une capture d'un 320px donc normal qu'on soit un peu tassé

Pas trop non, parce que je ne comprends pas ce que tu parles. Quand tu parles d'un PR que tu as en tête, la référé pour la vitesse compréhension de tous.

Le fait que tu as enlevé l'image des story ici pour les tests. C'est selon moi ici que c'est à fixé. C'est aussi ici que tu ajoutes le max 20.5height que je ne comprends pas cela bien de où. Aucune trace dans Jira

2022-05-05 11:29 UTC, JonathanLefebvreV requested changes

2022-05-05 11:29 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/scss/index.scss
> +    max-width: 20.5rem;
invalid et out of scope. Du moins faut m'expliquer.
Si c'est lié à avoir un rendu du "footer" property, invalid. C'est ok d'avoir un tile plus grand

2022-05-05 11:44 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/scss/index.scss
> +    max-width: 20.5rem;
Example figma en plus que 328.

width : 384
https://www.figma.com/file/7bTmk29aCBl7rCFszffYPr/DS---Components-%26-styles?node-id=13060%3A102915

Ca brise la notion de "fit" container. C'est à revoir et c'est en dehors de cette PR

2022-05-05 11:45 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/scss/index.scss
> +    max-width: 20.5rem;
Donc, sauf, selon tes explication - revert et ajusté les stories pour reproduire les cas, si nécessaire

2022-05-05 12:08 UTC, ThalieVideotron commented
> > je vais pouvoir jouer avec les marge du checkbox sur les petits devices pour laisser plus de place mais j'aimerais mieux le faire dans le fix de la checkbox si c'est ok avec toi - c'est une capture d'un 320px donc normal qu'on soit un peu tassé
> 
> Pas trop non, parce que je ne comprends pas ce que tu parles. Quand tu parles d'un PR que tu as en tête, la référé pour la vitesse compréhension de tous.
> 
> Le fait que tu as enlevé l'image des story ici pour les tests. C'est selon moi ici que c'est à fixé. C'est aussi ici que tu ajoutes le max 20.5height que je ne comprends pas cela bien de où. Aucune trace dans Jira

j'ai enlevé les background qui ne sont plus autorisés (les underground) parce que ça cache le footer. Les tuiles seront toujours sur des fond ground (voir Commentaire dans figma) 
La taille max en largueur a été mentionnée par Kathleen en présentation - c.est la taille des tuiles horizonlaes "larges" dans figma
Pour la réduction des marges sur les petits mobiles mobile. si je fais le changement ici je vais complexifier davantage le merge avec la PR du fix de la checkbox et je vais les perdre (ben oui je remplace la checkbox et c'est elle qui a la marge)

2022-05-05 12:13 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/scss/index.scss
> +    max-width: 20.5rem;
je dois valider avec Kathleen pcq on a 2 sources de vérité contradictoires : https://www.figma.com/file/7bTmk29aCBl7rCFszffYPr/DS---Components-%26-styles?node-id=10083%3A1806  = 328px

2022-05-05 12:48 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/scss/index.scss
> +    max-width: 20.5rem;
done - next version pour le max-width en sous-marin - 
Comme tu dit ça brise la notion de "fit" container qui ne faisait déjà pas de sens en vertical - On est aussi bien de revoir la notion : ex: hug:  true|false (hug c'est le terme de figma)

2022-05-05 20:07 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +  <div class='bf-selection-tile__inner {{ isDisabled ? 'disabled' }}'>
```suggestion
  <div class='bf-selection-tile__inner {{ isDisabled|default(false) ? 'disabled' }}'>
```

2022-05-05 20:07 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +        <div class='bf-selection-tile__content {{ hasVisual ? '' : 'bf-selection-tile__no-visual' }}' >
```suggestion
        <div class='bf-selection-tile__content {{ hasVisual ? '' : 'bf-selection-tile__no-visual' }}'>
```

2022-05-05 20:07 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +                {% if iconName is defined and iconName is not empty %}
ce `is not empty` ne devrait pas etre necessaire car iconName est une string.

2022-05-05 20:07 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +        {% if (info is defined and info) or ((orientation is same as ('vertical') and fit is same as ('container')) %}
```suggestion
        {% if (info is defined and info) or (orientation == 'vertical' and fit  == 'container') %}
```

2022-05-05 20:07 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +    <footer class='bf-selection-tile__footer p-3'>
Malheuresement le tag `footer` ne peux pas s'appliquer car il n'a pas de parent sémantique.

2022-05-06 13:09 UTC, bibifrost requested changes

2022-05-06 13:09 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/_doc/template.drupal.twig
> +<div class='container' {{ (orientation == 'horizontal') ? 'style="max-width:600px"':'style="max-width:1200px"'}}>
```suggestion
<div class='container' {{ (orientation == 'horizontal') ? 'style="max-width: 600px"' : 'style="max-width: 1200px"' }}>
```

2022-05-06 13:09 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/_doc/template.drupal.twig
> +    <p class='pt-3 pb-3'> Background: {{ ( index == 1 ) ? 'Ground': '' }} {{ ( index == 2 ) ? 'Reversed + Ground': '' }} {{ index == 3 ? 'Highlight': '' }}</p>
```suggestion
    <p class='py-3'>Background: {{ ( index == 1 ) ? 'Ground' : '' }} {{ ( index == 2 ) ? 'Reversed + Ground' : '' }} {{ index == 3 ? 'Highlight' : '' }}</p>
```

2022-05-06 13:09 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/_doc/template.drupal.twig
> +    <div class='{{ ( index == 1 ) ? 'bf-color-bg-ground': '' }} {{ ( index == 2 ) ? 'reversed  bf-color-bg-ground': '' }} {{ index == 3 ? 'bf-color-bg-highlight': '' }}' >
```suggestion
    <div class='{{ ( index == 1 ) ? 'bf-color-bg-ground' : '' }} {{ ( index == 2 ) ? 'reversed  bf-color-bg-ground' : '' }} {{ index == 3 ? 'bf-color-bg-highlight' : '' }}' >
```

2022-05-06 13:09 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
> +    @Input() fit: 'content' | 'container';// tODO - revisit the fit behavior : hug content vs max width
```suggestion
    @Input() fit: 'content' | 'container'; // TODO - revisit the fit behavior : hug content vs max width
```

2022-05-06 13:09 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
> +    /** Expected format: { src: string, alt: string, class: string } */
```suggestion
    /** Expected format: `{ src: string, alt: string, class: string }` */
```

2022-05-06 13:09 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +{# locals #}
locals?

2022-05-06 13:20 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
> +    @Input() fit: 'content' | 'container';// tODO - revisit the fit behavior : hug content vs max width
faudra pas oublier d'enlever le commentaire quand on fera le JIra

2022-05-06 13:21 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +{# locals #}
?

2022-05-06 13:24 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/_doc/doc.stories.mdx
> +//Horizontal Tile - fit container
done

2022-05-06 13:26 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/_doc/template.drupal.twig
> +{% set footer = footer|json_parse %}
PVI : je ne l'avais pas fait PCQ ça complique le backmerge quand le même changement est fait sur 2 branches - mais done

2022-05-06 13:26 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
> +import {HTMLElement} from '@webcomponents/custom-elements/src/Patch/Native';
@bibifrost  please resolve

2022-05-06 13:26 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +{# locals #}
Tu parles de variables locals j'imagine. Mais ce commentaire n'est pas utile.
D'ailleurs, tu vas avoir des inconsistences. Exemple: `{% set class = 'bf-banner ' ~ class|default(null) %}`.
Ici on override une variable contextuelle par une variable locale.

2022-05-06 13:27 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +<div class='bf-selection-tile bf-selection-tile--{{ orientation }} bf-selection-tile--{{ 'fit-' ~ fit }} {{ isInvalid ? 'color-warning' : '' }} {{ isSelected ? 'checked' : '' }} {{ class }}'>
active le soft wrap - le code généré est vraiment trop impacté.

2022-05-06 13:28 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/_doc/doc.stories.mdx
> +                text: `<p>Save on your monthly payments now by <strong> returning your phone </strong> after 24 months.</p>`,
done

2022-05-06 13:33 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +{# locals #}
ils sont tous supprimés

2022-05-06 13:34 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/_doc/template.drupal.twig
> +          info: info|default('12.34 $/Mois <br> pour 24 mois'),
done

2022-05-06 15:37 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +{# locals #}
> Tu parles de variables locals j'imagine. Mais ce commentaire n'est pas utile. D'ailleurs, tu vas avoir des inconsistences. Exemple: `{% set class = 'bf-banner ' ~ class|default(null) %}`. Ici on override une variable contextuelle par une variable locale.

Pour le moment - et c'est la quasi totalité des variables locales que je définie - elles servent à me créer un booleen local pour simplifier la lecture du code en aval. tu as propablemet juste mal choisis ton exemple parce je ne comprend pas où et dans quel contexte j'aurais des inconsistance. si je me sert de banner pour faire un test et obtenir booleen, ça va répondre quand même (pas dans selection tile mais si banner y était défini ça ne changerait rien).

2022-05-06 16:09 UTC, bibifrost requested changes

2022-05-06 16:09 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/_doc/doc.stories.mdx
> +                class:''
```suggestion
                src: '/images/logo/channels/tva-sports.svg',
                alt: 'TVA Sports',
                class: ''
```

2022-05-06 16:09 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/_doc/doc.stories.mdx
> +                class:''
```suggestion
                src: '/images/logo/channels/tva-sports.svg',
                alt: 'TVA Sports',
                class: ''
```

2022-05-06 16:09 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/_doc/doc.stories.mdx
> +                class:''
```suggestion
                src: '/images/logo/channels/tva-sports.svg',
                alt: 'TVA Sports',
                class: ''
```

2022-05-06 16:09 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
> +    text: HTMLElement;
```suggestion
    description: HTMLElement;
```
l'api text est problematique. Soyons plus précis/consistent.

2022-05-06 16:09 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/scss/index.scss
> +        &.disabled {
la class `.disabled` devrait s'appliquer au div le plus haut, pas inner.

2022-05-06 16:09 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/scss/index.scss
> +        *------------------------------------*/
Ce commentaire ne me semble pas utile, car la classe s'appelle `disabled`.

2022-05-06 16:09 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/scss/index.scss
> +                background-color: var(--bf-color-bg-underground); // Designer may comme back with a new color
```suggestion
                background-color: var(--bf-color-bg-underground); // TODO: Designer may comme back with a new color
```

2022-05-06 16:09 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +  <div class='bf-selection-tile__inner {{ isDisabled|default(false) ? 'disabled' }}'>
déplacer la class disabled sur `bf-selection-tile`

2022-05-06 16:18 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/scss/index.scss
> +                background-color: var(--bf-color-bg-underground); // Designer may comme back with a new color
non - j'aurasi mis un todo si  c'était certain que des designer nous reviennent avec des nouvelle couleurs

2022-05-06 16:18 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +  <div class='bf-selection-tile__inner {{ isDisabled|default(false) ? 'disabled' }}'>
non
je l'ai mise là exprès., le footer n'est pas à disabled dans le design (ni le message d'erreur qui va disparâitre)  juste le inner

2022-05-06 16:18 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/scss/index.scss
> +        &.disabled {
non. le footer n'est pas disabled - il est là exprès

2022-05-06 16:18 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
> +    text: HTMLElement;
bien d'accord mais éviter d'attendre le 8e passage pour me le souligner.

2022-05-06 16:24 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/_doc/template.drupal.twig
> +{% set footer = footer|json_parse %}
@bibifrost please resolve

2022-05-06 16:24 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/_doc/doc.stories.mdx
> +//Horizontal Tile - fit container
@bibifrost please resolve

2022-05-06 16:24 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/_doc/doc.stories.mdx
> +    style={{ height: '600px' }}>
@bibifrost please resolve

2022-05-06 16:24 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/_doc/doc.stories.mdx
> +    style={{ height: '600px' }}>
@bibifrost please resolve

2022-05-06 16:25 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
> +    @Input() fit: 'content'|'container';//hug content vs max width
@bibifrost please resolve

2022-05-06 16:25 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
> +    @Input() orientation: 'horizontal'|'vertical';
@bibifrost please resolve

2022-05-06 16:25 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
> +    /**{ src: string, alt: string, class: string } */
@bibifrost please resolve

2022-05-06 16:25 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/_doc/template.drupal.twig
> +          info: info|default('12.34 $/Mois <br> pour 24 mois'),
@bibifrost please resolve

2022-05-06 16:27 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
> +    text: HTMLElement;
@bibifrost please resolve
SVP ne pas faire de suggestions quand le changement doit se faire à plusieurs endroits - c'est un coup pour casser le chmilblick

2022-05-06 16:29 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/scss/index.scss
> +        *------------------------------------*/
Pour le moment je le garde - quand je ferais le merge avec le fix de la checkbox je vais pouvoir tous les enlever (idem pour horizontal et vertical) - oui mais next version

2022-05-06 17:00 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +{# locals #}
Ce n'était peut etre pas clair. Mais la notion de locals n'est pas toujours vrai car des fois tu veux juste setter des default ou boen aggreger des class contextuel + local.
On s'en rejase si ce n'est pas clair.

2022-05-06 17:06 UTC, bibifrost requested changes

2022-05-06 17:06 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
> +    text: HTMLElement;
Je te l'aurais dis avant, si je l'avait remarqué
Tu n'es pas obligé d'accepter la suggestion dans ce cas, c'est surtout pour bien comprendre mon commentaire.

2022-05-06 17:10 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +{# locals #}
ok c'est le terme local - ok. finalemenmt, je comprend ce que tu veux dire.

2022-05-07 19:08 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +{% set hasFooter = orientation is same as ('horizontal') and fit is same as ('container') and ((footer.text is defined and footer.text) or (footer.link is defined and footer.link is not empty)) %}
La condition d'avoir le footer seulement sur une orientation "container" est fausse du moins "non-confirmé" pour moi. 
Et si Kathleen te l'a confirmé. Je doute ce soit vrai.

Entk, on va le gardé pour le re confirmé ça dans la List de selection tile

2022-05-07 19:11 UTC, JonathanLefebvreV submitted a review, later dismissed

2022-05-07 19:14 UTC, JonathanLefebvreV approved these changes

2022-05-07 19:19 UTC, merged

2022-05-10 17:44 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +{% set hasFooter = orientation is same as ('horizontal') and fit is same as ('container') and ((footer.text is defined and footer.text) or (footer.link is defined and footer.link is not empty)) %}
![image](https://user-images.githubusercontent.com/82388009/167690075-340c40e8-2826-4e87-816d-b3ad7b4885ff.png)
 la doc c'est peut-être perdue en chemin perdue mais oui ça a été discuté/confirmé