Ds 339 fix checbox
bifrost-vui/bifrost-front-end-library pull request #326
Opened 2022-05-04 16:01 UTC by ThalieVideotron

2022-05-04 17:21 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
>      }
@Input() isSelected : boolean;  devrait être @Input() isChecked : boolean; comme dans checkbox. @bibifrost  faire le changement en même temps que le refactoring pour la liste ?

note que maintenant, selectionTile consomme la checkbox (pas juste partager le css)

2022-05-04 17:51 UTC, ThalieVideotron commented on CHANGELOG.mdx
> +- Fix checkbox display in Safari and IOS browsers for [Selection Tile](/story/components-selection-tile--selection-tile-vertical)
ouin ben checkbox n'est pas encore publié alors...

2022-05-04 17:53 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/_doc/doc.stories.mdx
> +            table       : { defaultValue : { summary: 'radio' } },
réalisé que dans figma on l'utilise presque toujours dans son format radio

2022-05-05 20:29 UTC, bibifrost commented on CHANGELOG.mdx
> +- Fix checkbox display in Safari and IOS browsers for [Selection Tile](/story/components-selection-tile--selection-tile-vertical)
```suggestion
- Fix checkbox display in iOS Safari.
```

2022-05-05 20:29 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/doc.stories.mdx
> +        type: { table: {disable: true}}, // not available in the checkbox stories - for usage in Selection Tiles
```suggestion
        type: { table: { disable: true } }, // Not available in the checkbox stories - for usage in Selection Tiles.
```

2022-05-05 20:29 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/template.drupal.twig
> +{% set _backgroundNames = ['ground','underground','ground + reversed','underground + reversed', 'highlight', 'highlight + reversed'] %}
Pourquoi ne pas faire un seul array avec une props `class` et une `name`. Je l'ai fait ailleurs.
```
{% set variants = [
  {
    name: 'ground',
    backgroundClass: 'bf-color-bg-ground',
  },
```

2022-05-05 20:29 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/template.drupal.twig
> +        name: name ~ (loop.index -1)
```suggestion
        name: name|default(name ~ (loop.index - 1))
```
a changer partout

2022-05-05 20:29 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/template.drupal.twig
> +    <div class='p-3'>
Tu peux retirer tous ces p.
et simplement ajouter class: 'p-3' dans les args des stories.

2022-05-05 20:29 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/angular/selection-tile.component.ts
>      }
oui ok

2022-05-05 20:29 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +        id: inputId|default(''),
```suggestion
        id: inputId|default(null),
```
quand c'est possible car ça permet d'etre détecter a chaque `if id is defined` sans avoir a faire `and id`.

2022-05-06 18:52 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/template.drupal.twig
> +{% for variant in _variants %}
```suggestion
{% for _variant in _variants %}
```

Bonne idee de prefixer de `_`. Je le garderais pour `_variant` aussi dans ce cas

2022-05-06 18:52 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-checkbox/_doc/template.drupal.twig
> +  <p class='p-3'>Background: {{ variant.name }} </p>
```suggestion
  <p class='p-3'>Background: {{ variant.name }}</p>
```

2022-05-06 18:52 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/_doc/template.drupal.twig
> +{% set type = type|json_parse %}
définir l'alignement

2022-05-06 18:52 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +        ariaLabel: ariaLabel|default(''),
```suggestion
        value: value|default(null),
        name: name|default(null),
        class: 'bf-selection-tile__label',
        ariaLabel: ariaLabel|default(null),
```

2022-05-06 18:52 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
> +        isChecked : isSelected|default(false),
```suggestion
        isChecked: isSelected|default(false),
```

2022-05-06 18:52 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
>  <div class='bf-selection-tile bf-selection-tile--{{ orientation }} bf-selection-tile--{{ 'fit-' ~ fit }} {{ isInvalid ? 'color-warning' : '' }} {{ isDisabled ? 'disabled' }} {{ isSelected ? 'checked'
On n'a pas de default ici.
C'était avant qu'on valide l'approche de strict_variable, j'imagine

2022-05-07 23:28 UTC, JonathanLefebvreV requested changes

2022-05-07 23:28 UTC, JonathanLefebvreV commented on CHANGELOG.mdx
> +- Fix checkbox display in iOS Safari.
Le change log est égal à la demande de Jira : Corriger du style cross-browser.

Là la PR est remplie de refactor avec des impacts sur bien plus que ce qui est attendu.

Donc scrappé toute la PR et faire le fix du style du checkbox uniquement

2022-05-09 12:09 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/selection-tile/twig/index.twig
>  <div class='bf-selection-tile bf-selection-tile--{{ orientation }} bf-selection-tile--{{ 'fit-' ~ fit }} {{ isInvalid ? 'color-warning' : '' }} {{ isDisabled ? 'disabled' }} {{ isSelected ? 'checked'
exact.

2022-05-09 12:09 UTC, ThalieVideotron commented on CHANGELOG.mdx
> +- Fix checkbox display in iOS Safari.
heu... non
un peu de code style mais le reste c'est des changements HTML/CSS pour réparer le bug et éviter d'en introduire de nouveaux

2022-05-09 16:59 UTC, closed without merging