DS-348 - New Business Logos
bifrost-vui/bifrost-front-end-library pull request #334
Opened 2022-05-10 18:54 UTC by ThalieVideotron

Updated SVGs

2022-05-11 12:06 UTC, bibifrost requested changes

2022-05-11 12:06 UTC, bibifrost commented on CHANGELOG.mdx
> +- Update Videotron Business [logo](/story/components-logo--drupal-all-logos)
Préciser que c'est juste l'image SVG qui a changé pour que ce soit clair qu'il n'y a aucun breaking change.

2022-05-11 12:06 UTC, bibifrost commented on projects/front-end-library/src/lib/components/logo/svg/logo-videotron-business-large-en.svg
> +<svg width="256" height="72" viewBox="0 0 256 72" fill="none" xmlns="http://www.w3.org/2000/svg">
Tous les SVG doivent etre optimisés et compressés.
Tu peux utiliser celui-ci:
https://jakearchibald.github.io/svgomg/
Tu va gagné en performance:
<img width="265" alt="image" src="https://user-images.githubusercontent.com/93746960/167845727-b6374fcb-9db3-4f90-870a-9c8010a2a32a.png">

2022-05-11 12:30 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/logo/svg/logo-videotron-business-large-en.svg
> +<svg width="256" height="72" viewBox="0 0 256 72" fill="none" xmlns="http://www.w3.org/2000/svg">
ho. on n'a pas fait ça pour les icones. 
aussi les small me semblent un peu fuzzy (anciens et nouveaux) - je me demandais si on ne devrait pas demander à ce qu'ils soient revus

2022-05-11 17:45 UTC, ThalieVideotron commented on projects/front-end-library/src/lib/components/logo/svg/logo-videotron-business-large-en.svg
> +<svg width="256" height="72" viewBox="0 0 256 72" fill="none" xmlns="http://www.w3.org/2000/svg">
done pour l'optimisation. Pour les small qui son fuzzy j'en glisserais un mot au weekly ou à la démo - c'est out of scope

2022-05-12 08:18 UTC, baptistemac commented on projects/front-end-library/src/lib/components/logo/svg/logo-videotron-business-large-en.svg
> +<svg width="256" height="72" viewBox="0 0 256 72" fill="none" xmlns="http://www.w3.org/2000/svg">
Le fuzzy n'apparaît que sur les écrans de résolutions x1. 
Pour l'éviter, il faut favoriser les valeurs sans decimals.

2022-05-12 12:20 UTC, ThalieVideotron commented on CHANGELOG.mdx
> +- Update Videotron Business [logo](/story/components-logo--drupal-all-logos)
@baptistemac please resolve

2022-06-17 11:59 UTC, JonathanLefebvreV approved these changes

2022-06-17 11:59 UTC, merged