ds-333-v2-create-input-checkbox
bifrost-vui/bifrost-front-end-library pull request #336
Opened 2022-05-13 12:53 UTC by bibifrost

2022-05-21 00:56 UTC, JonathanLefebvreV requested changes

2022-05-21 00:56 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/selection-tile/angular/api.model.ts
> +    extraAttribute: string;
footer property is missing from this interface. It's the most expected feature of the Input List for the current project that wait for us.

2022-05-21 00:56 UTC, JonathanLefebvreV commented on projects/front-end-library/src/lib/components/input-radio/twig/index.twig
> +              'fit': 'content',
Note to myself: need to test it more. Seem a hack that skips a feature of the selectionTile. 
I don't understand why it is not managed as a dynamic property

2022-05-21 00:59 UTC, JonathanLefebvreV commented
Note: if times before the packaging. 
- Refactor https://bifrost-front-end-library-vui.vercel.app/?path=/story/components-selection-tile--drupal-example-selection-color to be in the input list example instead

2022-05-21 19:00 UTC, bibifrost commented on projects/front-end-library/src/lib/components/selection-tile/angular/api.model.ts
> +    extraAttribute: string;
Done

2022-05-21 19:00 UTC, bibifrost commented
> Note: if times before the packaging.
> 
> * Refactor https://bifrost-front-end-library-vui.vercel.app/?path=/story/components-selection-tile--drupal-example-selection-color to be in the input list example instead

Done

2022-05-21 19:03 UTC, bibifrost commented on projects/front-end-library/src/lib/components/input-radio/twig/index.twig
> +              'fit': 'content',
C'est volontaire, car container = size large (avec un min-width et min-height).
Or, vu avec Kathleen, ce cas n'est pas désiré car on veux que toutes les tuiles aient la meme largeur pour faire des colonnes parfaites. C'est pourquoi `display: grid` prend le dessus et définie la largeur des tuiles.
Il existe cependant la props `areOptionTilesLarge` qui permet de grandir la taille des tuiles.

2022-05-22 11:29 UTC, JonathanLefebvreV commented
Merci @bibifrost d'avoir fait les fix. Tu viens de rendre ma journée moins intense. 
Je commence le 2e review de tout ça

2022-05-22 17:28 UTC, JonathanLefebvreV approved these changes

2022-05-22 17:28 UTC, merged