DS-438 | new | Good to know banner
bifrost-vui/bifrost-front-end-library pull request #439
Opened 2023-09-26 18:53 UTC by lolitavermeulen

Intégration de la bannière Good to know afin d'améliorer son affichage mobile
Résultat en desktop voulu : https://videotron.com/node/7286/layout

Résultat en mobile: blob:https://groupemedia.atlassian.net/753348ba-0534-4ad3-9342-9532ffcdad83#media-blob-url=true&id=c2f859b6-2b72-4b0a-8986-2f1a1af73aa5&contextId=1491466&collection=
(impossible d'afficher des images ici de mon bord)

2023-09-27 18:55 UTC, malalancette-alithya requested changes

2023-09-28 15:27 UTC, lolitavermeulen commented on projects/front-end-library/src/lib/components/good-to-know/angular/good-to-know.component.ts
> +    @Input() title: string = 'Bon à savoir';
Pas de changement pour le title, si je me réfère à ce qui existe déjà sur le site.
Mais j'ai fait le changement pour la description

2023-09-29 17:14 UTC, malalancette-alithya requested changes

2023-09-29 17:14 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/components/good-to-know/twig/index.twig
> +      } only %}
Pour l'icône, de la ligne 42 à 45, on va le transformer comme ceci : 

```
{% if icon is not iterable %}
    {% set icon = {
        name: icon
    } %}
{% endif %}
{% set icon = icon|merge({
    size: "large"
}) %}

{% include "@bf-components/icon/twig/index.twig" with icon only %}
```

La raison est que pour la propriété `icon`, en plus du type `string`, on utilise aussi le type `IIcon`. C'est soit l'un ou l'autre. Dans ton code, `icon` était bel et bien une `string`, mais il faut quand même donner la possibilité d'utiliser l'objet de type `IIcon`.

Donc, le code que je te donne ci-haut vérifie si la valeur reçu dans la propriété `icon` est `iterable` ou non. En d'autres mots, si c'est un objet ou un array. Si ce n'est pas le cas, alors c'est une `string` et il ajoute cette `string` dans l'attribut `name` d'un objet que l'on nomme `icon`, comme la propriété.

2023-09-29 17:14 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/components/good-to-know/twig/index.twig
> +{% set heroClasses = [
Renomme `heroClasses` par `goodToKnowClasses`, car nous ne sommes pas dans le Hero.

2023-09-29 17:14 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/components/good-to-know/twig/index.twig
> +  "class": heroClasses|join(' ')|trim,
Voir [ce commentaire](https://github.com/bifrost-vui/bifrost-front-end-library/pull/439/files#diff-615bbea5620fe38f0410ddd3c6948958f17247d92e95270a444a59a942363ce0R24) à la ligne 24.

2023-09-29 17:14 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/components/good-to-know/twig/index.twig
> +          {{ description_html }}
Changer le nom de la propriété selon [ce commentaire](https://github.com/bifrost-vui/bifrost-front-end-library/pull/439/files#diff-04c3a9032545cf307d1b84a3114f8fe99a7f7c43d37d4cd98dece3f6b9af4616R28).

2023-09-29 17:14 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/components/good-to-know/twig/index.twig
> +{% set hasDescription = description_html is defined and description_html is not empty %}
Changer le nom de la propriété selon [ce commentaire](https://github.com/bifrost-vui/bifrost-front-end-library/pull/439/files#diff-04c3a9032545cf307d1b84a3114f8fe99a7f7c43d37d4cd98dece3f6b9af4616R28).

2023-09-29 17:14 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/components/good-to-know/_doc/doc.stories.mdx
> +            description_html:
Changer le nom de la propriété selon [ce commentaire](https://github.com/bifrost-vui/bifrost-front-end-library/pull/439/files#diff-04c3a9032545cf307d1b84a3114f8fe99a7f7c43d37d4cd98dece3f6b9af4616R28).

2023-09-29 17:14 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/components/good-to-know/_doc/template.drupal.twig
> +{% set description_html = description_html|json_parse %}
Changer le nom de la propriété selon [ce commentaire](https://github.com/bifrost-vui/bifrost-front-end-library/pull/439/files#diff-04c3a9032545cf307d1b84a3114f8fe99a7f7c43d37d4cd98dece3f6b9af4616R28).

2023-09-29 17:14 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/components/good-to-know/_doc/template.drupal.twig
> +        description_html: description_html,
Changer le nom de la propriété selon [ce commentaire](https://github.com/bifrost-vui/bifrost-front-end-library/pull/439/files#diff-04c3a9032545cf307d1b84a3114f8fe99a7f7c43d37d4cd98dece3f6b9af4616R28).

2023-09-29 17:14 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/components/good-to-know/scss/index.scss
> +  }
As-tu encore besoin des styles entre les lignes 28 et 41 ?

2023-09-29 17:14 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/scss/index.scss
> +@import '../components/good-to-know/scss/index';
Déplacer cette ligne dans la section `// Bifröst components` que l'on retrouve à la ligne 68.

Place-le à la bonne place dans l'ordre alphabétique, svp.

2023-09-29 17:47 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/components/good-to-know/_doc/doc.stories.mdx
> +    icon : 'innovation',
@lolitavermeulen, je vois que tu as ajouté les propriétés manquantes, mais il manque la propriété `class`.

2023-10-02 14:59 UTC, malalancette-alithya requested changes

2023-10-02 14:59 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/components/good-to-know/_doc/doc.stories.mdx
> +        },
On va retirer les lignes 27 à 38. Je vais t'appeler pour t'expliquer pourquoi.

2023-10-02 14:59 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/components/good-to-know/_doc/doc.stories.mdx
> +    icon: 'innovation',
Voir [ce commentaire](https://github.com/bifrost-vui/bifrost-front-end-library/pull/439/files#diff-b118c56603db0f986cb4e951629622fa4709f1cf8fe7312c10d9f1a3734a038aR38). On va changer quelque chose ici aussi.

2023-10-02 14:59 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/components/good-to-know/_doc/doc.stories.mdx
> +    icon: 'innovation',
Voir [ce commentaire](https://github.com/bifrost-vui/bifrost-front-end-library/pull/439/files#diff-b118c56603db0f986cb4e951629622fa4709f1cf8fe7312c10d9f1a3734a038aR38). On va changer quelque chose ici aussi.

2023-10-02 15:46 UTC, malalancette-alithya requested changes
Ces quatre derniers commentaires et c'est vraiment terminé.

2023-10-02 15:46 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/components/good-to-know/twig/index.twig
> +  "p-4 d-flex align-items-center bf-good-to-know",
Enlève les classes `d-flex` et `align-items-center`.

Pour `align-items-center`, c'est l'alignement que tu mets déjà à la [ligne 36 du fichier SCSS](https://github.com/bifrost-vui/bifrost-front-end-library/pull/439/files#diff-fcfbaa9460f837db569badcb1b9c38557e79d6ae13ea14bbcf299daccacfd504R36). On va utiliser seulement le fichier SCSS pour ces styles.

2023-10-02 15:46 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/components/good-to-know/scss/index.scss
> +.bf-good-to-know {
Ajouter le style `display: flex;`, car on a supprimé la classe `d-flex`.

2023-10-02 15:46 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/components/good-to-know/scss/index.scss
> +  align-items: self-start !important;
Tu peux supprimer cette ligne, car en mobile l'alignement est déjà correct.

2023-10-02 15:46 UTC, malalancette-alithya commented on projects/front-end-library/src/lib/components/good-to-know/scss/index.scss
> +    align-items: center !important;
Comme on a enlevé la classe `align-items-center` à la [ligne 25 du fichier Twig](https://github.com/bifrost-vui/bifrost-front-end-library/pull/439/files#diff-615bbea5620fe38f0410ddd3c6948958f17247d92e95270a444a59a942363ce0R25), tu n'as plus besoin du `!important`, donc tu peux retirer le `!important`.

2023-10-02 17:06 UTC, malalancette-alithya approved these changes
Tout est bon. J'approuve. Très beau travail! :)

2023-10-02 17:07 UTC, merged